--Porject Name: Automation Files Center
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:07/08/2014
--Summary: Automation Files Center Job Logs and set up process
--Version: 0.5

--These view will be converted to table when all update basic table done every day
3. Oracle View Setup		
	3.1 X CURRENT ITEM VIEW
		DROP VIEW VIEW_INV_SAP_ITEM_X;
		SELECT * FROM VIEW_INV_SAP_ITEM_X;
		CREATE VIEW VIEW_INV_SAP_ITEM_X AS 
		SELECT DISTINCT * FROM
		(SELECT ISPM.ID           AS ID,
		  ISPM.DIRECT_SHIP_PLANT AS PLANT,
		  ISPM.MATERIALID        AS MATERIAL,
		  ISMC.CATALOG_STRING1   AS CATALOG_DASH,
		  ISMC.CATALOG_STRING2   AS CATALOG_NO_DASH,
		  ISPM.DIST_CHL          AS DIST_CHL,
		  ISPM.CURRENT_SERIES    AS CURRENT_SERIES
		FROM
		  (SELECT MATERIALID
			||'_'
			||DIRECT_SHIP_PLANT AS ID,
			MATERIALID,
			DIST_CHL,
			DIRECT_SHIP_PLANT,
			CURRENT_SERIES
		  FROM INV_SAP_PP_MVKE
		  WHERE CURRENT_SERIES = 'X'
		  )ISPM
		LEFT JOIN
		  (SELECT CATALOG_STRING1,
			CATALOG_STRING2,
			MATERIALID
		  FROM INV_SAP_NODASH_MAT_CATA
		  )ISMC
		ON ISPM.MATERIALID = ISMC.MATERIALID)	
		
	3.2 ITEM_ALL
		DROP VIEW VIEW_INV_SAP_ITEM_ALL;
		SELECT * FROM VIEW_INV_SAP_ITEM_ALL;
		CREATE VIEW VIEW_INV_SAP_ITEM_ALL AS 
		SELECT ISPM.ID           AS ID,
		  ISPM.DIRECT_SHIP_PLANT AS PLANT,
		  ISPM.MATERIALID        AS MATERIAL,
		  ISMC.CATALOG_STRING1   AS CATALOG_DASH,
		  ISMC.CATALOG_STRING2   AS CATALOG_NO_DASH,
		  ISPM.SALES_ORG         AS SALES_ORG,
		  ISPM.DIST_CHL          AS DIST_CHL,
		  ISPM.D_CHAIN_BLK       AS D_CHAIN_BLK,
		  ISPM.VALID_FROM_DATE   AS VALID_FROM_DATE,
		  ISPM.STOCK_STATUS      AS STOCK_STATUS,
		  ISPM.CURRENT_SERIES    AS CURRENT_SERIES
		FROM
		  (SELECT MATERIALID
			||'_'
			||DIRECT_SHIP_PLANT AS ID,
			MATERIALID,
			SALES_ORG,
			DIST_CHL,
			D_CHAIN_BLK,
			VALID_FROM_DATE,
			DIRECT_SHIP_PLANT,
			STOCK_STATUS,
			CURRENT_SERIES
		  FROM INV_SAP_PP_MVKE
		  )ISPM
		LEFT JOIN
		  (SELECT CATALOG_STRING1,
			CATALOG_STRING2,
			MATERIALID
		  FROM INV_SAP_NODASH_MAT_CATA
		  )ISMC
		ON ISPM.MATERIALID = ISMC.MATERIALID;
		
	3.3 VIEW_INV_SAP_PP_OPT_X with x current series
		DROP VIEW VIEW_INV_SAP_PP_OPT_X;
		SELECT * FROM VIEW_INV_SAP_PP_OPT_X WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');
		CREATE VIEW VIEW_INV_SAP_PP_OPT_X AS
		SELECT *
		FROM
		  (SELECT PP_BASIC.ID,
			PP_BASIC.LAST_REVIEW,
			PP_BASIC.MATERIAL,
			ITEM_X.CATALOG_DASH,
			ITEM_X.CATALOG_NO_DASH,
			PP_BASIC.PLANT,
			PP_BASIC.MAT_DESC,
			PP_BASIC.SAFETY_STOCK,
			PP_BASIC.OH_QTY,
			PP_BASIC.UNIT,
			PP_BASIC.UNIT_COST,
			PP_BASIC.OH_QTY_INTRANSIT,
			PP_BASIC.PROD_BU,
			PP_BASIC.PROD_FAM,
			PP_BASIC.PROC_TYPE,
			PP_BASIC.STRATEGY_GRP,
			PP_BASIC.MRP_TYPE,
			PP_BASIC.PROD_SCHEDULER,
			PP_BASIC.PLANT_SP_MATL_STA,
			PP_BASIC.VENDOR_KEY,
			PP_BASIC.VENDOR_ITEM,
			PP_BASIC.MIN_INV,
			PP_BASIC.TARGET_INV,
			PP_BASIC.MAX_INV,
			PP_BASIC.LOT_SIZE_QTY,
			PP_BASIC.LOT_ROUNDING_VALUE,
			PP_BASIC.LOT_SIZE_DISLS,
			PP_BASIC.AVG26_USAGE_QTY,
			PP_BASIC.STDEV26_USAGE,
			PP_BASIC.AVG13_USAGE_QTY,
			PP_BASIC.STDEV13_USAGE,
			PP_BASIC.Q1_LINES,
			PP_BASIC.Q2_LINES,
			PP_BASIC.Q3_LINES,
			PP_BASIC.Q4_LINES,
			PP_BASIC.Q1_FREQ_COUNT,
			PP_BASIC.Q2_FREQ_COUNT,
			PP_BASIC.Q3_FREQ_COUNT,
			PP_BASIC.Q4_FREQ_COUNT,
			PP_BASIC.EXCHANGE_RATE,
			PP_BASIC.LEVEL_TYPE,
			PP_BASIC.OUT_QTY_W01,
			PP_BASIC.OUT_QTY_W02,
			PP_BASIC.OUT_QTY_W03,
			PP_BASIC.OUT_QTY_W04,
			PP_BASIC.OUT_QTY_W05,
			PP_BASIC.OUT_QTY_W06,
			PP_BASIC.OUT_QTY_W07,
			PP_BASIC.OUT_QTY_W08,
			PP_BASIC.OUT_QTY_W09,
			PP_BASIC.OUT_QTY_W10,
			PP_BASIC.OUT_QTY_W11,
			PP_BASIC.OUT_QTY_W12,
			PP_BASIC.OUT_QTY_W13,
			PP_BASIC.OUT_QTY_W14,
			PP_BASIC.OUT_QTY_W15,
			PP_BASIC.OUT_QTY_W16,
			PP_BASIC.OUT_QTY_W17,
			PP_BASIC.OUT_QTY_W18,
			PP_BASIC.OUT_QTY_W19,
			PP_BASIC.OUT_QTY_W20,
			PP_BASIC.OUT_QTY_W21,
			PP_BASIC.OUT_QTY_W22,
			PP_BASIC.OUT_QTY_W23,
			PP_BASIC.OUT_QTY_W24,
			PP_BASIC.OUT_QTY_W25,
			PP_BASIC.OUT_QTY_W26,
			PP_BASIC.IN_QTY_W01,
			PP_BASIC.IN_QTY_W02,
			PP_BASIC.IN_QTY_W03,
			PP_BASIC.IN_QTY_W04,
			PP_BASIC.IN_QTY_W05,
			PP_BASIC.IN_QTY_W06,
			PP_BASIC.IN_QTY_W07,
			PP_BASIC.IN_QTY_W08,
			PP_BASIC.IN_QTY_W09,
			PP_BASIC.IN_QTY_W10,
			PP_BASIC.IN_QTY_W11,
			PP_BASIC.IN_QTY_W12,
			PP_BASIC.IN_QTY_W13,
			PP_BASIC.IN_QTY_W14,
			PP_BASIC.IN_QTY_W15,
			PP_BASIC.IN_QTY_W16,
			PP_BASIC.IN_QTY_W17,
			PP_BASIC.IN_QTY_W18,
			PP_BASIC.IN_QTY_W19,
			PP_BASIC.IN_QTY_W20,
			PP_BASIC.IN_QTY_W21,
			PP_BASIC.IN_QTY_W22,
			PP_BASIC.IN_QTY_W23,
			PP_BASIC.IN_QTY_W24,
			PP_BASIC.IN_QTY_W25,
			PP_BASIC.IN_QTY_W26,
			PP_BASIC.MATERIAL_LEVEL_VALUE,
			PP_BASIC.MRP_CONTROLLER,
			PP_BASIC.MRP_CONTROLLER_KEY,
			PP_BASIC.PURCH_GROUP,
			PP_BASIC.PURCH_GROUP_KEY,
			PP_BASIC.PROD_SCHED_KEY,
			PP_BASIC.RECORDER_POINT,
			PP_BASIC.LEAD_TIME,
			PP_BASIC.PDT,
			PP_BASIC.GRT,
			ITEM_X.DIST_CHL,
			PP_BASIC.ISSUE_UOM_NUMERATOR,
			PP_BASIC.PO_UOM_NUMERATOR,
			PP_BASIC.MATL_TYPE,
			ITEM_X.CURRENT_SERIES,
			PP_BASIC.ULTIMATE_SOURCE
		  FROM
			(SELECT MATERIALID
			  ||'_'
			  ||(PLANTID - 1) AS ID,
			  LAST_REVIEW,
			  MATERIALID    AS MATERIAL,
			  (PLANTID - 1) AS PLANT,
			  MAT_DESC,
			  SAFETY_STK AS SAFETY_STOCK,
			  OH_QTY,
			  UNIT_COST,
			  OH_QTY_INTRANSIT,
			  SUBSTR(PROD_BU,0,3) AS PROD_BU,
			  PROD_FAM,
			  PROC_TYPE,
			  STRATEGY_GRP,
			  MRP_TYPE,
			  PROD_SCHEDULER,
			  SP_MATL_STAT_MMSTA AS PLANT_SP_MATL_STA,
			  SPC_PROC_KEY_SOBSL AS VENDOR_KEY,
			  MATERIALID
			  ||'_'
			  ||SUBSTR(VENDOR_NAME,0,4)           AS VENDOR_ITEM,
			  (SAFETY_STK)                        AS MIN_INV,
			  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS TARGET_INV,
			  CEIL(SAFETY_STK + 1.2*LOT_SIZE_QTY) AS MAX_INV,
			  LOT_SIZE_QTY,
			  LOT_ROUNDING_VALUE,
			  LOT_SIZE_DISLS,
			  AVG26_USAGE_QTY,
			  STDEV26_USAGE,
			  AVG13_USAGE_QTY,
			  STDEV13_USAGE,
			  Q1_LINES,
			  Q2_LINES,
			  Q3_LINES,
			  Q4_LINES,
			  Q1_FREQ_COUNT,
			  Q2_FREQ_COUNT,
			  Q3_FREQ_COUNT,
			  Q4_FREQ_COUNT,
			  EXCHANGE_RATE,
			  LEVEL_TYPE,
			  OUT_QTY_W01,
			  OUT_QTY_W02,
			  OUT_QTY_W03,
			  OUT_QTY_W04,
			  OUT_QTY_W05,
			  OUT_QTY_W06,
			  OUT_QTY_W07,
			  OUT_QTY_W08,
			  OUT_QTY_W09,
			  OUT_QTY_W10,
			  OUT_QTY_W11,
			  OUT_QTY_W12,
			  OUT_QTY_W13,
			  OUT_QTY_W14,
			  OUT_QTY_W15,
			  OUT_QTY_W16,
			  OUT_QTY_W17,
			  OUT_QTY_W18,
			  OUT_QTY_W19,
			  OUT_QTY_W20,
			  OUT_QTY_W21,
			  OUT_QTY_W22,
			  OUT_QTY_W23,
			  OUT_QTY_W24,
			  OUT_QTY_W25,
			  OUT_QTY_W26,
			  IN_QTY_W01,
			  IN_QTY_W02,
			  IN_QTY_W03,
			  IN_QTY_W04,
			  IN_QTY_W05,
			  IN_QTY_W06,
			  IN_QTY_W07,
			  IN_QTY_W08,
			  IN_QTY_W09,
			  IN_QTY_W10,
			  IN_QTY_W11,
			  IN_QTY_W12,
			  IN_QTY_W13,
			  IN_QTY_W14,
			  IN_QTY_W15,
			  IN_QTY_W16,
			  IN_QTY_W17,
			  IN_QTY_W18,
			  IN_QTY_W19,
			  IN_QTY_W20,
			  IN_QTY_W21,
			  IN_QTY_W22,
			  IN_QTY_W23,
			  IN_QTY_W24,
			  IN_QTY_W25,
			  IN_QTY_W26,
			  MATERIAL_LEVEL_VALUE,
			  MRP_CONTROLLER,
			  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_KEY,
			  PURCH_GROUP,
			  PURCH_GROUP_EKGRP AS PURCH_GROUP_KEY,
			  PROD_SCHED_FEVOR  AS PROD_SCHED_KEY,
			  REORDER_PT        AS RECORDER_POINT,
			  CEIL(1.4*GRT + PDT)   AS LEAD_TIME,  --Lead Time Change!!
			  PDT AS PDT,
			  GRT AS GRT,
			  MEINS_ISSUE_UOM   AS UNIT,
			  ISSUE_UOM_NUMERATOR,
			  PO_UOM_NUMERATOR,
			  MATL_TYPE_MTART AS MATL_TYPE,
			  ULTIMATE_SOURCE
			FROM INV_SAP_PP_OPTIMIZATION --WHERE MATERIALID = '100-C09KJ400 A' AND PLANTID = '5200'
			)PP_BASIC
		  LEFT JOIN
			(SELECT ID,
			  MATERIAL,
			  CATALOG_DASH,
			  CATALOG_NO_DASH,
			  DIST_CHL,
			  CURRENT_SERIES
			FROM VIEW_INV_SAP_ITEM_X --WHERE MATERIAL = '100-C09KJ400 A' AND PLANTID = '5200'
			)ITEM_X
		  ON ITEM_X.ID = PP_BASIC.ID
		  )
		WHERE CURRENT_SERIES = 'X';
	3.3 VIEW_INV_SAP_PP_OPT_ALL 
		DROP VIEW VIEW_INV_SAP_PP_OPT_ALL;
		SELECT * FROM VIEW_INV_SAP_PP_OPT_ALL WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');
		CREATE VIEW VIEW_INV_SAP_PP_OPT_ALL AS
		SELECT *
		FROM
		  (SELECT PP_BASIC.ID,
			PP_BASIC.LAST_REVIEW,
			PP_BASIC.MATERIAL,
			ITEM_X.CATALOG_DASH,
			ITEM_X.CATALOG_NO_DASH,
			PP_BASIC.PLANT,
			PP_BASIC.MAT_DESC,
			PP_BASIC.SAFETY_STOCK,
			PP_BASIC.OH_QTY,
			PP_BASIC.UNIT,
			PP_BASIC.UNIT_COST,
			PP_BASIC.OH_QTY_INTRANSIT,
			PP_BASIC.PROD_BU,
			PP_BASIC.PROD_FAM,
			PP_BASIC.PROC_TYPE,
			PP_BASIC.STRATEGY_GRP,
			PP_BASIC.MRP_TYPE,
			PP_BASIC.PROD_SCHEDULER,
			PP_BASIC.PLANT_SP_MATL_STA,
			PP_BASIC.VENDOR_KEY,
			PP_BASIC.VENDOR_ITEM,
			PP_BASIC.MIN_INV,
			PP_BASIC.TARGET_INV,
			PP_BASIC.MAX_INV,
			PP_BASIC.LOT_SIZE_QTY,
			PP_BASIC.LOT_ROUNDING_VALUE,
			PP_BASIC.LOT_SIZE_DISLS,
			PP_BASIC.AVG26_USAGE_QTY,
			PP_BASIC.STDEV26_USAGE,
			PP_BASIC.AVG13_USAGE_QTY,
			PP_BASIC.STDEV13_USAGE,
			PP_BASIC.Q1_LINES,
			PP_BASIC.Q2_LINES,
			PP_BASIC.Q3_LINES,
			PP_BASIC.Q4_LINES,
			PP_BASIC.Q1_FREQ_COUNT,
			PP_BASIC.Q2_FREQ_COUNT,
			PP_BASIC.Q3_FREQ_COUNT,
			PP_BASIC.Q4_FREQ_COUNT,
			PP_BASIC.EXCHANGE_RATE,
			PP_BASIC.LEVEL_TYPE,
			PP_BASIC.OUT_QTY_W01,
			PP_BASIC.OUT_QTY_W02,
			PP_BASIC.OUT_QTY_W03,
			PP_BASIC.OUT_QTY_W04,
			PP_BASIC.OUT_QTY_W05,
			PP_BASIC.OUT_QTY_W06,
			PP_BASIC.OUT_QTY_W07,
			PP_BASIC.OUT_QTY_W08,
			PP_BASIC.OUT_QTY_W09,
			PP_BASIC.OUT_QTY_W10,
			PP_BASIC.OUT_QTY_W11,
			PP_BASIC.OUT_QTY_W12,
			PP_BASIC.OUT_QTY_W13,
			PP_BASIC.OUT_QTY_W14,
			PP_BASIC.OUT_QTY_W15,
			PP_BASIC.OUT_QTY_W16,
			PP_BASIC.OUT_QTY_W17,
			PP_BASIC.OUT_QTY_W18,
			PP_BASIC.OUT_QTY_W19,
			PP_BASIC.OUT_QTY_W20,
			PP_BASIC.OUT_QTY_W21,
			PP_BASIC.OUT_QTY_W22,
			PP_BASIC.OUT_QTY_W23,
			PP_BASIC.OUT_QTY_W24,
			PP_BASIC.OUT_QTY_W25,
			PP_BASIC.OUT_QTY_W26,
			PP_BASIC.IN_QTY_W01,
			PP_BASIC.IN_QTY_W02,
			PP_BASIC.IN_QTY_W03,
			PP_BASIC.IN_QTY_W04,
			PP_BASIC.IN_QTY_W05,
			PP_BASIC.IN_QTY_W06,
			PP_BASIC.IN_QTY_W07,
			PP_BASIC.IN_QTY_W08,
			PP_BASIC.IN_QTY_W09,
			PP_BASIC.IN_QTY_W10,
			PP_BASIC.IN_QTY_W11,
			PP_BASIC.IN_QTY_W12,
			PP_BASIC.IN_QTY_W13,
			PP_BASIC.IN_QTY_W14,
			PP_BASIC.IN_QTY_W15,
			PP_BASIC.IN_QTY_W16,
			PP_BASIC.IN_QTY_W17,
			PP_BASIC.IN_QTY_W18,
			PP_BASIC.IN_QTY_W19,
			PP_BASIC.IN_QTY_W20,
			PP_BASIC.IN_QTY_W21,
			PP_BASIC.IN_QTY_W22,
			PP_BASIC.IN_QTY_W23,
			PP_BASIC.IN_QTY_W24,
			PP_BASIC.IN_QTY_W25,
			PP_BASIC.IN_QTY_W26,
			PP_BASIC.MATERIAL_LEVEL_VALUE,
			PP_BASIC.MRP_CONTROLLER,
			PP_BASIC.MRP_CONTROLLER_KEY,
			PP_BASIC.PURCH_GROUP,
			PP_BASIC.PURCH_GROUP_KEY,
			PP_BASIC.PROD_SCHED_KEY,
			PP_BASIC.RECORDER_POINT,
			PP_BASIC.LEAD_TIME,
			PP_BASIC.PDT,
			PP_BASIC.GRT,
			ITEM_X.DIST_CHL,
			PP_BASIC.ISSUE_UOM_NUMERATOR,
			PP_BASIC.PO_UOM_NUMERATOR,
			PP_BASIC.MATL_TYPE,
			ITEM_X.CURRENT_SERIES,
			PP_BASIC.ULTIMATE_SOURCE
		  FROM
			(SELECT MATERIALID
			  ||'_'
			  ||(PLANTID - 1) AS ID,
			  LAST_REVIEW,
			  MATERIALID    AS MATERIAL,
			  (PLANTID - 1) AS PLANT,
			  MAT_DESC,
			  SAFETY_STK AS SAFETY_STOCK,
			  OH_QTY,
			  UNIT_COST,
			  OH_QTY_INTRANSIT,
			  SUBSTR(PROD_BU,0,3) AS PROD_BU,
			  PROD_FAM,
			  PROC_TYPE,
			  STRATEGY_GRP,
			  MRP_TYPE,
			  PROD_SCHEDULER,
			  SP_MATL_STAT_MMSTA AS PLANT_SP_MATL_STA,
			  SPC_PROC_KEY_SOBSL AS VENDOR_KEY,
			  MATERIALID
			  ||'_'
			  ||SUBSTR(VENDOR_NAME,0,4)           AS VENDOR_ITEM,
			  (SAFETY_STK)                        AS MIN_INV,
			  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS TARGET_INV,
			  CEIL(SAFETY_STK + 1.2*LOT_SIZE_QTY) AS MAX_INV,
			  LOT_SIZE_QTY,
			  LOT_ROUNDING_VALUE,
			  LOT_SIZE_DISLS,
			  AVG26_USAGE_QTY,
			  STDEV26_USAGE,
			  AVG13_USAGE_QTY,
			  STDEV13_USAGE,
			  Q1_LINES,
			  Q2_LINES,
			  Q3_LINES,
			  Q4_LINES,
			  Q1_FREQ_COUNT,
			  Q2_FREQ_COUNT,
			  Q3_FREQ_COUNT,
			  Q4_FREQ_COUNT,
			  EXCHANGE_RATE,
			  LEVEL_TYPE,
			  OUT_QTY_W01,
			  OUT_QTY_W02,
			  OUT_QTY_W03,
			  OUT_QTY_W04,
			  OUT_QTY_W05,
			  OUT_QTY_W06,
			  OUT_QTY_W07,
			  OUT_QTY_W08,
			  OUT_QTY_W09,
			  OUT_QTY_W10,
			  OUT_QTY_W11,
			  OUT_QTY_W12,
			  OUT_QTY_W13,
			  OUT_QTY_W14,
			  OUT_QTY_W15,
			  OUT_QTY_W16,
			  OUT_QTY_W17,
			  OUT_QTY_W18,
			  OUT_QTY_W19,
			  OUT_QTY_W20,
			  OUT_QTY_W21,
			  OUT_QTY_W22,
			  OUT_QTY_W23,
			  OUT_QTY_W24,
			  OUT_QTY_W25,
			  OUT_QTY_W26,
			  IN_QTY_W01,
			  IN_QTY_W02,
			  IN_QTY_W03,
			  IN_QTY_W04,
			  IN_QTY_W05,
			  IN_QTY_W06,
			  IN_QTY_W07,
			  IN_QTY_W08,
			  IN_QTY_W09,
			  IN_QTY_W10,
			  IN_QTY_W11,
			  IN_QTY_W12,
			  IN_QTY_W13,
			  IN_QTY_W14,
			  IN_QTY_W15,
			  IN_QTY_W16,
			  IN_QTY_W17,
			  IN_QTY_W18,
			  IN_QTY_W19,
			  IN_QTY_W20,
			  IN_QTY_W21,
			  IN_QTY_W22,
			  IN_QTY_W23,
			  IN_QTY_W24,
			  IN_QTY_W25,
			  IN_QTY_W26,
			  MATERIAL_LEVEL_VALUE,
			  MRP_CONTROLLER,
			  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_KEY,
			  PURCH_GROUP,
			  PURCH_GROUP_EKGRP AS PURCH_GROUP_KEY,
			  PROD_SCHED_FEVOR  AS PROD_SCHED_KEY,
			  REORDER_PT        AS RECORDER_POINT,
			  CEIL(1.4*GRT + PDT)   AS LEAD_TIME,  --Lead Time Change!!
			  PDT AS PDT,
			  GRT AS GRT,
			  MEINS_ISSUE_UOM   AS UNIT,
			  ISSUE_UOM_NUMERATOR,
			  PO_UOM_NUMERATOR,
			  MATL_TYPE_MTART AS MATL_TYPE,
			  ULTIMATE_SOURCE
			FROM INV_SAP_PP_OPTIMIZATION --WHERE MATERIALID = '100-C09KJ400 A' AND PLANTID = '5200'
			)PP_BASIC
		  LEFT JOIN
			(SELECT ID,
			  MATERIAL,
			  CATALOG_DASH,
			  CATALOG_NO_DASH,
			  DIST_CHL,
			  CURRENT_SERIES
			FROM VIEW_INV_SAP_ITEM_X --WHERE MATERIAL = '100-C09KJ400 A' AND PLANTID = '5200'
			)ITEM_X
		  ON ITEM_X.ID = PP_BASIC.ID
		  );
		  
  3.4 
    --VIEW_INV_SAP_FC_STATS
    --Will be converted everyday Job_Daily_FCSTAT_TABLE
    DROP VIEW VIEW_INV_SAP_FC55_STATS;
    SELECT * FROM VIEW_INV_SAP_FC55_STATS;
    CREATE VIEW VIEW_INV_SAP_FC55_STATS AS
    SELECT ITEM_BASIC_PP_FC13.ID,
      ITEM_BASIC_PP_FC13.MATERIAL,
      ITEM_BASIC_PP_FC13.CATALOG_DASH,
      ITEM_BASIC_PP_FC13.CATALOG_NO_DASH,
      ITEM_BASIC_PP_FC13.PLANT,
      ITEM_BASIC_PP_FC13.MAT_DESC,
      ITEM_BASIC_PP_FC13.SAFETY_STOCK,
      ITEM_BASIC_PP_FC13.OH_QTY,
      ITEM_BASIC_PP_FC13.UNIT,
      ITEM_BASIC_PP_FC13.PROC_TYPE,
      ITEM_BASIC_PP_FC13.UNIT_COST,
      ITEM_BASIC_PP_FC13.PROD_BU,
      ITEM_BASIC_PP_FC13.STRATEGY_GRP,
      ITEM_BASIC_PP_FC13.MRP_TYPE,
      ITEM_BASIC_PP_FC13.MRP_CONTROLLER,
      ITEM_BASIC_PP_FC13.PURCH_GROUP,
      ITEM_BASIC_PP_FC13.VENDOR_ITEM,
      ITEM_BASIC_PP_FC13.MATL_TYPE,
      ITEM_BASIC_PP_FC13.MIN_INV,
      ITEM_BASIC_PP_FC13.TARGET_INV,
      ITEM_BASIC_PP_FC13.MAX_INV,
      ITEM_BASIC_PP_FC13.LEAD_TIME,
      ITEM_BASIC_PP_FC13.AVG26_USAGE_QTY,
      ITEM_BASIC_PP_FC13.AVG13_USAGE_QTY,
      ITEM_BASIC_PP_FC13.FC_AVG13_WEEK_QTY,
      FC_AVG26_WEEK.FC_AVG26_WEEK_QTY
    FROM
      (SELECT ITEM_BASIC_PP.ID,
        ITEM_BASIC_PP.MATERIAL,
        ITEM_BASIC_PP.CATALOG_DASH,
        ITEM_BASIC_PP.CATALOG_NO_DASH,
        ITEM_BASIC_PP.PLANT,
        ITEM_BASIC_PP.MAT_DESC,
        ITEM_BASIC_PP.SAFETY_STOCK,
        ITEM_BASIC_PP.UNIT,
        ITEM_BASIC_PP.OH_QTY,
        ITEM_BASIC_PP.PROC_TYPE,
        ITEM_BASIC_PP.UNIT_COST,
        ITEM_BASIC_PP.PROD_BU,
        ITEM_BASIC_PP.STRATEGY_GRP,
        ITEM_BASIC_PP.MRP_TYPE,
        ITEM_BASIC_PP.MRP_CONTROLLER,
        ITEM_BASIC_PP.PURCH_GROUP,
        ITEM_BASIC_PP.VENDOR_ITEM,
        ITEM_BASIC_PP.MATL_TYPE,
        ITEM_BASIC_PP.MIN_INV,
        ITEM_BASIC_PP.TARGET_INV,
        ITEM_BASIC_PP.MAX_INV,
        ITEM_BASIC_PP.LEAD_TIME,
        ITEM_BASIC_PP.AVG26_USAGE_QTY,
        ITEM_BASIC_PP.AVG13_USAGE_QTY,
        FC_AVG13_WEEK.FC_AVG13_WEEK_QTY
      FROM
        (SELECT ID,
          MATERIAL,
          CATALOG_DASH,
          CATALOG_NO_DASH,
          PLANT,
          MAT_DESC,
          SAFETY_STOCK,
          UNIT,
          PROC_TYPE,
          UNIT_COST,
          PROD_BU,
          STRATEGY_GRP,
          MRP_TYPE,
          MRP_CONTROLLER,
          PURCH_GROUP,
          VENDOR_ITEM,
          OH_QTY,
          MATL_TYPE,
          MIN_INV,
          TARGET_INV,
          MAX_INV,
          LEAD_TIME,
          AVG26_USAGE_QTY,
          AVG13_USAGE_QTY
        FROM INV_SAP_PP_OPT_X
        )ITEM_BASIC_PP
      LEFT JOIN
        (SELECT MATERIALID
          ||'_'
          ||PLANTID                           AS ID,
          MATERIALID                          AS MATERIALID,
          PLANTID                             AS PLANTID,
          CEIL(SUM(PLNMG_PLANNEDQUANTITY)/13) AS FC_AVG13_WEEK_QTY
        FROM INV_SAP_PP_FRCST_PBIM_PBED
        WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
        AND VERSBP_VERSION = '55'
        GROUP BY MATERIALID,
          PLANTID
        )FC_AVG13_WEEK
      ON FC_AVG13_WEEK.ID = ITEM_BASIC_PP.ID
      )ITEM_BASIC_PP_FC13
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||PLANTID                           AS ID,
        MATERIALID                          AS MATERIALID,
        PLANTID                             AS PLANTID,
        CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK_QTY
      FROM INV_SAP_PP_FRCST_PBIM_PBED
      WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
      AND VERSBP_VERSION = '55'
      GROUP BY MATERIALID,
        PLANTID
      )FC_AVG26_WEEK
    ON ITEM_BASIC_PP_FC13.ID = FC_AVG26_WEEK.ID; 

    --VIEW_INV_SAP_FC_STATS
    --Will be converted everyday Job_Daily_FCSTAT_TABLE
    DROP VIEW VIEW_INV_SAP_FC00_STATS;
    SELECT * FROM VIEW_INV_SAP_FC00_STATS;
    CREATE VIEW VIEW_INV_SAP_FC00_STATS AS
    SELECT ITEM_BASIC_PP_FC13.ID,
      ITEM_BASIC_PP_FC13.MATERIAL,
      ITEM_BASIC_PP_FC13.CATALOG_DASH,
      ITEM_BASIC_PP_FC13.CATALOG_NO_DASH,
      ITEM_BASIC_PP_FC13.PLANT,
      ITEM_BASIC_PP_FC13.MAT_DESC,
      ITEM_BASIC_PP_FC13.SAFETY_STOCK,
      ITEM_BASIC_PP_FC13.OH_QTY,
      ITEM_BASIC_PP_FC13.UNIT,
      ITEM_BASIC_PP_FC13.PROC_TYPE,
      ITEM_BASIC_PP_FC13.UNIT_COST,
      ITEM_BASIC_PP_FC13.PROD_BU,
      ITEM_BASIC_PP_FC13.STRATEGY_GRP,
      ITEM_BASIC_PP_FC13.MRP_TYPE,
      ITEM_BASIC_PP_FC13.MRP_CONTROLLER,
      ITEM_BASIC_PP_FC13.PURCH_GROUP,
      ITEM_BASIC_PP_FC13.VENDOR_ITEM,
      ITEM_BASIC_PP_FC13.MATL_TYPE,
      ITEM_BASIC_PP_FC13.MIN_INV,
      ITEM_BASIC_PP_FC13.TARGET_INV,
      ITEM_BASIC_PP_FC13.MAX_INV,
      ITEM_BASIC_PP_FC13.LEAD_TIME,
      ITEM_BASIC_PP_FC13.AVG26_USAGE_QTY,
      ITEM_BASIC_PP_FC13.AVG13_USAGE_QTY,
      ITEM_BASIC_PP_FC13.FC_AVG13_WEEK_QTY,
      FC_AVG26_WEEK.FC_AVG26_WEEK_QTY
    FROM
      (SELECT ITEM_BASIC_PP.ID,
        ITEM_BASIC_PP.MATERIAL,
        ITEM_BASIC_PP.CATALOG_DASH,
        ITEM_BASIC_PP.CATALOG_NO_DASH,
        ITEM_BASIC_PP.PLANT,
        ITEM_BASIC_PP.MAT_DESC,
        ITEM_BASIC_PP.SAFETY_STOCK,
        ITEM_BASIC_PP.UNIT,
        ITEM_BASIC_PP.OH_QTY,
        ITEM_BASIC_PP.PROC_TYPE,
        ITEM_BASIC_PP.UNIT_COST,
        ITEM_BASIC_PP.PROD_BU,
        ITEM_BASIC_PP.STRATEGY_GRP,
        ITEM_BASIC_PP.MRP_TYPE,
        ITEM_BASIC_PP.MRP_CONTROLLER,
        ITEM_BASIC_PP.PURCH_GROUP,
        ITEM_BASIC_PP.VENDOR_ITEM,
        ITEM_BASIC_PP.MATL_TYPE,
        ITEM_BASIC_PP.MIN_INV,
        ITEM_BASIC_PP.TARGET_INV,
        ITEM_BASIC_PP.MAX_INV,
        ITEM_BASIC_PP.LEAD_TIME,
        ITEM_BASIC_PP.AVG26_USAGE_QTY,
        ITEM_BASIC_PP.AVG13_USAGE_QTY,
        FC_AVG13_WEEK.FC_AVG13_WEEK_QTY
      FROM
        (SELECT ID,
          MATERIAL,
          CATALOG_DASH,
          CATALOG_NO_DASH,
          PLANT,
          MAT_DESC,
          SAFETY_STOCK,
          UNIT,
          PROC_TYPE,
          UNIT_COST,
          PROD_BU,
          STRATEGY_GRP,
          MRP_TYPE,
          MRP_CONTROLLER,
          PURCH_GROUP,
          VENDOR_ITEM,
          OH_QTY,
          MATL_TYPE,
          MIN_INV,
          TARGET_INV,
          MAX_INV,
          LEAD_TIME,
          AVG26_USAGE_QTY,
          AVG13_USAGE_QTY
        FROM INV_SAP_PP_OPT_X
        )ITEM_BASIC_PP
      LEFT JOIN
        (SELECT MATERIALID
          ||'_'
          ||PLANTID                           AS ID,
          MATERIALID                          AS MATERIALID,
          PLANTID                             AS PLANTID,
          CEIL(SUM(PLNMG_PLANNEDQUANTITY)/13) AS FC_AVG13_WEEK_QTY
        FROM INV_SAP_PP_FRCST_PBIM_PBED
        WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
        AND VERSBP_VERSION = '00'
        GROUP BY MATERIALID,
          PLANTID
        )FC_AVG13_WEEK
      ON FC_AVG13_WEEK.ID = ITEM_BASIC_PP.ID
      )ITEM_BASIC_PP_FC13
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||PLANTID                           AS ID,
        MATERIALID                          AS MATERIALID,
        PLANTID                             AS PLANTID,
        CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK_QTY
      FROM INV_SAP_PP_FRCST_PBIM_PBED
      WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
      AND VERSBP_VERSION = '00'
      GROUP BY MATERIALID,
        PLANTID
      )FC_AVG26_WEEK
    ON ITEM_BASIC_PP_FC13.ID = FC_AVG26_WEEK.ID; 



