--Porject Name: Automation Files Center
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:07/08/2014
--Summary: Automation Files Center Job Logs and set up process
--Version: 0.5

1. Oracle Client Setup
	1.1 Net Service Name: data_analysis
		SERVICE_NAME: APAFC
		SID: APAFC
		HOST: APCNXMNGYKG422
		PORT: 1523
		PW：apafc198617
		Database Control URL :https://localhost:5500/em
	1.2 DB LINK CREATE
		DB LINK NAME:ROCKWELL_DW_DBLINK
		Connection:	RA_DB_Oracle		Host_Name:	qdws.mke.ra.rockwell.com
		User_Name:	INVANALYST		Port:	1522
		PWD:	Materials1		SID:	QDWS

		
	1.3 Ini Setup
		Drop table INV_SAP_PP_OPTIMIZATION;
		CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK;
		
		Drop table INV_SAP_SALES_VBAK_VBAP_VBUP;
		CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
		CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_LIKP_LIPS_DAILY; 
		CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91;

		DROP TABLE INV_SAP_INVENTORY_BY_PLANT;
		CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK;

		DROP TABLE INV_SAP_PP_PO_HISTORY;
		CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_IO_INPUTS_DAILY;
		CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK;
			
		DROP TABLE INV_SAP_SALES_HST;
		CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_PP_MVKE;
		CREATE TABLE INV_SAP_PP_MVKE AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK;

		
2. Oracle Job Setup
	2.1 Job Name: Job_Daily_INV_PP_OPT
		Job Time: 3:30 AM
		Job Repeat Frequency: Daily ? Two days better?
		Job Procedure:
		DECLARE
		  DROP_TABLE_PP_OPTIMIZATION   VARCHAR2(1000);
		  CREATE_TABLE_PP_OPTIMIZATION VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_PP_OPTIMIZATION   := 'DROP TABLE INV_SAP_PP_OPTIMIZATION';
		  CREATE_TABLE_PP_OPTIMIZATION := 'CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_PP_OPTIMIZATION;
		  EXECUTE IMMEDIATE CREATE_TABLE_PP_OPTIMIZATION;
		END;
		
		Job Initialization:
		Drop table INV_SAP_PP_OPTIMIZATION;
		CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK;
		
		
	2.2 Job Name: Job_Daily_INV_SO_OPEN
		Job Time: 4:30 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_OPEN_SALES   VARCHAR2(1000);
		  CREATE_TABLE_OPEN_SALES  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_OPEN_SALES   := 'Drop table INV_SAP_SALES_VBAK_VBAP_VBUP';
		  CREATE_TABLE_OPEN_SALES := 'CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_OPEN_SALES;
		  EXECUTE IMMEDIATE CREATE_TABLE_OPEN_SALES;
		END;
		
		Job Initialization: 
		Drop table INV_SAP_SALES_VBAK_VBAP_VBUP;
		CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK;

	2.3 Job Name: Job_Daily_INV_PP_FCST
		Job Time: 5:00 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_OPEN_FC   VARCHAR2(1000);
		  CREATE_TABLE_OPEN_FC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_OPEN_FC   := 'Drop table INV_SAP_PP_FRCST_PBIM_PBED';
		  CREATE_TABLE_OPEN_FC := 'CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE DROP_TABLE_OPEN_FC;
		  EXECUTE IMMEDIATE CREATE_TABLE_OPEN_FC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
		CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		
	2.4 Job Name: Job_Daily_INV_DELY
		Job Time: 5:20 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_DELIVERY_REC  VARCHAR2(1000);
		  CREATE_TABLE_DELIVERY_REC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_DELIVERY_REC   := 'Drop table INV_SAP_LIKP_LIPS_DAILY';
		  CREATE_TABLE_DELIVERY_REC := 'CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91';
		  EXECUTE IMMEDIATE DROP_TABLE_DELIVERY_REC;
		  EXECUTE IMMEDIATE CREATE_TABLE_DELIVERY_REC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_LIKP_LIPS_DAILY; 
		CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91;

	2.5 Job Name: Job_Daily_INV_PLANT
		Job Time: 5:40 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_INVENTORY_REC  VARCHAR2(1000);
		  CREATE_TABLE_INVENTORY_REC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INVENTORY_REC   := 'Drop table INV_SAP_INVENTORY_BY_PLANT';
		  CREATE_TABLE_INVENTORY_REC := 'CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_INVENTORY_REC;
		  EXECUTE IMMEDIATE CREATE_TABLE_INVENTORY_REC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_INVENTORY_BY_PLANT;
		CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK;

			
	2.6 Job Name: Job_Daily_INV_PP_PO
		Job Time: 6:10 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		  CREATE_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_PP_PO_HISTORY   := 'Drop table INV_SAP_PP_PO_HISTORY';
		  CREATE_TABLE_PP_PO_HISTORY := 'CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE DROP_TABLE_PP_PO_HISTORY;
		  EXECUTE IMMEDIATE CREATE_TABLE_PP_PO_HISTORY;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_PP_PO_HISTORY;
		CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

	2.7 Job Name: Job_Daily_INV_IO
		Job Time: 6:40 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_IO_REC  VARCHAR2(1000);
		  CREATE_TABLE_IO_REC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_IO_REC   := 'Drop table INV_SAP_IO_INPUTS_DAILY';
		  CREATE_TABLE_IO_REC := 'CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_IO_REC;
		  EXECUTE IMMEDIATE CREATE_TABLE_IO_REC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_IO_INPUTS_DAILY;
		CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK;
				
	2.8 Job Name: Job_Weekly_INV_SO_HST
		Job Time: 2:00 AM
		Job Repeat Frequency: Weekly
		Job Procedure:
		DECLARE
		  DROP_TABLE_SALES_HST  VARCHAR2(1000);
		  CREATE_TABLE_SALES_HST  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_SALES_HST   := 'Drop table INV_SAP_SALES_HST';
		  CREATE_TABLE_SALES_HST := 'CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE DROP_TABLE_SALES_HST;
		  EXECUTE IMMEDIATE CREATE_TABLE_SALES_HST;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_SALES_HST;
		CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

	2.9 Job Name: Job_Weekly_INV_PP_MVKE
		Job Time: 18:00 AM SUNDAY
		Job Repeat Frequency: Weekly
		Job Procedure:
		DECLARE
		  DROP_TABLE_INV_SAP_PP_MVKE   VARCHAR2(1000);
		  CREATE_TABLE_INV_SAP_PP_MVKE VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SAP_PP_MVKE   := 'DROP TABLE INV_SAP_PP_MVKE';
		  CREATE_TABLE_INV_SAP_PP_MVKE := 'CREATE TABLE INV_SAP_PP_MVKE AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_SAP_PP_MVKE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_SAP_PP_MVKE;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_PP_MVKE;
		CREATE TABLE INV_SAP_PP_MVKE AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK;

	2.10 Job Name: Job_Weekly_INV_PP_CATA
		Job Time: 20:00 AM SUNDAY
		Job Repeat Frequency: Weekly
		Job Procedure:
		DECLARE
		  CREATE_TABLE_INV_SAP_MATERIAL_CATALOG        VARCHAR2(1000);
		  DROP_TABLE_INV_SAP_MATERIAL_CATALOG              VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SAP_MATERIAL_CATALOG:= 'DROP TABLE INV_SAP_MATERIAL_CATALOG';
		  CREATE_TABLE_INV_SAP_MATERIAL_CATALOG:= 'CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE;
		  EXECUTE IMMEDIATE STR_CREATE_TABLE;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_MATERIAL_CATALOG;
		CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK;

		DROP TABLE INV_SAP_NODASH_MAT_CATA
		CREATE TABLE INV_SAP_NODASH_MAT_CATA AS SELECT * FROM INV_SAP_MATERIAL_CATALOG;
		DECLARE
		  CURSOR cur
		  IS
			SELECT a.CATALOG_STRING1,
			  b.ROWID ROW_ID
			FROM INV_SAP_MATERIAL_CATALOG a,
			  INV_SAP_NODASH_MAT_CATA b
			WHERE a.MATERIALID = b.MATERIALID
			ORDER BY b.ROWID; ---order by rowid
		  V_COUNTER NUMBER;
		BEGIN
		  V_COUNTER := 0;
		  FOR row IN cur
		  LOOP
			UPDATE INV_SAP_NODASH_MAT_CATA SET CATALOG_STRING2 = REPLACE(row.CATALOG_STRING1, '-') WHERE ROWID = row.ROW_ID;
			V_COUNTER     := V_COUNTER + 1;
			IF (V_COUNTER >= 1000) THEN
			  COMMIT;
			  V_COUNTER := 0;
			END IF;
		  END LOOP;
		  COMMIT;
		END;
		
	2.11 Job Name: Job_Monthly_INV_SHIPSOLD
		Job Time: Every month 9th 23:00 
		Job Repeat Frequency: Monthly
		Job Procedure:
		DROP TABLE INV_SAP_SHIP_SOLD_TO_PARTYID;
		CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK;
		
		DECLARE
		  DROP_TABLE_INV_SHIPSOLD  VARCHAR2(1000);
      CREATE_TABLE_INV_SHIPSOLD_DW  VARCHAR2(1000);
		  CREATE_TABLE_INV_SHIPSOLD_LO  VARCHAR2(1000);
      TRUN_INV_SHIP_SOLD  VARCHAR2(1000);
      INSERT_INV_SHIPSOLD_A  VARCHAR2(1000);
      INSERT_INV_SHIPSOLD_B  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SHIPSOLD   := 'Drop table INV_SAP_SHIP_SOLD_TO_PARTYID';
		  CREATE_TABLE_INV_SHIPSOLD_DW := 'CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK';
      CREATE_TABLE_INV_SHIPSOLD_LO := 'CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
      SELECT * FROM SYSTEM.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_LOCAL_BK';
      TRUN_INV_SHIP_SOLD := 'TRUNCATE TABLE INV_SAP_SHIP_SOLD_TO';
      INSERT_INV_SHIPSOLD_A := 'INSERT INTO INV_SAP_SHIP_SOLD_TO
          SELECT SHIP_SOLD_TOPARTY,
          SHIP_TO_PARTY_NAME,
          SHIP_TO_CITY,
          SHIP_TO_POSTAL_CODE,
          SHIP_TO_COUNTRY
        FROM INV_SAP_SHIP_SOLD_TO_PARTYID';
      INSERT_INV_SHIPSOLD_B := 'INSERT INTO INV_SAP_SHIP_SOLD_TO 
        SELECT 
        SHIP_SOLD_TOPARTY,
        SOLD_TO_PARTY_NAME,
        SOLD_TO_CITY,
        SOLD_TO_POSTAL_CODE,
        SOLD_TO_COUNTRY
        FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NULL';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_SHIPSOLD;
		  --EXECUTE IMMEDIATE CREATE_TABLE_INV_SHIPSOLD_DW;
      EXECUTE IMMEDIATE CREATE_TABLE_INV_SHIPSOLD_LO;
      EXECUTE IMMEDIATE TRUN_INV_SHIP_SOLD;
      EXECUTE IMMEDIATE INSERT_INV_SHIPSOLD_A;
      EXECUTE IMMEDIATE INSERT_INV_SHIPSOLD_B;
		END;
    

	2.12 Job Name: Job_Daily_PP_TABLE
		Job Time: 7:00 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DROP TABLE INV_SAP_PP_OPT_X;
		CREATE TABLE INV_SAP_PP_OPT_X AS
		SELECT * FROM VIEW_INV_SAP_PP_OPT_X;
		
		DECLARE
		  DROP_TABLE_INV_PP_TABLE  VARCHAR2(1000);
		  CREATE_TABLE_INV_PP_TABLE  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_PP_TABLE   := 'Drop table INV_SAP_PP_OPT_X';
		  CREATE_TABLE_INV_PP_TABLE := 'CREATE TABLE INV_SAP_PP_OPT_X AS
      SELECT * FROM VIEW_INV_SAP_PP_OPT_X';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_PP_TABLED;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_PP_TABLE;
		END;
    
  2.13 Job Name: Job_Monthly_PLANT_SOG
		Job Time: Every Month Last week Sat
		Job Repeat Frequency: Monthly
		Job Procedure:
		DROP TABLE INV_SAP_PLANT_SOG;
		CREATE TABLE INV_SAP_PLANT_SOG AS
		SELECT DISTINCT PLANT, SALES_ORG FROM INV_SAP_SALES_VBAK_VBAP_VBUP;
		
		DECLARE
		  DROP_TABLE_INV_PLANT_SOG  VARCHAR2(1000);
		  CREATE_TABLE_INV_PLANT_SOG  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_PLANT_SOG   := 'Drop table INV_SAP_PLANT_SOG';
		  CREATE_TABLE_INV_PLANT_SOG := 'CREATE TABLE INV_SAP_PLANT_SOG AS
      SELECT DISTINCT PLANT, SALES_ORG FROM INV_SAP_SALES_VBAK_VBAP_VBUP';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_PLANT_SOG;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_PLANT_SOG;
		END;





3. Oracle View Setup		
	3.1 X CURRENT ITEM VIEW
		DROP VIEW VIEW_INV_SAP_ITEM_X;
		SELECT * FROM VIEW_INV_SAP_ITEM_X;
		CREATE VIEW VIEW_INV_SAP_ITEM_X AS 
		SELECT DISTINCT * FROM
		(SELECT ISPM.ID           AS ID,
		  ISPM.DIRECT_SHIP_PLANT AS PLANT,
		  ISPM.MATERIALID        AS MATERIAL,
		  ISMC.CATALOG_STRING1   AS CATALOG_DASH,
		  ISMC.CATALOG_STRING2   AS CATALOG_NO_DASH,
		  ISPM.DIST_CHL          AS DIST_CHL,
		  ISPM.CURRENT_SERIES    AS CURRENT_SERIES
		FROM
		  (SELECT MATERIALID
			||'_'
			||DIRECT_SHIP_PLANT AS ID,
			MATERIALID,
			DIST_CHL,
			DIRECT_SHIP_PLANT,
			CURRENT_SERIES
		  FROM INV_SAP_PP_MVKE
		  WHERE CURRENT_SERIES = 'X'
		  )ISPM
		LEFT JOIN
		  (SELECT CATALOG_STRING1,
			CATALOG_STRING2,
			MATERIALID
		  FROM INV_SAP_NODASH_MAT_CATA
		  )ISMC
		ON ISPM.MATERIALID = ISMC.MATERIALID)	
		
	3.2 ITEM_ALL
		DROP VIEW VIEW_INV_SAP_ITEM_ALL;
		SELECT * FROM VIEW_INV_SAP_ITEM_ALL;
		CREATE VIEW VIEW_INV_SAP_ITEM_ALL AS 
		SELECT ISPM.ID           AS ID,
		  ISPM.DIRECT_SHIP_PLANT AS PLANT,
		  ISPM.MATERIALID        AS MATERIAL,
		  ISMC.CATALOG_STRING1   AS CATALOG_DASH,
		  ISMC.CATALOG_STRING2   AS CATALOG_NO_DASH,
		  ISPM.SALES_ORG         AS SALES_ORG,
		  ISPM.DIST_CHL          AS DIST_CHL,
		  ISPM.D_CHAIN_BLK       AS D_CHAIN_BLK,
		  ISPM.VALID_FROM_DATE   AS VALID_FROM_DATE,
		  ISPM.STOCK_STATUS      AS STOCK_STATUS,
		  ISPM.CURRENT_SERIES    AS CURRENT_SERIES
		FROM
		  (SELECT MATERIALID
			||'_'
			||DIRECT_SHIP_PLANT AS ID,
			MATERIALID,
			SALES_ORG,
			DIST_CHL,
			D_CHAIN_BLK,
			VALID_FROM_DATE,
			DIRECT_SHIP_PLANT,
			STOCK_STATUS,
			CURRENT_SERIES
		  FROM INV_SAP_PP_MVKE
		  )ISPM
		LEFT JOIN
		  (SELECT CATALOG_STRING1,
			CATALOG_STRING2,
			MATERIALID
		  FROM INV_SAP_NODASH_MAT_CATA
		  )ISMC
		ON ISPM.MATERIALID = ISMC.MATERIALID;
		
	3.3 VIEW_INV_SAP_PP_OPT_X with x current series
		DROP VIEW VIEW_INV_SAP_PP_OPT_X;
		SELECT * FROM VIEW_INV_SAP_PP_OPT_X WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');
		CREATE VIEW VIEW_INV_SAP_PP_OPT_X AS
		SELECT *
		FROM
		  (SELECT PP_BASIC.ID,
			PP_BASIC.LAST_REVIEW,
			PP_BASIC.MATERIAL,
			ITEM_X.CATALOG_DASH,
			ITEM_X.CATALOG_NO_DASH,
			PP_BASIC.PLANT,
			PP_BASIC.MAT_DESC,
			PP_BASIC.SAFETY_STOCK,
			PP_BASIC.OH_QTY,
			PP_BASIC.UNIT,
			PP_BASIC.UNIT_COST,
			PP_BASIC.OH_QTY_INTRANSIT,
			PP_BASIC.PROD_BU,
			PP_BASIC.PROD_FAM,
			PP_BASIC.PROC_TYPE,
			PP_BASIC.STRATEGY_GRP,
			PP_BASIC.MRP_TYPE,
			PP_BASIC.PROD_SCHEDULER,
			PP_BASIC.PLANT_SP_MATL_STA,
			PP_BASIC.VENDOR_KEY,
			PP_BASIC.VENDOR_ITEM,
			PP_BASIC.MIN_INV,
			PP_BASIC.TARGET_INV,
			PP_BASIC.MAX_INV,
			PP_BASIC.LOT_SIZE_QTY,
			PP_BASIC.LOT_ROUNDING_VALUE,
			PP_BASIC.LOT_SIZE_DISLS,
			PP_BASIC.AVG26_USAGE_QTY,
			PP_BASIC.STDEV26_USAGE,
			PP_BASIC.AVG13_USAGE_QTY,
			PP_BASIC.STDEV13_USAGE,
			PP_BASIC.Q1_LINES,
			PP_BASIC.Q2_LINES,
			PP_BASIC.Q3_LINES,
			PP_BASIC.Q4_LINES,
			PP_BASIC.Q1_FREQ_COUNT,
			PP_BASIC.Q2_FREQ_COUNT,
			PP_BASIC.Q3_FREQ_COUNT,
			PP_BASIC.Q4_FREQ_COUNT,
			PP_BASIC.EXCHANGE_RATE,
			PP_BASIC.LEVEL_TYPE,
			PP_BASIC.OUT_QTY_W01,
			PP_BASIC.OUT_QTY_W02,
			PP_BASIC.OUT_QTY_W03,
			PP_BASIC.OUT_QTY_W04,
			PP_BASIC.OUT_QTY_W05,
			PP_BASIC.OUT_QTY_W06,
			PP_BASIC.OUT_QTY_W07,
			PP_BASIC.OUT_QTY_W08,
			PP_BASIC.OUT_QTY_W09,
			PP_BASIC.OUT_QTY_W10,
			PP_BASIC.OUT_QTY_W11,
			PP_BASIC.OUT_QTY_W12,
			PP_BASIC.OUT_QTY_W13,
			PP_BASIC.OUT_QTY_W14,
			PP_BASIC.OUT_QTY_W15,
			PP_BASIC.OUT_QTY_W16,
			PP_BASIC.OUT_QTY_W17,
			PP_BASIC.OUT_QTY_W18,
			PP_BASIC.OUT_QTY_W19,
			PP_BASIC.OUT_QTY_W20,
			PP_BASIC.OUT_QTY_W21,
			PP_BASIC.OUT_QTY_W22,
			PP_BASIC.OUT_QTY_W23,
			PP_BASIC.OUT_QTY_W24,
			PP_BASIC.OUT_QTY_W25,
			PP_BASIC.OUT_QTY_W26,
			PP_BASIC.IN_QTY_W01,
			PP_BASIC.IN_QTY_W02,
			PP_BASIC.IN_QTY_W03,
			PP_BASIC.IN_QTY_W04,
			PP_BASIC.IN_QTY_W05,
			PP_BASIC.IN_QTY_W06,
			PP_BASIC.IN_QTY_W07,
			PP_BASIC.IN_QTY_W08,
			PP_BASIC.IN_QTY_W09,
			PP_BASIC.IN_QTY_W10,
			PP_BASIC.IN_QTY_W11,
			PP_BASIC.IN_QTY_W12,
			PP_BASIC.IN_QTY_W13,
			PP_BASIC.IN_QTY_W14,
			PP_BASIC.IN_QTY_W15,
			PP_BASIC.IN_QTY_W16,
			PP_BASIC.IN_QTY_W17,
			PP_BASIC.IN_QTY_W18,
			PP_BASIC.IN_QTY_W19,
			PP_BASIC.IN_QTY_W20,
			PP_BASIC.IN_QTY_W21,
			PP_BASIC.IN_QTY_W22,
			PP_BASIC.IN_QTY_W23,
			PP_BASIC.IN_QTY_W24,
			PP_BASIC.IN_QTY_W25,
			PP_BASIC.IN_QTY_W26,
			PP_BASIC.MATERIAL_LEVEL_VALUE,
			PP_BASIC.MRP_CONTROLLER,
			PP_BASIC.MRP_CONTROLLER_KEY,
			PP_BASIC.PURCH_GROUP,
			PP_BASIC.PURCH_GROUP_KEY,
			PP_BASIC.PROD_SCHED_KEY,
			PP_BASIC.RECORDER_POINT,
			PP_BASIC.LEAD_TIME,
			PP_BASIC.PDT,
			PP_BASIC.GRT,
			ITEM_X.DIST_CHL,
			PP_BASIC.ISSUE_UOM_NUMERATOR,
			PP_BASIC.PO_UOM_NUMERATOR,
			PP_BASIC.MATL_TYPE,
			ITEM_X.CURRENT_SERIES,
			PP_BASIC.ULTIMATE_SOURCE
		  FROM
			(SELECT MATERIALID
			  ||'_'
			  ||(PLANTID - 1) AS ID,
			  LAST_REVIEW,
			  MATERIALID    AS MATERIAL,
			  (PLANTID - 1) AS PLANT,
			  MAT_DESC,
			  SAFETY_STK AS SAFETY_STOCK,
			  OH_QTY,
			  UNIT_COST,
			  OH_QTY_INTRANSIT,
			  SUBSTR(PROD_BU,0,3) AS PROD_BU,
			  PROD_FAM,
			  PROC_TYPE,
			  STRATEGY_GRP,
			  MRP_TYPE,
			  PROD_SCHEDULER,
			  SP_MATL_STAT_MMSTA AS PLANT_SP_MATL_STA,
			  SPC_PROC_KEY_SOBSL AS VENDOR_KEY,
			  MATERIALID
			  ||'_'
			  ||SUBSTR(VENDOR_NAME,0,4)           AS VENDOR_ITEM,
			  (SAFETY_STK)                        AS MIN_INV,
			  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS TARGET_INV,
			  CEIL(SAFETY_STK + 1.2*LOT_SIZE_QTY) AS MAX_INV,
			  LOT_SIZE_QTY,
			  LOT_ROUNDING_VALUE,
			  LOT_SIZE_DISLS,
			  AVG26_USAGE_QTY,
			  STDEV26_USAGE,
			  AVG13_USAGE_QTY,
			  STDEV13_USAGE,
			  Q1_LINES,
			  Q2_LINES,
			  Q3_LINES,
			  Q4_LINES,
			  Q1_FREQ_COUNT,
			  Q2_FREQ_COUNT,
			  Q3_FREQ_COUNT,
			  Q4_FREQ_COUNT,
			  EXCHANGE_RATE,
			  LEVEL_TYPE,
			  OUT_QTY_W01,
			  OUT_QTY_W02,
			  OUT_QTY_W03,
			  OUT_QTY_W04,
			  OUT_QTY_W05,
			  OUT_QTY_W06,
			  OUT_QTY_W07,
			  OUT_QTY_W08,
			  OUT_QTY_W09,
			  OUT_QTY_W10,
			  OUT_QTY_W11,
			  OUT_QTY_W12,
			  OUT_QTY_W13,
			  OUT_QTY_W14,
			  OUT_QTY_W15,
			  OUT_QTY_W16,
			  OUT_QTY_W17,
			  OUT_QTY_W18,
			  OUT_QTY_W19,
			  OUT_QTY_W20,
			  OUT_QTY_W21,
			  OUT_QTY_W22,
			  OUT_QTY_W23,
			  OUT_QTY_W24,
			  OUT_QTY_W25,
			  OUT_QTY_W26,
			  IN_QTY_W01,
			  IN_QTY_W02,
			  IN_QTY_W03,
			  IN_QTY_W04,
			  IN_QTY_W05,
			  IN_QTY_W06,
			  IN_QTY_W07,
			  IN_QTY_W08,
			  IN_QTY_W09,
			  IN_QTY_W10,
			  IN_QTY_W11,
			  IN_QTY_W12,
			  IN_QTY_W13,
			  IN_QTY_W14,
			  IN_QTY_W15,
			  IN_QTY_W16,
			  IN_QTY_W17,
			  IN_QTY_W18,
			  IN_QTY_W19,
			  IN_QTY_W20,
			  IN_QTY_W21,
			  IN_QTY_W22,
			  IN_QTY_W23,
			  IN_QTY_W24,
			  IN_QTY_W25,
			  IN_QTY_W26,
			  MATERIAL_LEVEL_VALUE,
			  MRP_CONTROLLER,
			  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_KEY,
			  PURCH_GROUP,
			  PURCH_GROUP_EKGRP AS PURCH_GROUP_KEY,
			  PROD_SCHED_FEVOR  AS PROD_SCHED_KEY,
			  REORDER_PT        AS RECORDER_POINT,
			  CEIL(1.4*GRT + PDT)   AS LEAD_TIME,  --Lead Time Change!!
			  PDT AS PDT,
			  GRT AS GRT,
			  MEINS_ISSUE_UOM   AS UNIT,
			  ISSUE_UOM_NUMERATOR,
			  PO_UOM_NUMERATOR,
			  MATL_TYPE_MTART AS MATL_TYPE,
			  ULTIMATE_SOURCE
			FROM INV_SAP_PP_OPTIMIZATION --WHERE MATERIALID = '100-C09KJ400 A' AND PLANTID = '5200'
			)PP_BASIC
		  LEFT JOIN
			(SELECT ID,
			  MATERIAL,
			  CATALOG_DASH,
			  CATALOG_NO_DASH,
			  DIST_CHL,
			  CURRENT_SERIES
			FROM VIEW_INV_SAP_ITEM_X --WHERE MATERIAL = '100-C09KJ400 A' AND PLANTID = '5200'
			)ITEM_X
		  ON ITEM_X.ID = PP_BASIC.ID
		  )
		WHERE CURRENT_SERIES = 'X';
	3.3 VIEW_INV_SAP_PP_OPT_ALL 
		DROP VIEW VIEW_INV_SAP_PP_OPT_ALL;
		SELECT * FROM VIEW_INV_SAP_PP_OPT_ALL WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');
		CREATE VIEW VIEW_INV_SAP_PP_OPT_ALL AS
		SELECT *
		FROM
		  (SELECT PP_BASIC.ID,
			PP_BASIC.LAST_REVIEW,
			PP_BASIC.MATERIAL,
			ITEM_X.CATALOG_DASH,
			ITEM_X.CATALOG_NO_DASH,
			PP_BASIC.PLANT,
			PP_BASIC.MAT_DESC,
			PP_BASIC.SAFETY_STOCK,
			PP_BASIC.OH_QTY,
			PP_BASIC.UNIT,
			PP_BASIC.UNIT_COST,
			PP_BASIC.OH_QTY_INTRANSIT,
			PP_BASIC.PROD_BU,
			PP_BASIC.PROD_FAM,
			PP_BASIC.PROC_TYPE,
			PP_BASIC.STRATEGY_GRP,
			PP_BASIC.MRP_TYPE,
			PP_BASIC.PROD_SCHEDULER,
			PP_BASIC.PLANT_SP_MATL_STA,
			PP_BASIC.VENDOR_KEY,
			PP_BASIC.VENDOR_ITEM,
			PP_BASIC.MIN_INV,
			PP_BASIC.TARGET_INV,
			PP_BASIC.MAX_INV,
			PP_BASIC.LOT_SIZE_QTY,
			PP_BASIC.LOT_ROUNDING_VALUE,
			PP_BASIC.LOT_SIZE_DISLS,
			PP_BASIC.AVG26_USAGE_QTY,
			PP_BASIC.STDEV26_USAGE,
			PP_BASIC.AVG13_USAGE_QTY,
			PP_BASIC.STDEV13_USAGE,
			PP_BASIC.Q1_LINES,
			PP_BASIC.Q2_LINES,
			PP_BASIC.Q3_LINES,
			PP_BASIC.Q4_LINES,
			PP_BASIC.Q1_FREQ_COUNT,
			PP_BASIC.Q2_FREQ_COUNT,
			PP_BASIC.Q3_FREQ_COUNT,
			PP_BASIC.Q4_FREQ_COUNT,
			PP_BASIC.EXCHANGE_RATE,
			PP_BASIC.LEVEL_TYPE,
			PP_BASIC.OUT_QTY_W01,
			PP_BASIC.OUT_QTY_W02,
			PP_BASIC.OUT_QTY_W03,
			PP_BASIC.OUT_QTY_W04,
			PP_BASIC.OUT_QTY_W05,
			PP_BASIC.OUT_QTY_W06,
			PP_BASIC.OUT_QTY_W07,
			PP_BASIC.OUT_QTY_W08,
			PP_BASIC.OUT_QTY_W09,
			PP_BASIC.OUT_QTY_W10,
			PP_BASIC.OUT_QTY_W11,
			PP_BASIC.OUT_QTY_W12,
			PP_BASIC.OUT_QTY_W13,
			PP_BASIC.OUT_QTY_W14,
			PP_BASIC.OUT_QTY_W15,
			PP_BASIC.OUT_QTY_W16,
			PP_BASIC.OUT_QTY_W17,
			PP_BASIC.OUT_QTY_W18,
			PP_BASIC.OUT_QTY_W19,
			PP_BASIC.OUT_QTY_W20,
			PP_BASIC.OUT_QTY_W21,
			PP_BASIC.OUT_QTY_W22,
			PP_BASIC.OUT_QTY_W23,
			PP_BASIC.OUT_QTY_W24,
			PP_BASIC.OUT_QTY_W25,
			PP_BASIC.OUT_QTY_W26,
			PP_BASIC.IN_QTY_W01,
			PP_BASIC.IN_QTY_W02,
			PP_BASIC.IN_QTY_W03,
			PP_BASIC.IN_QTY_W04,
			PP_BASIC.IN_QTY_W05,
			PP_BASIC.IN_QTY_W06,
			PP_BASIC.IN_QTY_W07,
			PP_BASIC.IN_QTY_W08,
			PP_BASIC.IN_QTY_W09,
			PP_BASIC.IN_QTY_W10,
			PP_BASIC.IN_QTY_W11,
			PP_BASIC.IN_QTY_W12,
			PP_BASIC.IN_QTY_W13,
			PP_BASIC.IN_QTY_W14,
			PP_BASIC.IN_QTY_W15,
			PP_BASIC.IN_QTY_W16,
			PP_BASIC.IN_QTY_W17,
			PP_BASIC.IN_QTY_W18,
			PP_BASIC.IN_QTY_W19,
			PP_BASIC.IN_QTY_W20,
			PP_BASIC.IN_QTY_W21,
			PP_BASIC.IN_QTY_W22,
			PP_BASIC.IN_QTY_W23,
			PP_BASIC.IN_QTY_W24,
			PP_BASIC.IN_QTY_W25,
			PP_BASIC.IN_QTY_W26,
			PP_BASIC.MATERIAL_LEVEL_VALUE,
			PP_BASIC.MRP_CONTROLLER,
			PP_BASIC.MRP_CONTROLLER_KEY,
			PP_BASIC.PURCH_GROUP,
			PP_BASIC.PURCH_GROUP_KEY,
			PP_BASIC.PROD_SCHED_KEY,
			PP_BASIC.RECORDER_POINT,
			PP_BASIC.LEAD_TIME,
			PP_BASIC.PDT,
			PP_BASIC.GRT,
			ITEM_X.DIST_CHL,
			PP_BASIC.ISSUE_UOM_NUMERATOR,
			PP_BASIC.PO_UOM_NUMERATOR,
			PP_BASIC.MATL_TYPE,
			ITEM_X.CURRENT_SERIES,
			PP_BASIC.ULTIMATE_SOURCE
		  FROM
			(SELECT MATERIALID
			  ||'_'
			  ||(PLANTID - 1) AS ID,
			  LAST_REVIEW,
			  MATERIALID    AS MATERIAL,
			  (PLANTID - 1) AS PLANT,
			  MAT_DESC,
			  SAFETY_STK AS SAFETY_STOCK,
			  OH_QTY,
			  UNIT_COST,
			  OH_QTY_INTRANSIT,
			  SUBSTR(PROD_BU,0,3) AS PROD_BU,
			  PROD_FAM,
			  PROC_TYPE,
			  STRATEGY_GRP,
			  MRP_TYPE,
			  PROD_SCHEDULER,
			  SP_MATL_STAT_MMSTA AS PLANT_SP_MATL_STA,
			  SPC_PROC_KEY_SOBSL AS VENDOR_KEY,
			  MATERIALID
			  ||'_'
			  ||SUBSTR(VENDOR_NAME,0,4)           AS VENDOR_ITEM,
			  (SAFETY_STK)                        AS MIN_INV,
			  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS TARGET_INV,
			  CEIL(SAFETY_STK + 1.2*LOT_SIZE_QTY) AS MAX_INV,
			  LOT_SIZE_QTY,
			  LOT_ROUNDING_VALUE,
			  LOT_SIZE_DISLS,
			  AVG26_USAGE_QTY,
			  STDEV26_USAGE,
			  AVG13_USAGE_QTY,
			  STDEV13_USAGE,
			  Q1_LINES,
			  Q2_LINES,
			  Q3_LINES,
			  Q4_LINES,
			  Q1_FREQ_COUNT,
			  Q2_FREQ_COUNT,
			  Q3_FREQ_COUNT,
			  Q4_FREQ_COUNT,
			  EXCHANGE_RATE,
			  LEVEL_TYPE,
			  OUT_QTY_W01,
			  OUT_QTY_W02,
			  OUT_QTY_W03,
			  OUT_QTY_W04,
			  OUT_QTY_W05,
			  OUT_QTY_W06,
			  OUT_QTY_W07,
			  OUT_QTY_W08,
			  OUT_QTY_W09,
			  OUT_QTY_W10,
			  OUT_QTY_W11,
			  OUT_QTY_W12,
			  OUT_QTY_W13,
			  OUT_QTY_W14,
			  OUT_QTY_W15,
			  OUT_QTY_W16,
			  OUT_QTY_W17,
			  OUT_QTY_W18,
			  OUT_QTY_W19,
			  OUT_QTY_W20,
			  OUT_QTY_W21,
			  OUT_QTY_W22,
			  OUT_QTY_W23,
			  OUT_QTY_W24,
			  OUT_QTY_W25,
			  OUT_QTY_W26,
			  IN_QTY_W01,
			  IN_QTY_W02,
			  IN_QTY_W03,
			  IN_QTY_W04,
			  IN_QTY_W05,
			  IN_QTY_W06,
			  IN_QTY_W07,
			  IN_QTY_W08,
			  IN_QTY_W09,
			  IN_QTY_W10,
			  IN_QTY_W11,
			  IN_QTY_W12,
			  IN_QTY_W13,
			  IN_QTY_W14,
			  IN_QTY_W15,
			  IN_QTY_W16,
			  IN_QTY_W17,
			  IN_QTY_W18,
			  IN_QTY_W19,
			  IN_QTY_W20,
			  IN_QTY_W21,
			  IN_QTY_W22,
			  IN_QTY_W23,
			  IN_QTY_W24,
			  IN_QTY_W25,
			  IN_QTY_W26,
			  MATERIAL_LEVEL_VALUE,
			  MRP_CONTROLLER,
			  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_KEY,
			  PURCH_GROUP,
			  PURCH_GROUP_EKGRP AS PURCH_GROUP_KEY,
			  PROD_SCHED_FEVOR  AS PROD_SCHED_KEY,
			  REORDER_PT        AS RECORDER_POINT,
			  CEIL(1.4*GRT + PDT)   AS LEAD_TIME,  --Lead Time Change!!
			  PDT AS PDT,
			  GRT AS GRT,
			  MEINS_ISSUE_UOM   AS UNIT,
			  ISSUE_UOM_NUMERATOR,
			  PO_UOM_NUMERATOR,
			  MATL_TYPE_MTART AS MATL_TYPE,
			  ULTIMATE_SOURCE
			FROM INV_SAP_PP_OPTIMIZATION --WHERE MATERIALID = '100-C09KJ400 A' AND PLANTID = '5200'
			)PP_BASIC
		  LEFT JOIN
			(SELECT ID,
			  MATERIAL,
			  CATALOG_DASH,
			  CATALOG_NO_DASH,
			  DIST_CHL,
			  CURRENT_SERIES
			FROM VIEW_INV_SAP_ITEM_X --WHERE MATERIAL = '100-C09KJ400 A' AND PLANTID = '5200'
			)ITEM_X
		  ON ITEM_X.ID = PP_BASIC.ID
		  );
		  
    3.4 
    DROP VIEW VIEW_INV_SAP_OPEN_SO;
    SELECT * FROM VIEW_INV_SAP_OPEN_SO WHERE SO_ID = '6501783979_12';
    CREATE TABLE VIEW_INV_SAP_OPEN_SO AS
    SELECT SALESDOC
      ||'_'
      || SALESDOCITEM AS SO_ID,
      MATERIAL
      ||'_'
      || PLANT              AS ID,
      SALESDOC              AS SALES_DOC,
      SALESDOCITEM          AS LINE_NUM,
      MATERIAL              AS MATERIAL,
      PLANT                 AS PLANT,
      SALES_ORG             AS SALES_ORG,
      LINECREATEDATE        AS LINE_CREATED_DATE,
      SUBSTR(PRODHIER,0,3)  AS BU,
      ORDERQTY              AS ORDER_QTY,
      OPEN_QTY              AS OPEN_QTY,
      PROFITCENTER          AS PROFIT_CENTER,
      SALESPRICE            AS SALES_PRICE,
      CURRENCY              AS CURRENCY,
      MAX_COMMIT_DATE       AS COMMITTED_DATE,
      MAX_CONFIRM_DATE      AS CONFIRM_DATE,
      SOLD_TO               AS SOLD_TO_PARTY,
      DELIVSTATUS           AS DELIVERY_STATUS,
      OVERALLDELIVSTATSU    AS OVER_ALL_DELIVERY_STATUS,
      SALESDOCTYPE          AS SALE_DOC_TYPE,
      SHIPFROM_VSTEL        AS SHIPPING_POINT,
      STOCKSTATUS           AS STOCK_STATUS,
      DELIVPRIO             AS DELIVERY_PRIORITY,
      LST_ACT_GI_DATE       AS LST_ACT_GI_DATE,
      LST_DELV_CREATED_DATE AS LST_DELIVERY_CREATE_DATE,
      EXCHANGE_RATE_TO_USD  AS EXCHANGE_RATE_TO_USD,
      MAX_REQUEST_DATE      AS REQUIRE_DATE,
      REQTYPE               AS REQTYPE,
      ROUTE                 AS ROUTE
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP;
    



4. Automate Reports
	4.1 AUS REPORTS
	4.1.1 
		--5140 INV CLS REPORT
		--AUTHOR: HUANG MO YUE
		--DATE:7/2/2014
		DROP VIEW VIEW_SAP_INV_CLS_AUSRE;
		SELECT * FROM VIEW_SAP_INV_CLS_AUSRE;
		CREATE VIEW VIEW_SAP_INV_CLS_AUSRE AS
		SELECT PLANT AS PLANT,
		  MATERIAL AS MATERIAL,
		  CATALOG_DASH AS CATALOG,
		  MAT_DESC AS MAT_DESC,
		  PROD_BU AS PRODUCT_GRP,
		  STRATEGY_GRP AS STRATEGY_GRP,
		  SAFETY_STOCK AS SAFETY_STOCK,
		  UNIT AS UNIT,
		  LEAD_TIME AS LEAD_TIME,
		  PROC_TYPE AS PROC_TYPE,
		  PLANT_SP_MATL_STA AS Material_Status,
		  ISSUE_UOM_NUMERATOR AS Delivery_Unit
		FROM VIEW_INV_SAP_PP_OPT_X
		WHERE PLANT IN ('5140','5150');
		
		
  4.2 
    --Stock Item Performance
    --Author: Huang Moyue
    --Date:5/28/2014
    4.2.1.Setup data
    ---Upload History Data
      truncate TABLE STOCK_ITEM_STATUS_BY_BU_WEEK;
      SELECT * FROM STOCK_ITEM_STATUS_BY_BU_WEEK where id = '09-JUN-14_5140_ICM-INTGR COND MONITOR';
      SELECT count(*) FROM STOCK_ITEM_STATUS_BY_BU_WEEK;
      
      truncate TABLE STOCK_ITEM_STATUS_BY_ITEM;
      SELECT * FROM STOCK_ITEM_STATUS_BY_ITEM where id = '07-JUL-14_5140_LGC-IEC LOGIC COMPONENTS_700-HLT12Z24 A';
      SELECT count(*) FROM STOCK_ITEM_STATUS_BY_ITEM;
		
		

  4.3 
      --Backlog Report
      --Author: Huang Moyue
      --Date: 7/15/2014
      4.3.1 Open Sales Order
      --VIEW_INV_SAP_BACKLOG_SO
      DROP VIEW VIEW_INV_SAP_BACKLOG_SO;
      CREATE VIEW VIEW_INV_SAP_BACKLOG_SO AS
      SELECT SO_PP_BS.ID                  AS ID,
        SO_PP_BS.PROC_TYPE                AS PROC_TYPE,
        SO_PP_BS.PLANT                    AS PLANT,
        SO_PP_BS.SALES_ORG                AS SALES_ORG,
        SO_PP_BS.SHIPPING_POINT           AS SHIPPING_POINT,
        SO_PP_BS.SALE_DOC_TYPE            AS SALE_DOC_TYPE,
        SO_PP_BS.SALES_DOC                AS SALES_DOC,
        SO_PP_BS.LINE_NUM                 AS LINE_NUM,
        SO_PP_BS.MATERIAL                 AS MATERIAL,
        SO_PP_BS.CATALOG_DASH             AS CATALOG_DASH,
        SO_PP_BS.MAT_DESC                 AS MAT_DESC,
        SO_PP_BS.MATL_TYPE                AS MATL_TYPE,
        SO_PP_BS.SAFETY_STOCK             AS SAFETY_STOCK,
        SO_PP_BS.STRATEGY_GRP             AS STRATEGY_GRP,
        SO_PP_BS.LEAD_TIME                AS LEAD_TIME,
        SO_PP_BS.BU                       AS BU,
        SO_PP_BS.LINE_CREATED_DATE        AS LINE_CREATED_DATE,
        SO_PP_BS.REQUIRE_DATE             AS REQUIRE_DATE,
        SO_PP_BS.COMMITTED_DATE           AS COMMITTED_DATE,
        SO_PP_BS.CONFIRM_DATE             AS CONFIRM_DATE,
        0                                 AS GAP,
        SO_PP_BS.LST_ACT_GI_DATE          AS LST_ACT_GI_DATE,
        SO_PP_BS.LST_DELIVERY_CREATE_DATE AS LST_DELIVERY_CREATE_DATE,
        SO_PP_BS.ORDER_QTY                AS ORDER_QTY,
        SO_PP_BS.OPEN_QTY                 AS OPEN_QTY,
        SO_PP_BS.SHIPPED_QTY              AS SHIPPED_QTY,
        SO_PP_BS.UNIT                     AS UNIT,
        SO_PP_BS.PROFIT_CENTER            AS PROFIT_CENTER,
        SO_PP_BS.SALES_PRICE              AS SALES_PRICE,
        SO_PP_BS.CURRENCY                 AS CURRENCY,
        SO_PP_BS.SOLD_TO_PARTY            AS SOLD_TO_PARTY,
        SOLD_SHIP.SHIP_SOLD_TO_PARTY_NAME AS SHIP_SOLD_TO_PARTY_NAME,
        SO_PP_BS.ROUTE                    AS ROUTE,
        SO_PP_BS.DELIVERY_PRIORITY        AS DELIVERY_PRIORITY,
        SO_PP_BS.MRP_CONTROLLER           AS MRP_CONTROLLER,
        SO_PP_BS.PURCH_GROUP              AS PURCH_GROUP,
        SO_PP_BS.MRP_TYPE                 AS MRP_TYPE,
        SO_PP_BS.DELIVERY_STATUS          AS DELIVERY_STATUS,
        SO_PP_BS.OVER_ALL_DELIVERY_STATUS AS OVER_ALL_DELIVERY_STATUS,
        SO_PP_BS.VENDOR_KEY               AS VENDOR_KEY,
        SO_PP_BS.STOCK_STATUS             AS STOCK_STATUS,
        SO_PP_BS.REQTYPE                  AS REQTYPE,
        SO_PP_BS.EXCHANGE_RATE_TO_USD     AS EXCHANGE_RATE_TO_USD
      FROM
        (SELECT OPEN_SO_BASIC.ID                             AS ID,
          SALES_PP_X.PROC_TYPE                               AS PROC_TYPE,
          OPEN_SO_BASIC.PLANT                                AS PLANT,
          OPEN_SO_BASIC.SALES_ORG                            AS SALES_ORG,
          OPEN_SO_BASIC.SHIPPING_POINT                       AS SHIPPING_POINT,
          OPEN_SO_BASIC.SALE_DOC_TYPE                        AS SALE_DOC_TYPE,
          OPEN_SO_BASIC.SALES_DOC                            AS SALES_DOC,
          OPEN_SO_BASIC.LINE_NUM                             AS LINE_NUM,
          OPEN_SO_BASIC.MATERIAL                             AS MATERIAL,
          SALES_PP_X.CATALOG_DASH                            AS CATALOG_DASH,
          SALES_PP_X.MAT_DESC                                AS MAT_DESC,
          SALES_PP_X.MATL_TYPE                               AS MATL_TYPE,
          SALES_PP_X.SAFETY_STOCK                            AS SAFETY_STOCK,
          SALES_PP_X.STRATEGY_GRP                            AS STRATEGY_GRP,
          SALES_PP_X.LEAD_TIME                               AS LEAD_TIME,
          OPEN_SO_BASIC.BU                                   AS BU,
          OPEN_SO_BASIC.LINE_CREATED_DATE                    AS LINE_CREATED_DATE,
          OPEN_SO_BASIC.REQUIRE_DATE                         AS REQUIRE_DATE,
          OPEN_SO_BASIC.COMMITTED_DATE                       AS COMMITTED_DATE,
          OPEN_SO_BASIC.CONFIRM_DATE                         AS CONFIRM_DATE,
          OPEN_SO_BASIC.LST_ACT_GI_DATE                      AS LST_ACT_GI_DATE,
          OPEN_SO_BASIC.LST_DELIVERY_CREATE_DATE             AS LST_DELIVERY_CREATE_DATE,
          OPEN_SO_BASIC.ORDER_QTY                            AS ORDER_QTY,
          OPEN_SO_BASIC.OPEN_QTY                             AS OPEN_QTY,
          (OPEN_SO_BASIC.ORDER_QTY - OPEN_SO_BASIC.OPEN_QTY) AS SHIPPED_QTY,
          SALES_PP_X.UNIT                                    AS UNIT,
          OPEN_SO_BASIC.PROFIT_CENTER                        AS PROFIT_CENTER,
          OPEN_SO_BASIC.SALES_PRICE                          AS SALES_PRICE,
          OPEN_SO_BASIC.CURRENCY                             AS CURRENCY,
          LPAD(OPEN_SO_BASIC.SOLD_TO_PARTY,10,'0')           AS SOLD_TO_PARTY,
          OPEN_SO_BASIC.ROUTE                                AS ROUTE,
          OPEN_SO_BASIC.DELIVERY_PRIORITY                    AS DELIVERY_PRIORITY,
          SALES_PP_X.MRP_CONTROLLER                          AS MRP_CONTROLLER,
          SALES_PP_X.PURCH_GROUP                             AS PURCH_GROUP,
          SALES_PP_X.MRP_TYPE                                AS MRP_TYPE,
          OPEN_SO_BASIC.DELIVERY_STATUS                      AS DELIVERY_STATUS,
          OPEN_SO_BASIC.OVER_ALL_DELIVERY_STATUS             AS OVER_ALL_DELIVERY_STATUS,
          SALES_PP_X.VENDOR_KEY                              AS VENDOR_KEY,
          OPEN_SO_BASIC.STOCK_STATUS                         AS STOCK_STATUS,
          OPEN_SO_BASIC.REQTYPE                              AS REQTYPE,
          OPEN_SO_BASIC.EXCHANGE_RATE_TO_USD                 AS EXCHANGE_RATE_TO_USD
        FROM
          (SELECT ID,
            SALES_DOC,
            LINE_NUM,
            MATERIAL,
            PLANT,
            SALES_ORG,
            LINE_CREATED_DATE,
            BU,
            ORDER_QTY,
            OPEN_QTY,
            PROFIT_CENTER,
            SALES_PRICE,
            CURRENCY,
            COMMITTED_DATE,
            CONFIRM_DATE,
            SOLD_TO_PARTY,
            DELIVERY_STATUS,
            OVER_ALL_DELIVERY_STATUS,
            SALE_DOC_TYPE,
            SHIPPING_POINT,
            STOCK_STATUS,
            DELIVERY_PRIORITY,
            LST_ACT_GI_DATE,
            LST_DELIVERY_CREATE_DATE,
            EXCHANGE_RATE_TO_USD,
            REQUIRE_DATE,
            REQTYPE,
            ROUTE
          FROM VIEW_INV_SAP_OPEN_SO
          WHERE SALES_ORG IN ('5003','5007')
          )OPEN_SO_BASIC
        LEFT JOIN
          (SELECT ID,
            CATALOG_DASH,
            MAT_DESC,
            SAFETY_STOCK,
            PROC_TYPE,
            UNIT,
            STRATEGY_GRP,
            MRP_TYPE,
            VENDOR_KEY,
            MRP_CONTROLLER,
            PURCH_GROUP,
            LEAD_TIME,
            MATL_TYPE
          FROM INV_SAP_PP_OPT_X
          )SALES_PP_X
        ON SALES_PP_X.ID = OPEN_SO_BASIC.ID
        )SO_PP_BS
      LEFT JOIN
        (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
          SHIP_SOLD_TO_PARTY_NAME
        FROM INV_SAP_SHIP_SOLD_TO
        )SOLD_SHIP
      ON SO_PP_BS.SOLD_TO_PARTY = SOLD_SHIP.SHIP_SOLD_TO_PARTY;
    
      4.3.2 Stock status
      --VIEW_INV_SAP_BACKLOG_INV
      DROP VIEW VIEW_INV_SAP_BACKLOG_INV;
      SELECT * FROM VIEW_INV_SAP_BACKLOG_INV;
      CREATE VIEW VIEW_INV_SAP_BACKLOG_INV AS
      SELECT INV_BASIC.ID AS ID,
        INV_BASIC.PLANT                 AS PLANT,
        INV_BASIC.MATERIAL              AS MATERIAL,
        ITEM_BASIC.CATALOG_DASH         AS CATALOG_DASH,
        ITEM_BASIC.MAT_DESC             AS MAT_DESC,
        ITEM_BASIC.PROD_BU              AS PROD_BU,
        ITEM_BASIC.MATL_TYPE            AS MATL_TYPE,
        ITEM_BASIC.STRATEGY_GRP         AS STRATEGY_GRP,
        ITEM_BASIC.SAFETY_STOCK         AS SAFETY_STOCK,
        INV_BASIC.TOTAL_QTY             AS TOTAL_QTY,
        INV_BASIC.LOCATIONID            AS LOCATION
      FROM
        (SELECT MATERIALID
          ||'_'
          ||PLANTID     AS ID,
          MATERIALID    AS MATERIAL,
          PLANTID       AS PLANT,
          LOCATIONID    AS LOCATIONID,
          NVL(OH_QTY,0) AS TOTAL_QTY,
          ASOFDATE      AS LAST_REVIEW_DATE
        FROM INV_SAP_INVENTORY_BY_PLANT
        )INV_BASIC
      LEFT JOIN
        (SELECT ID,
          CATALOG_DASH,
          MAT_DESC,
          SAFETY_STOCK,
          UNIT,
          STRATEGY_GRP,
          PROD_BU,
          MATL_TYPE
        FROM INV_SAP_PP_OPT_X
        )ITEM_BASIC
      ON ITEM_BASIC.ID = INV_BASIC.ID;
      
      4.3.3 Open PO
      
      
      
      
      
      
      
      
      
      
      
      
      