--Porject Name: Automation Files Center
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:07/08/2014
--Summary: Automation Files Center Job Logs and set up process
--Version: 0.5

1. Oracle Client Setup
	1.1 Net Service Name: data_analysis
		SERVICE_NAME: APAFC
		SID: APAFC
		HOST: APCNXMNGYKG422
		PORT: 1523
		PW:apafc198617
		Database Control URL :https://localhost:5500/em
	1.2 DB LINK CREATE
		DB LINK NAME:ROCKWELL_DW_DBLINK
		Connection:	RA_DB_Oracle		Host_Name:	qdws.mke.ra.rockwell.com
		User_Name:	INVANALYST		Port:	1522
		PWD:	Materials1		SID:	QDWS

		
	1.3 Ini Setup
		Drop table INV_SAP_PP_OPTIMIZATION;
		CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK;
		
		Drop table INV_SAP_SALES_VBAK_VBAP_VBUP;
		CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
		CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_LIKP_LIPS_DAILY; 
		CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91;

		DROP TABLE INV_SAP_INVENTORY_BY_PLANT;
		CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK;

		DROP TABLE INV_SAP_PP_PO_HISTORY;
		CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_IO_INPUTS_DAILY;
		CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK;
			
		DROP TABLE INV_SAP_SALES_HST;
		CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		DROP TABLE INV_SAP_PP_MVKE;
		CREATE TABLE INV_SAP_PP_MVKE AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK;

		
2. Oracle Job Setup
	2.1 Job Name: Job_Daily_INV_PP_OPT
		Job Time: 3:30 AM
		Job Repeat Frequency: Daily ? Two days better?
		Job Procedure:
		DECLARE
		  DROP_TABLE_PP_OPTIMIZATION   VARCHAR2(1000);
		  CREATE_TABLE_PP_OPTIMIZATION VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_PP_OPTIMIZATION   := 'DROP TABLE INV_SAP_PP_OPTIMIZATION';
		  CREATE_TABLE_PP_OPTIMIZATION := 'CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_PP_OPTIMIZATION;
		  EXECUTE IMMEDIATE CREATE_TABLE_PP_OPTIMIZATION;
		END;
		
		Job Initialization:
		Drop table INV_SAP_PP_OPTIMIZATION;
		CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DW_DBLINK;
		
		
	2.2 Job Name: Job_Daily_INV_SO_OPEN
		Job Time: 4:30 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_OPEN_SALES   VARCHAR2(1000);
		  CREATE_TABLE_OPEN_SALES  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_OPEN_SALES   := 'Drop table INV_SAP_SALES_VBAK_VBAP_VBUP';
		  CREATE_TABLE_OPEN_SALES := 'CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_OPEN_SALES;
		  EXECUTE IMMEDIATE CREATE_TABLE_OPEN_SALES;
		END;
		
		Job Initialization: 
		Drop table INV_SAP_SALES_VBAK_VBAP_VBUP;
		CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DW_DBLINK;

	2.3 Job Name: Job_Daily_INV_PP_FCST
		Job Time: 5:00 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_OPEN_FC   VARCHAR2(1000);
		  CREATE_TABLE_OPEN_FC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_OPEN_FC   := 'Drop table INV_SAP_PP_FRCST_PBIM_PBED';
		  CREATE_TABLE_OPEN_FC := 'CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE DROP_TABLE_OPEN_FC;
		  EXECUTE IMMEDIATE CREATE_TABLE_OPEN_FC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
		CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

		
	2.4 Job Name: Job_Daily_INV_DELY
		Job Time: 5:20 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_DELIVERY_REC  VARCHAR2(1000);
		  CREATE_TABLE_DELIVERY_REC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_DELIVERY_REC   := 'Drop table INV_SAP_LIKP_LIPS_DAILY';
		  CREATE_TABLE_DELIVERY_REC := 'CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91';
		  EXECUTE IMMEDIATE DROP_TABLE_DELIVERY_REC;
		  EXECUTE IMMEDIATE CREATE_TABLE_DELIVERY_REC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_LIKP_LIPS_DAILY; 
		CREATE TABLE INV_SAP_LIKP_LIPS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DW_DBLINK WHERE CREATED_ON_DATE > SYSDATE - 91;

	2.5 Job Name: Job_Daily_INV_PLANT
		Job Time: 5:40 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_INVENTORY_REC  VARCHAR2(1000);
		  CREATE_TABLE_INVENTORY_REC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INVENTORY_REC   := 'Drop table INV_SAP_INVENTORY_BY_PLANT';
		  CREATE_TABLE_INVENTORY_REC := 'CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
			SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_INVENTORY_REC;
		  EXECUTE IMMEDIATE CREATE_TABLE_INVENTORY_REC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_INVENTORY_BY_PLANT;
		CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DW_DBLINK;

			
	2.6 Job Name: Job_Daily_INV_PP_PO
		Job Time: 6:10 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		  CREATE_TABLE_PP_PO_HISTORY  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_PP_PO_HISTORY   := 'Drop table INV_SAP_PP_PO_HISTORY';
		  CREATE_TABLE_PP_PO_HISTORY := 'CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE DROP_TABLE_PP_PO_HISTORY;
		  EXECUTE IMMEDIATE CREATE_TABLE_PP_PO_HISTORY;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_PP_PO_HISTORY;
		CREATE TABLE INV_SAP_PP_PO_HISTORY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

	2.7 Job Name: Job_Daily_INV_IO
		Job Time: 6:40 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DECLARE
		  DROP_TABLE_IO_REC  VARCHAR2(1000);
		  CREATE_TABLE_IO_REC  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_IO_REC   := 'Drop table INV_SAP_IO_INPUTS_DAILY';
		  CREATE_TABLE_IO_REC := 'CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_IO_REC;
		  EXECUTE IMMEDIATE CREATE_TABLE_IO_REC;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_IO_INPUTS_DAILY;
		CREATE TABLE INV_SAP_IO_INPUTS_DAILY AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS_DAILY@ROCKWELL_DW_DBLINK;
				
	2.8 Job Name: Job_Weekly_INV_SO_HST
		Job Time: 2:00 AM
		Job Repeat Frequency: Weekly
		Job Procedure:
		DECLARE
		  DROP_TABLE_SALES_HST  VARCHAR2(1000);
		  CREATE_TABLE_SALES_HST  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_SALES_HST   := 'Drop table INV_SAP_SALES_HST';
		  CREATE_TABLE_SALES_HST := 'CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('||5040||', '||5050||', '||5100||', '||5110||', '||5120||', '||5160||', '||5190||', '||5200||','||5070||','||5140||')';
		  EXECUTE IMMEDIATE DROP_TABLE_SALES_HST;
		  EXECUTE IMMEDIATE CREATE_TABLE_SALES_HST;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_SALES_HST;
		CREATE TABLE INV_SAP_SALES_HST AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DW_DBLINK WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

	2.9 Job Name: Job_Weekly_INV_PP_MVKE
		Job Time: 18:00 AM SUNDAY
		Job Repeat Frequency: Weekly
		Job Procedure:
		DECLARE
		  DROP_TABLE_INV_SAP_PP_MVKE   VARCHAR2(1000);
		  CREATE_TABLE_INV_SAP_PP_MVKE VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SAP_PP_MVKE   := 'DROP TABLE INV_SAP_PP_MVKE';
		  CREATE_TABLE_INV_SAP_PP_MVKE := 'CREATE TABLE INV_SAP_PP_MVKE AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_SAP_PP_MVKE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_SAP_PP_MVKE;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_PP_MVKE;
		CREATE TABLE INV_SAP_PP_MVKE AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DW_DBLINK;

	2.10 Job Name: Job_Weekly_INV_PP_CATA
		Job Time: 20:00 AM SUNDAY
		Job Repeat Frequency: Weekly
		Job Procedure:
		DECLARE
		  CREATE_TABLE_INV_SAP_MATERIAL_CATALOG        VARCHAR2(1000);
		  DROP_TABLE_INV_SAP_MATERIAL_CATALOG              VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SAP_MATERIAL_CATALOG:= 'DROP TABLE INV_SAP_MATERIAL_CATALOG';
		  CREATE_TABLE_INV_SAP_MATERIAL_CATALOG:= 'CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK';
		  EXECUTE IMMEDIATE DROP_TABLE;
		  EXECUTE IMMEDIATE STR_CREATE_TABLE;
		END;
		
		Job Initialization: 
		DROP TABLE INV_SAP_MATERIAL_CATALOG;
		CREATE TABLE INV_SAP_MATERIAL_CATALOG AS SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DW_DBLINK;

		DROP TABLE INV_SAP_NODASH_MAT_CATA
		CREATE TABLE INV_SAP_NODASH_MAT_CATA AS SELECT * FROM INV_SAP_MATERIAL_CATALOG;
		DECLARE
		  CURSOR cur
		  IS
			SELECT a.CATALOG_STRING1,
			  b.ROWID ROW_ID
			FROM INV_SAP_MATERIAL_CATALOG a,
			  INV_SAP_NODASH_MAT_CATA b
			WHERE a.MATERIALID = b.MATERIALID
			ORDER BY b.ROWID; ---order by rowid
		  V_COUNTER NUMBER;
		BEGIN
		  V_COUNTER := 0;
		  FOR row IN cur
		  LOOP
			UPDATE INV_SAP_NODASH_MAT_CATA SET CATALOG_STRING2 = REPLACE(row.CATALOG_STRING1, '-') WHERE ROWID = row.ROW_ID;
			V_COUNTER     := V_COUNTER + 1;
			IF (V_COUNTER >= 1000) THEN
			  COMMIT;
			  V_COUNTER := 0;
			END IF;
		  END LOOP;
		  COMMIT;
		END;
		
	2.11 Job Name: Job_Monthly_INV_SHIPSOLD
		Job Time: Every month 9th 23:00 
		Job Repeat Frequency: Monthly
		Job Procedure:
		DROP TABLE INV_SAP_SHIP_SOLD_TO_PARTYID;
		CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
		SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK;
		
		DECLARE
		  DROP_TABLE_INV_SHIPSOLD  VARCHAR2(1000);
      CREATE_TABLE_INV_SHIPSOLD_DW  VARCHAR2(1000);
		  CREATE_TABLE_INV_SHIPSOLD_LO  VARCHAR2(1000);
      TRUN_INV_SHIP_SOLD  VARCHAR2(1000);
      INSERT_INV_SHIPSOLD_A  VARCHAR2(1000);
      INSERT_INV_SHIPSOLD_B  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_SHIPSOLD   := 'Drop table INV_SAP_SHIP_SOLD_TO_PARTYID';
		  CREATE_TABLE_INV_SHIPSOLD_DW := 'CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
      SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DW_DBLINK';
      CREATE_TABLE_INV_SHIPSOLD_LO := 'CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
      SELECT * FROM SYSTEM.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_LOCAL_BK';
      TRUN_INV_SHIP_SOLD := 'TRUNCATE TABLE INV_SAP_SHIP_SOLD_TO';
      INSERT_INV_SHIPSOLD_A := 'INSERT INTO INV_SAP_SHIP_SOLD_TO
          SELECT SHIP_SOLD_TOPARTY,
          SHIP_TO_PARTY_NAME,
          SHIP_TO_CITY,
          SHIP_TO_POSTAL_CODE,
          SHIP_TO_COUNTRY
        FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NOT NULL';
      INSERT_INV_SHIPSOLD_B := 'INSERT INTO INV_SAP_SHIP_SOLD_TO 
        SELECT 
        SHIP_SOLD_TOPARTY,
        SOLD_TO_PARTY_NAME,
        SOLD_TO_CITY,
        SOLD_TO_POSTAL_CODE,
        SOLD_TO_COUNTRY
        FROM INV_SAP_SHIP_SOLD_TO_PARTYID WHERE SHIP_TO_PARTY_NAME IS NULL';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_SHIPSOLD;
		  --EXECUTE IMMEDIATE CREATE_TABLE_INV_SHIPSOLD_DW;
      EXECUTE IMMEDIATE CREATE_TABLE_INV_SHIPSOLD_LO;
      EXECUTE IMMEDIATE TRUN_INV_SHIP_SOLD;
      EXECUTE IMMEDIATE INSERT_INV_SHIPSOLD_A;
      EXECUTE IMMEDIATE INSERT_INV_SHIPSOLD_B;
		END;
    

	2.12 Job Name: Job_Daily_PP_TABLE
		Job Time: 7:00 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DROP TABLE INV_SAP_PP_OPT_X;
		CREATE TABLE INV_SAP_PP_OPT_X AS
		SELECT * FROM VIEW_INV_SAP_PP_OPT_X;
		
		DECLARE
		  DROP_TABLE_INV_PP_TABLE  VARCHAR2(1000);
		  CREATE_TABLE_INV_PP_TABLE  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_PP_TABLE   := 'Drop table INV_SAP_PP_OPT_X';
		  CREATE_TABLE_INV_PP_TABLE := 'CREATE TABLE INV_SAP_PP_OPT_X AS
      SELECT * FROM VIEW_INV_SAP_PP_OPT_X';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_PP_TABLE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_PP_TABLE;
		END;
  
  2.13 Job Name: Job_Monthly_PLANT_SOG
		Job Time: Every Month Last week Sat
		Job Repeat Frequency: Monthly
		Job Procedure:
		DROP TABLE INV_SAP_PLANT_SOG;
		CREATE TABLE INV_SAP_PLANT_SOG AS
		SELECT DISTINCT PLANT, SALES_ORG FROM INV_SAP_SALES_VBAK_VBAP_VBUP;
		
		DECLARE
		  DROP_TABLE_INV_PLANT_SOG  VARCHAR2(1000);
		  CREATE_TABLE_INV_PLANT_SOG  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_PLANT_SOG   := 'Drop table INV_SAP_PLANT_SOG';
		  CREATE_TABLE_INV_PLANT_SOG := 'CREATE TABLE INV_SAP_PLANT_SOG AS
      SELECT DISTINCT PLANT, SALES_ORG FROM INV_SAP_SALES_VBAK_VBAP_VBUP';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_PLANT_SOG;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_PLANT_SOG;
		END;

	2.14 Job Name: Job_Daily_FCSTAT_TABLE
		Job Time: 7:10 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DROP TABLE INV_SAP_FC_STATS;
		CREATE TABLE INV_SAP_FC_STATS AS
		SELECT * FROM VIEW_INV_SAP_FC_STATS;
		
		DECLARE
		  DROP_TABLE_INV_FCSTAT_TABLE  VARCHAR2(1000);
		  CREATE_TABLE_INV_FCSTAT_TABLE  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_FCSTAT_TABLE   := 'Drop table INV_SAP_FC_STATS';
		  CREATE_TABLE_INV_FCSTAT_TABLE := 'CREATE TABLE INV_SAP_FC_STATS AS
      SELECT * FROM VIEW_INV_SAP_FC_STATS';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_FCSTAT_TABLE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_FCSTAT_TABLE;
		END;
    
	2.15 Job Name: Job_Daily_BLSO_TABLE
		Job Time: 7:20 AM
		Job Repeat Frequency: Daily
		Job Procedure:
		DROP TABLE INV_SAP_BACKLOG_SO;
		CREATE TABLE INV_SAP_BACKLOG_SO AS
		SELECT * FROM VIEW_INV_SAP_BACKLOG_SO;

		DECLARE
		  DROP_TABLE_INV_BLSO_TABLE  VARCHAR2(1000);
		  CREATE_TABLE_INV_BLSO_TABLE  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_BLSO_TABLE   := 'Drop table INV_SAP_BACKLOG_SO';
		  CREATE_TABLE_INV_BLSO_TABLE := 'CREATE TABLE INV_SAP_BACKLOG_SO AS
      SELECT * FROM VIEW_INV_SAP_BACKLOG_SO';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_BLSO_TABLE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_BLSO_TABLE;
		END;    
    
	2.16 Job Name: Job_Daily_BLINV_TABLE
		Job Time: 7:25 AM
		Job Repeat Frequency: Daily
		Job Procedure:
    DROP TABLE INV_SAP_BACKLOG_INV;
    CREATE TABLE INV_SAP_BACKLOG_INV AS
    SELECT * FROM VIEW_INV_SAP_BACKLOG_INV;
		
		DECLARE
		  DROP_TABLE_INV_BLINV_TABLE  VARCHAR2(1000);
		  CREATE_TABLE_INV_BLINV_TABLE  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_BLINV_TABLE   := 'Drop table INV_SAP_BACKLOG_INV';
		  CREATE_TABLE_INV_BLINV_TABLE := 'CREATE TABLE INV_SAP_BACKLOG_INV AS
      SELECT * FROM VIEW_INV_SAP_BACKLOG_INV';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_BLINV_TABLE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_BLINV_TABLE;
		END; 
      
	2.17 Job Name: Job_Daily_BLPO_TABLE
		Job Time: 7:30 AM
		Job Repeat Frequency: Daily
		Job Procedure:
    DROP TABLE INV_SAP_BACKLOG_PO;
    CREATE TABLE INV_SAP_BACKLOG_PO AS
    SELECT * FROM VIEW_INV_SAP_BACKLOG_PO;

		DECLARE
		  DROP_TABLE_INV_BLPO_TABLE  VARCHAR2(1000);
		  CREATE_TABLE_INV_BLPO_TABLE  VARCHAR2(1000);
		BEGIN
		  DROP_TABLE_INV_BLPO_TABLE   := 'Drop table INV_SAP_BACKLOG_PO';
		  CREATE_TABLE_INV_BLPO_TABLE := 'CREATE TABLE INV_SAP_BACKLOG_PO AS
      SELECT * FROM VIEW_INV_SAP_BACKLOG_PO';
		  EXECUTE IMMEDIATE DROP_TABLE_INV_BLPO_TABLE;
		  EXECUTE IMMEDIATE CREATE_TABLE_INV_BLPO_TABLE;
		END;
    
	2.18 Job Name: Job_Daily_SOST_TABLE
		Job Time: 7:35 AM
		Job Repeat Frequency: Daily
		Job Procedure:
    TRUNCATE TABLE INV_SAP_ITEM_SO_STAT;
    INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTIN13TMP;
    INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTOUT13TMP;

		DECLARE
		  TRUNCATE_TABLE_SOST  VARCHAR2(1000);
		  INSERT_TABLE_SOST_A  VARCHAR2(1000);
      INSERT_TABLE_SOST_B  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_TABLE_SOST   := 'TRUNCATE TABLE INV_SAP_ITEM_SO_STAT';
		  INSERT_TABLE_SOST_A := 'INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTIN13TMP';
      INSERT_TABLE_SOST_B := 'INSERT INTO INV_SAP_ITEM_SO_STAT SELECT * FROM VIEW_INV_SAP_IMSO_LTOUT13TMP';
      
		  EXECUTE IMMEDIATE TRUNCATE_TABLE_SOST;
		  EXECUTE IMMEDIATE INSERT_TABLE_SOST_A;
      EXECUTE IMMEDIATE INSERT_TABLE_SOST_B;
		END;  
    
    
	2.19 Job Name: Job_Daily_JOB_LOG_TABLE
		Job Time: 8:30 AM
		Job Repeat Frequency: Daily
		Job Procedure:
    CREATE TABLE INV_USER_SCHEDULE_JOB_LOG AS SELECT * FROM user_scheduler_job_log;
    CREATE TABLE INV_USER_SCHEDULE_JOB_DETAILS AS SELECT * FROM user_scheduler_job_run_details;
    TRUNCATE TABLE INV_USER_SCHEDULE_JOB_LOG;
    TRUNCATE TABLE INV_USER_SCHEDULE_JOB_DETAILS;
    INSERT INTO INV_USER_SCHEDULE_JOB_LOG SELECT * FROM user_scheduler_job_log;
    INSERT INTO INV_USER_SCHEDULE_JOB_DETAILS SELECT * FROM user_scheduler_job_run_details;

		DECLARE
		  TRUNCATE_JOB_LOG  VARCHAR2(1000);
      TRUNCATE_JOB_DETAILS  VARCHAR2(1000);
		  INSERT_TABLE_JOB_LOG  VARCHAR2(1000);
      INSERT_TABLE_JOB_DETAILS  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_JOB_LOG   := 'TRUNCATE TABLE INV_USER_SCHEDULE_JOB_LOG';
		  TRUNCATE_JOB_DETAILS := 'TRUNCATE TABLE INV_USER_SCHEDULE_JOB_DETAILS';
      INSERT_TABLE_JOB_LOG := 'INSERT INTO INV_USER_SCHEDULE_JOB_LOG SELECT * FROM user_scheduler_job_log';
      INSERT_TABLE_JOB_DETAILS := 'INSERT INTO INV_USER_SCHEDULE_JOB_DETAILS SELECT * FROM user_scheduler_job_run_details';
		  EXECUTE IMMEDIATE TRUNCATE_JOB_LOG;
		  EXECUTE IMMEDIATE TRUNCATE_JOB_DETAILS;
      EXECUTE IMMEDIATE INSERT_TABLE_JOB_LOG;
      EXECUTE IMMEDIATE INSERT_TABLE_JOB_DETAILS;
		END;
    
	2.20 Job Name: Job_Daily_SVD_TO_TABLE
		Job Time: 8:15 AM
		Job Repeat Frequency: Daily
		Job Procedure:
    CREATE TABLE INV_PP_SVD_TO_TABLE AS SELECT * FROM VIEW_INV_SAP_SVD_REPORT;
    TRUNCATE TABLE INV_PP_SVD_TO_TABLE;
    INSERT INTO INV_PP_SVD_TO_TABLE SELECT * FROM VIEW_INV_SAP_SVD_REPORT;

		DECLARE
		  TRUNCATE_SVD_TABLE  VARCHAR2(1000);
		  INSERT_TABLE_SVD  VARCHAR2(1000);
		BEGIN
		  TRUNCATE_SVD_TABLE   := 'TRUNCATE TABLE INV_PP_SVD_TO_TABLE';
      INSERT_TABLE_SVD := 'INSERT INTO INV_PP_SVD_TO_TABLE SELECT * FROM VIEW_INV_SAP_SVD_REPORT';
		  EXECUTE IMMEDIATE TRUNCATE_SVD_TABLE;
      EXECUTE IMMEDIATE INSERT_TABLE_SVD;
		END;   