SELECT FPP.MATERIALID
    ||'-'
    ||FPP.PLANTID                     AS ID,
    FPP.MATERIALID                    AS MATERIALID,
    FPP.PLANTID                       AS PLANTID,
	ROUND(SUM(FPP.PLNMG_PLANNEDQUANTITY)/13, 2) AS FORECAST_QTY,
    FPP.MEINS_BASEUNITOFMEASURE       AS UNIT,
    FPP.VERSBP_VERSION                AS VERSBP_VERSION
  FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED FPP
  WHERE (FPP.PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
  AND VERSBP_VERSION = '55'
  AND MATERIALID    IN
    (SELECT MATERIALID
    FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
    WHERE CURRENT_SERIES  = 'X'
    AND DIRECT_SHIP_PLANT = 'sql_plantid'
    AND EXISTS
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
      WHERE CATALOG_STRING1 IN (sql_materials)
      AND MVK.MATERIALID     = ISMC.MATERIALID
      )
    )
  AND PLANTID IN
    (SELECT VP.PLANTID
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = 'sql_plantid'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = 'sql_plantid'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN (sql_materials)
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    UNION ALL
    SELECT VP.EXPECTED_SHIP_PLANT_1
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = 'sql_plantid'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = 'sql_plantid'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN (sql_materials)
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    )
  GROUP BY FPP.MATERIALID,
    FPP.PLANTID,
    FPP.MEINS_BASEUNITOFMEASURE,
    FPP.VERSBP_VERSION,
    FPP.MATERIALID
    ||'-'
    ||FPP.PLANTID