SELECT POPR.ITEM             AS ITEM,
  POPR.PLANT            AS PLANT,
  FPPR.UNIT             AS UNIT,
  FPPR.VERSBP_VERSION   AS VERSBP_VERSION,
  POPR.SAFETY_STOCK     AS SAFETY_STOCK,
  POPR.STRATEGY_GRP     AS STRATEGY_GRP,
  POPR.ON_HAND_STOCK    AS ON_HAND_STOCK,
  POPR.LEAD_TIME        AS LEAD_TIME,
  POPR.AVG52_USAGE_QTY  AS AVG52_USAGE_QTY_By_Year,
  POPR.AVG26_USAGE_QTY  AS AVG26_USAGE_QTY_By_HalfYear,
  POPR.AVG13_USAGE_QTY  AS AVG13_USAGE_QTY_By_Quarter,
  ROUND(FPPR.PLANNED_QUANTITY, 2) AS FORECAST_QTY
FROM
  (SELECT POP.MATERIALID
    ||'-'
    ||POP.PLANTID                  AS ID,
    POP.MATERIALID                 AS ITEM,
    POP.PLANTID                    AS PLANT,
    POP.MAT_DESC                   AS DESCRIPTION,
    POP.SAFETY_STK                 AS SAFETY_STOCK,
    POP.STRATEGY_GRP               AS STRATEGY_GRP,
    POP.OH_QTY                     AS ON_HAND_STOCK,
    POP.UNIT_COST                  AS UNIT_COST,
    POP.PROD_BU                    AS PROD_BU,
    POP.VENDOR_NAME                AS VENDOR,
    POP.ANNUAL52_PLANT_VOLUMNE_QTY AS ANNUAL52,
    POP.AVG52_USAGE_QTY            AS AVG52_USAGE_QTY,
    POP.AVG26_USAGE_QTY            AS AVG26_USAGE_QTY,
    POP.AVG13_USAGE_QTY            AS AVG13_USAGE_QTY,
    POP.PDT                        AS LEAD_TIME
  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION POP
  WHERE MATERIALID IN
    (SELECT MATERIALID
    FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
    WHERE CURRENT_SERIES  = 'X'
    AND DIRECT_SHIP_PLANT = '5040'
    AND EXISTS
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
      WHERE CATALOG_STRING1 IN ('1756-EN2T','1202-C03' ,'1734-IE2V' ,'1734-IR2' ,'1734-OB8' ,'1734-OE2V' ,'1734-OW2' ,'1734-TBS' ,'1756-A17' ,'1756-ENBT' ,'1756-IB32' ,'1756-M16SE')
      AND MVK.MATERIALID     = ISMC.MATERIALID
      )
    )
  AND PLANTID IN
    (SELECT VP.PLANTID
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = '5040'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = '5040'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN ('1756-EN2T','1202-C03' ,'1734-IE2V' ,'1734-IR2' ,'1734-OB8' ,'1734-OE2V' ,'1734-OW2' ,'1734-TBS' ,'1756-A17' ,'1756-ENBT' ,'1756-IB32' ,'1756-M16SE')
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    UNION ALL
    SELECT VP.EXPECTED_SHIP_PLANT_1
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = '5040'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = '5040'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN ('1756-EN2T','1202-C03' ,'1734-IE2V' ,'1734-IR2' ,'1734-OB8' ,'1734-OE2V' ,'1734-OW2' ,'1734-TBS' ,'1756-A17' ,'1756-ENBT' ,'1756-IB32' ,'1756-M16SE')
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    )
  ) POPR
LEFT JOIN
  (SELECT FPP.MATERIALID
    ||'-'
    ||FPP.PLANTID                     AS ID,
    FPP.MATERIALID                    AS MATERIALID,
    FPP.PLANTID                       AS PLANTID,
    SUM(FPP.PLNMG_PLANNEDQUANTITY)/13 AS PLANNED_QUANTITY,
    FPP.MEINS_BASEUNITOFMEASURE       AS UNIT,
    FPP.VERSBP_VERSION                AS VERSBP_VERSION
  FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED FPP
  WHERE (FPP.PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
  AND VERSBP_VERSION = '55'
  AND MATERIALID    IN
    (SELECT MATERIALID
    FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
    WHERE CURRENT_SERIES  = 'X'
    AND DIRECT_SHIP_PLANT = '5040'
    AND EXISTS
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
      WHERE CATALOG_STRING1 IN ('1756-EN2T','1202-C03' ,'1734-IE2V' ,'1734-IR2' ,'1734-OB8' ,'1734-OE2V' ,'1734-OW2' ,'1734-TBS' ,'1756-A17' ,'1756-ENBT' ,'1756-IB32' ,'1756-M16SE')
      AND MVK.MATERIALID     = ISMC.MATERIALID
      )
    )
  AND PLANTID IN
    (SELECT VP.PLANTID
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = '5040'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = '5040'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN ('1756-EN2T','1202-C03' ,'1734-IE2V' ,'1734-IR2' ,'1734-OB8' ,'1734-OE2V' ,'1734-OW2' ,'1734-TBS' ,'1756-A17' ,'1756-ENBT' ,'1756-IB32' ,'1756-M16SE')
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    UNION ALL
    SELECT VP.EXPECTED_SHIP_PLANT_1
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = '5040'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = '5040'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN ('1756-EN2T','1202-C03' ,'1734-IE2V' ,'1734-IR2' ,'1734-OB8' ,'1734-OE2V' ,'1734-OW2' ,'1734-TBS' ,'1756-A17' ,'1756-ENBT' ,'1756-IB32' ,'1756-M16SE')
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    )
  GROUP BY FPP.MATERIALID,
    FPP.PLANTID,
    FPP.MEINS_BASEUNITOFMEASURE,
    FPP.VERSBP_VERSION,
    FPP.MATERIALID
    ||'-'
    ||FPP.PLANTID
  ) FPPR
ON POPR.ID = FPPR.ID;


