SELECT POP.MATERIALID
    ||'-'
    ||POP.PLANTID                  AS ID,
    POP.MATERIALID                 AS ITEM,
    POP.PLANTID                    AS PLANT,
	POP.PDT                        AS LEAD_TIME,
    POP.SAFETY_STK                 AS SAFETY_STOCK,
    POP.STRATEGY_GRP               AS STRATEGY_GRP,
    POP.OH_QTY                     AS ON_HAND_STOCK,
    POP.VENDOR_NAME                AS VENDOR,
    POP.ANNUAL52_PLANT_VOLUMNE_QTY AS ANNUAL52,
    POP.AVG52_USAGE_QTY            AS AVG52_USAGE_QTY,
    POP.AVG26_USAGE_QTY            AS AVG26_USAGE_QTY,
    POP.AVG13_USAGE_QTY            AS AVG13_USAGE_QTY
  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION POP
  WHERE MATERIALID IN
    (SELECT MATERIALID
    FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
    WHERE CURRENT_SERIES  = 'X'
    AND DIRECT_SHIP_PLANT = 'sql_plantid'
    AND EXISTS
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
      WHERE CATALOG_STRING1 IN (sql_materials)
      AND MVK.MATERIALID     = ISMC.MATERIALID
      )
    )
  AND PLANTID IN
    (SELECT VP.PLANTID
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = 'sql_plantid'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = 'sql_plantid'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN (sql_materials)
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    UNION ALL
    SELECT VP.EXPECTED_SHIP_PLANT_1
    FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO VP
    WHERE PLANTID   = 'sql_plantid'
    AND MATERIALID IN
      (SELECT MATERIALID
      FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE MVK
      WHERE CURRENT_SERIES  = 'X'
      AND DIRECT_SHIP_PLANT = 'sql_plantid'
      AND EXISTS
        (SELECT MATERIALID
        FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG ISMC
        WHERE CATALOG_STRING1 IN (sql_materials)
        AND MVK.MATERIALID     = ISMC.MATERIALID
        )
      )
    )