---------------------------------------------------------------------------
--Backlog report sql file
---SO detail information
---PO detail information
---PR detail information
---INV detail information
---------------------------------------------------------------------------

----SO detail information
----Need to add ship-to information and Customer Name
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID ;

Select * from DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP where SALESDOC = '6501808127'; 
Select * from DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP where LINECREATEDATE = '15-APR-14' and plant = '1090'; 
Select * from DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP where MATERIAL = '1756-N2 B' and plant = '5050';


SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP WHERE SALES_ORG = '5003'AND PLANT NOT IN ('5040');
----Ship-To&Sold-To Info
-----Sold-To Party
select * from DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID where SHIP_SOLD_TOPARTY = '91312213';

-----Ship-To Party
select * from DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID where SHIP_SOLD_TOPARTY = '91316290';

---------------------------------------------
---ADD GAP COL COMMITTED DATE - COMFIRM DATE
SELECT
  (MAX_COMMIT_DATE-MAX_CONFIRM_DATE) AS GAP
FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP;

--LINE BLOCK
SELECT
  CASE
    WHEN MAX_COMMIT_DATE IS NULL OR MAX_CONFIRM_DATE IS NULL
    THEN 'OVERALL BLOCKED/CREDIT BLOCK'
    ELSE
    'NO_BLOCK'
  END LINE_BLOCK
FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP;

---SOLD TO PATY INFORMAITON
SELECT STPT_S.ID,
STPT_S.SOLD_TO_PARTY,
STPT_P.CUSTOMER_NAME
FROM
  (SELECT SALESDOC
    ||'_'
    || SALESDOCITEM AS ID,
    SOLD_TO         AS SOLD_TO_PARTY
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
  )STPT_S
LEFT JOIN
  (SELECT SHIP_SOLD_TOPARTY AS SOLD_TO_PARTY,
    SHIP_TO_PARTY_NAME      AS CUSTOMER_NAME
  FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID
  ) STPT_P
ON STPT_P.SOLD_TO_PARTY = STPT_S.SOLD_TO_PARTY;

--DEFAULT Delivery Block
SELECT 
  SALE_BK.ID AS ID,
  SALE_BK.MATERIAL AS MATERIAL,
  MVKE_BK.D_CHAIN_BLK AS D_CHAIN_BLK
FROM 
(
  SELECT 
    SALESDOC
    ||'_'
    || SALESDOCITEM AS ID,
    MATERIAL
    ||'_'
    || PLANT AS ID1,
    MATERIAL,
    PLANT
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
)SALE_BK
LEFT JOIN
(
SELECT MATERIALID
  ||'_'
  ||DIRECT_SHIP_PLANT AS ID,
  MATERIALID,
  D_CHAIN_BLK,
  DIRECT_SHIP_PLANT
FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE
)MVKE_BK
ON MVKE_BK.ID = SALE_BK.ID1;

--Add Catalog#
SELECT 
  SALE_MA.ID AS ID,
  SALE_MA.MATERIAL AS MATERIAL,
  MA_CA.CATALOG_STRING1 AS CATALOG_STRING
FROM 
(
  SELECT 
    SALESDOC
    ||'_'
    || SALESDOCITEM AS ID,
    MATERIAL
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
)SALE_MA
LEFT JOIN
(SELECT CATALOG_STRING1,
  MATERIALID
FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG
)MA_CA
ON MA_CA.MATERIALID = SALE_MA.MATERIAL;

--INFORMATION  FROM PP TABLE
SELECT  
  SOFR_PP.ID AS ID,
  PP.PLANTID AS PLANT,
  PP.MATERIALID AS MATERIAL,
  PP.MAT_DESC AS MATERIAL_DES,
  PP.SAFETY_STK AS SAFTY_STOCK,
  PP.OH_QTY AS OH_QTY,
  PP.PROD_BU AS PROD_BU,
  PP.PROD_FAM AS PROD_FAM,
  PP.PROD_HIERARCHY AS PROD_HIERARCHY,
  PP.MRP_CONTROLLER AS MRP_CONTROLLER,
  PP.PURCH_GROUP AS PURCH_GROUP,
  PP.PROC_TYPE AS PROC_TYPE,
  PP.PROD_SCHEDULER AS PROD_SCHEDULER,
  PP.LOT_SIZE_DISLS AS LOT_SIZE_DIS,
  PP.MEINS_ISSUE_UOM AS UNIT,
  PP.STRATEGY_GRP AS STRATEGY_GRP,
  PP.MRP_TYPE AS MRP_TYPE
FROM
(SELECT SALESDOC
    ||'_'
    || SALESDOCITEM AS ID,
    MATERIAL
    ||'_'
    || PLANT AS ID1,
    MATERIAL,
    PLANT
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
)SOFR_PP
LEFT JOIN
(SELECT 
  MATERIALID
    ||'_'
    || PLANTID AS ID1,
  MATERIALID,
  PLANTID,
  MAT_DESC,
  SAFETY_STK,
  OH_QTY,
  SUBSTR(PROD_BU,0,3) AS PROD_BU,
  PROD_FAM,
  PROD_HIERARCHY,
  MRP_CONTROLLER,
  PURCH_GROUP,
  PROC_TYPE,
  PROD_SCHEDULER,
  LOT_SIZE_DISLS,
  MEINS_ISSUE_UOM,
  STRATEGY_GRP,
  MRP_TYPE
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION
)PP
ON PP.ID1 = SOFR_PP.ID1;



----PR detail information

SELECT *
FROM DWQ$LIBRARIAN.INV_SAP_PO_EKPO
WHERE PLANTID              = '5050'
AND MATERIALID             = '1756-N2 B'
AND ELIKZDELIVERYCOMPLETE IS NULL;

select * from DWQ$LIBRARIAN.INV_SAP_PO_EKPO WHERE PLANTID in('5050','5040') AND ELIKZDELIVERYCOMPLETE is null;



--BACKLOG REPORT
--1. SO ORDER TAB

SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK WHERE PLANT = '5040';

--Add block status
SELECT DIRECT_SHIP_PLANT||'_'||MATERIALID AS ID, MATERIALID, D_CHAIN_BLK FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DBLINK;
 
--Add Catalog#
SELECT CATALOG_STRING1, MATERIALID FROM CATALOG_NODASH_MATERIAL WHERE MATERIALID IN ('PN-154319');
 
--SO Details

SELECT SALES_PP.ID                   AS ID,
  SALES_PP.SALESDOC                  AS SALES_DOC,
  SALES_PP.SALESDOCITEM              AS ITEM,
  SALES_PP.MATERIAL                  AS MATERIAL,
  SALES_PP.PLANT                     AS PLANT,
  SALES_PP.LINECREATEDATE            AS LINE_CREATE_DATE,
  SALES_PP.PRODHIER                  AS BU,
  SALES_PP.ORDERQTY                  AS ORDER_QTY,
  SALES_PP.CONFIRMQTY                AS CONFIRM_QTY,
  SALES_PP.DELIVPRIO                 AS DELIVERY_PRIORITY,
  SALES_PP.LINECREATEDCOUNTER        AS LINECREATEDCOUNTER,
  SALES_PP.PROFITCENTER              AS PROFIT_CENTER,
  SALES_PP.SALESPRICE                AS SALES_PRICE,
  SALES_PP.COST                      AS COST,
  SALES_PP.STOCKSTATUS               AS STOCK_STATUS,
  SALES_PP.MAX_COMMIT_DATE           AS COMMITTED_DATE,
  SALES_PP.REQTYPE                   AS REQUEST_TYPE,
  SALES_PP.PSPT                      AS PAST_ORDER_NUMBER,
  SALES_PP.HEADERCREATECOUNTER       AS HEADERCREATECOUNTER,
  SALES_PP.MAX_CONFIRM_DATE          AS CONFIRM_DATE,
  SALES_PP.DELIVSTATUS               AS DELIVERY_STATUS,
  SALES_PP.REJECTSTATUS              AS REJECTSTATUS,
  SALES_PP.SALESDOCTYPE              AS SALES_DOC_TYPE,
  SALES_PP.SALEDOCITEMCATEGORY_PSTYV AS SALEDOCITEMCATEGORY_PSTYV,
  SALES_PP.SHIPFROM_VSTEL            AS SHIPPING_POINT,
  SALES_PP.SALES_ORG                 AS SALES_ORG,
  SALES_PP.CURRENCY                  AS CURRENCY,
  SALES_PP.OPEN_QTY                  AS OPEN_QTY,
  SALES_PP.OPEN_QTY_BASE_UOM         AS OPEN_QTY_BASE_UOM,
  SALES_PP.LST_ACT_GI_DATE           AS LST_ACT_GI_DATE,
  SALES_PP.LST_DELV_CREATED_DATE     AS LST_DELV_CREATED_DATE,
  SALES_PP.EXCHANGE_RATE_TO_USD      AS RATE,
  SALES_PP.MATERIAL_DES              AS MATERIAL_DES,
  SALES_PP.SAFTY_STOCK               AS SAFTY_STOCK,
  SALES_PP.OH_QTY                    AS OH_QTY,
  SALES_PP.PROD_BU                   AS PROD_BU,
  SALES_PP.PROD_FAM                  AS PROD_FAM,
  SALES_PP.PROD_HIERARCHY            AS PROD_HIERARCHY,
  SALES_PP.MRP_CONTROLLER            AS MRP_CONTROLLER,
  SALES_PP.PURCH_GROUP               AS PURCH_GROUP,
  SALES_PP.PROC_TYPE                 AS PROC_TYPE,
  SALES_PP.PROD_SCHEDULER            AS PROD_SCHEDULER,
  SALES_PP.LOT_SIZE_DIS              AS LOT_SIZE_DIS,
  SALES_PP.UNIT                      AS UNIT,
  SALES_PP.STRATEGY_GRP              AS STRATEGY_GRP,
  SALES_PP.MRP_TYPE                  AS MRP_TYPE,
  PT_BK.SOLD_TO_PARTY                AS SOLD_TO_PARTY,
  PT_BK.CUSTOMER_NAME                AS CUSTOMER_NAME,
  PT_BK.MATERIAL                     AS MATERIAL,
  PT_BK.D_CHAIN_BLK                  AS D_CHAIN_BLK
FROM
  (SELECT SALES_BASE.ID AS ID,
    SALES_BASE.SALESDOC,
    SALES_BASE.SALESDOCITEM,
    SALES_BASE.MATERIAL,
    SALES_BASE.PLANT,
    SALES_BASE.LINECREATEDATE,
    SALES_BASE.PRODHIER,
    SALES_BASE.ORDERQTY,
    SALES_BASE.CONFIRMQTY,
    SALES_BASE.DELIVPRIO,
    SALES_BASE.LINECREATEDCOUNTER,
    SALES_BASE.PROFITCENTER,
    SALES_BASE.SALESPRICE,
    SALES_BASE.COST,
    SALES_BASE.STOCKSTATUS,
    SALES_BASE.MAX_COMMIT_DATE,
    SALES_BASE.REQTYPE,
    SALES_BASE.PSPT,
    SALES_BASE.HEADERCREATECOUNTER,
    SALES_BASE.MAX_CONFIRM_DATE,
    SALES_BASE.SOLD_TO,
    SALES_BASE.SALESOFF,
    SALES_BASE.TELE,
    SALES_BASE.DELIVSTATUS,
    SALES_BASE.OVERALLDELIVSTATSU,
    SALES_BASE.REJECTSTATUS,
    SALES_BASE.DW_DATE,
    SALES_BASE.SALESDOCTYPE,
    SALES_BASE.REJECTREASON_ABGRU,
    SALES_BASE.SALEDOCITEMCATEGORY_PSTYV,
    SALES_BASE.REQ_DELIVERYQTY_LSMENG,
    SALES_BASE.SHIPFROM_VSTEL,
    SALES_BASE.SALES_ORG,
    SALES_BASE.CURRENCY,
    SALES_BASE.NUMERATOR,
    SALES_BASE.DENOMINATOR,
    SALES_BASE.OPEN_QTY,
    SALES_BASE.OPEN_QTY_BASE_UOM,
    SALES_BASE.LST_ACT_GI_DATE,
    SALES_BASE.LST_DELV_CREATED_DATE,
    SALES_BASE.EXCHANGE_RATE_TO_USD,
    PPINF.MATERIAL_DES   AS MATERIAL_DES,
    PPINF.SAFTY_STOCK    AS SAFTY_STOCK,
    PPINF.OH_QTY         AS OH_QTY,
    PPINF.PROD_BU        AS PROD_BU,
    PPINF.PROD_FAM       AS PROD_FAM,
    PPINF.PROD_HIERARCHY AS PROD_HIERARCHY,
    PPINF.MRP_CONTROLLER AS MRP_CONTROLLER,
    PPINF.PURCH_GROUP    AS PURCH_GROUP,
    PPINF.PROC_TYPE      AS PROC_TYPE,
    PPINF.PROD_SCHEDULER AS PROD_SCHEDULER,
    PPINF.LOT_SIZE_DIS   AS LOT_SIZE_DIS,
    PPINF.UNIT           AS UNIT,
    PPINF.STRATEGY_GRP   AS STRATEGY_GRP,
    PPINF.MRP_TYPE       AS MRP_TYPE
  FROM
    (SELECT SALESDOC
      ||'_'
      || SALESDOCITEM AS ID,
      SALESDOC,
      SALESDOCITEM,
      MATERIAL,
      PLANT,
      LINECREATEDATE,
      PRODHIER,
      ORDERQTY,
      CONFIRMQTY,
      DELIVPRIO,
      LINECREATEDCOUNTER,
      PROFITCENTER,
      SALESPRICE,
      COST,
      STOCKSTATUS,
      MAX_COMMIT_DATE,
      REQTYPE,
      PSPT,
      HEADERCREATECOUNTER,
      MAX_CONFIRM_DATE,
      SOLD_TO,
      SALESOFF,
      TELE,
      DELIVSTATUS,
      OVERALLDELIVSTATSU,
      REJECTSTATUS,
      DW_DATE,
      SALESDOCTYPE,
      REJECTREASON_ABGRU,
      SALEDOCITEMCATEGORY_PSTYV,
      REQ_DELIVERYQTY_LSMENG,
      SHIPFROM_VSTEL,
      SALES_ORG,
      CURRENCY,
      NUMERATOR,
      DENOMINATOR,
      OPEN_QTY,
      OPEN_QTY_BASE_UOM,
      LST_ACT_GI_DATE,
      LST_DELV_CREATED_DATE,
      EXCHANGE_RATE_TO_USD
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP
    )SALES_BASE
  LEFT JOIN
    (SELECT SOFR_PP.ID   AS ID,
      PP.PLANTID         AS PLANT,
      PP.MATERIALID      AS MATERIAL,
      PP.MAT_DESC        AS MATERIAL_DES,
      PP.SAFETY_STK      AS SAFTY_STOCK,
      PP.OH_QTY          AS OH_QTY,
      PP.PROD_BU         AS PROD_BU,
      PP.PROD_FAM        AS PROD_FAM,
      PP.PROD_HIERARCHY  AS PROD_HIERARCHY,
      PP.MRP_CONTROLLER  AS MRP_CONTROLLER,
      PP.PURCH_GROUP     AS PURCH_GROUP,
      PP.PROC_TYPE       AS PROC_TYPE,
      PP.PROD_SCHEDULER  AS PROD_SCHEDULER,
      PP.LOT_SIZE_DISLS  AS LOT_SIZE_DIS,
      PP.MEINS_ISSUE_UOM AS UNIT,
      PP.STRATEGY_GRP    AS STRATEGY_GRP,
      PP.MRP_TYPE        AS MRP_TYPE
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SOFR_PP
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        || PLANTID AS ID1,
        MATERIALID,
        PLANTID,
        MAT_DESC,
        SAFETY_STK,
        OH_QTY,
        SUBSTR(PROD_BU,0,3) AS PROD_BU,
        PROD_FAM,
        PROD_HIERARCHY,
        MRP_CONTROLLER,
        PURCH_GROUP,
        PROC_TYPE,
        PROD_SCHEDULER,
        LOT_SIZE_DISLS,
        MEINS_ISSUE_UOM,
        STRATEGY_GRP,
        MRP_TYPE
      FROM INV_SAP_PP_OPTIMIZATION
      )PP
    ON PP.ID1          = SOFR_PP.ID1
    )PPINF ON PPINF.ID = SALES_BASE.ID
  )SALES_PP
LEFT JOIN
  (SELECT SOLD_PT.ID      AS ID,
    SOLD_PT.SOLD_TO_PARTY AS SOLD_TO_PARTY,
    SOLD_PT.CUSTOMER_NAME AS CUSTOMER_NAME,
    ITEM_BK.MATERIAL      AS MATERIAL,
    ITEM_BK.D_CHAIN_BLK   AS D_CHAIN_BLK
  FROM
    (
    ---SOLD TO PATY INFORMAITON
    SELECT STPT_S.ID,
      STPT_S.SOLD_TO_PARTY,
      STPT_P.CUSTOMER_NAME
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        SOLD_TO         AS SOLD_TO_PARTY
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )STPT_S
    LEFT JOIN
      (SELECT SHIP_SOLD_TOPARTY AS SOLD_TO_PARTY,
        SHIP_TO_PARTY_NAME      AS CUSTOMER_NAME
      FROM INV_SAP_SHIP_SOLD_TO_PARTYID
      ) STPT_P
    ON STPT_P.SOLD_TO_PARTY = STPT_S.SOLD_TO_PARTY
    )SOLD_PT
  LEFT JOIN
    (
    --DEFAULT Delivery Block
    SELECT SALE_BK.ID     AS ID,
      SALE_BK.MATERIAL    AS MATERIAL,
      MVKE_BK.D_CHAIN_BLK AS D_CHAIN_BLK
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SALE_BK
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||DIRECT_SHIP_PLANT AS ID,
        MATERIALID,
        D_CHAIN_BLK,
        DIRECT_SHIP_PLANT
      FROM INV_SAP_PP_MVKE
      )MVKE_BK
    ON MVKE_BK.ID          = SALE_BK.ID1
    )ITEM_BK ON ITEM_BK.ID = SOLD_PT.ID
  )PT_BK ON PT_BK.ID       = SALES_PP.ID;


 
 --2. PO TAB
 
---STO_OPEN_QTY

SELECT EBELNPURCHDOCNO,
  MATERIALID,
  PLANTID,
  PO_SO_SA_FLAG,
  SUM(COMMITTEDQTY) AS OPEN_QTY
FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
WHERE PLANTID         = '5050'
AND PO_SO_SA_FLAG     = 'STO'
AND DELIVERYCOMPLETE IS NULL
GROUP BY MATERIALID,
  PLANTID,
  EBELNPURCHDOCNO,
  PO_SO_SA_FLAG;

---Line count 

SELECT EBELNPURCHDOCNO
  ||'_'
  ||MATERIALID AS ID,
  MATERIALID,
  PLANTID,
  SUM(PLANTID)/PLANTID AS LINECOUNT
FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
WHERE PLANTID = '5050'
GROUP BY EBELNPURCHDOCNO
  ||'_'
  ||MATERIALID,
  MATERIALID,
  PLANTID; --,EBELNPURCHDOCNO--,ETENRPURCHDELIVSCHLINE;


SELECT EBELNPURCHDOCNO
  ||'_'
  ||MATERIALID AS ID,
  PLANTID,
  EBELNPURCHDOCNO,
  MATERIALID,
  ETENRPURCHDELIVSCHLINE,
  SLFDTSTATDELIVERYDATE,
  COMMITTED_DATE
FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
WHERE PLANTID       = '5050'
AND MATERIALID      = 'PN-D13004'
AND EBELNPURCHDOCNO = '6301317677';


SELECT * FROM PO_DETAIL_DEMO;
DROP TABLE PO_DETAIL_DEMO;
CREATE TABLE PO_DETAIL_DEMO AS
SELECT PO_HIS.ID                AS ID,
  PO_HIS.PO                     AS PO,
  PO_HIS.LINE                   AS LINE,
  PO_HIS.MATERIAL               AS MATERIAL,
  PO_HIS.PLANT                  AS PLANT,
  PO_HIS.PURCHDOCCAT            AS PURCHDOCCAT,
  PO_HIS.PURCHDOC_TYPE          AS PURCHDOC_TYPE,
  PO_HIS.STATUSPURCHDOC         AS STATUSPURCHDOC,
  PO_HIS.VENDOR                 AS VENDOR,
  PO_HIS.PURCHDELIVSCH_LINE     AS PURCHDELIVSCH_LINE,
  PO_HIS.PURHCASE_QTY           AS PURHCASE_QTY,
  PO_HIS.RECEIVED_QTY           AS RECEIVED_QTY,
  PO_HIS.START_DELIVER_DATE     AS START_DELIVER_DATE,
  PO_HIS.DELIVERY_COMPLETE_FLAG AS DELIVERY_COMPLETE_FLAG,
  PO_HIS.COMMITTED_DATE         AS COMMITTED_DATE,
  PO_HIS.COMMITTED_QTY          AS COMMITTED_QTY,
  PO_HIS.COMMIT_VS_CONFIRM      AS COMMIT_VS_CONFIRM,
  PO_HIS.PO_SO_SA_FLAG          AS PO_SO_SA_FLAG,
  PO_HIS.CREATED_DATE           AS CREATED_DATE,
  PO_HIS.CURRENCY               AS CURRENCY,
  PO_HIS.ORDER_VALUE            AS ORDER_VALUE,
  PO_HIS.LEAD_TIME              AS LEAD_TIME,
  PO_HIS.MRP_CONTROLLER         AS MRP_CONTROLLER,
  PO_HIS.PROC_KEY               AS PROC_KEY,
  PO_HIS.PURCH_GROUP            AS PURCH_GROUP,
  PO_HIS.STRATEGY_GRP           AS STRATEGY_GRP,
  PO_HIS.UNIT_COST              AS UNIT_COST,
  PO_HIS.PR                     AS PR,
  PO_HIS.SHIPPING_POINT         AS SHIPPING_POINT,
  PO_HIS.DELIVERY_PRIORITY      AS DELIVERY_PRIORITY,
  PO_HIS.ROUTE                  AS ROUTE,
  PO_HIS.TRANSIT_DAYS           AS TRANSIT_DAYS,
  SPLIT_LINE_DELIVERY.COUNT     AS COUNT
FROM
  (SELECT EBELNPURCHDOCNO
    ||'_'
    ||MATERIALID             AS ID,
    MATERIALID               AS MATERIAL,
    PLANTID                  AS PLANT,
    BSTYP_PURCHDOCCAT        AS PURCHDOCCAT,
    BSART_PURCHDOCTYPE       AS PURCHDOC_TYPE,
    STATU_STATUSPURCHDOC     AS STATUSPURCHDOC,
    LIFNR_VENDORNO           AS VENDOR,
    EBELNPURCHDOCNO          AS PO,
    EBELPPURCHITEMNO         AS LINE,
    ETENRPURCHDELIVSCHLINESA AS PURCHDELIVSCH_LINE,
    MENGESCHEDULEDQTY        AS PURHCASE_QTY,
    WEMNGRECEIVEDQTY         AS RECEIVED_QTY,
    SLFDTSTATDELIVERYDATE    AS START_DELIVER_DATE,
    DELIVERYCOMPLETE         AS DELIVERY_COMPLETE_FLAG,
    COMMITTED_DATE           AS COMMITTED_DATE,
    COMMITTEDQTY             AS COMMITTED_QTY,
    COMMIT_CONFIRM_SUM       AS COMMIT_VS_CONFIRM,
    PO_SO_SA_FLAG            AS PO_SO_SA_FLAG,
    CREATED_DATE             AS CREATED_DATE,
    WAERS_CURRENCYKEY        AS CURRENCY,
    NETWRNETORDERVALUE       AS ORDER_VALUE,
    LT                       AS LEAD_TIME,
    MRP_CONTROLLER           AS MRP_CONTROLLER,
    SPC_PROC_KEY             AS PROC_KEY,
    PURCH_GROUP              AS PURCH_GROUP,
    STRATEGY_GRP             AS STRATEGY_GRP,
    UNIT_COST                AS UNIT_COST,
    PURCH_REQ                AS PR,
    SHIPPING_POINT           AS SHIPPING_POINT,
    DELIVERY_PRIORITY        AS DELIVERY_PRIORITY,
    ROUTE                    AS ROUTE,
    TRANSIT_DAYS             AS TRANSIT_DAYS
  FROM INV_SAP_PP_PO_HISTORY
  WHERE DELIVERYCOMPLETE        IS NULL
  AND ETENRPURCHDELIVSCHLINESA = '1'
  )PO_HIS
LEFT JOIN
(SELECT ID,
  MATERIALID,
  PLANTID,
  CASE
    WHEN LINECOUNT = '1'
    THEN 1
    ELSE (LINECOUNT - 1)
  END COUNT
FROM
  (SELECT EBELNPURCHDOCNO
    ||'_'
    ||MATERIALID AS ID,
    MATERIALID,
    PLANTID,
    SUM(PLANTID)/PLANTID AS LINECOUNT
  FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY
  GROUP BY EBELNPURCHDOCNO
    ||'_'
    ||MATERIALID,
    MATERIALID,
    PLANTID
  )
LEFT JOIN
  (SELECT EBELNPURCHDOCNO
    ||'_'
    ||MATERIALID AS ID,
    EBELNPURCHDOCNO,
    MATERIALID,
    PLANTID,
    PO_SO_SA_FLAG,
    SUM(COMMITTEDQTY) AS OPEN_QTY
  FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
  WHERE DELIVERYCOMPLETE IS NULL
  GROUP BY MATERIALID,
    PLANTID,
    EBELNPURCHDOCNO,
    PO_SO_SA_FLAG
  )
)SPLIT_LINE_DELIVERY
ON SPLIT_LINE_DELIVERY.ID = PO_HIS.ID;




--PARCIAL_SHIPMENT_LINE_COUNT
SELECT ID,
  MATERIALID,
  PLANTID,
  CASE
    WHEN LINECOUNT = '1'
    THEN 1
    ELSE (LINECOUNT - 1)
  END COUNT
FROM LINE_DEMO_TEST;

CREATE TABLE LINE_DEMO_TEST AS 
SELECT ID,
  MATERIALID,
  PLANTID,
  LINECOUNT
FROM
  (SELECT EBELNPURCHDOCNO
    ||'_'
    ||MATERIALID AS ID,
    MATERIALID,
    PLANTID,
    SUM(PLANTID)/PLANTID AS LINECOUNT
  FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
  WHERE PLANTID IN ('5050')
  GROUP BY EBELNPURCHDOCNO
    ||'_'
    ||MATERIALID,
    MATERIALID,
    PLANTID,
    EBELNPURCHDOCNO
  );

----INV detail information
----Need to Supplier,	Supplier Stock, Safty Stock, Item Leadtime, Item Standard Cost, Item Description,ABC_Class
----STRATEGY_GRP
----Status: Done!!!
CREATE TABLE INV_SAP_INVENTORY_BY_PLANT AS

--BASIC DATA 
SELECT MATERIAL
  ||'_'
  ||PLANTID  AS ID,
  MATERIALID AS MATERIAL,
  PLANTID    AS PLANT,
  LOCATIONID AS LOCATION,
  OH_QTY     AS OH_QTY,
  ASOFDATE   AS LAST_REVIEW_DATE
FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DBLINK
WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') ---ALL PLANTS HERE!!
  ;






--Sales Orders Status
SELECT BACKLOG_OPEN.ID            AS ID,
  BACKLOG_OPEN.OPEN_QTY           AS BACKLOG_OPEN,
  PAST_DUE_OPEN.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN
FROM
  (SELECT MATERIAL
    ||'_'
    ||PLANT       AS ID,
    MATERIAL      AS MATERIALID,
    PLANT         AS PLANTID,
    SUM(OPEN_QTY) AS OPEN_QTY
  FROM INV_SAP_SALES_VBAK_VBAP_VBUP
  WHERE PLANT IN ('5040', '5070', '5100', '5110', '5140', '5200') ---All Plants
  GROUP BY MATERIAL
    ||'_'
    ||PLANT,
    MATERIAL,
    PLANT
  )BACKLOG_OPEN
LEFT JOIN
  (SELECT MATERIAL
    ||'_'
    ||PLANT               AS ID,
    MATERIAL              AS MATERIALID,
    PLANT                 AS PLANTID,
    NVL(SUM(OPEN_QTY), 0) AS PAST_DUE_OPEN_QTY
  FROM INV_SAP_SALES_VBAK_VBAP_VBUP
  WHERE PLANT                  IN ('5040', '5070', '5100', '5110', '5140', '5200') ---All Plants
  AND MAX_COMMIT_DATE < SYSDATE - 1
  GROUP BY MATERIAL
    ||'_'
    ||PLANT,
    MATERIAL,
    PLANT
  )PAST_DUE_OPEN
ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID;

---STO_OPEN_QTY
SELECT EBELNPURCHDOCNO,
  MATERIALID,
  PLANTID,
  PO_SO_SA_FLAG,
  SUM(COMMITTEDQTY) AS OPEN_QTY
FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
WHERE PLANTID         = '5050'
AND PO_SO_SA_FLAG     = 'STO'
AND DELIVERYCOMPLETE IS NULL
GROUP BY MATERIALID,
  PLANTID,
  EBELNPURCHDOCNO,
  PO_SO_SA_FLAG; 
  
  
---Material Details
SELECT MATERIALID
  ||'_'
  ||PLANTID            AS ID,
  MATERIALID           AS MATERIALID,
  PLANTID              AS PLANTID,
  MAT_DESC             AS Material_Description,
  PROD_BU              AS BU,
  PROC_TYPE            AS Procurement_Type,
  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_ID,
  MRP_CONTROLLER       AS MRP_CONTROLLER,
  MATL_TYPE_MTART      AS MATL_TYPE,
  MRP_TYPE             AS MRP_TYPE,
  STRATEGY_GRP         AS Stock_Strategy,
  UNIT_COST            AS Unit_Price,
  REORDER_PT           AS Reorder_Point,
  SAFETY_STK           AS Safety_stock_Qty,
  PDT                  AS PDT
FROM INV_SAP_PP_OPTIMIZATION
WHERE PLANTID IN ('5040', '5070', '5100', '5110', '5140', '5200') --- ALL PLANTS HERE!!
  ;

---Generate INV_DEMO_REPORT REPORT
DROP TABLE INV_DEMO_REPORT;
SELECT * FROM INV_DEMO_REPORT;
CREATE TABLE INV_DEMO_REPORT AS 
SELECT 
  INV_ITEM_BASIC.LAST_REVIEW_DATE      AS LAST_REVIEW_DATE,
  INV_ITEM_BASIC.ID               AS ID,
  INV_ITEM_BASIC.PLANT                 AS PLANT,
  INV_ITEM_BASIC.MATERIAL              AS MATERIAL,
  INV_ITEM_BASIC.TOTAL_QTY             AS TOTAL_QTY,
  INV_ITEM_BASIC.LOCATION              AS LOCATION,
  INV_ITEM_BASIC.Material_Description  AS Material_Description,
  INV_ITEM_BASIC.Safety_Stock_Qty      AS Safety_Stock_Qty,
  INV_ITEM_BASIC.LEAD_TIME                   AS LEAD_TIME,
  STO_SALES_OPEN_QTY.BACKLOG_OPEN_QTY  AS BACKLOG_OPEN_QTY,
  STO_SALES_OPEN_QTY.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN_QTY,
  STO_SALES_OPEN_QTY.PO_SO_SA_FLAG     AS PO_SO_SA_FLAG,
  STO_SALES_OPEN_QTY.STO_OPEN_QTY      AS STO_OPEN_QTY,
  INV_ITEM_BASIC.BU                    AS BU,
  INV_ITEM_BASIC.Procurement_Type      AS Procurement_Type,
  INV_ITEM_BASIC.MATL_TYPE             AS MATL_TYPE,
  INV_ITEM_BASIC.MRP_TYPE              AS MRP_TYPE,
  INV_ITEM_BASIC.Stock_Strategy        AS Stock_Strategy
FROM
  (SELECT INV_BASIC.ID              AS ID,
    INV_BASIC.PLANT                 AS PLANT,
    INV_BASIC.MATERIAL              AS MATERIAL,
    INV_BASIC.TOTAL_QTY             AS TOTAL_QTY,
    INV_BASIC.LAST_REVIEW_DATE      AS LAST_REVIEW_DATE,
    INV_BASIC.LOCATION              AS LOCATION,
    ITEM_BASIC.Material_Description AS Material_Description,
    ITEM_BASIC.BU                   AS BU,
    ITEM_BASIC.Procurement_Type     AS Procurement_Type,
    ITEM_BASIC.MATL_TYPE            AS MATL_TYPE,
    ITEM_BASIC.MRP_TYPE             AS MRP_TYPE,
    ITEM_BASIC.Stock_Strategy       AS Stock_Strategy,
    ITEM_BASIC.Safety_Stock_Qty     AS Safety_Stock_Qty,
    ITEM_BASIC.LEAD_TIME                  AS LEAD_TIME
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID     AS ID,
      MATERIALID    AS MATERIAL,
      PLANTID       AS PLANT,
      LOCATIONID    AS LOCATION,
      NVL(OH_QTY,0) AS TOTAL_QTY,
      ASOFDATE      AS LAST_REVIEW_DATE
    FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') --- ALL PLANTS HERE!!
    )INV_BASIC
  LEFT JOIN
    (SELECT MATERIALID
      ||'_'
      ||PLANTID            AS ID,
      MATERIALID           AS MATERIALID,
      PLANTID              AS PLANTID,
      MAT_DESC             AS Material_Description,
      PROD_BU              AS BU,
      PROC_TYPE            AS Procurement_Type,
      MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_ID,
      MRP_CONTROLLER       AS MRP_CONTROLLER,
      MATL_TYPE_MTART      AS MATL_TYPE,
      MRP_TYPE             AS MRP_TYPE,
      STRATEGY_GRP         AS Stock_Strategy,
      UNIT_COST            AS Unit_Price,
      NVL(REORDER_PT,0)    AS Reorder_Point,
      NVL(SAFETY_STK,0)    AS Safety_Stock_Qty,
      (GRT+PDT)                 AS LEAD_TIME
    FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') --- ALL PLANTS HERE!!
    )ITEM_BASIC
  ON ITEM_BASIC.ID = INV_BASIC.ID
  )INV_ITEM_BASIC
LEFT JOIN
  (
  --OPEN STATUS
  SELECT SALES_OPEN_PASS_QTY.ID           AS ID,
    SALES_OPEN_PASS_QTY.BACKLOG_OPEN_QTY  AS BACKLOG_OPEN_QTY,
    SALES_OPEN_PASS_QTY.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN_QTY,
    STO_OPEN_QTY_S.PO_SO_SA_FLAG          AS PO_SO_SA_FLAG,
    STO_OPEN_QTY_S.STO_OPEN_QTY           AS STO_OPEN_QTY
  FROM
    (
    --Sales Orders Status
    SELECT BACKLOG_OPEN.ID                   AS ID,
      NVL(BACKLOG_OPEN.OPEN_QTY,0)           AS BACKLOG_OPEN_QTY,
      NVL(PAST_DUE_OPEN.PAST_DUE_OPEN_QTY,0) AS PAST_DUE_OPEN_QTY
    FROM
      (SELECT MATERIAL
        ||'_'
        ||PLANT              AS ID,
        MATERIAL             AS MATERIALID,
        PLANT                AS PLANTID,
        NVL(SUM(OPEN_QTY),0) AS OPEN_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')  ---All Plants
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )BACKLOG_OPEN
    LEFT JOIN
      (SELECT MATERIAL
        ||'_'
        ||PLANT               AS ID,
        MATERIAL              AS MATERIALID,
        PLANT                 AS PLANTID,
        NVL(SUM(OPEN_QTY), 0) AS PAST_DUE_OPEN_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') ---All Plants
      AND MAX_COMMIT_DATE < SYSDATE - 1
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )PAST_DUE_OPEN
    ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID
    )SALES_OPEN_PASS_QTY
  LEFT JOIN
    ---STO_OPEN_QTY
    (
    SELECT MATERIALID
      ||'_'
      ||PLANTID AS ID,
      MATERIALID,
      PLANTID,
      PO_SO_SA_FLAG,
      NVL(SUM(COMMITTEDQTY),0) AS STO_OPEN_QTY
    FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
    WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') ---All Plants
    AND PO_SO_SA_FLAG     = 'STO'
    AND DELIVERYCOMPLETE IS NULL
    GROUP BY MATERIALID,
      PLANTID,
      PO_SO_SA_FLAG
    )STO_OPEN_QTY_S
  ON SALES_OPEN_PASS_QTY.ID                    = STO_OPEN_QTY_S.ID
  )STO_SALES_OPEN_QTY ON STO_SALES_OPEN_QTY.ID = INV_ITEM_BASIC.ID;
