--Porject Name: Basic Function View
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:09/26/2014
--Summary: Automation Files Center Job Logs and set up process
--VIEW_INV_SAP_FC55_STATS&VIEW_INV_SAP_FC00_STATS

--VIEW_INV_SAP_FC55_STATS VERSBP_VERSION = '55'
		DROP VIEW VIEW_INV_SAP_FC55_STATS;
		SELECT * FROM VIEW_INV_SAP_FC55_STATS;
		CREATE VIEW VIEW_INV_SAP_FC55_STATS AS
		SELECT ITEM_BASIC_PP_FC13.ID,
		  ITEM_BASIC_PP_FC13.MATERIAL,
		  ITEM_BASIC_PP_FC13.CATALOG_DASH,
		  ITEM_BASIC_PP_FC13.CATALOG_NO_DASH,
		  ITEM_BASIC_PP_FC13.PLANT,
		  ITEM_BASIC_PP_FC13.MAT_DESC,
		  ITEM_BASIC_PP_FC13.SAFETY_STOCK,
		  ITEM_BASIC_PP_FC13.OH_QTY,
		  ITEM_BASIC_PP_FC13.UNIT,
		  ITEM_BASIC_PP_FC13.PROC_TYPE,
		  ITEM_BASIC_PP_FC13.UNIT_COST,
		  ITEM_BASIC_PP_FC13.PROD_BU,
		  ITEM_BASIC_PP_FC13.STRATEGY_GRP,
		  ITEM_BASIC_PP_FC13.MRP_TYPE,
		  ITEM_BASIC_PP_FC13.MRP_CONTROLLER,
		  ITEM_BASIC_PP_FC13.PURCH_GROUP,
		  ITEM_BASIC_PP_FC13.VENDOR_ITEM,
		  ITEM_BASIC_PP_FC13.MATL_TYPE,
		  ITEM_BASIC_PP_FC13.MIN_INV,
		  ITEM_BASIC_PP_FC13.TARGET_INV,
		  ITEM_BASIC_PP_FC13.MAX_INV,
		  ITEM_BASIC_PP_FC13.LEAD_TIME,
		  ITEM_BASIC_PP_FC13.AVG26_USAGE_QTY,
		  ITEM_BASIC_PP_FC13.AVG13_USAGE_QTY,
		  ITEM_BASIC_PP_FC13.FC_AVG13_WEEK_QTY,
		  FC_AVG26_WEEK.FC_AVG26_WEEK_QTY
		FROM
		  (SELECT ITEM_BASIC_PP.ID,
			ITEM_BASIC_PP.MATERIAL,
			ITEM_BASIC_PP.CATALOG_DASH,
			ITEM_BASIC_PP.CATALOG_NO_DASH,
			ITEM_BASIC_PP.PLANT,
			ITEM_BASIC_PP.MAT_DESC,
			ITEM_BASIC_PP.SAFETY_STOCK,
			ITEM_BASIC_PP.UNIT,
			ITEM_BASIC_PP.OH_QTY,
			ITEM_BASIC_PP.PROC_TYPE,
			ITEM_BASIC_PP.UNIT_COST,
			ITEM_BASIC_PP.PROD_BU,
			ITEM_BASIC_PP.STRATEGY_GRP,
			ITEM_BASIC_PP.MRP_TYPE,
			ITEM_BASIC_PP.MRP_CONTROLLER,
			ITEM_BASIC_PP.PURCH_GROUP,
			ITEM_BASIC_PP.VENDOR_ITEM,
			ITEM_BASIC_PP.MATL_TYPE,
			ITEM_BASIC_PP.MIN_INV,
			ITEM_BASIC_PP.TARGET_INV,
			ITEM_BASIC_PP.MAX_INV,
			ITEM_BASIC_PP.LEAD_TIME,
			ITEM_BASIC_PP.AVG26_USAGE_QTY,
			ITEM_BASIC_PP.AVG13_USAGE_QTY,
			FC_AVG13_WEEK.FC_AVG13_WEEK_QTY
		  FROM
			(SELECT ID,
			  MATERIAL,
			  CATALOG_DASH,
			  CATALOG_NO_DASH,
			  PLANT,
			  MAT_DESC,
			  SAFETY_STOCK,
			  UNIT,
			  PROC_TYPE,
			  UNIT_COST,
			  PROD_BU,
			  STRATEGY_GRP,
			  MRP_TYPE,
			  MRP_CONTROLLER,
			  PURCH_GROUP,
			  VENDOR_ITEM,
			  OH_QTY,
			  MATL_TYPE,
			  MIN_INV,
			  TARGET_INV,
			  MAX_INV,
			  LEAD_TIME,
			  AVG26_USAGE_QTY,
			  AVG13_USAGE_QTY
			FROM INV_SAP_PP_OPT_X
			)ITEM_BASIC_PP
		  LEFT JOIN
			(SELECT MATERIALID
			  ||'_'
			  ||PLANTID                           AS ID,
			  MATERIALID                          AS MATERIALID,
			  PLANTID                             AS PLANTID,
			  CEIL(SUM(PLNMG_PLANNEDQUANTITY)/13) AS FC_AVG13_WEEK_QTY
			FROM INV_SAP_PP_FRCST_PBIM_PBED
			WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
			AND VERSBP_VERSION = '55'
			GROUP BY MATERIALID,
			  PLANTID
			)FC_AVG13_WEEK
		  ON FC_AVG13_WEEK.ID = ITEM_BASIC_PP.ID
		  )ITEM_BASIC_PP_FC13
		LEFT JOIN
		  (SELECT MATERIALID
			||'_'
			||PLANTID                           AS ID,
			MATERIALID                          AS MATERIALID,
			PLANTID                             AS PLANTID,
			CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK_QTY
		  FROM INV_SAP_PP_FRCST_PBIM_PBED
		  WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
		  AND VERSBP_VERSION = '55'
		  GROUP BY MATERIALID,
			PLANTID
		  )FC_AVG26_WEEK
		ON ITEM_BASIC_PP_FC13.ID = FC_AVG26_WEEK.ID; 

--VIEW_INV_SAP_FC00_STATS VERSBP_VERSION = '00'
		DROP VIEW VIEW_INV_SAP_FC00_STATS;
		SELECT * FROM VIEW_INV_SAP_FC00_STATS;
		CREATE VIEW VIEW_INV_SAP_FC00_STATS AS
		SELECT ITEM_BASIC_PP_FC13.ID,
		  ITEM_BASIC_PP_FC13.MATERIAL,
		  ITEM_BASIC_PP_FC13.CATALOG_DASH,
		  ITEM_BASIC_PP_FC13.CATALOG_NO_DASH,
		  ITEM_BASIC_PP_FC13.PLANT,
		  ITEM_BASIC_PP_FC13.MAT_DESC,
		  ITEM_BASIC_PP_FC13.SAFETY_STOCK,
		  ITEM_BASIC_PP_FC13.OH_QTY,
		  ITEM_BASIC_PP_FC13.UNIT,
		  ITEM_BASIC_PP_FC13.PROC_TYPE,
		  ITEM_BASIC_PP_FC13.UNIT_COST,
		  ITEM_BASIC_PP_FC13.PROD_BU,
		  ITEM_BASIC_PP_FC13.STRATEGY_GRP,
		  ITEM_BASIC_PP_FC13.MRP_TYPE,
		  ITEM_BASIC_PP_FC13.MRP_CONTROLLER,
		  ITEM_BASIC_PP_FC13.PURCH_GROUP,
		  ITEM_BASIC_PP_FC13.VENDOR_ITEM,
		  ITEM_BASIC_PP_FC13.MATL_TYPE,
		  ITEM_BASIC_PP_FC13.MIN_INV,
		  ITEM_BASIC_PP_FC13.TARGET_INV,
		  ITEM_BASIC_PP_FC13.MAX_INV,
		  ITEM_BASIC_PP_FC13.LEAD_TIME,
		  ITEM_BASIC_PP_FC13.AVG26_USAGE_QTY,
		  ITEM_BASIC_PP_FC13.AVG13_USAGE_QTY,
		  ITEM_BASIC_PP_FC13.FC_AVG13_WEEK_QTY,
		  FC_AVG26_WEEK.FC_AVG26_WEEK_QTY
		FROM
		  (SELECT ITEM_BASIC_PP.ID,
			ITEM_BASIC_PP.MATERIAL,
			ITEM_BASIC_PP.CATALOG_DASH,
			ITEM_BASIC_PP.CATALOG_NO_DASH,
			ITEM_BASIC_PP.PLANT,
			ITEM_BASIC_PP.MAT_DESC,
			ITEM_BASIC_PP.SAFETY_STOCK,
			ITEM_BASIC_PP.UNIT,
			ITEM_BASIC_PP.OH_QTY,
			ITEM_BASIC_PP.PROC_TYPE,
			ITEM_BASIC_PP.UNIT_COST,
			ITEM_BASIC_PP.PROD_BU,
			ITEM_BASIC_PP.STRATEGY_GRP,
			ITEM_BASIC_PP.MRP_TYPE,
			ITEM_BASIC_PP.MRP_CONTROLLER,
			ITEM_BASIC_PP.PURCH_GROUP,
			ITEM_BASIC_PP.VENDOR_ITEM,
			ITEM_BASIC_PP.MATL_TYPE,
			ITEM_BASIC_PP.MIN_INV,
			ITEM_BASIC_PP.TARGET_INV,
			ITEM_BASIC_PP.MAX_INV,
			ITEM_BASIC_PP.LEAD_TIME,
			ITEM_BASIC_PP.AVG26_USAGE_QTY,
			ITEM_BASIC_PP.AVG13_USAGE_QTY,
			FC_AVG13_WEEK.FC_AVG13_WEEK_QTY
		  FROM
			(SELECT ID,
			  MATERIAL,
			  CATALOG_DASH,
			  CATALOG_NO_DASH,
			  PLANT,
			  MAT_DESC,
			  SAFETY_STOCK,
			  UNIT,
			  PROC_TYPE,
			  UNIT_COST,
			  PROD_BU,
			  STRATEGY_GRP,
			  MRP_TYPE,
			  MRP_CONTROLLER,
			  PURCH_GROUP,
			  VENDOR_ITEM,
			  OH_QTY,
			  MATL_TYPE,
			  MIN_INV,
			  TARGET_INV,
			  MAX_INV,
			  LEAD_TIME,
			  AVG26_USAGE_QTY,
			  AVG13_USAGE_QTY
			FROM INV_SAP_PP_OPT_X
			)ITEM_BASIC_PP
		  LEFT JOIN
			(SELECT MATERIALID
			  ||'_'
			  ||PLANTID                           AS ID,
			  MATERIALID                          AS MATERIALID,
			  PLANTID                             AS PLANTID,
			  CEIL(SUM(PLNMG_PLANNEDQUANTITY)/13) AS FC_AVG13_WEEK_QTY
			FROM INV_SAP_PP_FRCST_PBIM_PBED
			WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
			AND VERSBP_VERSION = '00'
			GROUP BY MATERIALID,
			  PLANTID
			)FC_AVG13_WEEK
		  ON FC_AVG13_WEEK.ID = ITEM_BASIC_PP.ID
		  )ITEM_BASIC_PP_FC13
		LEFT JOIN
		  (SELECT MATERIALID
			||'_'
			||PLANTID                           AS ID,
			MATERIALID                          AS MATERIALID,
			PLANTID                             AS PLANTID,
			CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK_QTY
		  FROM INV_SAP_PP_FRCST_PBIM_PBED
		  WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
		  AND VERSBP_VERSION = '00'
		  GROUP BY MATERIALID,
			PLANTID
		  )FC_AVG26_WEEK
		ON ITEM_BASIC_PP_FC13.ID = FC_AVG26_WEEK.ID; 