--DBTOOLS
--AUTHOR:Huang Moyue
--DATE:04/08/2014

--VIEW SALS HST LOC
DROP VIEW VIEW_INV_SAP_SALES_HST_LC;
CREATE VIEW VIEW_INV_SAP_SALES_HST_LC AS
SELECT SOH_SOSH.ID,
  SOH_SOSH.MATERIAL,
  SOH_SOSH.CATALOG#,
  SOH_SOSH.SALES_DOC,
  SOH_SOSH.ITEM,
  ITEM_BSC.SAFETY_STOCK,
  ITEM_BSC.OH_QTY,
  ITEM_BSC.STRATEGY_GRP,
  ITEM_BSC.MRP_TYPE,
  ITEM_BSC.MATL_TYPE,
  ITEM_BSC.VENDOR,
  ITEM_BSC.BU,
  ITEM_BSC.LEAD_TIME,
  ITEM_BSC.PDT,
  ITEM_BSC.UNIT_COST,
  ITEM_BSC.MRP_CONTROLLER,
  SOH_SOSH.SOLD_TO_PARTY,
  SOH_SOSH.SOLD_TO_NAME,
  SOH_SOSH.SHIP_TO_PARTY,
  SOH_SOSH.SHIP_TO_NAME,
  SOH_SOSH.COMMITTED_DATE,
  SOH_SOSH.LAST_GI_DATE,
  SOH_SOSH.CREATION_DATE,
  SOH_SOSH.REQUEST_DATE,
  SOH_SOSH.PLANT,
  SOH_SOSH.SO_TYPE,
  SOH_SOSH.ORDER_QTY,
  SOH_SOSH.OPEN_QTY,
  SOH_SOSH.SALES_ORG,
  SOH_SOSH.CURRENCY,
  SOH_SOSH.SHIPPING_POINT,
  ITEM_BSC.ULTIMATE_SOURCE
FROM
  (SELECT SO_HST_SOLD.ID,
    SO_HST_SOLD.MATERIAL,
    SO_HST_SOLD.CATALOG#,
    SO_HST_SOLD.SALES_DOC,
    SO_HST_SOLD.ITEM,
    SO_HST_SOLD.SOLD_TO_PARTY,
    SO_HST_SOLD.SOLD_TO_NAME,
    SO_HST_SOLD.SHIP_TO_PARTY,
    ADDRESS_SHIP.SHIP_SOLD_TO_PARTY_NAME AS SHIP_TO_NAME,
    SO_HST_SOLD.COMMITTED_DATE,
    SO_HST_SOLD.LAST_GI_DATE,
    SO_HST_SOLD.CREATION_DATE,
    SO_HST_SOLD.REQUEST_DATE,
    SO_HST_SOLD.PLANT,
    SO_HST_SOLD.SO_TYPE,
    SO_HST_SOLD.ORDER_QTY,
    SO_HST_SOLD.OPEN_QTY,
    SO_HST_SOLD.SALES_ORG,
    SO_HST_SOLD.CURRENCY,
    SO_HST_SOLD.SHIPPING_POINT
  FROM
    (SELECT SO_HST.ID,
      SO_HST.MATERIAL,
      SO_HST.CATALOG#,
      SO_HST.SALES_DOC,
      SO_HST.ITEM,
      SO_HST.SOLD_TO_PARTY,
      ADDRESS.SHIP_SOLD_TO_PARTY_NAME AS SOLD_TO_NAME,
      SO_HST.SHIP_TO_PARTY,
      SO_HST.COMMITTED_DATE,
      SO_HST.LAST_GI_DATE,
      SO_HST.CREATION_DATE,
      SO_HST.REQUEST_DATE,
      SO_HST.PLANT,
      SO_HST.SO_TYPE,
      SO_HST.ORDER_QTY,
      SO_HST.OPEN_QTY,
      SO_HST.SALES_ORG,
      SO_HST.CURRENCY,
      SO_HST.SHIPPING_POINT
    FROM
      (SELECT MATERIALID
        ||'_'
        ||PLANTID            AS ID,
        MATERIALID           AS MATERIAL,
        CATALOGID            AS CATALOG#,
        SALESDOC             AS SALES_DOC,
        SALESDOCITEM         AS ITEM,
        LPAD(SOLDTOPARTY,10,'0')          AS SOLD_TO_PARTY,
        LPAD(SHIPTOPARTY,10,'0')          AS SHIP_TO_PARTY,
        COMMITTEDDATE        AS COMMITTED_DATE,
        LASTACTGIDATE        AS LAST_GI_DATE,
        LINECREATIONDATE     AS CREATION_DATE,
        REQUIREDDELIVERYDATE AS REQUEST_DATE,
        PLANTID              AS PLANT,
        SALESDOCTYPE         AS SO_TYPE,
        ORDERQTY             AS ORDER_QTY,
        OPENQTY              AS OPEN_QTY,
        SALES_ORG            AS SALES_ORG,
        CURRENCY             AS CURRENCY,
        SHIPPING_POINT       AS SHIPPING_POINT
      FROM INV_SAP_SALES_HST
      )SO_HST
    LEFT JOIN
      (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
        SHIP_SOLD_TO_PARTY_NAME
      FROM INV_SAP_SHIP_SOLD_TO
      )ADDRESS
    ON ADDRESS.SHIP_SOLD_TO_PARTY = SO_HST.SOLD_TO_PARTY
    )SO_HST_SOLD
  LEFT JOIN
    (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
      SHIP_SOLD_TO_PARTY_NAME
    FROM INV_SAP_SHIP_SOLD_TO
    )ADDRESS_SHIP
  ON ADDRESS_SHIP.SHIP_SOLD_TO_PARTY = SO_HST_SOLD.SHIP_TO_PARTY
  )SOH_SOSH
LEFT JOIN
  (SELECT ID,
    MATERIAL,
    PLANT,
    CATALOG_DASH,
    SAFETY_STOCK,
    OH_QTY,
    STRATEGY_GRP,
    MATL_TYPE,
    MRP_TYPE,
    SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
    SUBSTR(PROD_BU,0,3)    AS BU,
    LEAD_TIME,
    PDT,
    UNIT_COST,
    MRP_CONTROLLER,
    ULTIMATE_SOURCE
  FROM INV_SAP_PP_OPT_X
  )ITEM_BSC
ON ITEM_BSC.ID = SOH_SOSH.ID;

select * from INV_SAP_INVENTORY_BY_PLANT where materialid = 'PN-204747' and plantid = '5140'
1.
SELECT ID,
  PLANT,
  MATERIAL,
  CATALOG#,
  SALES_DOC,
  ITEM,
  STRATEGY_GRP,
  LEAD_TIME,
  PDT,
  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  SHIP_TO_PARTY,
  SHIP_TO_NAME,
  COMMITTED_DATE,
  LAST_GI_DATE,
  CREATION_DATE,
  REQUEST_DATE,
  ORDER_QTY,
  OPEN_QTY,
  SALES_ORG,
  CURRENCY
FROM VIEW_INV_SAP_SALES_HST_LC
WHERE PLANT = 'PlantId'
AND CREATION_DATE BETWEEN 'From_Date' AND 'To_Date';
  
  
  SELECT * FROM INV_SAP_IO_INPUTS_DAILY WHERE MATERIALid = '100CX25ZJ10' AND PLANTID = '5040'

2.

SELECT ID,
  PLANT,
  MATERIAL,
  CATALOG#,
  SALES_DOC,
  ITEM,
  STRATEGY_GRP,
  LEAD_TIME,
  PDT,
  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  SHIP_TO_PARTY,
  SHIP_TO_NAME,
  COMMITTED_DATE,
  LAST_GI_DATE,
  CREATION_DATE,
  REQUEST_DATE,
  ORDER_QTY,
  OPEN_QTY,
  SALES_ORG,
  CURRENCY
FROM VIEW_INV_SAP_SALES_HST_LC
WHERE PLANT = 'PlantId'
 AND MATERIAL = 'Material' AND CREATION_DATE BETWEEN 'From_Date' AND 'To_Date';

3.
SELECT ID,
  PLANT,
  MATERIAL,
  CATALOG#,
  SALES_DOC,
  ITEM,
  STRATEGY_GRP,
  LEAD_TIME,
  PDT,
  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  SHIP_TO_PARTY,
  SHIP_TO_NAME,
  COMMITTED_DATE,
  LAST_GI_DATE,
  CREATION_DATE,
  REQUEST_DATE,
  ORDER_QTY,
  OPEN_QTY,
  SALES_ORG,
  CURRENCY
FROM VIEW_INV_SAP_SALES_HST_LC
 WHERE SALES_DOC =  'SALESDOC_Replace' 

