---Find MaterialID and check with X current seri
DROP TABLE MATEIAL_CATALOG_X;
CREATE TABLE MATEIAL_CATALOG_X AS
SELECT 
  ISPM.MATERIALID,
  ISPM.CURRENT_SERIES,
  ISMC.CATALOG_STRING1,
  ISMC.CATALOG_STRING2
FROM
  (SELECT MATERIALID,
    CURRENT_SERIES,
    DIRECT_SHIP_PLANT
  FROM INV_SAP_PP_MVKE
  )ISPM
LEFT JOIN
  (SELECT MATERIALID,
    CATALOG_STRING1,
    CATALOG_STRING2
  FROM CATALOG_NODASH_MATERIAL
  )ISMC
ON ISPM.MATERIALID = ISMC.MATERIALID;
  
SELECT * FROM MATEIAL_CATALOG_X WHERE CATALOG_STRING2 IN ('8019056002R',
'8019056021R') AND CURRENT_SERIES IS NOT NULL;
