--DATE:08132014
--AUTHOR:HUANG MOYUE
--GRT CHECK

SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN PLANT = '5040' AND GRT < 7
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END LS_CHECK
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5040'), '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

-- FOR DIFF PLANTS, USE DIFF CODE TO CHECK.
SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN GRT < 7
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END GRT_CHECK,
  7 AS ST_D
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5040');

SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN GRT < 6
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END GRT_CHECK,
  6 AS ST_D
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5070');

SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN GRT < 2
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END GRT_CHECK,
  2 AS ST_D
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5110','5050');

SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN GRT < 5
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END GRT_CHECK,
  5 AS ST_D
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5140','5160','5190','5200','5120','5100');
