--DATE:08132014
--AUTHOR:HUANG MOYUE
--GRT CHECK

SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN PLANT = '5040' AND GRT < 7
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END LS_CHECK
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5040'), '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');








SELECT PLANT,
  MATERIAL,
  GRT,
  CASE
    WHEN GRT < 7
    THEN 'Need To Check'
    ELSE 'Changed Done'
  END GRT_CHECK
FROM INV_SAP_PP_OPT_X
WHERE PLANT IN ('5040');











MERGE INTO INV_SAP_SVD_COMMENTS SVD_COM USING
(SELECT ID,
  LAST_COMMENT_DATE,
  COMMENTS,
  PLANNER,
  LAST_UPDATE_DATE
FROM INV_SAP_SVD_COMMENTS_TMP
) TMP ON ( SVD_COM.ID=TMP.ID)
WHEN MATCHED THEN
  UPDATE
  SET SVD_COM.LAST_COMMENT_DATE = TMP.LAST_COMMENT_DATE,
    SVD_COM.COMMENTS            = TMP.COMMENTS,
    SVD_COM.PLANNER             = TMP.PLANNER,
    SVD_COM.LAST_UPDATE_DATE    = TMP.LAST_UPDATE_DATE WHEN NOT MATCHED THEN
  INSERT VALUES
    (
      TMP.ID,
      TMP.LAST_COMMENT_DATE,
      TMP.COMMENTS,
      TMP.PLANNER,
      TMP.LAST_UPDATE_DATE
    )


CREATE TABLE INV_SAP_SVD_COMME_TMP AS 
SELECT * FROM INV_SAP_SVD_COMMENTS







"INSERT
INTO INV_SAP_SVD_COMMENTS_TMP
  (
    ID,
    LAST_COMMENT_DATE,
    COMMENTS,
    PLANNER,
    LAST_UPDATE_DATE
  )
  VALUES
  (
    'ID_1',
    SYSDATE_1,
    'COMMENTS_1',
    'PLANNER_1',
    SYSDATE_2
  )"
