
SELECT * FROM
(
SELECT 
PO_HIS.ID,
PO_HIS.MATERIALID,
PO_HIS.PLANTID,
PO_HIS.EBELNPURCHDOCNO,
PO_HIS.EBELPPURCHITEMNO,
PO_HIS.TOTALRECIEVEDYQTY,
PO_HIS.SLFDTSTATDELIVERYDATE,
PP.UNIT_COST,
PP.MATL_TYPE,
(NVL(PP.UNIT_COST,0)*NVL(PO_HIS.TOTALRECIEVEDYQTY,0)) AS PO_ITEM_VAL
FROM
(
SELECT 
MATERIALID||'_'||PLANTID AS ID,
EBELNPURCHDOCNO,
EBELPPURCHITEMNO,
MATERIALID,
PLANTID,
SLFDTSTATDELIVERYDATE,
TOTALRECIEVEDYQTY
FROM INV_SAP_PP_PO_HISTORY WHERE DELIVERYCOMPLETE = 'X0'  
AND PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140','5130','5150','5180')
AND SLFDTSTATDELIVERYDATE BETWEEN TO_CHAR(SYSDATE- 325) AND TO_CHAR(SYSDATE)
)PO_HIS
LEFT JOIN
(
SELECT ID, UNIT_COST,MATL_TYPE FROM INV_SAP_PP_OPT_X
)PP
ON PP.ID = PO_HIS.ID
)WHERE TOTALRECIEVEDYQTY <> 0