 --Porject Name: Automation Files Center
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:07/08/2014
--Summary: Automation Files Center Job Logs and set up process
--Version: 0.5


SELECT MATERIALID||'_'||(PLANTID-1) AS ID,LEADTIME_WEEKS FROM INV_SAP_PP_OPTIMIZATION WHERE STRATEGY_GRP = '40' AND PLANTID IN ('5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141');


SELECT MATERIALID, MATL_TYPE,SPC_PROC_KEY_SOBSL  FROM INV_SAP_PRODUCTION_PARAMETERS WHERE PLANTID = '5040';

SELECT COUNT(*) FROM INV_SAP_PP_OPTIMIZATION WHERE PLANTID = '5040';
SELECT MATERIALID, CATALOG_STRING1 FROM INV_SAP_NODASH_MAT_CATA WHERE MATERIALID = '1489-A2D320 A';

SELECT MATERIALID, D_CHAIN_BLK FROM INV_SAP_PP_MVKE WHERE MATERIALID = '1489-A2D320 A';

SELECT MATERIALID,SPC_PROC_KEY_SOBSL,SP_MATL_STAT_MMSTA FROM INV_SAP_PP_OPTIMIZATION WHERE MATERIALID = '1489-A2D320 A';

SELECT * FROM INV_SAP_SALES_HST WHERE MATERIALID = '855T-B24TA3 C' AND PLANTID = '5040'

SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_PARAM@ROCKWELL_DW_DBLINK WHERE MATERIALID = '855T-B24TA3 C' AND PLANTID = '5040'


SELECT *
FROM
  (SELECT MATERIALID,
    MATL_TYPE,
    SPC_PROC_KEY_SOBSL
  FROM INV_SAP_PRODUCTION_PARAMETERS
  WHERE PLANTID = '5040'
  AND MATL_TYPE = 'ZREP'
  )SP
LEFT JOIN
  (SELECT MATERIALID, CATALOG_STRING1 FROM INV_SAP_NODASH_MAT_CATA WHERE MATERIALID = '1489-A2D320 A'
  )PPM
ON PPM.MATERIALID = SP.MATERIALID



SELECT count(*)
FROM
  (SELECT MATERIALID,
    MATL_TYPE,
    SPC_PROC_KEY_SOBSL
  FROM INV_SAP_PRODUCTION_PARAMETERS
  WHERE PLANTID = '5040'
  --AND MATL_TYPE = 'ZREP'
  )
  
  
SELECT *
FROM INV_SAP_PP_OPTIMIZATION
WHERE PLANTID = '5040' AND MATL_TYPE_MTART = 'ZREP' AND MATERIALID = 'PN-117435'
  

------------------------------------------------------------------------------------------------------------------------

--Upload the ZREP CATA info
SELECT * FROM INV_SAP_ZREP_ITEM_CATALOG;
TRUNCATE TABLE INV_SAP_ZREP_ITEM_CATALOG;
INSERT
INTO INV_SAP_ZREP_ITEM_CATALOG
  (
    MATERIAL,
    CATALOG
  )
  VALUES
  (
    'MATL_1',
    'CATA_1'
  );
  
-- Upload the COO info
SELECT * FROM INV_SAP_ITEM_COO WHERE MATERIAL = 'PN-281525';
TRUNCATE TABLE INV_SAP_ITEM_COO;
INSERT
INTO INV_SAP_ITEM_COO
  (
    MATERIAL,
    COO,
    HS_CODE,
    ECCN
  )
  VALUES
  (
    'MATL_1',
    'COO_1',
    'HSCODE_1',
    'ECCN_1'
  );
  
--Pre-Classification Items(NO ZREP)
SELECT ITEM_BASCMC.MATERIALID,
  ITEM_BASCMC.CATALOG_STRING1,
  ITEM_BASCMC.MATL_TYPE_MTART,
  ITEM_BASCMC.PROD_BU,
  MATL_DC.D_CHAIN_BLK,
  ITEM_BASCMC.SP_MATL_STAT_MMSTA,
  ITEM_BASCMC.MAT_DESC,
  ITEM_BASCMC.COO,
  ITEM_BASCMC.HS_CODE,
  ITEM_BASCMC.VENDOR,
  ITEM_BASCMC.SPC_PROC_KEY_SOBSL,
  ITEM_BASCMC.VENDOR_NAME
FROM
  (SELECT ITEM_BASCM.MATERIALID,
    ITEM_BASCM.CATALOG_STRING1,
    ITEM_BASCM.SPC_PROC_KEY_SOBSL,
    ITEM_BASCM.MAT_DESC,
    ITEM_BASCM.VENDOR,
    ITEM_BASCM.VENDOR_NAME,
    ITEM_BASCM.PROD_BU,
    ITEM_BASCM.SP_MATL_STAT_MMSTA,
    ITEM_BASCM.MATL_TYPE_MTART,
    MCOO.COO,
    MCOO.HS_CODE
  FROM
    (SELECT ITEM_BASC.MATERIALID,
      MC.CATALOG_STRING1,
      ITEM_BASC.SPC_PROC_KEY_SOBSL,
      ITEM_BASC.MAT_DESC,
      ITEM_BASC.VENDOR,
      ITEM_BASC.VENDOR_NAME,
      ITEM_BASC.PROD_BU,
      ITEM_BASC.SP_MATL_STAT_MMSTA,
      ITEM_BASC.MATL_TYPE_MTART
    FROM
      (SELECT MATERIALID,
        SPC_PROC_KEY_SOBSL,
        SP_MATL_STAT_MMSTA,
        MAT_DESC,
        SUBSTR(VENDOR_NAME,0,4) AS VENDOR,
        VENDOR_NAME,
        SUBSTR(PROD_BU,0,3) AS PROD_BU,
        MATL_TYPE_MTART
      FROM INV_SAP_PP_OPTIMIZATION
      WHERE PLANTID            = '5041'
      AND MATL_TYPE_MTART NOT IN ('ZREP')
      )ITEM_BASC
    LEFT JOIN
      (SELECT MATERIALID, CATALOG_STRING1 FROM INV_SAP_NODASH_MAT_CATA
      )MC
    ON MC.MATERIALID = ITEM_BASC.MATERIALID
    )ITEM_BASCM
  LEFT JOIN
    ( SELECT MATERIAL, COO,HS_CODE FROM INV_SAP_ITEM_COO
    )MCOO
  ON MCOO.MATERIAL = ITEM_BASCM.MATERIALID
  )ITEM_BASCMC
LEFT JOIN
  (SELECT MATERIALID,
    D_CHAIN_BLK
  FROM INV_SAP_PP_MVKE
  WHERE DIRECT_SHIP_PLANT = '5040'
  )MATL_DC
ON MATL_DC.MATERIALID = ITEM_BASCMC.MATERIALID;

--Pre-Classification Items( ZREP)
SELECT ITEM_BASCMC.MATERIALID,
  ITEM_BASCMC.CATALOG,
  ITEM_BASCMC.MATL_TYPE_MTART,
  ITEM_BASCMC.PROD_BU,
  MATL_DC.D_CHAIN_BLK,
  ITEM_BASCMC.SP_MATL_STAT_MMSTA,
  ITEM_BASCMC.MAT_DESC,
  ITEM_BASCMC.COO,
  ITEM_BASCMC.HS_CODE,
  ITEM_BASCMC.VENDOR,
  ITEM_BASCMC.SPC_PROC_KEY_SOBSL,
  ITEM_BASCMC.VENDOR_NAME
FROM
  (SELECT ITEM_BASCM.MATERIALID,
    ITEM_BASCM.CATALOG,
    ITEM_BASCM.SPC_PROC_KEY_SOBSL,
    ITEM_BASCM.MAT_DESC,
    ITEM_BASCM.VENDOR,
    ITEM_BASCM.VENDOR_NAME,
    ITEM_BASCM.PROD_BU,
    ITEM_BASCM.SP_MATL_STAT_MMSTA,
    ITEM_BASCM.MATL_TYPE_MTART,
    MCOO.COO,
    MCOO.HS_CODE
  FROM
    (SELECT ITEM_BASC.MATERIALID,
      MC.CATALOG,
      ITEM_BASC.SPC_PROC_KEY_SOBSL,
      ITEM_BASC.MAT_DESC,
      ITEM_BASC.VENDOR,
      ITEM_BASC.VENDOR_NAME,
      ITEM_BASC.PROD_BU,
      ITEM_BASC.SP_MATL_STAT_MMSTA,
      ITEM_BASC.MATL_TYPE_MTART
    FROM
      (SELECT MATERIALID,
        SPC_PROC_KEY_SOBSL,
        SP_MATL_STAT_MMSTA,
        MAT_DESC,
        SUBSTR(VENDOR_NAME,0,4) AS VENDOR,
        VENDOR_NAME,
        SUBSTR(PROD_BU,0,3) AS PROD_BU,
        MATL_TYPE_MTART
      FROM INV_SAP_PP_OPTIMIZATION
      WHERE PLANTID        = '5041'
      AND MATL_TYPE_MTART IN ('ZREP')
      )ITEM_BASC
    LEFT JOIN
      (SELECT MATERIAL, CATALOG FROM INV_SAP_ZREP_ITEM_CATALOG
      )MC
    ON MC.MATERIAL = ITEM_BASC.MATERIALID
    )ITEM_BASCM
  LEFT JOIN
    ( SELECT MATERIAL, COO,HS_CODE FROM INV_SAP_ITEM_COO
    )MCOO
  ON MCOO.MATERIAL = ITEM_BASCM.MATERIALID
  )ITEM_BASCMC
LEFT JOIN
  (SELECT MATERIALID,
    D_CHAIN_BLK
  FROM INV_SAP_PP_MVKE
  WHERE DIRECT_SHIP_PLANT = '5040'
  )MATL_DC
ON MATL_DC.MATERIALID = ITEM_BASCMC.MATERIALID;

--STO/PO


SELECT 
        EBELNPURCHDOCNO            AS STO,
        BSART_PURCHDOCTYPE         AS STO_TYPE,
        EBELPPURCHITEMNO           AS ITEM,
        MATERIALID                 AS MATERIAL,
        PLANTID                    AS PLANT
      FROM INV_SAP_PP_PO_HISTORY 
      WHERE PLANTID             IN ('5040')
      AND ETENRPURCHDELIVSCHLINE = '1'
      AND DELIVERYCOMPLETE  IS NOT NULL

SELECT COUNT(*) FROM
(SELECT DISTINCT MATERIALID FROM INV_SAP_PP_PO_HISTORY WHERE PLANTID IN ('5040') AND DELIVERYCOMPLETE IS NULL);


--SO

SELECT DISTINCT MATERIAL FROM INV_SAP_SALES_VBAK_VBAP_VBUP WHERE SALES_ORG = '5003';


--SO&STO
SELECT * FROM
()


"SELECT ID,
  MATERIAL,
  CATALOG#,
  SALES_DOC,
  ITEM,
  SAFETY_STOCK,
  OH_QTY,
  STRATEGY_GRP,
  MRP_TYPE,
  VENDOR,
  BU,
  LEAD_TIME,
  PDT,
  UNIT_COST,
  MRP_CONTROLLER,
  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  TO_CHAR(COMMITTED_DATE,'MM/DD/YYYY') AS COMMITTED_DATE,
  TO_CHAR(LAST_GI_DATE,'MM/DD/YYYY') AS LAST_GI_DATE,
  TO_CHAR(CREATION_DATE,'MM/DD/YYYY') AS CREATION_DATE,
  TO_CHAR(REQUEST_DATE,'MM/DD/YYYY') AS REQUEST_DATE,
  PLANT,
  ORDER_QTY,
  OPEN_QTY,
  SALES_ORG,
  SALES_PRICE_EX,
  CURRENCY,
  SHIP_TO_COUNTRY,
  SHIPPING_POINT
  FROM VIEW_INV_SAP_SALES_HST_LC WHERE PLANT IN ('5040','5050') AND CREATION_DATE BETWEEN TO_CHAR(SYSDATE - 540) AND TO_CHAR(SYSDATE)"
