--Date:09032014
--Author: HuangMoyue
--Pass Due PO Stats




SELECT PLANT, MATERIAL, UNIT_COST FROM INV_SAP_PP_OPT_X WHERE MATERIAL = 'MVD-BILLPLAN-MAT' AND PLANT = '5040';
 
SELECT * FROM INV_SAP_LIKP_LIPS_DAILY