--Name: PP_REPORT
--Author:Huang Moyue
--Date:08/06/2014
--Monthly Update! First sat day of the month.

--VIEW_INV_SAP_ITEM_SOG
		DROP VIEW VIEW_INV_SAP_ITEM_SOG;
		DROP TABLE INV_SAP_ITEM_SOG;
		SELECT * FROM INV_SAP_ITEM_SOG;
		CREATE TABLE INV_SAP_ITEM_SOG AS SELECT * FROM VIEW_INV_SAP_ITEM_SOG;
		CREATE VIEW VIEW_INV_SAP_ITEM_SOG AS
			SELECT 
			DISTINCT
			ISPM.ID           AS ID,
			ISPM.SOG_ID            AS SOG_ID,
			ISPM.SALES_ORG         AS SALES_ORG,
			ISPM.DIRECT_SHIP_PLANT AS PLANT,
			ISPM.MATERIALID        AS MATERIAL,
			ISMC.CATALOG_STRING1   AS CATALOG_DASH,
			ISMC.CATALOG_STRING2   AS CATALOG_NO_DASH,
			ISPM.DIST_CHL          AS DIST_CHL,
			ISPM.CURRENT_SERIES    AS CURRENT_SERIES,
			ISPM.D_CHAIN_BLK    AS D_CHAIN_BLK
			FROM
			(SELECT DISTINCT MATERIALID
			  ||'_'
			  ||SALES_ORG AS SOG_ID,
			  MATERIALID
			  ||'_'
			  ||DIRECT_SHIP_PLANT AS ID,
			  MATERIALID,
			  SALES_ORG,
			  D_CHAIN_BLK,
			  DIST_CHL,
			  DIRECT_SHIP_PLANT,
			  CURRENT_SERIES
			FROM INV_SAP_PP_MVKE
			)ISPM
			LEFT JOIN
			(SELECT CATALOG_STRING1,
			  CATALOG_STRING2,
			  MATERIALID
			FROM INV_SAP_NODASH_MAT_CATA 
			)ISMC
			ON ISPM.MATERIALID = ISMC.MATERIALID;	
      
      
      SELECT MATERIAL,
      CATALOG_DASH,
      PLANT,
      SALES_ORG,
      UNIT_COST,       
        AVG52_USAGE_QTY,--changed
        STDEV52_USAGE,
			  AVG26_USAGE_QTY,
			  STDEV26_USAGE,
			  AVG13_USAGE_QTY,
			  STDEV13_USAGE,
			  Q1_LINES,
        Q2_LINES,
			  Q3_LINES,
			  Q4_LINES,
			  Q1_FREQ_COUNT,
			  Q2_FREQ_COUNT,
			  Q3_FREQ_COUNT,
			  Q4_FREQ_COUNT
        FROM VIEW_INV_SAP_PP_ALL WHERE PLANT = '5200'
-- PP report
		DROP VIEW VIEW_INV_SAP_PP_OPT;
		DROP TABLE INV_SAP_PP_OPT;
		SELECT * FROM VIEW_INV_SAP_PP_ALL;
		CREATE TABLE INV_SAP_PP_OPT_541 AS SELECT * FROM VIEW_INV_SAP_PP_ALL WHERE PLANT IN('5110','5050','5040');   
		CREATE VIEW VIEW_INV_SAP_PP_ALL AS 
    SELECT PP_BSC_SOG.ID              AS ID,
			  PP_BSC_SOG.LAST_REVIEW          AS LAST_REVIEW,
			  PP_BSC_SOG.MATERIAL             AS MATERIAL,
			  ITEM_SOG_X.CATALOG_DASH         AS CATALOG_DASH,
			  ITEM_SOG_X.CATALOG_NO_DASH      AS CATALOG_NO_DASH,
			  PP_BSC_SOG.PLANT                AS PLANT,
			  PP_BSC_SOG.SALES_ORG            AS SALES_ORG,
			  PP_BSC_SOG.PLANTID_DESC         AS PLANTID_DESC,
			  PP_BSC_SOG.MAT_DESC             AS MAT_DESC,
			  PP_BSC_SOG.SAFETY_STOCK         AS SAFETY_STOCK,
			  PP_BSC_SOG.OH_QTY               AS OH_QTY,
			  PP_BSC_SOG.UNIT                 AS UNIT,
			  PP_BSC_SOG.UNIT_COST            AS UNIT_COST,
			  PP_BSC_SOG.OH_QTY_INTRANSIT     AS OH_QTY_INTRANSIT,
			  PP_BSC_SOG.PROD_BU              AS PROD_BU,
			  PP_BSC_SOG.PROD_FAM             AS PROD_FAM,
			  PP_BSC_SOG.PROC_TYPE            AS PROC_TYPE,
			  PP_BSC_SOG.STRATEGY_GRP         AS STRATEGY_GRP,
			  PP_BSC_SOG.MRP_TYPE             AS MRP_TYPE,
			  PP_BSC_SOG.PROD_SCHEDULER       AS PROD_SCHEDULER,
			  PP_BSC_SOG.PLANT_SP_MATL_STA    AS PLANT_SP_MATL_STA,
        SUBSTR(PP_BSC_SOG.VENDOR_KEY,0,4) AS VENDOR_KEY,
			  PP_BSC_SOG.VENDOR_ITEM          AS VENDOR_ITEM,
			  PP_BSC_SOG.MIN_INV              AS MIN_INV,
			  PP_BSC_SOG.TARGET_INV           AS TARGET_INV,
			  PP_BSC_SOG.MAX_INV              AS MAX_INV,
			  PP_BSC_SOG.LOT_SIZE_QTY         AS LOT_SIZE_QTY,
			  PP_BSC_SOG.LOT_ROUNDING_VALUE   AS LOT_ROUNDING_VALUE,
			  PP_BSC_SOG.LOT_SIZE_DISLS       AS LOT_SIZE_DISLS,
			  PP_BSC_SOG.LOT_MIN_BUY          AS LOT_MIN_BUY,
        PP_BSC_SOG.AVG52_USAGE_QTY AS AVG52_USAGE_QTY,--changed
        PP_BSC_SOG.STDEV52_USAGE AS STDEV52_USAGE,
			  PP_BSC_SOG.AVG26_USAGE_QTY      AS AVG26_USAGE_QTY,
			  PP_BSC_SOG.STDEV26_USAGE        AS STDEV26_USAGE,
			  PP_BSC_SOG.AVG13_USAGE_QTY      AS AVG13_USAGE_QTY,
			  PP_BSC_SOG.STDEV13_USAGE        AS STDEV13_USAGE,
			  PP_BSC_SOG.Q1_LINES             AS Q1_LINES,
			  PP_BSC_SOG.Q2_LINES             AS Q2_LINES,
			  PP_BSC_SOG.Q3_LINES             AS Q3_LINES,
			  PP_BSC_SOG.Q4_LINES             AS Q4_LINES,
			  PP_BSC_SOG.Q1_FREQ_COUNT        AS Q1_FREQ_COUNT,
			  PP_BSC_SOG.Q2_FREQ_COUNT        AS Q2_FREQ_COUNT,
			  PP_BSC_SOG.Q3_FREQ_COUNT        AS Q3_FREQ_COUNT,
			  PP_BSC_SOG.Q4_FREQ_COUNT        AS Q4_FREQ_COUNT,
			  PP_BSC_SOG.EXCHANGE_RATE        AS EXCHANGE_RATE,
			  PP_BSC_SOG.LEVEL_TYPE           AS LEVEL_TYPE,
			  PP_BSC_SOG.MATERIAL_LEVEL_VALUE AS MATERIAL_LEVEL_VALUE,
			  PP_BSC_SOG.MRP_CONTROLLER       AS MRP_CONTROLLER,
			  PP_BSC_SOG.MRP_CONTROLLER_KEY   AS MRP_CONTROLLER_KEY,
			  PP_BSC_SOG.PURCH_GROUP          AS PURCH_GROUP,
			  PP_BSC_SOG.PURCH_GROUP_KEY      AS PURCH_GROUP_KEY,
			  PP_BSC_SOG.PROD_SCHED_KEY       AS PROD_SCHED_KEY,
			  PP_BSC_SOG.RECORDER_POINT       AS RECORDER_POINT,
			  PP_BSC_SOG.LEAD_TIME            AS LEAD_TIME,
			  PP_BSC_SOG.PDT                  AS PDT,
			  PP_BSC_SOG.GRT                  AS GRT,
			  ITEM_SOG_X.DIST_CHL             AS DIST_CHL,
			  ITEM_SOG_X.D_CHAIN_BLK          AS D_CHAIN_BLK,
			  PP_BSC_SOG.ISSUE_UOM_NUMERATOR  AS ISSUE_UOM_NUMERATOR,
			  PP_BSC_SOG.PO_UOM_NUMERATOR     AS PO_UOM_NUMERATOR,
			  PP_BSC_SOG.MATL_TYPE            AS MATL_TYPE,
			  ITEM_SOG_X.CURRENT_SERIES       AS CURRENT_SERIES,
			  PP_BSC_SOG.ULTIMATE_SOURCE      AS ULTIMATE_SOURCE
			FROM
			  (SELECT PP_BASIC.ID,
					  PP_BASIC.MATERIAL
					  ||'_'
					  ||PLANT_SOG.SALES_ORG AS SG_ID,
						PP_BASIC.LAST_REVIEW,
						PP_BASIC.MATERIAL,
						PP_BASIC.PLANT,
						PLANT_SOG.SALES_ORG,
						PLANT_SOG.PLANTID_DESC,
						PP_BASIC.MAT_DESC,
						PP_BASIC.SAFETY_STOCK,
						PP_BASIC.OH_QTY,
						PP_BASIC.UNIT,
						PP_BASIC.UNIT_COST,
						PP_BASIC.OH_QTY_INTRANSIT,
						PP_BASIC.PROD_BU,
						PP_BASIC.PROD_FAM,
						PP_BASIC.PROC_TYPE,
						PP_BASIC.STRATEGY_GRP,
						PP_BASIC.MRP_TYPE,
						PP_BASIC.PROD_SCHEDULER,
						PP_BASIC.PLANT_SP_MATL_STA,
						PP_BASIC.VENDOR_KEY,
						PP_BASIC.VENDOR_ITEM,
						PP_BASIC.MIN_INV,
						PP_BASIC.TARGET_INV,
						PP_BASIC.MAX_INV,
						PP_BASIC.LOT_SIZE_QTY,
						PP_BASIC.LOT_ROUNDING_VALUE,
						PP_BASIC.LOT_SIZE_DISLS,
						PP_BASIC.LOT_MIN_BUY,
            PP_BASIC.AVG52_USAGE_QTY,--changed
            PP_BASIC.STDEV52_USAGE,
						PP_BASIC.AVG26_USAGE_QTY,
						PP_BASIC.STDEV26_USAGE,
						PP_BASIC.AVG13_USAGE_QTY,
						PP_BASIC.STDEV13_USAGE,
						PP_BASIC.Q1_LINES,
						PP_BASIC.Q2_LINES,
						PP_BASIC.Q3_LINES,
						PP_BASIC.Q4_LINES,
						PP_BASIC.Q1_FREQ_COUNT,
						PP_BASIC.Q2_FREQ_COUNT,
						PP_BASIC.Q3_FREQ_COUNT,
						PP_BASIC.Q4_FREQ_COUNT,
						PP_BASIC.EXCHANGE_RATE,
						PP_BASIC.LEVEL_TYPE,
						PP_BASIC.MATERIAL_LEVEL_VALUE,
						PP_BASIC.MRP_CONTROLLER,
						PP_BASIC.MRP_CONTROLLER_KEY,
						PP_BASIC.PURCH_GROUP,
						PP_BASIC.PURCH_GROUP_KEY,
						PP_BASIC.PROD_SCHED_KEY,
						PP_BASIC.RECORDER_POINT,
						PP_BASIC.LEAD_TIME,
						PP_BASIC.PDT,
						PP_BASIC.GRT,
						PP_BASIC.ISSUE_UOM_NUMERATOR,
						PP_BASIC.PO_UOM_NUMERATOR,
						PP_BASIC.MATL_TYPE,
						PP_BASIC.ULTIMATE_SOURCE
					  FROM
						(SELECT MATERIALID
						  ||'_'
						  ||(PLANTID - 1) AS ID,
						  LAST_REVIEW,
						  MATERIALID    AS MATERIAL,
						  (PLANTID - 1) AS PLANT,
						  MAT_DESC,
						  SAFETY_STK AS SAFETY_STOCK,
						  OH_QTY,
						  UNIT_COST,
						  OH_QTY_INTRANSIT,
						  SUBSTR(PROD_BU,0,3) AS PROD_BU,
						  PROD_FAM,
						  PROC_TYPE,
						  STRATEGY_GRP,
						  MRP_TYPE,
						  PROD_SCHEDULER,
						  SP_MATL_STAT_MMSTA AS PLANT_SP_MATL_STA,
						  SPC_PROC_KEY_SOBSL AS VENDOR_KEY,
						  MATERIALID
						  ||'_'
						  ||SUBSTR(VENDOR_NAME,0,4)           AS VENDOR_ITEM,
						  (SAFETY_STK)                        AS MIN_INV,
						  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS TARGET_INV,
						  CEIL(SAFETY_STK + 1.2*LOT_SIZE_QTY) AS MAX_INV,
						  LOT_SIZE_QTY,
						  LOT_ROUNDING_VALUE,
						  LOT_SIZE_DISLS,
						  LOT_MIN_BUY,
              AVG52_USAGE_QTY,--changed
              STDEV52_USAGE,
						  AVG26_USAGE_QTY,
						  STDEV26_USAGE,
						  AVG13_USAGE_QTY,
						  STDEV13_USAGE,
						  Q1_LINES,
						  Q2_LINES,
						  Q3_LINES,
						  Q4_LINES,
						  Q1_FREQ_COUNT,
						  Q2_FREQ_COUNT,
						  Q3_FREQ_COUNT,
						  Q4_FREQ_COUNT,
						  EXCHANGE_RATE,
						  LEVEL_TYPE,
						  MATERIAL_LEVEL_VALUE,
						  MRP_CONTROLLER,
						  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_KEY,
						  PURCH_GROUP,
						  PURCH_GROUP_EKGRP   AS PURCH_GROUP_KEY,
						  PROD_SCHED_FEVOR    AS PROD_SCHED_KEY,
						  REORDER_PT          AS RECORDER_POINT,
						  CEIL(1.4*GRT + PDT) AS LEAD_TIME, --Lead Time Change!!
						  PDT                 AS PDT,
						  GRT                 AS GRT,
						  MEINS_ISSUE_UOM     AS UNIT,
						  ISSUE_UOM_NUMERATOR,
						  PO_UOM_NUMERATOR,
						  MATL_TYPE_MTART AS MATL_TYPE,
						  ULTIMATE_SOURCE
						FROM INV_SAP_PP_OPTIMIZATION --WHERE MATERIALID = '100-C09KJ400 A' AND PLANTID = '5200'
						)PP_BASIC
					  LEFT JOIN
						( SELECT PLANTID, PLANTID_DESC, SALES_ORG FROM INV_SAP_PP_PLANT_SAOG
						)PLANT_SOG
					  ON PLANT_SOG.PLANTID = PP_BASIC.PLANT
					  )PP_BSC_SOG
					LEFT JOIN
					  (SELECT ID,
						SOG_ID,
						SALES_ORG,
						PLANT,
						MATERIAL,
						CATALOG_DASH,
						CATALOG_NO_DASH,
						DIST_CHL,
						D_CHAIN_BLK,
						CURRENT_SERIES
					  FROM INV_SAP_ITEM_SOG
					  )ITEM_SOG_X
					ON ITEM_SOG_X.SOG_ID = PP_BSC_SOG.SG_ID