



--AP On Hand Inventory





--out_qty_week is total requirement
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_STAT2 WHERE MATERIAL = '700-P400A2 E' AND PLANT = '5050';

SELECT 
MATERIALID,
  PLANTID,
OUT_QTY_W01,
OUT_QTY_W02,
OUT_QTY_W03,
OUT_QTY_W04,
OUT_QTY_W05,
OUT_QTY_W06,
OUT_QTY_W07,
OUT_QTY_W08,
OUT_QTY_W09,
OUT_QTY_W10,
OUT_QTY_W11,
OUT_QTY_W12,
OUT_QTY_W13,
IN_QTY_W01,
IN_QTY_W02,
IN_QTY_W03,
IN_QTY_W04,
IN_QTY_W05,
IN_QTY_W06,
IN_QTY_W07,
IN_QTY_W08,
IN_QTY_W09,
IN_QTY_W10,
IN_QTY_W11,
IN_QTY_W12,
IN_QTY_W13

 FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION WHERE MATERIALID = '700-P400A2 E' AND PLANTID = '5050'

--IndReq
--vse/vsf
---How to calculate the week number.
---SELECT TO_CHAR(SYSDATE,'iw') AS weekn,
--  TO_CHAR(to_date('20050425','yyyymmdd'),'iw')      AS week1
--FROM dual; 

SELECT MATERIALID,
  PLANTID,
  PDATU_DELIV_ORDFINISHDATE,
  MEINS_BASEUNITOFMEASURE,
  PLNMG_PLANNEDQUANTITY,
  BEDAEP_REQUIREMENTSTYPE,
  VERSBP_VERSION
FROM INV_SAP_PP_FRCST_PBIM_PBED
WHERE VERSBP_VERSION = '55';
