--RiskBuy
--Date:09302014
--Huang Moyue

--The first vesion of risk buy

SELECT KS_AP.ID            AS ID,
  KS_AP.PLANT              AS PLANT,
  KS_AP.MATERIAL           AS MATERIAL,
  KS_AP.AVG26_USAGE_QTY    AS AVG26_USAGE_QTY,
  KS_AP.D_CHAIN_BLK        AS D_CHAIN_BLK,
  KS_AP.KOR_STRATEGY_GRP   AS KOR_STRATEGY_GRP,
  KS_AP.KOR_VENDOR_ITEM    AS KOR_VENDOR_ITEM,
  KS_AP.AP_PLANT           AS AP_PLANT,
  KS_AP.AP_AVG26_USAGE_QTY AS AP_AVG26_USAGE_QTY,
  KS_AP.AP_DCHAIN_BLK      AS AP_DCHAIN_BLK,
  KS_AP.AP_STRATEGY_GRP    AS AP_STRATEGY_GRP,
  SUP.ID                   AS SUPPLIER,
  SUP.AVG26_USAGE_QTY      AS SUP_AVG26_USAGE_QTY,
  SUP.STRATEGY_GRP         AS SUP_STRATEGY_GRP
FROM
  (SELECT KS.ID        AS ID,
    KS.PLANT           AS PLANT,
    KS.MATERIAL        AS MATERIAL,
    KS.AVG26_USAGE_QTY AS AVG26_USAGE_QTY,
    KS.D_CHAIN_BLK     AS D_CHAIN_BLK,
    KS.STRATEGY_GRP    AS KOR_STRATEGY_GRP,
    KS.VENDOR_ITEM     AS KOR_VENDOR_ITEM,
    AP.PLANT           AS AP_PLANT,
    AP.AVG26_USAGE_QTY AS AP_AVG26_USAGE_QTY,
    AP.D_CHAIN_BLK     AS AP_DCHAIN_BLK,
    AP.STRATEGY_GRP    AS AP_STRATEGY_GRP
  FROM
    (SELECT ID,
      PLANT,
      MATERIAL,
      AVG26_USAGE_QTY,
      D_CHAIN_BLK,
      STRATEGY_GRP,
      VENDOR_ITEM
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT  IN ('5100')
    AND MATERIAL IN ('PN-184723',
'1756-IB32 B',
'1756-OB32 A',
'1321-3R35-B A',
'PN-114256',
'PN-52276',
'1756-PA72 C',
'PN-198907',
'1756-IT6I2 A',
'1756-OF4 A',
'1756-IF8 A',
'PN-159331',
'22F-D8P7N113 A')
    )KS
  LEFT JOIN
    (SELECT PLANT,
      MATERIAL,
      AVG26_USAGE_QTY,
      D_CHAIN_BLK,
      STRATEGY_GRP
    FROM INV_SAP_PP_OPT_X
    WHERE PLANT      IN ('5040', '5050', '5110', '5120', '5160', '5190', '5200','5070','5140','5130','5150','5180')
    )AP
  ON AP.MATERIAL = KS.MATERIAL
  )
LEFT JOIN
  ( SELECT ID, AVG26_USAGE_QTY, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )SUP
ON SUP.ID = KS_AP.KOR_VENDOR_ITEM;


------------------------------------------------------------------------------------------------------------------------
--The second version of the risk buy
SELECT REQ_AP_SGU.REQ_ID                                                 AS REQ_ID,
  REQ_AP_SGU.REQ_PLANT                                                   AS REQ_PLANT,
  REQ_AP_SGU.REQ_MATERIAL                                                AS REQ_MATERIAL,
  REQ_AP_SGU.REQ_AVG26_USAGE_QTY                                         AS REQ_AVG26_USAGE_QTY,
  REQ_AP_SGU.REQ_D_CHAIN_BLK                                             AS REQ_D_CHAIN_BLK,
  REQ_AP_SGU.REQ_STRATEGY_GRP                                            AS REQ_STRATEGY_GRP,
  REQ_AP_SGU.REQ_VENDOR_ITEM                                             AS REQ_VENDOR_ITEM,
  NVL((REQ_AP_SGU.APT_AVG26_USAGE_QTY-REQ_AP_SGU.REQ_AVG26_USAGE_QTY),0) AS APT_AVG26_USAGE_QTY,
  REQ_AP_SGU.AP_SG_CHECK                                                 AS AP_SG_CHECK,
  VENDOR.AVG26_USAGE_QTY                                                 AS VEN_AVG26_USG_QTY,
  VENDOR.STRATEGY_GRP                                                    AS VEN_STRATEGY_GRP
FROM
  (SELECT REQ_AP_USG.REQ_ID        AS REQ_ID,
    REQ_AP_USG.REQ_PLANT           AS REQ_PLANT,
    REQ_AP_USG.REQ_MATERIAL        AS REQ_MATERIAL,
    REQ_AP_USG.REQ_AVG26_USAGE_QTY AS REQ_AVG26_USAGE_QTY,
    REQ_AP_USG.REQ_D_CHAIN_BLK     AS REQ_D_CHAIN_BLK,
    REQ_AP_USG.REQ_STRATEGY_GRP    AS REQ_STRATEGY_GRP,
    REQ_AP_USG.REQ_VENDOR_ITEM     AS REQ_VENDOR_ITEM,
    REQ_AP_USG.APT_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY,
    AP_SG.SG_CHECK                 AS AP_SG_CHECK
  FROM
    (SELECT REQ_PLANT.ID              AS REQ_ID,
      REQ_PLANT.PLANT                 AS REQ_PLANT,
      REQ_PLANT.MATERIAL              AS REQ_MATERIAL,
      REQ_PLANT.AVG26_USAGE_QTY       AS REQ_AVG26_USAGE_QTY,
      REQ_PLANT.D_CHAIN_BLK           AS REQ_D_CHAIN_BLK,
      REQ_PLANT.STRATEGY_GRP          AS REQ_STRATEGY_GRP,
      REQ_PLANT.VENDOR_ITEM           AS REQ_VENDOR_ITEM,
      AP_USAGE.TOT_AP_AVG26_USAGE_QTY AS APT_AVG26_USAGE_QTY
    FROM
      (SELECT ID,
        PLANT,
        MATERIAL,
        AVG26_USAGE_QTY,
        D_CHAIN_BLK,
        STRATEGY_GRP,
        VENDOR_ITEM
      FROM INV_SAP_PP_OPT_X
      WHERE PLANT  IN ('5100')
      AND MATERIAL IN ('PN-184723', '1756-IB32 B', '1756-OB32 A', '1321-3R35-B A', 'PN-114256', 'PN-52276', '1756-PA72 C', 'PN-198907', '1756-IT6I2 A', '1756-OF4 A', '1756-IF8 A', 'PN-159331', '22F-D8P7N113 A')
      )REQ_PLANT
    LEFT JOIN
      (SELECT MATERIAL,
        NVL(SUM(AVG26_USAGE_QTY),0) AS TOT_AP_AVG26_USAGE_QTY
      FROM INV_SAP_PP_OPT_X
      WHERE PLANT IN ('5040', '5050', '5110', '5120', '5160', '5190', '5200','5070','5140','5130','5150','5180')
      GROUP BY MATERIAL
      )AP_USAGE
    ON AP_USAGE.MATERIAL = REQ_PLANT.MATERIAL
    )REQ_AP_USG
  LEFT JOIN
    (SELECT ID,SG_CHECK FROM INV_SAP_SR_SGCHECK
    )AP_SG
  ON AP_SG.ID = REQ_AP_USG.REQ_ID
  )REQ_AP_SGU
LEFT JOIN
  ( SELECT ID, AVG26_USAGE_QTY, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )VENDOR
ON VENDOR.ID = REQ_AP_SGU.REQ_VENDOR_ITEM;

  
  
  
  
  
  
  
  
  

