--Author: Huang Moyue
--Date:08272014
--Sales Order Hst in last 6 months AP.

--1. LAST GI DATE VERSION
SELECT SO_BSC.PLANT,
  SO_BSC.SALES_ORG,
  SO_BSC.MATERIAL,
  SO_BSC.CATALOG#,
  SO_BSC.STRATEGY_GRP,
  SO_BSC.PROC_TYPE,
  SO_BSC.SALES_DOC,
  SO_BSC.ITEM,
  SO_BSC.BU,
  SO_BSC.PDT,
  SO_BSC.GRT,
  SO_BSC.SOLD_TO_PARTY,
  SO_BSC.SHIP_TO_PARTY,
  SO_BSC.COMMITTED_DATE,
  SO_BSC.CONFIRM_DELI_DATE,
  SO_BSC.LAST_GI_DATE,
  SO_BSC.CREATION_DATE,
  SO_BSC.REQUIRE_DELI_DATE,
  SO_BSC.SO_TYPE,
  SO_BSC.ORDER_QTY,
  SO_BSC.OPEN_QTY,
  SO_BSC.CONFIRM_QTY,
  SO_BSC.SHIP_QTY,
  SO_BSC.CURRENCY,
  SO_BSC.SHIPPING_POINT,
  SO_BSC.MATL_TYPE,
  SO_BSC.VENDOR,
  ITEM_BSV.STRATEGY_GRP AS V_SG
FROM
  (SELECT SO_HST.PLANT,
    SO_HST.SALES_ORG,
    SO_HST.MATERIAL,
    SO_HST.CATALOG#,
    SO_HST.SALES_DOC,
    SO_HST.ITEM,
    SO_HST.SOLD_TO_PARTY,
    SO_HST.SHIP_TO_PARTY,
    SO_HST.COMMITTED_DATE,
    SO_HST.CONFIRM_DELI_DATE,
    SO_HST.LAST_GI_DATE,
    SO_HST.CREATION_DATE,
    SO_HST.REQUIRE_DELI_DATE,
    SO_HST.SO_TYPE,
    SO_HST.ORDER_QTY,
    SO_HST.OPEN_QTY,
    SO_HST.CONFIRM_QTY,
    SO_HST.SHIP_QTY,
    SO_HST.CURRENCY,
    SO_HST.SHIPPING_POINT,
    ITEM_BSC.STRATEGY_GRP,
    ITEM_BSC.PROC_TYPE,
    ITEM_BSC.VENDOR_ITEM,
    ITEM_BSC.VENDOR,
    ITEM_BSC.BU,
    ITEM_BSC.PDT,
    ITEM_BSC.GRT,
    ITEM_BSC.MATL_TYPE
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                                   AS ID,
      PLANTID                                     AS PLANT,
      SALES_ORG                                   AS SALES_ORG,
      MATERIALID                                  AS MATERIAL,
      CATALOGID                                   AS CATALOG#,
      SALESDOC                                    AS SALES_DOC,
      SALESDOCITEM                                AS ITEM,
      LPAD(SOLDTOPARTY,10,'0')                    AS SOLD_TO_PARTY,
      LPAD(SHIPTOPARTY,10,'0')                    AS SHIP_TO_PARTY,
      TO_CHAR(COMMITTEDDATE,'MM/DD/YYYY')         AS COMMITTED_DATE,
      TO_CHAR(CONFIRMEDDELIVERYDATE,'MM/DD/YYYY') AS CONFIRM_DELI_DATE,
      TO_CHAR(LASTACTGIDATE,'MM/DD/YYYY')         AS LAST_GI_DATE,
      TO_CHAR(LINECREATIONDATE,'MM/DD/YYYY')      AS CREATION_DATE,
      TO_CHAR(REQUIREDDELIVERYDATE,'MM/DD/YYYY')  AS REQUIRE_DELI_DATE,
      SALESDOCTYPE                                AS SO_TYPE,
      ORDERQTY                                    AS ORDER_QTY,
      OPENQTY                                     AS OPEN_QTY,
      CONFIRMEDQTY                                AS CONFIRM_QTY,
      SHIPQTY                                     AS SHIP_QTY,
      CURRENCY                                    AS CURRENCY,
      SHIPPING_POINT                              AS SHIPPING_POINT
    FROM INV_SAP_SALES_HST
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND OPENQTY    = 0
    AND LINECREATIONDATE BETWEEN TO_CHAR(SYSDATE - 184) AND TO_CHAR(SYSDATE)
    )SO_HST
  LEFT JOIN
    (SELECT ID,
      STRATEGY_GRP,
      PROC_TYPE,
      VENDOR_ITEM,
      SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
      SUBSTR(PROD_BU,0,3) AS BU,
      PDT,
      MATL_TYPE,
      GRT
    FROM INV_SAP_PP_OPT_X
    )ITEM_BSC
  ON ITEM_BSC.ID = SO_HST.ID
  )SO_BSC
LEFT JOIN
  (SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )ITEM_BSV
ON SO_BSC.VENDOR_ITEM = ITEM_BSV.ID;

 
--2 SO ENTRY DATE VERSION
SELECT SO_BSC.PLANT,
  SO_BSC.SALES_ORG,
  SO_BSC.MATERIAL,
  SO_BSC.CATALOG#,
  SO_BSC.STRATEGY_GRP,
  SO_BSC.PROC_TYPE,
  SO_BSC.SALES_DOC,
  SO_BSC.ITEM,
  SO_BSC.BU,
  SO_BSC.PDT,
  SO_BSC.GRT,
  SO_BSC.SOLD_TO_PARTY,
  SO_BSC.SHIP_TO_PARTY,
  SO_BSC.COMMITTED_DATE,
  SO_BSC.CONFIRM_DELI_DATE,
  SO_BSC.LAST_GI_DATE,
  SO_BSC.CREATION_DATE,
  SO_BSC.REQUIRE_DELI_DATE,
  SO_BSC.SO_TYPE,
  SO_BSC.ORDER_QTY,
  SO_BSC.OPEN_QTY,
  SO_BSC.CONFIRM_QTY,
  SO_BSC.SHIP_QTY,
  SO_BSC.CURRENCY,
  SO_BSC.SHIPPING_POINT,
  SO_BSC.MATL_TYPE,
  SO_BSC.VENDOR,
  ITEM_BSV.STRATEGY_GRP AS V_SG
FROM
  (SELECT SO_HST.PLANT,
    SO_HST.SALES_ORG,
    SO_HST.MATERIAL,
    SO_HST.CATALOG#,
    SO_HST.SALES_DOC,
    SO_HST.ITEM,
    SO_HST.SOLD_TO_PARTY,
    SO_HST.SHIP_TO_PARTY,
    SO_HST.COMMITTED_DATE,
    SO_HST.CONFIRM_DELI_DATE,
    SO_HST.LAST_GI_DATE,
    SO_HST.CREATION_DATE,
    SO_HST.REQUIRE_DELI_DATE,
    SO_HST.SO_TYPE,
    SO_HST.ORDER_QTY,
    SO_HST.OPEN_QTY,
    SO_HST.CONFIRM_QTY,
    SO_HST.SHIP_QTY,
    SO_HST.CURRENCY,
    SO_HST.SHIPPING_POINT,
    ITEM_BSC.STRATEGY_GRP,
    ITEM_BSC.PROC_TYPE,
    ITEM_BSC.VENDOR_ITEM,
    ITEM_BSC.VENDOR,
    ITEM_BSC.BU,
    ITEM_BSC.PDT,
    ITEM_BSC.GRT,
    ITEM_BSC.MATL_TYPE
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                                   AS ID,
      PLANTID                                     AS PLANT,
      SALES_ORG                                   AS SALES_ORG,
      MATERIALID                                  AS MATERIAL,
      CATALOGID                                   AS CATALOG#,
      SALESDOC                                    AS SALES_DOC,
      SALESDOCITEM                                AS ITEM,
      LPAD(SOLDTOPARTY,10,'0')                    AS SOLD_TO_PARTY,
      LPAD(SHIPTOPARTY,10,'0')                    AS SHIP_TO_PARTY,
      TO_CHAR(COMMITTEDDATE,'MM/DD/YYYY')         AS COMMITTED_DATE,
      TO_CHAR(CONFIRMEDDELIVERYDATE,'MM/DD/YYYY') AS CONFIRM_DELI_DATE,
      TO_CHAR(LASTACTGIDATE,'MM/DD/YYYY')         AS LAST_GI_DATE,
      TO_CHAR(LINECREATIONDATE,'MM/DD/YYYY')      AS CREATION_DATE,
      TO_CHAR(REQUIREDDELIVERYDATE,'MM/DD/YYYY')  AS REQUIRE_DELI_DATE,
      SALESDOCTYPE                                AS SO_TYPE,
      ORDERQTY                                    AS ORDER_QTY,
      OPENQTY                                     AS OPEN_QTY,
      CONFIRMEDQTY                                AS CONFIRM_QTY,
      SHIPQTY                                     AS SHIP_QTY,
      CURRENCY                                    AS CURRENCY,
      SHIPPING_POINT                              AS SHIPPING_POINT
    FROM INV_SAP_SALES_HST
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND OPENQTY    = 0
    AND LASTACTGIDATE BETWEEN TO_CHAR(SYSDATE - 184) AND TO_CHAR(SYSDATE)
    )SO_HST
  LEFT JOIN
    (SELECT ID,
      STRATEGY_GRP,
      PROC_TYPE,
      VENDOR_ITEM,
      SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
      SUBSTR(PROD_BU,0,3) AS BU,
      PDT,
      MATL_TYPE,
      GRT
    FROM INV_SAP_PP_OPT_X
    )ITEM_BSC
  ON ITEM_BSC.ID = SO_HST.ID
  )SO_BSC
LEFT JOIN
  (SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )ITEM_BSV
ON SO_BSC.VENDOR_ITEM = ITEM_BSV.ID;

