--Porject Name: Basic Function View
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:09/26/2014
--Summary: Automation Files Center Job Logs and set up process
--Sales Order Hst in last 6 months AP&VIEW_INV_SAP_SALES_HST_LC

--Delivery Data
SELECT SO.ID,
  SO.SALES_DOC,
  SO.ITEM,
  DELI.CREATED_ON_DATE,
  DELI.DELIVERY
FROM
  (SELECT SALES_DOC
    ||'_'
    ||ITEM AS ID,
    SALES_DOC,
    ITEM
  FROM VIEW_INV_SAP_SOHST_6MM_ENT
  )SO
LEFT JOIN
  (SELECT REFERENCE_DOC_TRIM
    ||'_'
    ||REFERENCE_DOC_ITEM_TRIM AS ID,
    DELIVERY,
    CREATED_ON_DATE
  FROM INV_SAP_LIKP_LIPS_DAILY_6MM
  )DELI
ON DELI.ID = SO.ID;

--1. LAST GI DATE VERSION
CREATE VIEW VIEW_INV_SAP_SOHST_6MM_ENT AS
SELECT SO_BSC.PLANT,
  SO_BSC.SALES_ORG,
  SO_BSC.MATERIAL,
  SO_BSC.CATALOG#,
  SO_BSC.STRATEGY_GRP,
  SO_BSC.PROC_TYPE,
  SO_BSC.SALES_DOC,
  SO_BSC.ITEM,
  SO_BSC.BU,
  SO_BSC.PDT,
  SO_BSC.GRT,
  SO_BSC.SOLD_TO_PARTY,
  SO_BSC.SHIP_TO_PARTY,
  SO_BSC.COMMITTED_DATE,
  SO_BSC.CONFIRM_DELI_DATE,
  SO_BSC.LAST_GI_DATE,
  SO_BSC.CREATION_DATE,
  SO_BSC.REQUIRE_DELI_DATE,
  SO_BSC.SO_TYPE,
  SO_BSC.ORDER_QTY,
  SO_BSC.OPEN_QTY,
  SO_BSC.CONFIRM_QTY,
  SO_BSC.SHIP_QTY,
  SO_BSC.CURRENCY,
  SO_BSC.SHIPPING_POINT,
  SO_BSC.MATL_TYPE,
  SO_BSC.VENDOR,
  ITEM_BSV.STRATEGY_GRP AS V_SG
FROM
  (SELECT SO_HST.PLANT,
    SO_HST.SALES_ORG,
    SO_HST.MATERIAL,
    SO_HST.CATALOG#,
    SO_HST.SALES_DOC,
    SO_HST.ITEM,
    SO_HST.SOLD_TO_PARTY,
    SO_HST.SHIP_TO_PARTY,
    SO_HST.COMMITTED_DATE,
    SO_HST.CONFIRM_DELI_DATE,
    SO_HST.LAST_GI_DATE,
    SO_HST.CREATION_DATE,
    SO_HST.REQUIRE_DELI_DATE,
    SO_HST.SO_TYPE,
    SO_HST.ORDER_QTY,
    SO_HST.OPEN_QTY,
    SO_HST.CONFIRM_QTY,
    SO_HST.SHIP_QTY,
    SO_HST.CURRENCY,
    SO_HST.SHIPPING_POINT,
    ITEM_BSC.STRATEGY_GRP,
    ITEM_BSC.PROC_TYPE,
    ITEM_BSC.VENDOR_ITEM,
    ITEM_BSC.VENDOR,
    ITEM_BSC.BU,
    ITEM_BSC.PDT,
    ITEM_BSC.GRT,
    ITEM_BSC.MATL_TYPE
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                                   AS ID,
      PLANTID                                     AS PLANT,
      SALES_ORG                                   AS SALES_ORG,
      MATERIALID                                  AS MATERIAL,
      CATALOGID                                   AS CATALOG#,
      SALESDOC                                    AS SALES_DOC,
      SALESDOCITEM                                AS ITEM,
      LPAD(SOLDTOPARTY,10,'0')                    AS SOLD_TO_PARTY,
      LPAD(SHIPTOPARTY,10,'0')                    AS SHIP_TO_PARTY,
      TO_CHAR(COMMITTEDDATE,'MM/DD/YYYY')         AS COMMITTED_DATE,
      TO_CHAR(CONFIRMEDDELIVERYDATE,'MM/DD/YYYY') AS CONFIRM_DELI_DATE,
      TO_CHAR(LASTACTGIDATE,'MM/DD/YYYY')         AS LAST_GI_DATE,
      TO_CHAR(LINECREATIONDATE,'MM/DD/YYYY')      AS CREATION_DATE,
      TO_CHAR(REQUIREDDELIVERYDATE,'MM/DD/YYYY')  AS REQUIRE_DELI_DATE,
      SALESDOCTYPE                                AS SO_TYPE,
      ORDERQTY                                    AS ORDER_QTY,
      OPENQTY                                     AS OPEN_QTY,
      CONFIRMEDQTY                                AS CONFIRM_QTY,
      SHIPQTY                                     AS SHIP_QTY,
      CURRENCY                                    AS CURRENCY,
      SHIPPING_POINT                              AS SHIPPING_POINT
      FROM INV_SAP_SALES_HST
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND OPENQTY    = 0
    AND LINECREATIONDATE BETWEEN TO_CHAR(SYSDATE - 195) AND TO_CHAR(SYSDATE)
    )SO_HST
  LEFT JOIN
    (SELECT ID,
      STRATEGY_GRP,
      PROC_TYPE,
      VENDOR_ITEM,
      SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
      SUBSTR(PROD_BU,0,3) AS BU,
      PDT,
      MATL_TYPE,
      GRT
    FROM INV_SAP_PP_OPT_X
    )ITEM_BSC
  ON ITEM_BSC.ID = SO_HST.ID
  )SO_BSC
LEFT JOIN
  (SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )ITEM_BSV
ON SO_BSC.VENDOR_ITEM = ITEM_BSV.ID;

--2 SO ENTRY DATE VERSION
SELECT SO_BSC.PLANT,
  SO_BSC.SALES_ORG,
  SO_BSC.MATERIAL,
  SO_BSC.CATALOG#,
  SO_BSC.STRATEGY_GRP,
  SO_BSC.PROC_TYPE,
  SO_BSC.SALES_DOC,
  SO_BSC.ITEM,
  SO_BSC.BU,
  SO_BSC.PDT,
  SO_BSC.GRT,
  SO_BSC.SOLD_TO_PARTY,
  SO_BSC.SHIP_TO_PARTY,
  SO_BSC.COMMITTED_DATE,
  SO_BSC.CONFIRM_DELI_DATE,
  SO_BSC.LAST_GI_DATE,
  SO_BSC.CREATION_DATE,
  SO_BSC.REQUIRE_DELI_DATE,
  SO_BSC.SO_TYPE,
  SO_BSC.ORDER_QTY,
  SO_BSC.OPEN_QTY,
  SO_BSC.CONFIRM_QTY,
  SO_BSC.SHIP_QTY,
  SO_BSC.CURRENCY,
  SO_BSC.SHIPPING_POINT,
  SO_BSC.MATL_TYPE,
  SO_BSC.VENDOR,
  ITEM_BSV.STRATEGY_GRP AS V_SG
FROM
  (SELECT SO_HST.PLANT,
    SO_HST.SALES_ORG,
    SO_HST.MATERIAL,
    SO_HST.CATALOG#,
    SO_HST.SALES_DOC,
    SO_HST.ITEM,
    SO_HST.SOLD_TO_PARTY,
    SO_HST.SHIP_TO_PARTY,
    SO_HST.COMMITTED_DATE,
    SO_HST.CONFIRM_DELI_DATE,
    SO_HST.LAST_GI_DATE,
    SO_HST.CREATION_DATE,
    SO_HST.REQUIRE_DELI_DATE,
    SO_HST.SO_TYPE,
    SO_HST.ORDER_QTY,
    SO_HST.OPEN_QTY,
    SO_HST.CONFIRM_QTY,
    SO_HST.SHIP_QTY,
    SO_HST.CURRENCY,
    SO_HST.SHIPPING_POINT,
    ITEM_BSC.STRATEGY_GRP,
    ITEM_BSC.PROC_TYPE,
    ITEM_BSC.VENDOR_ITEM,
    ITEM_BSC.VENDOR,
    ITEM_BSC.BU,
    ITEM_BSC.PDT,
    ITEM_BSC.GRT,
    ITEM_BSC.MATL_TYPE
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                                   AS ID,
      PLANTID                                     AS PLANT,
      SALES_ORG                                   AS SALES_ORG,
      MATERIALID                                  AS MATERIAL,
      CATALOGID                                   AS CATALOG#,
      SALESDOC                                    AS SALES_DOC,
      SALESDOCITEM                                AS ITEM,
      LPAD(SOLDTOPARTY,10,'0')                    AS SOLD_TO_PARTY,
      LPAD(SHIPTOPARTY,10,'0')                    AS SHIP_TO_PARTY,
      TO_CHAR(COMMITTEDDATE,'MM/DD/YYYY')         AS COMMITTED_DATE,
      TO_CHAR(CONFIRMEDDELIVERYDATE,'MM/DD/YYYY') AS CONFIRM_DELI_DATE,
      TO_CHAR(LASTACTGIDATE,'MM/DD/YYYY')         AS LAST_GI_DATE,
      TO_CHAR(LINECREATIONDATE,'MM/DD/YYYY')      AS CREATION_DATE,
      TO_CHAR(REQUIREDDELIVERYDATE,'MM/DD/YYYY')  AS REQUIRE_DELI_DATE,
      SALESDOCTYPE                                AS SO_TYPE,
      ORDERQTY                                    AS ORDER_QTY,
      OPENQTY                                     AS OPEN_QTY,
      CONFIRMEDQTY                                AS CONFIRM_QTY,
      SHIPQTY                                     AS SHIP_QTY,
      CURRENCY                                    AS CURRENCY,
      SHIPPING_POINT                              AS SHIPPING_POINT
    FROM INV_SAP_SALES_HST
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND OPENQTY    = 0
    AND LASTACTGIDATE BETWEEN TO_CHAR(SYSDATE - 195) AND TO_CHAR(SYSDATE)
    )SO_HST
  LEFT JOIN
    (SELECT ID,
      STRATEGY_GRP,
      PROC_TYPE,
      VENDOR_ITEM,
      SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
      SUBSTR(PROD_BU,0,3) AS BU,
      PDT,
      MATL_TYPE,
      GRT
    FROM INV_SAP_PP_OPT_X
    )ITEM_BSC
  ON ITEM_BSC.ID = SO_HST.ID
  )SO_BSC
LEFT JOIN
  (SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )ITEM_BSV
ON SO_BSC.VENDOR_ITEM = ITEM_BSV.ID;

SELECT * FROM INV_SAP_SALES_HST
--VIEW_INV_SAP_SALES_HST_LC



DROP VIEW VIEW_INV_SAP_SALES_HST_LC;
CREATE VIEW VIEW_INV_SAP_SALES_HST_LC AS
SELECT SOH_SOSH.ID,
  SOH_SOSH.MATERIAL,
  SOH_SOSH.CATALOG#,
  SOH_SOSH.SALES_DOC,
  SOH_SOSH.ITEM,
  ITEM_BSC.SAFETY_STOCK,
  ITEM_BSC.OH_QTY,
  ITEM_BSC.STRATEGY_GRP,
  ITEM_BSC.MRP_TYPE,
  ITEM_BSC.VENDOR,
  ITEM_BSC.BU,
  ITEM_BSC.LEAD_TIME,
  ITEM_BSC.PDT,
  ITEM_BSC.UNIT_COST,
  ITEM_BSC.MRP_CONTROLLER,
  SOH_SOSH.SOLD_TO_PARTY,
  SOH_SOSH.SOLD_TO_NAME,
  SOH_SOSH.SHIP_TO_PARTY,
  SOH_SOSH.SHIP_TO_NAME,
  SOH_SOSH.COMMITTED_DATE,
  SOH_SOSH.LAST_GI_DATE,
  SOH_SOSH.CREATION_DATE,
  SOH_SOSH.REQUEST_DATE,
  SOH_SOSH.PLANT,
  SOH_SOSH.SO_TYPE,
  SOH_SOSH.ORDER_QTY,
  SOH_SOSH.OPEN_QTY,
  SOH_SOSH.SALES_ORG,
  SOH_SOSH.CURRENCY,
  SOH_SOSH.SALES_PRICE_EX,
  SOH_SOSH.SHIP_TO_COUNTRY,
  SOH_SOSH.SHIPPING_POINT,
  ITEM_BSC.ULTIMATE_SOURCE
FROM
  (SELECT SO_HST_SOLD.ID,
    SO_HST_SOLD.MATERIAL,
    SO_HST_SOLD.CATALOG#,
    SO_HST_SOLD.SALES_DOC,
    SO_HST_SOLD.ITEM,
    SO_HST_SOLD.SOLD_TO_PARTY,
    SO_HST_SOLD.SOLD_TO_NAME,
    SO_HST_SOLD.SHIP_TO_PARTY,
    ADDRESS_SHIP.SHIP_SOLD_TO_PARTY_NAME AS SHIP_TO_NAME,
    SO_HST_SOLD.COMMITTED_DATE,
    SO_HST_SOLD.LAST_GI_DATE,
    SO_HST_SOLD.CREATION_DATE,
    SO_HST_SOLD.REQUEST_DATE,
    SO_HST_SOLD.PLANT,
    SO_HST_SOLD.SO_TYPE,
    SO_HST_SOLD.ORDER_QTY,
    SO_HST_SOLD.OPEN_QTY,
    SO_HST_SOLD.SALES_ORG,
    SO_HST_SOLD.SALES_PRICE_EX,
    SO_HST_SOLD.CURRENCY,
    ADDRESS_SHIP.SHIP_SOLD_TO_COUNTRY AS SHIP_TO_COUNTRY,
    SO_HST_SOLD.SHIPPING_POINT
  FROM
    (SELECT SO_HST.ID,
      SO_HST.MATERIAL,
      SO_HST.CATALOG#,
      SO_HST.SALES_DOC,
      SO_HST.ITEM,
      SO_HST.SOLD_TO_PARTY,
      ADDRESS.SHIP_SOLD_TO_PARTY_NAME AS SOLD_TO_NAME,
      SO_HST.SHIP_TO_PARTY,
      SO_HST.COMMITTED_DATE,
      SO_HST.LAST_GI_DATE,
      SO_HST.CREATION_DATE,
      SO_HST.REQUEST_DATE,
      SO_HST.PLANT,
      SO_HST.SO_TYPE,
      SO_HST.ORDER_QTY,
      SO_HST.OPEN_QTY,
      SO_HST.SALES_ORG,
      SO_HST.SALES_PRICE_EX,
      SO_HST.CURRENCY,
      SO_HST.SHIPPING_POINT
    FROM
      (SELECT MATERIALID
        ||'_'
        ||PLANTID            AS ID,
        MATERIALID           AS MATERIAL,
        CATALOGID            AS CATALOG#,
        SALESDOC             AS SALES_DOC,
        SALESDOCITEM         AS ITEM,
        LPAD(SOLDTOPARTY,10,'0')          AS SOLD_TO_PARTY,
        LPAD(SHIPTOPARTY,10,'0')          AS SHIP_TO_PARTY,
        COMMITTEDDATE        AS COMMITTED_DATE,
        LASTACTGIDATE        AS LAST_GI_DATE,
        LINECREATIONDATE     AS CREATION_DATE,
        REQUIREDDELIVERYDATE AS REQUEST_DATE,
        PLANTID              AS PLANT,
        SALESDOCTYPE         AS SO_TYPE,
        ORDERQTY             AS ORDER_QTY,
        OPENQTY              AS OPEN_QTY,
        SALES_ORG            AS SALES_ORG,
        GBBB_SALES_AMT       AS SALES_PRICE_EX,
        CURRENCY             AS CURRENCY,
        SHIPPING_POINT       AS SHIPPING_POINT
      FROM INV_SAP_SALES_HST
      )SO_HST
    LEFT JOIN
      (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
        SHIP_SOLD_TO_PARTY_NAME
      FROM INV_SAP_SHIP_SOLD_TO
      )ADDRESS
    ON ADDRESS.SHIP_SOLD_TO_PARTY = SO_HST.SOLD_TO_PARTY
    )SO_HST_SOLD
  LEFT JOIN
    (SELECT LPAD(SHIP_SOLD_TO_PARTY,10,'0') AS SHIP_SOLD_TO_PARTY,
      SHIP_SOLD_TO_PARTY_NAME,
      SHIP_SOLD_TO_COUNTRY
    FROM INV_SAP_SHIP_SOLD_TO
    )ADDRESS_SHIP
  ON ADDRESS_SHIP.SHIP_SOLD_TO_PARTY = SO_HST_SOLD.SHIP_TO_PARTY
  )SOH_SOSH
LEFT JOIN
  (SELECT ID,
    MATERIAL,
    PLANT,
    CATALOG_DASH,
    SAFETY_STOCK,
    OH_QTY,
    STRATEGY_GRP,
    MRP_TYPE,
    SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
    SUBSTR(PROD_BU,0,3)    AS BU,
    LEAD_TIME,
    PDT,
    UNIT_COST,
    MRP_CONTROLLER,
    ULTIMATE_SOURCE
  FROM INV_SAP_PP_OPT_X
  )ITEM_BSC
ON ITEM_BSC.ID = SOH_SOSH.ID;

---For GRC Team
SELECT ID,
  MATERIAL,
  CATALOG#,
  SALES_DOC,
  ITEM,
  SAFETY_STOCK,
  OH_QTY,
  STRATEGY_GRP,
  MRP_TYPE,
  VENDOR,
  BU,
  LEAD_TIME,
  PDT,
  UNIT_COST,
  MRP_CONTROLLER,
  SOLD_TO_PARTY,
  SOLD_TO_NAME,
  TO_CHAR(COMMITTED_DATE,'MM/DD/YYYY') AS COMMITTED_DATE,
  TO_CHAR(LAST_GI_DATE,'MM/DD/YYYY') AS LAST_GI_DATE,
  TO_CHAR(CREATION_DATE,'MM/DD/YYYY') AS CREATION_DATE,
  TO_CHAR(REQUEST_DATE,'MM/DD/YYYY') AS REQUEST_DATE,
  PLANT,
  ORDER_QTY,
  OPEN_QTY,
  SALES_ORG,
  SALES_PRICE_EX,
  CURRENCY,
  SHIP_TO_COUNTRY,
  SHIPPING_POINT
  FROM VIEW_INV_SAP_SALES_HST_LC WHERE PLANT IN ('5040','5050') AND CREATION_DATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE);


--
CREATE TABLE INV_SAP_SALES_HST_LC AS 
SELECT * FROM VIEW_INV_SAP_SALES_HST_LC;



SELECT PLANTID,
SALESDOC,
SALESDOCITEM,
MATERIALID,
LINECREATIONDATE,
REQUIREDDELIVERYDATE,
PRIORITY_ORDER
 FROM INV_SAP_SALES_HST WHERE PLANTID IN('5040','5050') AND LINECREATIONDATE BETWEEN TO_CHAR(SYSDATE - 365) AND TO_CHAR(SYSDATE)
















SELECT
  SO_BSC.SALES_DOC||'_'||SO_BSC.ITEM AS SO_ID,
  SO_BSC.PLANT,
  SO_BSC.SALES_ORG,
  SO_BSC.MATERIAL,
  SO_BSC.CATALOG#,
  SO_BSC.STRATEGY_GRP,
  SO_BSC.PROC_TYPE,
  SO_BSC.SALES_DOC,
  SO_BSC.ITEM,
  SO_BSC.BU,
  SO_BSC.PDT,
  SO_BSC.GRT,
  SO_BSC.SOLD_TO_PARTY,
  SO_BSC.SHIP_TO_PARTY,
  SO_BSC.COMMITTED_DATE,
  SO_BSC.CONFIRM_DELI_DATE,
  SO_BSC.LAST_GI_DATE,
  SO_BSC.CREATION_DATE,
  SO_BSC.REQUIRE_DELI_DATE,
  0  AS DELIVERY_CREATE_DATE,
  SO_BSC.SO_TYPE,
  SO_BSC.ORDER_QTY,
  SO_BSC.OPEN_QTY,
  SO_BSC.CONFIRM_QTY,
  SO_BSC.SHIP_QTY,
  SO_BSC.CURRENCY,
  SO_BSC.SHIPPING_POINT,
  SO_BSC.MATL_TYPE,
  SO_BSC.VENDOR,
  ITEM_BSV.STRATEGY_GRP AS V_SG
FROM
  (SELECT 
    SO_HST.ID,
    SO_HST.PLANT,
    SO_HST.SALES_ORG,
    SO_HST.MATERIAL,
    SO_HST.CATALOG#,
    SO_HST.SALES_DOC,
    SO_HST.ITEM,
    SO_HST.SOLD_TO_PARTY,
    SO_HST.SHIP_TO_PARTY,
    SO_HST.COMMITTED_DATE,
    SO_HST.CONFIRM_DELI_DATE,
    SO_HST.LAST_GI_DATE,
    SO_HST.CREATION_DATE,
    SO_HST.REQUIRE_DELI_DATE,
    SO_HST.SO_TYPE,
    SO_HST.ORDER_QTY,
    SO_HST.OPEN_QTY,
    SO_HST.CONFIRM_QTY,
    SO_HST.SHIP_QTY,
    SO_HST.CURRENCY,
    SO_HST.SHIPPING_POINT,
    ITEM_BSC.STRATEGY_GRP,
    ITEM_BSC.PROC_TYPE,
    ITEM_BSC.VENDOR_ITEM,
    ITEM_BSC.VENDOR,
    ITEM_BSC.BU,
    ITEM_BSC.PDT,
    ITEM_BSC.GRT,
    ITEM_BSC.MATL_TYPE
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                                   AS ID,
      PLANTID                                     AS PLANT,
      SALES_ORG                                   AS SALES_ORG,
      MATERIALID                                  AS MATERIAL,
      CATALOGID                                   AS CATALOG#,
      SALESDOC                                    AS SALES_DOC,
      SALESDOCITEM                                AS ITEM,
      LPAD(SOLDTOPARTY,10,'0')                    AS SOLD_TO_PARTY,
      LPAD(SHIPTOPARTY,10,'0')                    AS SHIP_TO_PARTY,
      TO_CHAR(COMMITTEDDATE,'MM/DD/YYYY')         AS COMMITTED_DATE,
      TO_CHAR(CONFIRMEDDELIVERYDATE,'MM/DD/YYYY') AS CONFIRM_DELI_DATE,
      TO_CHAR(LASTACTGIDATE,'MM/DD/YYYY')         AS LAST_GI_DATE,
      TO_CHAR(LINECREATIONDATE,'MM/DD/YYYY')      AS CREATION_DATE,
      TO_CHAR(REQUIREDDELIVERYDATE,'MM/DD/YYYY')  AS REQUIRE_DELI_DATE,
      SALESDOCTYPE                                AS SO_TYPE,
      ORDERQTY                                    AS ORDER_QTY,
      OPENQTY                                     AS OPEN_QTY,
      CONFIRMEDQTY                                AS CONFIRM_QTY,
      SHIPQTY                                     AS SHIP_QTY,
      CURRENCY                                    AS CURRENCY,
      SHIPPING_POINT                              AS SHIPPING_POINT
    FROM INV_SAP_SALES_HST
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND OPENQTY    = 0
    AND LINECREATIONDATE BETWEEN TO_CHAR(SYSDATE - 195) AND TO_CHAR(SYSDATE)
    )SO_HST
  LEFT JOIN
    (SELECT ID,
      STRATEGY_GRP,
      PROC_TYPE,
      VENDOR_ITEM,
      SUBSTR(VENDOR_KEY,0,4) AS VENDOR,
      SUBSTR(PROD_BU,0,3) AS BU,
      PDT,
      MATL_TYPE,
      GRT
    FROM INV_SAP_PP_OPT_X
    )ITEM_BSC
  ON ITEM_BSC.ID = SO_HST.ID
  )SO_BSC
LEFT JOIN
  (SELECT ID, STRATEGY_GRP FROM INV_SAP_PP_OPT_X
  )ITEM_BSV
ON SO_BSC.VENDOR_ITEM = ITEM_BSV.ID





