--Porject Name: Basic Function View
--Author: Huang Moyue 
--Mail: mhuang1@ra.rockwell.com
--Date:09/26/2014
--Summary: Automation Files Center Job Logs and set up process
--STO Hst 6 Months
--VIEW_INV_SAP_STO_HST_6MMS

DROP VIEW VIEW_INV_SAP_STO_HST_6MMS;
CREATE VIEW VIEW_INV_SAP_STO_HST_6MMS AS
SELECT STO_HST_CV.ID,
  STO_HST_CV.STO_ID,
  STO_HST_CV.STO,
  STO_HST_CV.STO_TYPE,
  STO_HST_CV.ITEM,
  STO_HST_CV.MATERIAL,
  STO_HST_CV.CATALOG_DASH,
  STO_HST_CV.PROC_TYPE,
  STO_HST_CV.SPC_PROC_KEY,
  STO_HST_CV.CUS_SG,
  STO_HST_CV.PLANT,
  STO_HST_CV.ORDER_QTY,
  STO_HST_CV.SHIP_QTY,
  STO_HST_CV.ORDER_CREATE_DATE,
  STO_HST_CV.COMMITTED_DATE,
  STO_HST_CV.DELIVERY_DATE,
  STO_HST_CV.RECEIVE_DATE,
  STO_HST_CV.LAST_GI_DATE,
  STO_REDATE.START_DELI_DATE,
  STO_HST_CV.PDT,
  STO_HST_CV.GRT,
  STO_HST_CV.BU,
  STO_HST_CV.MATL_TYPE,
  STO_HST_CV.UNIT_COST,
  STO_HST_CV.ORDER_VALUE,
  STO_HST_CV.CURRENCY,
  STO_HST_CV.V_ITEM,
  STO_HST_CV.STO_VENDOR,
  STO_HST_CV.VEN_SG
FROM
  (SELECT STO_HST_C.ID,
    STO_HST_C.STO_ID,
    STO_HST_C.STO,
    STO_HST_C.STO_TYPE,
    STO_HST_C.ITEM,
    STO_HST_C.MATERIAL,
    STO_HST_C.CATALOG_DASH,
    STO_HST_C.PROC_TYPE,
    STO_HST_C.SPC_PROC_KEY,
    STO_HST_C.CUS_SG,
    STO_HST_C.PLANT,
    STO_HST_C.ORDER_QTY,
    STO_HST_C.SHIP_QTY,
    STO_HST_C.ORDER_CREATE_DATE,
    STO_HST_C.COMMITTED_DATE,
    STO_HST_C.DELIVERY_DATE,
    STO_HST_C.RECEIVE_DATE,
    STO_HST_C.LAST_GI_DATE,
    STO_HST_C.PDT,
    STO_HST_C.GRT,
    STO_HST_C.BU,
    STO_HST_C.MATL_TYPE,
    STO_HST_C.UNIT_COST,
    STO_HST_C.ORDER_VALUE,
    STO_HST_C.CURRENCY,
    STO_HST_C.V_ITEM,
    STO_HST_C.STO_VENDOR,
    VENDOR_X.VEN_SG
  FROM
    (SELECT STO_HST.ID,
      STO_HST.STO_ID,
      STO_HST.STO,
      STO_HST.STO_TYPE,
      STO_HST.ITEM,
      STO_HST.MATERIAL,
      CUS_X.CATALOG_DASH,
      CUS_X.PROC_TYPE,
      STO_HST.SPC_PROC_KEY,
      CUS_X.CUS_SG,
      STO_HST.PLANT,
      STO_HST.ORDER_QTY,
      STO_HST.SHIP_QTY,
      STO_HST.ORDER_CREATE_DATE,
      STO_HST.COMMITTED_DATE,
      STO_HST.DELIVERY_DATE,
      STO_HST.RECEIVE_DATE,
      STO_HST.LAST_GI_DATE,
      CUS_X.PDT,
      CUS_X.GRT,
      CUS_X.BU,
      CUS_X.MATL_TYPE,
      STO_HST.UNIT_COST,
      STO_HST.ORDER_VALUE,
      STO_HST.CURRENCY,
      STO_HST.V_ITEM,
      STO_HST.STO_VENDOR
    FROM
      (SELECT EBELNPURCHDOCNO
        ||'_'
        ||MATERIALID AS STO_ID,
        MATERIALID
        ||'_'
        ||PLANTID                  AS ID,
        MATERIALID
        ||'_'
        ||SUBSTR(LIFNR_VENDORNO,2,5) AS V_ITEM,
        EBELNPURCHDOCNO            AS STO,
        BSART_PURCHDOCTYPE         AS STO_TYPE,
        EBELPPURCHITEMNO           AS ITEM,
        MATERIALID                 AS MATERIAL,
        PLANTID                    AS PLANT,
        MENGESCHEDULEDQTY          AS ORDER_QTY,
        TOTALRECIEVEDYQTY          AS SHIP_QTY,
        BEDATSCHEDULELINEORDERDATE AS ORDER_CREATE_DATE,
        COMMITTED_DATE             AS COMMITTED_DATE,
        EINDTPURCHITEMDELIVDATE    AS DELIVERY_DATE,
        SLFDTSTATDELIVERYDATE      AS RECEIVE_DATE,
        LAST_SHIP_DATE             AS LAST_GI_DATE,
        SPC_PROC_KEY               AS SPC_PROC_KEY,
        UNIT_COST                  AS UNIT_COST,
        NETWRNETORDERVALUE         AS ORDER_VALUE,
        WAERS_CURRENCYKEY          AS CURRENCY,
        SUBSTR(LIFNR_VENDORNO,2,5) AS STO_VENDOR
      FROM INV_SAP_PP_PO_HISTORY 
      WHERE PLANTID             IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
      AND ETENRPURCHDELIVSCHLINE = '1'
      AND BEDATSCHEDULELINEORDERDATE BETWEEN TO_CHAR(SYSDATE - 184) AND TO_CHAR(SYSDATE) --ORDER ENTRY DATE
      AND BSART_PURCHDOCTYPE = 'ZST'
      AND DELIVERYCOMPLETE  IS NOT NULL
      )STO_HST
    LEFT JOIN
      (SELECT ID,
        CATALOG_DASH,
        PROC_TYPE,
        STRATEGY_GRP AS CUS_SG,
        PDT,
        GRT,
        MATL_TYPE,
        SUBSTR(PROD_BU,0,3)    AS BU
      FROM INV_SAP_PP_OPT_X
      )CUS_X
    ON CUS_X.ID = STO_HST.ID
    )STO_HST_C
  LEFT JOIN
    (SELECT ID, STRATEGY_GRP AS VEN_SG FROM INV_SAP_PP_OPT_X
    )VENDOR_X
  ON VENDOR_X.ID = STO_HST_C.V_ITEM
  )STO_HST_CV
LEFT JOIN
  (SELECT STO_ID,
    START_DELI_DATE
  FROM
    (SELECT STO_STATDATE.STO_ID,
      CASE
        WHEN STO_STATDATE.ETENRPURCHDELIVSCHLINESA = SPLIT_LINE.LINECOUNT
        THEN STO_STATDATE.SLFDTSTATDELIVERYDATE
      END START_DELI_DATE
    FROM
      (SELECT EBELNPURCHDOCNO
        ||'_'
        ||MATERIALID AS STO_ID,
        SLFDTSTATDELIVERYDATE,
        ETENRPURCHDELIVSCHLINESA
      FROM INV_SAP_PP_PO_HISTORY
      )STO_STATDATE
    LEFT JOIN
      (SELECT EBELNPURCHDOCNO
        ||'_'
        ||MATERIALID AS STO_ID,
        MATERIALID,
        PLANTID,
        SUM(PLANTID)/PLANTID AS LINECOUNT
      FROM INV_SAP_PP_PO_HISTORY
      GROUP BY EBELNPURCHDOCNO,
        MATERIALID,
        PLANTID
      )SPLIT_LINE
    ON SPLIT_LINE.STO_ID = STO_STATDATE.STO_ID
    )
  WHERE START_DELI_DATE              IS NOT NULL
  )STO_REDATE ON STO_REDATE.STO_ID = STO_HST_CV.STO_ID;

SELECT * FROM INV_SAP_PP_PO_HISTORY WHERE EBELNPURCHDOCNO = '6301654222'



SELECT SO_C.STO_ID,
  SO_C.START_DELI_DATE,
  DELI_R.GOOD_REC_DATE,
  DELI_R.REC_DEL,
  SO_C.SDD_DEL
FROM
  (SELECT SO.STO_ID,
    DELI.START_DELI_DATE,
    DELI.SDD_DEL
  FROM
    (SELECT STO_ID
    FROM VIEW_INV_SAP_STO_HST_6MMS
    )SO
  LEFT JOIN
    (SELECT REFERENCE_DOC_TRIM
      ||'_'
      ||MATERIALID    AS ID,
      DELIVERY        AS SDD_DEL,
      CREATED_ON_DATE AS START_DELI_DATE
    FROM INV_SAP_LIKP_LIPS_DAILY_6MM
    WHERE MVMT_TYPE NOT IN ('101','161') 
    )DELI
  ON DELI.ID = SO.STO_ID
  )SO_C
LEFT JOIN
  (SELECT REFERENCE_DOC_TRIM
    ||'_'
    ||MATERIALID    AS ID,
    CHANGED_ON_DATE AS GOOD_REC_DATE,
    DELIVERY        AS REC_DEL
  FROM INV_SAP_LIKP_LIPS_DAILY_6MM
  WHERE MVMT_TYPE IN ('101','161')
  )DELI_R
ON DELI_R.ID = SO_C.STO_ID;

SELECT * FROM INV_SAP_LIKP_LIPS_DAILY_6MM WHERE REFERENCE_DOC_TRIM = '6301394831'

DROP VIEW VIEW_INV_SAP_STO_HST_6MMS;
CREATE VIEW VIEW_INV_SAP_STO_HST_6MMS AS
SELECT STO_HST_C.ID,
    STO_HST_C.STO_ID,
    STO_HST_C.STO,
    STO_HST_C.STO_TYPE,
    STO_HST_C.ITEM,
    STO_HST_C.MATERIAL,
    STO_HST_C.CATALOG_DASH,
    STO_HST_C.PROC_TYPE,
    STO_HST_C.SPC_PROC_KEY,
    STO_HST_C.CUS_SG,
    STO_HST_C.PLANT,
    STO_HST_C.ORDER_QTY,
    STO_HST_C.SHIP_QTY,
    STO_HST_C.ORDER_CREATE_DATE,
    STO_HST_C.COMMITTED_DATE,
    STO_HST_C.DELIVERY_DATE,
    STO_HST_C.RECEIVE_DATE,
    STO_HST_C.LAST_GI_DATE,
    STO_HST_C.PDT,
    STO_HST_C.GRT,
    STO_HST_C.BU,
    STO_HST_C.MATL_TYPE,
    STO_HST_C.UNIT_COST,
    STO_HST_C.ORDER_VALUE,
    STO_HST_C.CURRENCY,
    STO_HST_C.V_ITEM,
    STO_HST_C.STO_VENDOR,
    VENDOR_X.VEN_SG
  FROM
    (SELECT STO_HST.ID,
      STO_HST.STO_ID,
      STO_HST.STO,
      STO_HST.STO_TYPE,
      STO_HST.ITEM,
      STO_HST.MATERIAL,
      CUS_X.CATALOG_DASH,
      CUS_X.PROC_TYPE,
      STO_HST.SPC_PROC_KEY,
      CUS_X.CUS_SG,
      STO_HST.PLANT,
      STO_HST.ORDER_QTY,
      STO_HST.SHIP_QTY,
      STO_HST.ORDER_CREATE_DATE,
      STO_HST.COMMITTED_DATE,
      STO_HST.DELIVERY_DATE,
      STO_HST.RECEIVE_DATE,
      STO_HST.LAST_GI_DATE,
      CUS_X.PDT,
      CUS_X.GRT,
      CUS_X.BU,
      CUS_X.MATL_TYPE,
      STO_HST.UNIT_COST,
      STO_HST.ORDER_VALUE,
      STO_HST.CURRENCY,
      STO_HST.V_ITEM,
      STO_HST.STO_VENDOR
    FROM
      (SELECT EBELNPURCHDOCNO
        ||'_'
        ||MATERIALID AS STO_ID,
        MATERIALID
        ||'_'
        ||PLANTID                  AS ID,
        MATERIALID
        ||'_'
        ||SUBSTR(LIFNR_VENDORNO,2,5) AS V_ITEM,
        EBELNPURCHDOCNO            AS STO,
        BSART_PURCHDOCTYPE         AS STO_TYPE,
        EBELPPURCHITEMNO           AS ITEM,
        MATERIALID                 AS MATERIAL,
        PLANTID                    AS PLANT,
        MENGESCHEDULEDQTY          AS ORDER_QTY,
        TOTALRECIEVEDYQTY          AS SHIP_QTY,
        BEDATSCHEDULELINEORDERDATE AS ORDER_CREATE_DATE,
        COMMITTED_DATE             AS COMMITTED_DATE,
        EINDTPURCHITEMDELIVDATE    AS DELIVERY_DATE,
        SLFDTSTATDELIVERYDATE      AS RECEIVE_DATE,
        LAST_SHIP_DATE             AS LAST_GI_DATE,
        SPC_PROC_KEY               AS SPC_PROC_KEY,
        UNIT_COST                  AS UNIT_COST,
        NETWRNETORDERVALUE         AS ORDER_VALUE,
        WAERS_CURRENCYKEY          AS CURRENCY,
        SUBSTR(LIFNR_VENDORNO,2,5) AS STO_VENDOR
      FROM INV_SAP_PP_PO_HISTORY 
      WHERE PLANTID             IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
      AND ETENRPURCHDELIVSCHLINE = '1'
      AND BEDATSCHEDULELINEORDERDATE BETWEEN TO_CHAR(SYSDATE - 200) AND TO_CHAR(SYSDATE) --ORDER ENTRY DATE
      AND BSART_PURCHDOCTYPE = 'ZST'
      AND DELIVERYCOMPLETE  IS NOT NULL
      )STO_HST
    LEFT JOIN
      (SELECT ID,
        CATALOG_DASH,
        PROC_TYPE,
        STRATEGY_GRP AS CUS_SG,
        PDT,
        GRT,
        MATL_TYPE,
        SUBSTR(PROD_BU,0,3)    AS BU
      FROM INV_SAP_PP_OPT_X
      )CUS_X
    ON CUS_X.ID = STO_HST.ID
    )STO_HST_C
  LEFT JOIN
    (SELECT ID, STRATEGY_GRP AS VEN_SG FROM INV_SAP_PP_OPT_X
    )VENDOR_X
  ON VENDOR_X.ID = STO_HST_C.V_ITEM;
  
  
--In REP
SELECT 
STO_ID,
STO,
STO_TYPE,
ITEM,
MATERIAL,
CATALOG_DASH,
PROC_TYPE,
SPC_PROC_KEY,
CUS_SG,
PLANT,
ORDER_QTY,
SHIP_QTY,
ORDER_CREATE_DATE,
COMMITTED_DATE,
DELIVERY_DATE,
0 AS START_DELI_DATE,
LAST_GI_DATE,
0 AS REC_DATE,
PDT,
GRT,
BU,
MATL_TYPE,
UNIT_COST,
ORDER_VALUE,
CURRENCY,
STO_VENDOR,
VEN_SG
FROM VIEW_INV_SAP_STO_HST_6MMS;
