--- SVD Report 6/6/2014
--  A Material
--	B AP plant
--	C Strategy Group
--	D SBU
--	E Safety stock
--	F Average 13 weeks fc
--	G On hand
--	H Stock in transit  --
--	I Qty Open sales order committed until 13 weeks to the future ( > 13 weeks)
--	J Qty Open SO due this week 
--	K Qty Open SO Past due 
--	Limit data by only taking materials with SG 40 and Z4
--	Mtype is ZTG and ZFG only
	
--'5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141'
--'5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140'

SELECT * FROM SVD_REPORT_DEMO;
CREATE VIEW VIEW_SVD_REPORT AS
SELECT SVD_REPORT.ID        AS ID,
  SVD_REPORT.MATERIAL       AS MATERIAL,
  SVD_REPORT.PLANT          AS PLANT,
  SVD_REPORT.STRATEGY_GRP   AS STRATEGY_GRP,
  SVD_REPORT.SBU            AS SBU,
  SVD_REPORT.SAFETY_STK     AS SAFETY_STK,
  FC_AVG_WEEK.FC_AVG26_WEEK AS FC_AVG26_WEEK_QTY,
  SVD_REPORT.OH_QTY AS OH_QTY,
  SVD_REPORT.STOCK_IN_TRANSIT_QTY AS STOCK_IN_TRANSIT_QTY,
  SVD_REPORT.BACKLOG_OPEN AS BACKLOG_OPEN,
  SVD_REPORT.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS,
  SVD_REPORT.PAST_DUE_OPEN AS PAST_DUE_OPEN
FROM
  (SELECT SVD_BASISC_INFO.ID                 AS ID,
    SVD_BASISC_INFO.MATERIAL                 AS MATERIAL,
    (SVD_BASISC_INFO.PLANT - 1)              AS PLANT,
    SVD_BASISC_INFO.STRATEGY_GRP             AS STRATEGY_GRP,
    SUBSTR(SVD_BASISC_INFO.SBU,0,3)          AS SBU,
    SVD_BASISC_INFO.SAFETY_STK               AS SAFETY_STK,
    SVD_BASISC_INFO.OH_QTY                   AS OH_QTY,
    SVD_BASISC_INFO.BACKLOG_OPEN             AS BACKLOG_OPEN,
    SVD_BASISC_INFO.PAST_DUE_OPEN            AS PAST_DUE_OPEN,
    SVD_BASISC_INFO.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS,
    STOCK_IN_TRAINST.STOCK_IN_TRANSIT_QTY    AS STOCK_IN_TRANSIT_QTY
  FROM
    (SELECT PP_INFO.ID                                   AS ID,
      PP_INFO.MATERIALID                                 AS MATERIAL,
      PP_INFO.PLANTID                                    AS PLANT,
      PP_INFO.STRATEGY_GRP                               AS STRATEGY_GRP,
      PP_INFO.PROD_BU                                    AS SBU,
      PP_INFO.SAFETY_STK                                 AS SAFETY_STK,
      PP_INFO.OH_QTY                                     AS OH_QTY,
      BACKLOG_PASTDUE_DUE_THREE.BACKLOG_OPEN             AS BACKLOG_OPEN,
      BACKLOG_PASTDUE_DUE_THREE.PAST_DUE_OPEN            AS PAST_DUE_OPEN,
      BACKLOG_PASTDUE_DUE_THREE.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS
    FROM
      (SELECT MATERIALID
        ||'_'
        ||(PLANTID - 1) AS ID,
        MATERIALID,
        PLANTID,
        STRATEGY_GRP,
        PROD_BU,
        SAFETY_STK,
        OH_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
      WHERE STRATEGY_GRP  IN ('SG', '40', 'Z4')
      AND MATL_TYPE_MTART IN ('ZFG','ZTG')
      AND PLANTID         IN ('5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141')
      )PP_INFO
    LEFT JOIN
      (SELECT BACKLOG_PASTDUE.ID                    AS ID,
        BACKLOG_PASTDUE.BACKLOG_OPEN                AS BACKLOG_OPEN,
        BACKLOG_PASTDUE.PAST_DUE_OPEN               AS PAST_DUE_OPEN,
        DUE_IN_THREE_WEEKS.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS
      FROM
        (SELECT BACKLOG_OPEN.ID           AS ID,
          BACKLOG_OPEN.OPEN_QTY           AS BACKLOG_OPEN,
          PAST_DUE_OPEN.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN
        FROM
          (SELECT MATERIAL
            ||'_'
            ||PLANT       AS ID,
            MATERIAL      AS MATERIALID,
            PLANT         AS PLANTID,
            SUM(OPEN_QTY) AS OPEN_QTY
          FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
          WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
          AND MAX_COMMIT_DATE < SYSDATE + 91
          GROUP BY MATERIAL
            ||'_'
            ||PLANT,
            MATERIAL,
            PLANT
          )BACKLOG_OPEN
        LEFT JOIN
          (SELECT MATERIAL
            ||'_'
            ||PLANT       AS ID,
            MATERIAL      AS MATERIALID,
            PLANT         AS PLANTID,
            SUM(OPEN_QTY) AS PAST_DUE_OPEN_QTY
          FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
          WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
          AND MAX_COMMIT_DATE < SYSDATE - 1
          GROUP BY MATERIAL
            ||'_'
            ||PLANT,
            MATERIAL,
            PLANT
          )PAST_DUE_OPEN
        ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID
        )BACKLOG_PASTDUE
      LEFT JOIN
        (SELECT MATERIAL
          ||'_'
          ||PLANT       AS ID,
          MATERIAL      AS MATERIALID,
          PLANT         AS PLANTID,
          SUM(OPEN_QTY) AS DUE_OPEN_QTY_THREE_WEEKS
        FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
        WHERE PLANT                                                      IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
        AND (MAX_COMMIT_DATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 21))
        GROUP BY MATERIAL
          ||'_'
          ||PLANT,
          MATERIAL,
          PLANT
        )DUE_IN_THREE_WEEKS
      ON DUE_IN_THREE_WEEKS.ID                                   = BACKLOG_PASTDUE.ID
      )BACKLOG_PASTDUE_DUE_THREE ON BACKLOG_PASTDUE_DUE_THREE.ID = PP_INFO.ID
    )SVD_BASISC_INFO
  LEFT JOIN
    (SELECT MATERIALID
      ||'_'
      ||PLANTID AS ID,
      MATERIALID,
      PLANTID,
      SUM(DELIVERY_QTY_SUOM) AS STOCK_IN_TRANSIT_QTY
    FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DBLINK
    WHERE REFERENCE_DOC_TRIM IN
      (SELECT EBELNPURCHDOCNO
      FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
      WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
      AND DELIVERYCOMPLETE IS NULL
      )AND CHANGED_ON_DATE IS NULL
    GROUP BY MATERIALID,
      MATERIALID,
      PLANTID
    )STOCK_IN_TRAINST
  ON STOCK_IN_TRAINST.ID = SVD_BASISC_INFO.ID
  )SVD_REPORT
LEFT JOIN
  (SELECT MATERIALID
    ||'_'
    ||PLANTID                           AS ID,
    MATERIALID                          AS MATERIALID,
    PLANTID                             AS PLANTID,
    CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK
  FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
  WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
  AND PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
  AND VERSBP_VERSION = '55'
  GROUP BY MATERIALID,
    MATERIALID
    ||'_'
    ||PLANTID,
    PLANTID,
    MATERIALID
  )FC_AVG_WEEK
ON FC_AVG_WEEK.ID = SVD_REPORT.ID;

---Local Version
DROP VIEW VIEW_SVD_REPORT;
SELECT count(*) FROM VIEW_SVD_REPORT;
CREATE VIEW VIEW_SVD_REPORT AS
SELECT SVD_REPORT.ID                  AS ID,
  SVD_REPORT.MATERIAL                 AS MATERIAL,
  SVD_REPORT.PLANT                    AS PLANT,
  SVD_REPORT.STRATEGY_GRP             AS STRATEGY_GRP,
  SVD_REPORT.SBU                      AS SBU,
  SVD_REPORT.SAFETY_STK               AS SAFETY_STK,
  FC_AVG_WEEK.FC_AVG26_WEEK           AS FC_AVG26_WEEK_QTY,
  SVD_REPORT.OH_QTY                   AS OH_QTY,
  SVD_REPORT.STOCK_IN_TRANSIT_QTY     AS STOCK_IN_TRANSIT_QTY,
  SVD_REPORT.BACKLOG_OPEN             AS BACKLOG_OPEN,
  SVD_REPORT.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS,
  SVD_REPORT.PAST_DUE_OPEN            AS PAST_DUE_OPEN
FROM
  (SELECT SVD_REPORT_ADD.ID                 AS ID,
    SVD_REPORT_ADD.MATERIAL                 AS MATERIAL,
    SVD_REPORT_ADD.PLANT                    AS PLANT,
    SVD_REPORT_ADD.STRATEGY_GRP             AS STRATEGY_GRP,
    SVD_REPORT_ADD.SBU                      AS SBU,
    SVD_REPORT_ADD.SAFETY_STK               AS SAFETY_STK,
    SVD_REPORT_ADD.OH_QTY                   AS OH_QTY,
    SVD_REPORT_ADD.BACKLOG_OPEN             AS BACKLOG_OPEN,
    SVD_REPORT_ADD.PAST_DUE_OPEN            AS PAST_DUE_OPEN,
    SVD_REPORT_ADD.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS,
    SVD_REPORT_ADD.STOCK_IN_TRANSIT_QTY     AS STOCK_IN_TRANSIT_QTY
  FROM
    (SELECT DISTINCT MATERIAL
      ||'_'
      ||PLANT AS ID
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP
    WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )OPEN_ORDER_MATERIAL
  LEFT JOIN
    (SELECT SVD_BASISC_INFO.ID                 AS ID,
      SVD_BASISC_INFO.MATERIAL                 AS MATERIAL,
      (SVD_BASISC_INFO.PLANT - 1)              AS PLANT,
      SVD_BASISC_INFO.STRATEGY_GRP             AS STRATEGY_GRP,
      SUBSTR(SVD_BASISC_INFO.SBU,0,3)          AS SBU,
      SVD_BASISC_INFO.SAFETY_STK               AS SAFETY_STK,
      SVD_BASISC_INFO.OH_QTY                   AS OH_QTY,
      SVD_BASISC_INFO.BACKLOG_OPEN             AS BACKLOG_OPEN,
      SVD_BASISC_INFO.PAST_DUE_OPEN            AS PAST_DUE_OPEN,
      SVD_BASISC_INFO.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS,
      STOCK_IN_TRAINST.STOCK_IN_TRANSIT_QTY    AS STOCK_IN_TRANSIT_QTY
    FROM
      (SELECT PP_INFO.ID                                   AS ID,
        PP_INFO.MATERIALID                                 AS MATERIAL,
        PP_INFO.PLANTID                                    AS PLANT,
        PP_INFO.STRATEGY_GRP                               AS STRATEGY_GRP,
        PP_INFO.PROD_BU                                    AS SBU,
        PP_INFO.SAFETY_STK                                 AS SAFETY_STK,
        PP_INFO.OH_QTY                                     AS OH_QTY,
        BACKLOG_PASTDUE_DUE_THREE.BACKLOG_OPEN             AS BACKLOG_OPEN,
        BACKLOG_PASTDUE_DUE_THREE.PAST_DUE_OPEN            AS PAST_DUE_OPEN,
        BACKLOG_PASTDUE_DUE_THREE.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS
      FROM
        (SELECT MATERIALID
          ||'_'
          ||(PLANTID - 1) AS ID,
          MATERIALID,
          PLANTID,
          STRATEGY_GRP,
          PROD_BU,
          SAFETY_STK,
          OH_QTY
        FROM INV_SAP_PP_OPTIMIZATION
        WHERE STRATEGY_GRP  IN ('SG', '40', 'Z4')
        AND MATL_TYPE_MTART IN ('ZFG','ZTG')
        AND PLANTID         IN ('5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141')
        )PP_INFO
      LEFT JOIN
        (SELECT BACKLOG_PASTDUE.ID                    AS ID,
          BACKLOG_PASTDUE.BACKLOG_OPEN                AS BACKLOG_OPEN,
          BACKLOG_PASTDUE.PAST_DUE_OPEN               AS PAST_DUE_OPEN,
          DUE_IN_THREE_WEEKS.DUE_OPEN_QTY_THREE_WEEKS AS DUE_OPEN_QTY_THREE_WEEKS
        FROM
          (SELECT BACKLOG_OPEN.ID           AS ID,
            BACKLOG_OPEN.OPEN_QTY           AS BACKLOG_OPEN,
            PAST_DUE_OPEN.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN
          FROM
            (SELECT MATERIAL
              ||'_'
              ||PLANT       AS ID,
              MATERIAL      AS MATERIALID,
              PLANT         AS PLANTID,
              SUM(OPEN_QTY) AS OPEN_QTY
            FROM INV_SAP_SALES_VBAK_VBAP_VBUP
            WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
            AND MAX_COMMIT_DATE < SYSDATE + 91
            GROUP BY MATERIAL
              ||'_'
              ||PLANT,
              MATERIAL,
              PLANT
            )BACKLOG_OPEN
          LEFT JOIN
            (SELECT MATERIAL
              ||'_'
              ||PLANT       AS ID,
              MATERIAL      AS MATERIALID,
              PLANT         AS PLANTID,
              SUM(OPEN_QTY) AS PAST_DUE_OPEN_QTY
            FROM INV_SAP_SALES_VBAK_VBAP_VBUP
            WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
            AND MAX_COMMIT_DATE < SYSDATE - 1
            GROUP BY MATERIAL
              ||'_'
              ||PLANT,
              MATERIAL,
              PLANT
            )PAST_DUE_OPEN
          ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID
          )BACKLOG_PASTDUE
        LEFT JOIN
          (SELECT MATERIAL
            ||'_'
            ||PLANT       AS ID,
            MATERIAL      AS MATERIALID,
            PLANT         AS PLANTID,
            SUM(OPEN_QTY) AS DUE_OPEN_QTY_THREE_WEEKS
          FROM INV_SAP_SALES_VBAK_VBAP_VBUP
          WHERE PLANT                                                      IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
          AND (MAX_COMMIT_DATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 21))
          GROUP BY MATERIAL
            ||'_'
            ||PLANT,
            MATERIAL,
            PLANT
          )DUE_IN_THREE_WEEKS
        ON DUE_IN_THREE_WEEKS.ID                                   = BACKLOG_PASTDUE.ID
        )BACKLOG_PASTDUE_DUE_THREE ON BACKLOG_PASTDUE_DUE_THREE.ID = PP_INFO.ID
      )SVD_BASISC_INFO
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||PLANTID AS ID,
        MATERIALID,
        PLANTID,
        SUM(DELIVERY_QTY_SUOM) AS STOCK_IN_TRANSIT_QTY
      FROM INV_SAP_LIKP_LIPS_DAILY
      WHERE REFERENCE_DOC_TRIM IN
        (SELECT EBELNPURCHDOCNO
        FROM INV_SAP_PP_PO_HISTORY
        WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
        AND DELIVERYCOMPLETE IS NULL
        )
      AND CHANGED_ON_DATE IS NULL
      GROUP BY MATERIALID,
        MATERIALID,
        PLANTID
      )STOCK_IN_TRAINST
    ON STOCK_IN_TRAINST.ID               = SVD_BASISC_INFO.ID
    )SVD_REPORT_ADD ON SVD_REPORT_ADD.ID = OPEN_ORDER_MATERIAL.ID
  )SVD_REPORT
LEFT JOIN
  (SELECT MATERIALID
    ||'_'
    ||PLANTID                           AS ID,
    MATERIALID                          AS MATERIALID,
    PLANTID                             AS PLANTID,
    CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK
  FROM INV_SAP_PP_FRCST_PBIM_PBED
  WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
  AND PLANTID                                                                        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
  AND VERSBP_VERSION = '55'
  GROUP BY MATERIALID,
    MATERIALID
    ||'_'
    ||PLANTID,
    PLANTID,
    MATERIALID
  )FC_AVG_WEEK
ON FC_AVG_WEEK.ID = SVD_REPORT.ID;


--Add Sales Orders detail review
SELECT * FROM 
(
SELECT SALES_PP.ID                   AS ID,
  SALES_PP.SALESDOC                  AS SALES_DOC,
  SALES_PP.SALESDOCITEM              AS ITEM,
  SALES_PP.MATERIAL                  AS MATERIAL,
  SALES_PP.MATERIAL_DES              AS MATERIAL_DES,
  SALES_PP.PLANT                     AS PLANT,
  SALES_PP.LINECREATEDATE            AS LINE_CREATE_DATE,
  SALES_PP.ORDERQTY                  AS ORDER_QTY,
  SALES_PP.DELIVPRIO                 AS DELIVERY_PRIORITY,
  SALES_PP.SALESPRICE                AS SALES_PRICE,
  SALES_PP.COST                      AS COST,
  SALES_PP.MAX_COMMIT_DATE           AS COMMITTED_DATE,
  SALES_PP.MAX_CONFIRM_DATE          AS CONFIRM_DATE,
  SALES_PP.SALESDOCTYPE              AS SALES_DOC_TYPE,
  SALES_PP.SALEDOCITEMCATEGORY_PSTYV AS SALEDOCITEMCATEGORY_PSTYV,
  SALES_PP.SHIPFROM_VSTEL            AS SHIPPING_POINT,
  SALES_PP.SALES_ORG                 AS SALES_ORG,
  SALES_PP.CURRENCY                  AS CURRENCY,
  SALES_PP.OPEN_QTY                  AS OPEN_QTY,
  SALES_PP.OPEN_QTY_BASE_UOM         AS OPEN_QTY_BASE_UOM,
  SALES_PP.LST_ACT_GI_DATE           AS LST_ACT_GI_DATE,
  SALES_PP.LST_DELV_CREATED_DATE     AS LST_DELV_CREATED_DATE,
  SALES_PP.EXCHANGE_RATE_TO_USD      AS RATE,
  SALES_PP.SAFTY_STOCK               AS SAFTY_STOCK,
  SALES_PP.OH_QTY                    AS OH_QTY,
  SALES_PP.PROD_BU                   AS PROD_BU,
  SALES_PP.MRP_CONTROLLER            AS MRP_CONTROLLER,
  SALES_PP.PURCH_GROUP               AS PURCH_GROUP,
  SALES_PP.PROC_TYPE                 AS PROC_TYPE,
  SALES_PP.UNIT                      AS UNIT,
  SALES_PP.STRATEGY_GRP              AS STRATEGY_GRP,
  SALES_PP.MRP_TYPE                  AS MRP_TYPE,
  PT_BK.SOLD_TO_PARTY                AS SOLD_TO_PARTY,
  PT_BK.CUSTOMER_NAME                AS CUSTOMER_NAME,
  PT_BK.D_CHAIN_BLK                  AS D_CHAIN_BLK,
  SALES_PP.PSPT                      AS PAST_ORDER_NUMBER
FROM
  (SELECT SALES_BASE.ID AS ID,
    SALES_BASE.SALESDOC,
    SALES_BASE.SALESDOCITEM,
    SALES_BASE.MATERIAL,
    SALES_BASE.PLANT,
    SALES_BASE.LINECREATEDATE,
    SALES_BASE.PRODHIER,
    SALES_BASE.ORDERQTY,
    SALES_BASE.CONFIRMQTY,
    SALES_BASE.DELIVPRIO,
    SALES_BASE.LINECREATEDCOUNTER,
    SALES_BASE.PROFITCENTER,
    SALES_BASE.SALESPRICE,
    SALES_BASE.COST,
    SALES_BASE.STOCKSTATUS,
    SALES_BASE.MAX_COMMIT_DATE,
    SALES_BASE.REQTYPE,
    SALES_BASE.PSPT,
    SALES_BASE.HEADERCREATECOUNTER,
    SALES_BASE.MAX_CONFIRM_DATE,
    SALES_BASE.SOLD_TO,
    SALES_BASE.SALESOFF,
    SALES_BASE.TELE,
    SALES_BASE.DELIVSTATUS,
    SALES_BASE.OVERALLDELIVSTATSU,
    SALES_BASE.REJECTSTATUS,
    SALES_BASE.DW_DATE,
    SALES_BASE.SALESDOCTYPE,
    SALES_BASE.REJECTREASON_ABGRU,
    SALES_BASE.SALEDOCITEMCATEGORY_PSTYV,
    SALES_BASE.REQ_DELIVERYQTY_LSMENG,
    SALES_BASE.SHIPFROM_VSTEL,
    SALES_BASE.SALES_ORG,
    SALES_BASE.CURRENCY,
    SALES_BASE.NUMERATOR,
    SALES_BASE.DENOMINATOR,
    SALES_BASE.OPEN_QTY,
    SALES_BASE.OPEN_QTY_BASE_UOM,
    SALES_BASE.LST_ACT_GI_DATE,
    SALES_BASE.LST_DELV_CREATED_DATE,
    SALES_BASE.EXCHANGE_RATE_TO_USD,
    PPINF.MATERIAL_DES   AS MATERIAL_DES,
    PPINF.SAFTY_STOCK    AS SAFTY_STOCK,
    PPINF.OH_QTY         AS OH_QTY,
    PPINF.PROD_BU        AS PROD_BU,
    PPINF.PROD_FAM       AS PROD_FAM,
    PPINF.PROD_HIERARCHY AS PROD_HIERARCHY,
    PPINF.MRP_CONTROLLER AS MRP_CONTROLLER,
    PPINF.PURCH_GROUP    AS PURCH_GROUP,
    PPINF.PROC_TYPE      AS PROC_TYPE,
    PPINF.PROD_SCHEDULER AS PROD_SCHEDULER,
    PPINF.LOT_SIZE_DIS   AS LOT_SIZE_DIS,
    PPINF.UNIT           AS UNIT,
    PPINF.STRATEGY_GRP   AS STRATEGY_GRP,
    PPINF.MRP_TYPE       AS MRP_TYPE
  FROM
    (SELECT SALESDOC
      ||'_'
      || SALESDOCITEM AS ID,
      SALESDOC,
      SALESDOCITEM,
      MATERIAL,
      PLANT,
      LINECREATEDATE,
      PRODHIER,
      ORDERQTY,
      CONFIRMQTY,
      DELIVPRIO,
      LINECREATEDCOUNTER,
      PROFITCENTER,
      SALESPRICE,
      COST,
      STOCKSTATUS,
      MAX_COMMIT_DATE,
      REQTYPE,
      PSPT,
      HEADERCREATECOUNTER,
      MAX_CONFIRM_DATE,
      SOLD_TO,
      SALESOFF,
      TELE,
      DELIVSTATUS,
      OVERALLDELIVSTATSU,
      REJECTSTATUS,
      DW_DATE,
      SALESDOCTYPE,
      REJECTREASON_ABGRU,
      SALEDOCITEMCATEGORY_PSTYV,
      REQ_DELIVERYQTY_LSMENG,
      SHIPFROM_VSTEL,
      SALES_ORG,
      CURRENCY,
      NUMERATOR,
      DENOMINATOR,
      OPEN_QTY,
      OPEN_QTY_BASE_UOM,
      LST_ACT_GI_DATE,
      LST_DELV_CREATED_DATE,
      EXCHANGE_RATE_TO_USD
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP
    )SALES_BASE
  LEFT JOIN
    (SELECT SOFR_PP.ID   AS ID,
      PP.PLANTID         AS PLANT,
      PP.MATERIALID      AS MATERIAL,
      PP.MAT_DESC        AS MATERIAL_DES,
      PP.SAFETY_STK      AS SAFTY_STOCK,
      PP.OH_QTY          AS OH_QTY,
      PP.PROD_BU         AS PROD_BU,
      PP.PROD_FAM        AS PROD_FAM,
      PP.PROD_HIERARCHY  AS PROD_HIERARCHY,
      PP.MRP_CONTROLLER  AS MRP_CONTROLLER,
      PP.PURCH_GROUP     AS PURCH_GROUP,
      PP.PROC_TYPE       AS PROC_TYPE,
      PP.PROD_SCHEDULER  AS PROD_SCHEDULER,
      PP.LOT_SIZE_DISLS  AS LOT_SIZE_DIS,
      PP.MEINS_ISSUE_UOM AS UNIT,
      PP.STRATEGY_GRP    AS STRATEGY_GRP,
      PP.MRP_TYPE        AS MRP_TYPE
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SOFR_PP
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        || PLANTID AS ID1,
        MATERIALID,
        PLANTID,
        MAT_DESC,
        SAFETY_STK,
        OH_QTY,
        SUBSTR(PROD_BU,0,3) AS PROD_BU,
        PROD_FAM,
        PROD_HIERARCHY,
        MRP_CONTROLLER,
        PURCH_GROUP,
        PROC_TYPE,
        PROD_SCHEDULER,
        LOT_SIZE_DISLS,
        MEINS_ISSUE_UOM,
        STRATEGY_GRP,
        MRP_TYPE
      FROM INV_SAP_PP_OPTIMIZATION
      )PP
    ON PP.ID1          = SOFR_PP.ID1
    )PPINF ON PPINF.ID = SALES_BASE.ID
  )SALES_PP
LEFT JOIN
  (SELECT SOLD_PT.ID      AS ID,
    SOLD_PT.SOLD_TO_PARTY AS SOLD_TO_PARTY,
    SOLD_PT.CUSTOMER_NAME AS CUSTOMER_NAME,
    ITEM_BK.MATERIAL      AS MATERIAL,
    ITEM_BK.D_CHAIN_BLK   AS D_CHAIN_BLK
  FROM
    (
    ---SOLD TO PATY INFORMAITON
    SELECT STPT_S.ID,
      STPT_S.SOLD_TO_PARTY,
      STPT_P.CUSTOMER_NAME
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        SOLD_TO         AS SOLD_TO_PARTY
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )STPT_S
    LEFT JOIN
      (SELECT SHIP_SOLD_TOPARTY AS SOLD_TO_PARTY,
        SHIP_TO_PARTY_NAME      AS CUSTOMER_NAME
      FROM INV_SAP_SHIP_SOLD_TO_PARTYID
      ) STPT_P
    ON STPT_P.SOLD_TO_PARTY = STPT_S.SOLD_TO_PARTY
    )SOLD_PT
  LEFT JOIN
    (
    --DEFAULT Delivery Block
    SELECT SALE_BK.ID     AS ID,
      SALE_BK.MATERIAL    AS MATERIAL,
      MVKE_BK.D_CHAIN_BLK AS D_CHAIN_BLK
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SALE_BK
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||DIRECT_SHIP_PLANT AS ID,
        MATERIALID,
        D_CHAIN_BLK,
        DIRECT_SHIP_PLANT
      FROM INV_SAP_PP_MVKE
      )MVKE_BK
    ON MVKE_BK.ID          = SALE_BK.ID1
    )ITEM_BK ON ITEM_BK.ID = SOLD_PT.ID
  )PT_BK ON PT_BK.ID       = SALES_PP.ID
  )WHERE COMMITTED_DATE < SYSDATE + 91 AND PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

----Sales Pass due
SELECT * FROM 
(
SELECT SALES_PP.ID                   AS ID,
  SALES_PP.SALESDOC                  AS SALES_DOC,
  SALES_PP.SALESDOCITEM              AS ITEM,
  SALES_PP.MATERIAL                  AS MATERIAL,
  SALES_PP.MATERIAL_DES              AS MATERIAL_DES,
  SALES_PP.PLANT                     AS PLANT,
  SALES_PP.LINECREATEDATE            AS LINE_CREATE_DATE,
  SALES_PP.ORDERQTY                  AS ORDER_QTY,
  SALES_PP.DELIVPRIO                 AS DELIVERY_PRIORITY,
  SALES_PP.SALESPRICE                AS SALES_PRICE,
  SALES_PP.COST                      AS COST,
  SALES_PP.MAX_COMMIT_DATE           AS COMMITTED_DATE,
  SALES_PP.MAX_CONFIRM_DATE          AS CONFIRM_DATE,
  SALES_PP.SALESDOCTYPE              AS SALES_DOC_TYPE,
  SALES_PP.SALEDOCITEMCATEGORY_PSTYV AS SALEDOCITEMCATEGORY_PSTYV,
  SALES_PP.SHIPFROM_VSTEL            AS SHIPPING_POINT,
  SALES_PP.SALES_ORG                 AS SALES_ORG,
  SALES_PP.CURRENCY                  AS CURRENCY,
  SALES_PP.OPEN_QTY                  AS OPEN_QTY,
  SALES_PP.OPEN_QTY_BASE_UOM         AS OPEN_QTY_BASE_UOM,
  SALES_PP.LST_ACT_GI_DATE           AS LST_ACT_GI_DATE,
  SALES_PP.LST_DELV_CREATED_DATE     AS LST_DELV_CREATED_DATE,
  SALES_PP.EXCHANGE_RATE_TO_USD      AS RATE,
  SALES_PP.SAFTY_STOCK               AS SAFTY_STOCK,
  SALES_PP.OH_QTY                    AS OH_QTY,
  SALES_PP.PROD_BU                   AS PROD_BU,
  SALES_PP.MRP_CONTROLLER            AS MRP_CONTROLLER,
  SALES_PP.PURCH_GROUP               AS PURCH_GROUP,
  SALES_PP.PROC_TYPE                 AS PROC_TYPE,
  SALES_PP.UNIT                      AS UNIT,
  SALES_PP.STRATEGY_GRP              AS STRATEGY_GRP,
  SALES_PP.MRP_TYPE                  AS MRP_TYPE,
  PT_BK.SOLD_TO_PARTY                AS SOLD_TO_PARTY,
  PT_BK.CUSTOMER_NAME                AS CUSTOMER_NAME,
  PT_BK.D_CHAIN_BLK                  AS D_CHAIN_BLK,
  SALES_PP.PSPT                      AS PAST_ORDER_NUMBER
FROM
  (SELECT SALES_BASE.ID AS ID,
    SALES_BASE.SALESDOC,
    SALES_BASE.SALESDOCITEM,
    SALES_BASE.MATERIAL,
    SALES_BASE.PLANT,
    SALES_BASE.LINECREATEDATE,
    SALES_BASE.PRODHIER,
    SALES_BASE.ORDERQTY,
    SALES_BASE.CONFIRMQTY,
    SALES_BASE.DELIVPRIO,
    SALES_BASE.LINECREATEDCOUNTER,
    SALES_BASE.PROFITCENTER,
    SALES_BASE.SALESPRICE,
    SALES_BASE.COST,
    SALES_BASE.STOCKSTATUS,
    SALES_BASE.MAX_COMMIT_DATE,
    SALES_BASE.REQTYPE,
    SALES_BASE.PSPT,
    SALES_BASE.HEADERCREATECOUNTER,
    SALES_BASE.MAX_CONFIRM_DATE,
    SALES_BASE.SOLD_TO,
    SALES_BASE.SALESOFF,
    SALES_BASE.TELE,
    SALES_BASE.DELIVSTATUS,
    SALES_BASE.OVERALLDELIVSTATSU,
    SALES_BASE.REJECTSTATUS,
    SALES_BASE.DW_DATE,
    SALES_BASE.SALESDOCTYPE,
    SALES_BASE.REJECTREASON_ABGRU,
    SALES_BASE.SALEDOCITEMCATEGORY_PSTYV,
    SALES_BASE.REQ_DELIVERYQTY_LSMENG,
    SALES_BASE.SHIPFROM_VSTEL,
    SALES_BASE.SALES_ORG,
    SALES_BASE.CURRENCY,
    SALES_BASE.NUMERATOR,
    SALES_BASE.DENOMINATOR,
    SALES_BASE.OPEN_QTY,
    SALES_BASE.OPEN_QTY_BASE_UOM,
    SALES_BASE.LST_ACT_GI_DATE,
    SALES_BASE.LST_DELV_CREATED_DATE,
    SALES_BASE.EXCHANGE_RATE_TO_USD,
    PPINF.MATERIAL_DES   AS MATERIAL_DES,
    PPINF.SAFTY_STOCK    AS SAFTY_STOCK,
    PPINF.OH_QTY         AS OH_QTY,
    PPINF.PROD_BU        AS PROD_BU,
    PPINF.PROD_FAM       AS PROD_FAM,
    PPINF.PROD_HIERARCHY AS PROD_HIERARCHY,
    PPINF.MRP_CONTROLLER AS MRP_CONTROLLER,
    PPINF.PURCH_GROUP    AS PURCH_GROUP,
    PPINF.PROC_TYPE      AS PROC_TYPE,
    PPINF.PROD_SCHEDULER AS PROD_SCHEDULER,
    PPINF.LOT_SIZE_DIS   AS LOT_SIZE_DIS,
    PPINF.UNIT           AS UNIT,
    PPINF.STRATEGY_GRP   AS STRATEGY_GRP,
    PPINF.MRP_TYPE       AS MRP_TYPE
  FROM
    (SELECT SALESDOC
      ||'_'
      || SALESDOCITEM AS ID,
      SALESDOC,
      SALESDOCITEM,
      MATERIAL,
      PLANT,
      LINECREATEDATE,
      PRODHIER,
      ORDERQTY,
      CONFIRMQTY,
      DELIVPRIO,
      LINECREATEDCOUNTER,
      PROFITCENTER,
      SALESPRICE,
      COST,
      STOCKSTATUS,
      MAX_COMMIT_DATE,
      REQTYPE,
      PSPT,
      HEADERCREATECOUNTER,
      MAX_CONFIRM_DATE,
      SOLD_TO,
      SALESOFF,
      TELE,
      DELIVSTATUS,
      OVERALLDELIVSTATSU,
      REJECTSTATUS,
      DW_DATE,
      SALESDOCTYPE,
      REJECTREASON_ABGRU,
      SALEDOCITEMCATEGORY_PSTYV,
      REQ_DELIVERYQTY_LSMENG,
      SHIPFROM_VSTEL,
      SALES_ORG,
      CURRENCY,
      NUMERATOR,
      DENOMINATOR,
      OPEN_QTY,
      OPEN_QTY_BASE_UOM,
      LST_ACT_GI_DATE,
      LST_DELV_CREATED_DATE,
      EXCHANGE_RATE_TO_USD
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP 
    )SALES_BASE
  LEFT JOIN
    (SELECT SOFR_PP.ID   AS ID,
      PP.PLANTID         AS PLANT,
      PP.MATERIALID      AS MATERIAL,
      PP.MAT_DESC        AS MATERIAL_DES,
      PP.SAFETY_STK      AS SAFTY_STOCK,
      PP.OH_QTY          AS OH_QTY,
      PP.PROD_BU         AS PROD_BU,
      PP.PROD_FAM        AS PROD_FAM,
      PP.PROD_HIERARCHY  AS PROD_HIERARCHY,
      PP.MRP_CONTROLLER  AS MRP_CONTROLLER,
      PP.PURCH_GROUP     AS PURCH_GROUP,
      PP.PROC_TYPE       AS PROC_TYPE,
      PP.PROD_SCHEDULER  AS PROD_SCHEDULER,
      PP.LOT_SIZE_DISLS  AS LOT_SIZE_DIS,
      PP.MEINS_ISSUE_UOM AS UNIT,
      PP.STRATEGY_GRP    AS STRATEGY_GRP,
      PP.MRP_TYPE        AS MRP_TYPE
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SOFR_PP
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        || PLANTID AS ID1,
        MATERIALID,
        PLANTID,
        MAT_DESC,
        SAFETY_STK,
        OH_QTY,
        SUBSTR(PROD_BU,0,3) AS PROD_BU,
        PROD_FAM,
        PROD_HIERARCHY,
        MRP_CONTROLLER,
        PURCH_GROUP,
        PROC_TYPE,
        PROD_SCHEDULER,
        LOT_SIZE_DISLS,
        MEINS_ISSUE_UOM,
        STRATEGY_GRP,
        MRP_TYPE
      FROM INV_SAP_PP_OPTIMIZATION
      )PP
    ON PP.ID1          = SOFR_PP.ID1
    )PPINF ON PPINF.ID = SALES_BASE.ID
  )SALES_PP
LEFT JOIN
  (SELECT SOLD_PT.ID      AS ID,
    SOLD_PT.SOLD_TO_PARTY AS SOLD_TO_PARTY,
    SOLD_PT.CUSTOMER_NAME AS CUSTOMER_NAME,
    ITEM_BK.MATERIAL      AS MATERIAL,
    ITEM_BK.D_CHAIN_BLK   AS D_CHAIN_BLK
  FROM
    (
    ---SOLD TO PATY INFORMAITON
    SELECT STPT_S.ID,
      STPT_S.SOLD_TO_PARTY,
      STPT_P.CUSTOMER_NAME
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        SOLD_TO         AS SOLD_TO_PARTY
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )STPT_S
    LEFT JOIN
      (SELECT SHIP_SOLD_TOPARTY AS SOLD_TO_PARTY,
        SHIP_TO_PARTY_NAME      AS CUSTOMER_NAME
      FROM INV_SAP_SHIP_SOLD_TO_PARTYID
      ) STPT_P
    ON STPT_P.SOLD_TO_PARTY = STPT_S.SOLD_TO_PARTY
    )SOLD_PT
  LEFT JOIN
    (
    --DEFAULT Delivery Block
    SELECT SALE_BK.ID     AS ID,
      SALE_BK.MATERIAL    AS MATERIAL,
      MVKE_BK.D_CHAIN_BLK AS D_CHAIN_BLK
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SALE_BK
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||DIRECT_SHIP_PLANT AS ID,
        MATERIALID,
        D_CHAIN_BLK,
        DIRECT_SHIP_PLANT
      FROM INV_SAP_PP_MVKE
      )MVKE_BK
    ON MVKE_BK.ID          = SALE_BK.ID1
    )ITEM_BK ON ITEM_BK.ID = SOLD_PT.ID
  )PT_BK ON PT_BK.ID       = SALES_PP.ID
  )WHERE COMMITTED_DATE < SYSDATE - 1 AND PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

---Sales Orders Due 2 weeks
SELECT * FROM 
(
SELECT SALES_PP.ID                   AS ID,
  SALES_PP.SALESDOC                  AS SALES_DOC,
  SALES_PP.SALESDOCITEM              AS ITEM,
  SALES_PP.MATERIAL                  AS MATERIAL,
  SALES_PP.MATERIAL_DES              AS MATERIAL_DES,
  SALES_PP.PLANT                     AS PLANT,
  SALES_PP.LINECREATEDATE            AS LINE_CREATE_DATE,
  SALES_PP.ORDERQTY                  AS ORDER_QTY,
  SALES_PP.DELIVPRIO                 AS DELIVERY_PRIORITY,
  SALES_PP.SALESPRICE                AS SALES_PRICE,
  SALES_PP.COST                      AS COST,
  SALES_PP.MAX_COMMIT_DATE           AS COMMITTED_DATE,
  SALES_PP.MAX_CONFIRM_DATE          AS CONFIRM_DATE,
  SALES_PP.SALESDOCTYPE              AS SALES_DOC_TYPE,
  SALES_PP.SALEDOCITEMCATEGORY_PSTYV AS SALEDOCITEMCATEGORY_PSTYV,
  SALES_PP.SHIPFROM_VSTEL            AS SHIPPING_POINT,
  SALES_PP.SALES_ORG                 AS SALES_ORG,
  SALES_PP.CURRENCY                  AS CURRENCY,
  SALES_PP.OPEN_QTY                  AS OPEN_QTY,
  SALES_PP.OPEN_QTY_BASE_UOM         AS OPEN_QTY_BASE_UOM,
  SALES_PP.LST_ACT_GI_DATE           AS LST_ACT_GI_DATE,
  SALES_PP.LST_DELV_CREATED_DATE     AS LST_DELV_CREATED_DATE,
  SALES_PP.EXCHANGE_RATE_TO_USD      AS RATE,
  SALES_PP.SAFTY_STOCK               AS SAFTY_STOCK,
  SALES_PP.OH_QTY                    AS OH_QTY,
  SALES_PP.PROD_BU                   AS PROD_BU,
  SALES_PP.MRP_CONTROLLER            AS MRP_CONTROLLER,
  SALES_PP.PURCH_GROUP               AS PURCH_GROUP,
  SALES_PP.PROC_TYPE                 AS PROC_TYPE,
  SALES_PP.UNIT                      AS UNIT,
  SALES_PP.STRATEGY_GRP              AS STRATEGY_GRP,
  SALES_PP.MRP_TYPE                  AS MRP_TYPE,
  PT_BK.SOLD_TO_PARTY                AS SOLD_TO_PARTY,
  PT_BK.CUSTOMER_NAME                AS CUSTOMER_NAME,
  PT_BK.D_CHAIN_BLK                  AS D_CHAIN_BLK,
  SALES_PP.PSPT                      AS PAST_ORDER_NUMBER
FROM
  (SELECT SALES_BASE.ID AS ID,
    SALES_BASE.SALESDOC,
    SALES_BASE.SALESDOCITEM,
    SALES_BASE.MATERIAL,
    SALES_BASE.PLANT,
    SALES_BASE.LINECREATEDATE,
    SALES_BASE.PRODHIER,
    SALES_BASE.ORDERQTY,
    SALES_BASE.CONFIRMQTY,
    SALES_BASE.DELIVPRIO,
    SALES_BASE.LINECREATEDCOUNTER,
    SALES_BASE.PROFITCENTER,
    SALES_BASE.SALESPRICE,
    SALES_BASE.COST,
    SALES_BASE.STOCKSTATUS,
    SALES_BASE.MAX_COMMIT_DATE,
    SALES_BASE.REQTYPE,
    SALES_BASE.PSPT,
    SALES_BASE.HEADERCREATECOUNTER,
    SALES_BASE.MAX_CONFIRM_DATE,
    SALES_BASE.SOLD_TO,
    SALES_BASE.SALESOFF,
    SALES_BASE.TELE,
    SALES_BASE.DELIVSTATUS,
    SALES_BASE.OVERALLDELIVSTATSU,
    SALES_BASE.REJECTSTATUS,
    SALES_BASE.DW_DATE,
    SALES_BASE.SALESDOCTYPE,
    SALES_BASE.REJECTREASON_ABGRU,
    SALES_BASE.SALEDOCITEMCATEGORY_PSTYV,
    SALES_BASE.REQ_DELIVERYQTY_LSMENG,
    SALES_BASE.SHIPFROM_VSTEL,
    SALES_BASE.SALES_ORG,
    SALES_BASE.CURRENCY,
    SALES_BASE.NUMERATOR,
    SALES_BASE.DENOMINATOR,
    SALES_BASE.OPEN_QTY,
    SALES_BASE.OPEN_QTY_BASE_UOM,
    SALES_BASE.LST_ACT_GI_DATE,
    SALES_BASE.LST_DELV_CREATED_DATE,
    SALES_BASE.EXCHANGE_RATE_TO_USD,
    PPINF.MATERIAL_DES   AS MATERIAL_DES,
    PPINF.SAFTY_STOCK    AS SAFTY_STOCK,
    PPINF.OH_QTY         AS OH_QTY,
    PPINF.PROD_BU        AS PROD_BU,
    PPINF.PROD_FAM       AS PROD_FAM,
    PPINF.PROD_HIERARCHY AS PROD_HIERARCHY,
    PPINF.MRP_CONTROLLER AS MRP_CONTROLLER,
    PPINF.PURCH_GROUP    AS PURCH_GROUP,
    PPINF.PROC_TYPE      AS PROC_TYPE,
    PPINF.PROD_SCHEDULER AS PROD_SCHEDULER,
    PPINF.LOT_SIZE_DIS   AS LOT_SIZE_DIS,
    PPINF.UNIT           AS UNIT,
    PPINF.STRATEGY_GRP   AS STRATEGY_GRP,
    PPINF.MRP_TYPE       AS MRP_TYPE
  FROM
    (SELECT SALESDOC
      ||'_'
      || SALESDOCITEM AS ID,
      SALESDOC,
      SALESDOCITEM,
      MATERIAL,
      PLANT,
      LINECREATEDATE,
      PRODHIER,
      ORDERQTY,
      CONFIRMQTY,
      DELIVPRIO,
      LINECREATEDCOUNTER,
      PROFITCENTER,
      SALESPRICE,
      COST,
      STOCKSTATUS,
      MAX_COMMIT_DATE,
      REQTYPE,
      PSPT,
      HEADERCREATECOUNTER,
      MAX_CONFIRM_DATE,
      SOLD_TO,
      SALESOFF,
      TELE,
      DELIVSTATUS,
      OVERALLDELIVSTATSU,
      REJECTSTATUS,
      DW_DATE,
      SALESDOCTYPE,
      REJECTREASON_ABGRU,
      SALEDOCITEMCATEGORY_PSTYV,
      REQ_DELIVERYQTY_LSMENG,
      SHIPFROM_VSTEL,
      SALES_ORG,
      CURRENCY,
      NUMERATOR,
      DENOMINATOR,
      OPEN_QTY,
      OPEN_QTY_BASE_UOM,
      LST_ACT_GI_DATE,
      LST_DELV_CREATED_DATE,
      EXCHANGE_RATE_TO_USD
    FROM INV_SAP_SALES_VBAK_VBAP_VBUP 
    )SALES_BASE
  LEFT JOIN
    (SELECT SOFR_PP.ID   AS ID,
      PP.PLANTID         AS PLANT,
      PP.MATERIALID      AS MATERIAL,
      PP.MAT_DESC        AS MATERIAL_DES,
      PP.SAFETY_STK      AS SAFTY_STOCK,
      PP.OH_QTY          AS OH_QTY,
      PP.PROD_BU         AS PROD_BU,
      PP.PROD_FAM        AS PROD_FAM,
      PP.PROD_HIERARCHY  AS PROD_HIERARCHY,
      PP.MRP_CONTROLLER  AS MRP_CONTROLLER,
      PP.PURCH_GROUP     AS PURCH_GROUP,
      PP.PROC_TYPE       AS PROC_TYPE,
      PP.PROD_SCHEDULER  AS PROD_SCHEDULER,
      PP.LOT_SIZE_DISLS  AS LOT_SIZE_DIS,
      PP.MEINS_ISSUE_UOM AS UNIT,
      PP.STRATEGY_GRP    AS STRATEGY_GRP,
      PP.MRP_TYPE        AS MRP_TYPE
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SOFR_PP
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        || PLANTID AS ID1,
        MATERIALID,
        PLANTID,
        MAT_DESC,
        SAFETY_STK,
        OH_QTY,
        SUBSTR(PROD_BU,0,3) AS PROD_BU,
        PROD_FAM,
        PROD_HIERARCHY,
        MRP_CONTROLLER,
        PURCH_GROUP,
        PROC_TYPE,
        PROD_SCHEDULER,
        LOT_SIZE_DISLS,
        MEINS_ISSUE_UOM,
        STRATEGY_GRP,
        MRP_TYPE
      FROM INV_SAP_PP_OPTIMIZATION
      )PP
    ON PP.ID1          = SOFR_PP.ID1
    )PPINF ON PPINF.ID = SALES_BASE.ID
  )SALES_PP
LEFT JOIN
  (SELECT SOLD_PT.ID      AS ID,
    SOLD_PT.SOLD_TO_PARTY AS SOLD_TO_PARTY,
    SOLD_PT.CUSTOMER_NAME AS CUSTOMER_NAME,
    ITEM_BK.MATERIAL      AS MATERIAL,
    ITEM_BK.D_CHAIN_BLK   AS D_CHAIN_BLK
  FROM
    (
    ---SOLD TO PATY INFORMAITON
    SELECT STPT_S.ID,
      STPT_S.SOLD_TO_PARTY,
      STPT_P.CUSTOMER_NAME
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        SOLD_TO         AS SOLD_TO_PARTY
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )STPT_S
    LEFT JOIN
      (SELECT SHIP_SOLD_TOPARTY AS SOLD_TO_PARTY,
        SHIP_TO_PARTY_NAME      AS CUSTOMER_NAME
      FROM INV_SAP_SHIP_SOLD_TO_PARTYID
      ) STPT_P
    ON STPT_P.SOLD_TO_PARTY = STPT_S.SOLD_TO_PARTY
    )SOLD_PT
  LEFT JOIN
    (
    --DEFAULT Delivery Block
    SELECT SALE_BK.ID     AS ID,
      SALE_BK.MATERIAL    AS MATERIAL,
      MVKE_BK.D_CHAIN_BLK AS D_CHAIN_BLK
    FROM
      (SELECT SALESDOC
        ||'_'
        || SALESDOCITEM AS ID,
        MATERIAL
        ||'_'
        || PLANT AS ID1,
        MATERIAL,
        PLANT
      FROM INV_SAP_SALES_VBAK_VBAP_VBUP
      )SALE_BK
    LEFT JOIN
      (SELECT MATERIALID
        ||'_'
        ||DIRECT_SHIP_PLANT AS ID,
        MATERIALID,
        D_CHAIN_BLK,
        DIRECT_SHIP_PLANT
      FROM INV_SAP_PP_MVKE
      )MVKE_BK
    ON MVKE_BK.ID          = SALE_BK.ID1
    )ITEM_BK ON ITEM_BK.ID = SOLD_PT.ID
  )PT_BK ON PT_BK.ID       = SALES_PP.ID
  )WHERE (COMMITTED_DATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 14)) AND PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

----SALES ORDER
CREATE VIEW VIEW_INV_SVD_OPEN_SO AS
SELECT * FROM VIEW_INV_SAP_OPEN_SO ;
CREATE VIEW VIEW_INV_SVD_BACKLOG AS
SELECT * FROM VIEW_INV_SAP_OPEN_SO WHERE COMMITTED_DATE < SYSDATE + 91 AND MATERIAL = '100-C09EJ10 A';
CREATE VIEW VIEW_INV_SVD_PASS_DUE AS
SELECT * FROM VIEW_INV_SAP_OPEN_SO WHERE COMMITTED_DATE < SYSDATE - 1;
CREATE VIEW VIEW_INV_SVD_THREE_WEEKS AS
SELECT * FROM VIEW_INV_SAP_OPEN_SO WHERE COMMITTED_DATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 21);