--Wu Huochan 6/11/2014
--New Extend item within one year need to review whether these items need to reserve. If they calculate in fiance.
--So we create a view for this.

CREATE VIEW VIEW_ITEM_CREATE_FSTUSE_DATE AS 
SELECT CREATE_DATE.ID,
  CREATE_DATE.MATERIALID,
  CREATE_DATE.PLANTID,
  FIRST_USE_DATE.SALES_ORG,
  CREATE_DATE.ERSDA_SAP_CREATED_DATE AS SAP_CREATE_DATE,
  FIRST_USE_DATE.FIRST_USED,
  FIRST_USE_DATE.LAST_USED
FROM
  (SELECT MATERIALID
    ||'_'
    ||PLANTID AS ID,
    MATERIALID,
    PLANTID,
    ERSDA_SAP_CREATED_DATE,
    DATE_OF_LAST_COUNT_DLINL,
    FIRST_SLOC_CREATED_DATE
  FROM DWQ$LIBRARIAN.INV_SAP_PP_PARAM@ROCKWELL_DBLINK
  )CREATE_DATE
LEFT JOIN
  (SELECT MATERIALID
    ||'_'
    ||EXPECTED_SHIP_PLANT AS ID,
    MATERIALID,
    FIRST_USED,
    LAST_USED,
    SALES_ORG,
    EXPECTED_SHIP_PLANT
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAP_1STUSED@ROCKWELL_DBLINK
  )FIRST_USE_DATE
ON CREATE_DATE.ID = FIRST_USE_DATE.ID;

SELECT *
FROM VIEW_ITEM_CREATE_FSTUSE_DATE
WHERE MATERIALID = 'PN-261044';