--Date#:07/22/2014
--Material
SELECT ID,
  PLANT,
  MATERIAL,
  CATALOG_DASH,
  MAT_DESC,
  PROD_BU,
  PROD_FAM,
  MATL_TYPE,
  STRATEGY_GRP,
  MRP_TYPE,
  ULTIMATE_SOURCE
FROM INV_SAP_PP_OPT_X
WHERE PLANT = '5040';

SELECT 
  MVK_OPT.PLANT,
  MVK_OPT.SALES_ORG,
  MVK_OPT.MATERIALID,
  ISMC.CATALOG_STRING1 AS CATALOG_DASH,
  MVK_OPT.MAT_DESC,
  MVK_OPT.PROD_BU,
  MVK_OPT.MATL_TYPE_MTART,
  MVK_OPT.STRATEGY_GRP,
  MVK_OPT.MRP_TYPE,
  MVK_OPT.ULTIMATE_SOURCE
FROM
  (SELECT MVK.MATERIALID,
    MVK.SALES_ORG,
    OPT.PLANT,
    OPT.MAT_DESC,
    OPT.ULTIMATE_SOURCE,
    OPT.PROD_BU,
    OPT.MATL_TYPE_MTART,
    OPT.STRATEGY_GRP,
    OPT.MRP_TYPE
  FROM
    (SELECT MATERIALID,
      SALES_ORG
    FROM INV_SAP_PP_MVKE
    WHERE SALES_ORG    = '5003'
    AND CURRENT_SERIES = 'X'
    )MVK
  LEFT JOIN
    (SELECT MATERIALID,
      MAT_DESC,
      (PLANTID - 1) AS PLANT,
      SUBSTR(PROD_BU,0,3) AS PROD_BU,
      ULTIMATE_SOURCE,
      MATL_TYPE_MTART,
      STRATEGY_GRP,
      MRP_TYPE
    FROM INV_SAP_PP_OPTIMIZATION
    )OPT
  ON OPT.MATERIALID = MVK.MATERIALID
  )MVK_OPT
LEFT JOIN
  (SELECT CATALOG_STRING1,
    CATALOG_STRING2,
    MATERIALID
  FROM INV_SAP_NODASH_MAT_CATA
  )ISMC
ON ISMC.MATERIALID = MVK_OPT.MATERIALID;


SELECT MVK_OPT.MATERIALID,
  ISMC.CATALOG_STRING1 AS CATALOG_DASH,
  MVK_OPT.SALES_ORG,
  MVK_OPT.MAT_DESC,
      MVK_OPT.ULTIMATE_SOURCE,
      MVK_OPT.MATL_TYPE_MTART,
      MVK_OPT.STRATEGY_GRP,
      MVK_OPT.MRP_TYPE
FROM
  (SELECT MVK.MATERIALID,
    MVK.SALES_ORG,
    OPT.PLANT,
    OPT.MAT_DESC,
    OPT.ULTIMATE_SOURCE,
      OPT.MATL_TYPE_MTART,
      OPT.STRATEGY_GRP,
      OPT.MRP_TYPE
  FROM
    (SELECT MATERIALID,
      SALES_ORG
    FROM INV_SAP_PP_MVKE
    WHERE SALES_ORG    = '5003'
    AND CURRENT_SERIES = 'X'
    )MVK
  LEFT JOIN
    (SELECT MATERIALID,
      MAT_DESC,
      (PLANTID - 1) AS PLANT,
      ULTIMATE_SOURCE,
      MATL_TYPE_MTART,
      STRATEGY_GRP,
      MRP_TYPE
    FROM INV_SAP_PP_OPTIMIZATION
    )OPT
  ON OPT.MATERIALID = MVK.MATERIALID
  )MVK_OPT
LEFT JOIN
  (SELECT CATALOG_STRING1,
    CATALOG_STRING2,
    MATERIALID
  FROM INV_SAP_NODASH_MAT_CATA
  )ISMC
ON ISMC.MATERIALID = MVK_OPT.MATERIALID;

--STOCK
SELECT * FROM INV_SAP_BACKLOG_INV WHERE PLANT = '5040';
--PO/SO ITEM LIST
--PO
SELECT DISTINCT PO_ITEM.ID,
  PO_ITEM.PLANTID,
  PO_ITEM.MATERIALID,
  ITEM_BSC.CATALOG_DASH,
  ITEM_BSC.MAT_DESC,
  ITEM_BSC.PROD_BU,
  ITEM_BSC.PROD_FAM,
  ITEM_BSC.MATL_TYPE,
  ITEM_BSC.STRATEGY_GRP,
  ITEM_BSC.MRP_TYPE
FROM
  (SELECT MATERIALID
    ||'_'
    ||PLANTID AS ID,
    MATERIALID,
    PLANTID
  FROM INV_SAP_PP_PO_HISTORY
  WHERE PLANTID = '5040'
  )PO_ITEM
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    PROD_BU,
    PROD_FAM,
    MATL_TYPE,
    STRATEGY_GRP,
    MRP_TYPE
  FROM INV_SAP_PP_OPT_X
  )ITEM_BSC
ON ITEM_BSC.ID = PO_ITEM.ID;
--SO
SELECT DISTINCT SO_ITEM.ID,
  SO_ITEM.PLANTID,
  SO_ITEM.SALES_ORG,
  SO_ITEM.MATERIALID,
  ITEM_BSC.CATALOG_DASH,
  ITEM_BSC.MAT_DESC,
  ITEM_BSC.PROD_BU,
  ITEM_BSC.PROD_FAM,
  ITEM_BSC.MATL_TYPE,
  ITEM_BSC.STRATEGY_GRP,
  ITEM_BSC.MRP_TYPE
FROM
  (SELECT MATERIALID
    ||'_'
    ||PLANTID AS ID,
    MATERIALID,
    PLANTID,
    SALES_ORG
  FROM INV_SAP_SALES_HST
  WHERE SALES_ORG = '5003'
  )SO_ITEM
LEFT JOIN
  (SELECT ID,
    CATALOG_DASH,
    MAT_DESC,
    PROD_BU,
    PROD_FAM,
    MATL_TYPE,
    STRATEGY_GRP,
    MRP_TYPE
  FROM INV_SAP_PP_OPT_X
  )ITEM_BSC
ON ITEM_BSC.ID = SO_ITEM.ID;