---This report for jane. It is about the delivery that all vendors shipment to 5040.
---Report frequency is weekly. Every Monday and time span is last week's suppliers' shipment status.
SELECT DELIVERY,
  DELIVERY_ITEM,
  CREATED_BY,
  CREATED_TIME CREATED_ON_DATE,
  MATERIALID,
  PLANTID,
  CATALOGID,
  MVMT_TYPE,
  DELIVERY_QTY_SUOM,
  BASE_UOM,
  SALES_UOM,
  NUMERATOR,
  DENOMINATOR,
  MATERIAL_AVAIL_DATE,
  REFERENCE_DOC,
  REFERENCE_DOC_ITEM,
  REFERENCE_DOC_TRIM,
  REFERENCE_DOC_ITEM_TRIM,
  DELIVERY_TYPE,
  UPC,
  INCOTERMS1,
  INCOTERMS2,
  DELIVERY_PRIORITY,
  CHANGED_ON_DATE,
  ACT_GI_DATE,
  DWQ_SRC_EXTRACT_DATE,
  DELIVERY_QTY_STO_ITEM
FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DBLINK
WHERE REFERENCE_DOC_TRIM IN
  (SELECT EBELNPURCHDOCNO
  FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
  WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
  AND DELIVERYCOMPLETE IS NULL
  );