--5140 INV CLS REPORT
--AUTHOR: HUANG MO YUE
--DATE:7/2/2014

DROP VIEW VIEW_SAP_INV_CLS_AUSRE;
SELECT * FROM VIEW_SAP_INV_CLS_AUSRE;
CREATE VIEW VIEW_SAP_INV_CLS_AUSRE AS
SELECT PLANT AS PLANT,
  MATERIAL AS MATERIAL,
  CATALOG_DASH AS CATALOG,
  MAT_DESC AS MAT_DESC,
  PROD_BU AS PRODUCT_GRP,
  STRATEGY_GRP AS STRATEGY_GRP,
  SAFETY_STOCK AS SAFETY_STOCK,
  UNIT AS UNIT,
  LEAD_TIME AS LEAD_TIME,
  PROC_TYPE AS PROC_TYPE,
  PLANT_SP_MATL_STA AS Material_Status,
  ISSUE_UOM_NUMERATOR AS Delivery_Unit
FROM VIEW_INV_SAP_PP_OPT_X
WHERE PLANT IN ('5140','5150');