--AUTHOR: HUANG MOYUE
--DATE: 6/29/2014
--DES: AUS REPORTS AUTOMATION

---REPORT 1


---REPORT 2
SELECT DELIVERY,
  DELIVERY_ITEM,
  CREATED_BY,
  CREATED_TIME,
  CREATED_ON_DATE,
  MATERIALID,
  PLANTID,
  CATALOGID,
  MVMT_TYPE,
  DELIVERY_QTY_SUOM,
  BASE_UOM,
  SALES_UOM,
  NUMERATOR,
  DENOMINATOR,
  MATERIAL_AVAIL_DATE,
  REFERENCE_DOC,
  REFERENCE_DOC_ITEM,
  REFERENCE_DOC_TRIM,
  REFERENCE_DOC_ITEM_TRIM,
  DELIVERY_TYPE,
  UPC,
  INCOTERMS1,
  INCOTERMS2,
  DELIVERY_PRIORITY,
  CHANGED_ON_DATE,
  ACT_GI_DATE,
  DWQ_SRC_EXTRACT_DATE
FROM INV_SAP_LIKP_LIPS_DAILY;