--NEW IDEA TO GENERATE REPORT. THAT WE CAN CALCULATE ALL PLANTS RESULTS, PUSH IN THE VIEW OR A TABLE. 
--WHEN WE NEED TO USE, WE ONLY QUERY THIS TABLE USE MATERIALS. It is easy and simply.

---To Create a useful tools for analyse pre-demand and supplier capacity.
---All plants
--'5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141'
--'5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140'

--Supplier And Customer Usage status.
--1. How to calculate fast-medium-slow?
--2. How to define the risk level?
--3. Provide the objective conclusion

--26 weeks Usage Lines Count
--Use line count to show the frequency that the customer order it. The qty do not reveal this. 

--------------------------------------26 weeks Usage Lines Count----------------------------
SELECT MATERIALID, PLANTID, (SUM(PLANTID)/PLANTID) AS LINE_COUNT
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DBLINK
WHERE MATERIALID    IN ('1734-EP24DC B')
AND PLANTID          = '5110'
AND REQUIREDDELIVERYDATE BETWEEN TO_CHAR(sysdate - 182) AND TO_CHAR(sysdate)
GROUP BY MATERIALID, PLANTID;
  
-----------------------------------------------------------------------------------------------------------
---Time: 5.28 12:00AM
--1. Check X current serials

SELECT  MATERIALID
      ||'_'
      ||DIRECT_SHIP_PLANT            AS ID,
  MATERIALID,
  CURRENT_SERIES,
  DIRECT_SHIP_PLANT
FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DBLINK
WHERE CURRENT_SERIES   = 'X' AND DIRECT_SHIP_PLANT = '5110' AND MATERIALID IN (
);

--2. 5110 data. oh, ss, fc_avg, 26weeks line count 

--Basic Data
CREATE TABLE CIP_5110_BASIC_DATA AS
SELECT 
PLANTID ||'_'||MATERIALID AS ID,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
STRATEGY_GRP,
MRP_TYPE,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG26_USAGE_QTY,
GRT,
PDT,
MEINS_ISSUE_UOM,
MATL_TYPE_MTART  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK WHERE PLANTID = '5110' AND      
MATERIALID IN ( );


--26weeks line count
CREATE TABLE CIP_5110_26WEEKS AS
SELECT 
PLANTID ||'_'||MATERIALID AS ID,
MATERIALID, PLANTID, (SUM(PLANTID)/PLANTID) AS LINE_COUNT
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DBLINK
WHERE MATERIALID    IN  ( )
AND PLANTID          = '5110'
AND COMMITTEDDATE BETWEEN TO_CHAR(sysdate - 182) AND TO_CHAR(sysdate)
GROUP BY MATERIALID, PLANTID;

--VSE_FC_AVG
CREATE TABLE CIP_5110_FCAVG AS
SELECT PLANTID
      ||'_'
      ||MATERIALID                           AS ID,
      MATERIALID                          AS MATERIALID,
      PLANTID                             AS PLANTID,
      CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG_WEEK
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND PLANTID = '5110'
    AND VERSBP_VERSION = '55'
    AND MATERIALID    IN  ()
    GROUP BY MATERIALID,
      MATERIALID
      ||'_'
      ||PLANTID,
      PLANTID,
      MATERIALID;


---SUPPLIER STATUS
CREATE TABLE CIP_5110_SUPPLIERS AS
SELECT * FROM
(SELECT 
MATERIALID||'_'||(PLANTID-1) AS ID,
MATERIALID,
PLANTID,
SAFETY_STK,
OH_QTY,
STRATEGY_GRP,
GRT,
PDT,
MEINS_ISSUE_UOM FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK)
WHERE ID IN ('PN-45767_1090');

---ANALYSE REPORT BASE DATA
DROP TABLE CIP_5110_26WEEKS;
DROP TABLE CIP_5110_BASIC_DATA;
DROP TABLE CIP_5110_FCAVG;
DROP TABLE CIP_5110_SUPPLIERS;

SELECT * FROM CIP_5110_26WEEKS;
SELECT * FROM CIP_5110_BASIC_DATA;
SELECT * FROM CIP_5110_FCAVG;
SELECT * FROM CIP_5110_SUPPLIERS;


--Local_Suppiler_Status
SELECT 
PP_BI_SLAES_LC.ID AS ID,
PP_BI_SLAES_LC.MATERIALID AS MATERIALID,
PP_BI_SLAES_LC.PLANTID AS PLANTID,
PP_BI_SLAES_LC.MAT_DESC AS MAT_DESC,
PP_BI_SLAES_LC.SAFETY_STK AS SAFETY_STK,
PP_BI_SLAES_LC.LOT_SIZE AS LOT_SIZE,
PP_BI_SLAES_LC.OH_QTY AS OH_QTY,
PP_BI_SLAES_LC.UNIT_COST AS UNIT_COST,
PP_BI_SLAES_LC.OH_$$ AS OH_$$,
PP_BI_SLAES_LC.MAX_INV_$$ AS MAX_INV_$$,
PP_BI_SLAES_LC.OH_WOS AS OH_WOS,
PP_BI_SLAES_LC.PLAN_INV_WOS AS PLAN_INV_WOS,
SUBSTR(PP_BI_SLAES_LC.PROD_BU,0,3) AS PROD_BU,
PP_BI_SLAES_LC.STRATEGY_GRP AS STRATEGY_GRP,
PP_BI_SLAES_LC.MATERIALID||'_'||SUBSTR(PP_BI_SLAES_LC.VENDOR_NAME,0,4) AS VENDOR_ITEM,
PP_BI_SLAES_LC.LOT_ROUNDING_VALUE AS LOT_ROUNDING_VALUE,
PP_BI_SLAES_LC.AVG26_USAGE_QTY AS AVG26_USAGE_QTY,
PP_BI_SLAES_LC.USE_LINES_COUNT_26WEEKS  AS USE_LINES_COUNT_26WEEKS,
FC_AVG.FC_AVG_WEEK AS FC_AVG_WEEK,
PP_BI_SLAES_LC.GRT AS GRT,
PP_BI_SLAES_LC.PDT AS PDT,
PP_BI_SLAES_LC.MEINS_ISSUE_UOM AS MEINS_ISSUE_UOM,
PP_BI_SLAES_LC.MATL_TYPE_MTART AS MATL_TYPE_MTART
FROM
(
SELECT 
PP_BASIC_INFO.ID AS ID,
PP_BASIC_INFO.MATERIALID AS MATERIALID,
PP_BASIC_INFO.PLANTID AS PLANTID,
PP_BASIC_INFO.MAT_DESC AS MAT_DESC,
PP_BASIC_INFO.SAFETY_STK AS SAFETY_STK,
PP_BASIC_INFO.LOT_SIZE AS LOT_SIZE,
PP_BASIC_INFO.OH_QTY AS OH_QTY,
PP_BASIC_INFO.UNIT_COST AS UNIT_COST,
PP_BASIC_INFO.OH_$$ AS OH_$$,
PP_BASIC_INFO.MAX_INV_$$ AS MAX_INV_$$,
PP_BASIC_INFO.OH_WOS AS OH_WOS,
PP_BASIC_INFO.PLAN_INV_WOS AS PLAN_INV_WOS,
PP_BASIC_INFO.PROD_BU AS PROD_BU,
PP_BASIC_INFO.STRATEGY_GRP AS STRATEGY_GRP,
PP_BASIC_INFO.MRP_TYPE AS MRP_TYPE,
PP_BASIC_INFO.VENDOR_NAME AS VENDOR_NAME,
PP_BASIC_INFO.LOT_ROUNDING_VALUE AS LOT_ROUNDING_VALUE,
PP_BASIC_INFO.AVG26_USAGE_QTY AS AVG26_USAGE_QTY,
SALES_LINT_COUNT.LINE_COUNT  AS USE_LINES_COUNT_26WEEKS,
PP_BASIC_INFO.GRT AS GRT,
PP_BASIC_INFO.PDT AS PDT,
PP_BASIC_INFO.MEINS_ISSUE_UOM AS MEINS_ISSUE_UOM,
PP_BASIC_INFO.MATL_TYPE_MTART AS MATL_TYPE_MTART
FROM
(SELECT 
PLANTID||'_'||MATERIALID AS ID,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
STRATEGY_GRP,
MRP_TYPE,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG26_USAGE_QTY,
GRT,
PDT,
MEINS_ISSUE_UOM,
MATL_TYPE_MTART  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK WHERE PLANTID = '5110' AND  MATERIALID IN ('1734-ARM C')
)PP_BASIC_INFO
LEFT JOIN
(
SELECT 
PLANTID||'_'||MATERIALID AS ID,
(SUM(PLANTID)/PLANTID) AS LINE_COUNT
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DBLINK
WHERE MATERIALID    IN  ('1734-ARM C')
AND PLANTID          = '5110'
AND COMMITTEDDATE BETWEEN TO_CHAR(sysdate - 182) AND TO_CHAR(sysdate)
GROUP BY MATERIALID, PLANTID,PLANTID||'_'||MATERIALID
)SALES_LINT_COUNT 
ON PP_BASIC_INFO.ID = SALES_LINT_COUNT.ID
)PP_BI_SLAES_LC
LEFT JOIN
(
SELECT PLANTID
      ||'_'
      ||MATERIALID                           AS ID,
      CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG_WEEK
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND PLANTID = '5110'
    AND VERSBP_VERSION = '55'
    AND MATERIALID IN  ('1734-ARM C')
    GROUP BY MATERIALID, PLANTID ||'_' ||MATERIALID, PLANTID
)FC_AVG
ON FC_AVG.ID = PP_BI_SLAES_LC.ID;


---Superior_Supplier_Status
---v1
SELECT ID,
MATERIALID,
PLANTID,
SAFETY_STK,
STRATEGY_GRP,
VENDOR_LT,
MEINS_ISSUE_UOM
FROM
(SELECT 
MATERIALID||'_'||PLANTID AS ID,
MATERIALID,
PLANTID,
SAFETY_STK,
OH_QTY,
STRATEGY_GRP,
AVG26_USAGE_QTY,
(GRT+PDT+1)AS VENDOR_LT,
MEINS_ISSUE_UOM FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK)
WHERE ID IN (SELECT DISTINCT
MATERIALID||'_'||SUBSTR(VENDOR_NAME,0,4) AS VENDOR_ITEM
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK WHERE PLANTID = '5110')
)Supplier_Bsc

--ALLPLANTS_Superior_Supplier_Status
SELECT ID,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
(GRT+PDT+1)AS VENDOR_LT,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART
FROM
(SELECT 
MATERIALID||'_'||PLANTID AS ID,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
(GRT+PDT+1)AS VENDOR_LT,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK)
WHERE ID IN (SELECT DISTINCT
MATERIALID||'_'||SUBSTR(VENDOR_NAME,0,4) AS VENDOR_ITEM
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK WHERE PLANTID = '5110');

---ALL PLANTS LOCAL_SUPPILER_STATUS
(
SELECT
MATERIALID||'_'||PLANTID AS ID,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
(GRT+PDT+1)AS VENDOR_LT,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
)PP_BASIC_INFO

--FV_AVG_26_weeks for all plants
LEFT JOIN
(
SELECT MATERIALID
      ||'_'
      ||PLANTID                           AS ID,
      CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG_WEEK
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND VERSBP_VERSION = '55'
    GROUP BY MATERIALID, MATERIALID ||'_' ||PLANTID, PLANTID
)FC_AVG.ID;

--Sales orders open lines count
LEFT JOIN
(
SELECT 
MATERIALID||'_'||PLANTID AS ID,
(SUM(PLANTID)/PLANTID) AS LINE_COUNT
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DBLINK
WHERE COMMITTEDDATE BETWEEN TO_CHAR(sysdate - 182) AND TO_CHAR(sysdate)
GROUP BY MATERIALID, PLANTID,PLANTID||'_'||MATERIALID
)SALES_LINT_COUNT 



---Generate REPORT

SELECT 
Local_Suppiler_BscInfo.ID,
Local_Suppiler_BscInfo.PROC_TYPE,
Local_Suppiler_BscInfo.MATERIALID,
Local_Suppiler_BscInfo.PLANTID,
Local_Suppiler_BscInfo.MAT_DESC,
Local_Suppiler_BscInfo.SAFETY_STK,
Local_Suppiler_BscInfo.LOT_SIZE,
Local_Suppiler_BscInfo.OH_QTY,
Local_Suppiler_BscInfo.UNIT_COST,
Local_Suppiler_BscInfo.OH_$$,
Local_Suppiler_BscInfo.MAX_INV_$$,
Local_Suppiler_BscInfo.OH_WOS,
Local_Suppiler_BscInfo.PLAN_INV_WOS,
Local_Suppiler_BscInfo.PROD_BU,
Local_Suppiler_BscInfo.PROD_FAM,
Local_Suppiler_BscInfo.PROD_HIERARCHY,
Local_Suppiler_BscInfo.MRP_CONTROLLER,
Local_Suppiler_BscInfo.PURCH_GROUP,
Local_Suppiler_BscInfo.STRATEGY_GRP,
Local_Suppiler_BscInfo.RP_TYPE,
Local_Suppiler_BscInfo.SP_MATL_STAT_MMSTA,
Local_Suppiler_BscInfo.SPC_PROC_KEY_SOBSL,
Local_Suppiler_BscInfo.VENDOR_NAME,
Local_Suppiler_BscInfo.LOT_ROUNDING_VALUE,
Local_Suppiler_BscInfo.AVG52_USAGE_QTY,
Local_Suppiler_BscInfo.STDEV52_USAGE,
Local_Suppiler_BscInfo.AVG26_USAGE_QTY,
Local_Suppiler_BscInfo.STDEV26_USAGE,
Local_Suppiler_BscInfo.AVG13_USAGE_QTY,
Local_Suppiler_BscInfo.STDEV13_USAGE,
Local_Suppiler_BscInfo.Q1_LINES,
Local_Suppiler_BscInfo.Q2_LINES,
Local_Suppiler_BscInfo.Q3_LINES,
Local_Suppiler_BscInfo.Q4_LINES,
Local_Suppiler_BscInfo.Q1_FREQ_COUNT,
Local_Suppiler_BscInfo.Q2_FREQ_COUNT,
Local_Suppiler_BscInfo.Q3_FREQ_COUNT,
Local_Suppiler_BscInfo.Q4_FREQ_COUNT,
Local_Suppiler_BscInfo.LEAD_TIME,
Local_Suppiler_BscInfo.GRT,
Local_Suppiler_BscInfo.PDT,
Local_Suppiler_BscInfo.MEINS_ISSUE_UOM,
Local_Suppiler_BscInfo.PURCH_GROUP_EKGRP,
Local_Suppiler_BscInfo.MATL_TYPE_MTART,
Local_Suppiler_BscInfo.VENDOR_ITEM,
FC_SALES.FC_QTY_AVG_26WEEKS AS FC_QTY_AVG_26WEEKS,
FC_SALES.USG_LN_COUNT_26WEEKS AS USG_LN_COUNT_26WEEKS
 FROM
(
SELECT
MATERIALID||'_'||PLANTID AS ID,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
SUBSTR(PROD_BU,0,4) AS PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
(GRT+PDT+1)AS LEAD_TIME,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART,
MATERIALID||'_'||SUBSTR(VENDOR_NAME,0,4) AS VENDOR_ITEM  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
)Local_Suppiler_BscInfo
LEFT JOIN
(
SELECT 
FC_AVG.ID AS ID,
FC_AVG.FC_QTY_AVG_26WEEKS AS FC_QTY_AVG_26WEEKS,
SALES_LINT_COUNT.USG_LN_COUNT_26WEEKS AS USG_LN_COUNT_26WEEKS
 FROM 
--ALL PLANTS FC_AVG
(
SELECT MATERIALID
      ||'_'
      ||PLANTID                           AS ID,
      CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_QTY_AVG_26WEEKS
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND VERSBP_VERSION = '55'
    GROUP BY MATERIALID, MATERIALID ||'_' ||PLANTID, PLANTID
)FC_AVG
--Sales orders open lines count
LEFT JOIN
(
SELECT 
MATERIALID||'_'||PLANTID AS ID,
(SUM(PLANTID)/PLANTID) AS USG_LN_COUNT_26WEEKS
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DBLINK
WHERE COMMITTEDDATE BETWEEN TO_CHAR(sysdate - 182) AND TO_CHAR(sysdate)
GROUP BY MATERIALID, PLANTID,MATERIALID||'_'||PLANTID
)SALES_LINT_COUNT
ON FC_AVG.ID = SALES_LINT_COUNT.ID
)FC_SALES
ON FC_SALES.ID = Local_Suppiler_BscInfo.ID;




--ALLPLANTS_Superior_Supplier_Status
SELECT 
Superior_Supplier_BscInfo.PROC_TYPE,
Superior_Supplier_BscInfo.MATERIALID,
Superior_Supplier_BscInfo.PLANTID,
Superior_Supplier_BscInfo.MAT_DESC,
Superior_Supplier_BscInfo.SAFETY_STK,
Superior_Supplier_BscInfo.LOT_SIZE,
Superior_Supplier_BscInfo.OH_QTY,
Superior_Supplier_BscInfo.UNIT_COST,
Superior_Supplier_BscInfo.OH_$$,
Superior_Supplier_BscInfo.MAX_INV_$$,
Superior_Supplier_BscInfo.OH_WOS,
Superior_Supplier_BscInfo.PLAN_INV_WOS,
Superior_Supplier_BscInfo.PROD_BU,
Superior_Supplier_BscInfo.PROD_FAM,
Superior_Supplier_BscInfo.PROD_HIERARCHY,
Superior_Supplier_BscInfo.MRP_CONTROLLER,
Superior_Supplier_BscInfo.PURCH_GROUP,
Superior_Supplier_BscInfo.STRATEGY_GRP,
Superior_Supplier_BscInfo.MRP_TYPE,
Superior_Supplier_BscInfo.SP_MATL_STAT_MMSTA,
Superior_Supplier_BscInfo.SPC_PROC_KEY_SOBSL,
Superior_Supplier_BscInfo.VENDOR_NAME,
Superior_Supplier_BscInfo.LOT_ROUNDING_VALUE,
Superior_Supplier_BscInfo.AVG52_USAGE_QTY,
Superior_Supplier_BscInfo.STDEV52_USAGE,
Superior_Supplier_BscInfo.AVG26_USAGE_QTY,
Superior_Supplier_BscInfo.STDEV26_USAGE,
Superior_Supplier_BscInfo.AVG13_USAGE_QTY,
Superior_Supplier_BscInfo.STDEV13_USAGE,
Superior_Supplier_BscInfo.Q1_LINES,
Superior_Supplier_BscInfo.Q2_LINES,
Superior_Supplier_BscInfo.Q3_LINES,
Superior_Supplier_BscInfo.Q4_LINES,
Superior_Supplier_BscInfo.Q1_FREQ_COUNT,
Superior_Supplier_BscInfo.Q2_FREQ_COUNT,
Superior_Supplier_BscInfo.Q3_FREQ_COUNT,
Superior_Supplier_BscInfo.Q4_FREQ_COUNT,
Superior_Supplier_BscInfo.VENDOR_LT,
Superior_Supplier_BscInfo.GRT,
Superior_Supplier_BscInfo.PDT,
Superior_Supplier_BscInfo.MEINS_ISSUE_UOM,
Superior_Supplier_BscInfo.PURCH_GROUP_EKGRP,
Superior_Supplier_BscInfo.MATL_TYPE_MTART,
FC_SALES.FC_QTY_AVG_26WEEKS AS FC_QTY_AVG_26WEEKS,
FC_SALES.USG_LN_COUNT_26WEEKS AS USG_LN_COUNT_26WEEKS
FROM
(
SELECT ID,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
SUBSTR(PROD_BU,0,4) AS PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
(GRT+PDT+1)AS VENDOR_LT,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART
FROM
(SELECT 
MATERIALID||'_'||PLANTID AS ID,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
(GRT+PDT+1)AS VENDOR_LT,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK)
WHERE ID IN (SELECT DISTINCT
MATERIALID||'_'||SUBSTR(VENDOR_NAME,0,4) AS VENDOR_ITEM
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK)
)Superior_Supplier_BscInfo
LEFT JOIN
(
SELECT 
FC_AVG.ID AS ID,
FC_AVG.FC_QTY_AVG_26WEEKS AS FC_QTY_AVG_26WEEKS,
SALES_LINT_COUNT.USG_LN_COUNT_26WEEKS AS USG_LN_COUNT_26WEEKS
 FROM 
--ALL PLANTS FC_AVG
(
SELECT MATERIALID
      ||'_'
      ||PLANTID                           AS ID,
      CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_QTY_AVG_26WEEKS
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND VERSBP_VERSION = '55'
    GROUP BY MATERIALID, MATERIALID ||'_' ||PLANTID, PLANTID
)FC_AVG
--Sales orders open lines count
LEFT JOIN
(
SELECT 
MATERIALID||'_'||PLANTID AS ID,
(SUM(PLANTID)/PLANTID) AS USG_LN_COUNT_26WEEKS
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST@ROCKWELL_DBLINK
WHERE COMMITTEDDATE BETWEEN TO_CHAR(sysdate - 182) AND TO_CHAR(sysdate)
GROUP BY MATERIALID, PLANTID,MATERIALID||'_'||PLANTID
)SALES_LINT_COUNT
ON FC_AVG.ID = SALES_LINT_COUNT.ID
)FC_SALES
ON
FC_SALES.ID = Superior_Supplier_BscInfo.ID;
