--ITEM_PROSPECTIVE_REQUIREMENT
--AUTHOR: HUANG MOYUE
--6/17/2014
CREATE VIEW VIEW_INV_SAP_CUS_VEN_FC AS
SELECT CUSTOMER.ID           AS ID,
  CUSTOMER.MATERIAL          AS MATERIAL,
  CUSTOMER.CATALOG_DASH      AS CATALOG_DASH,
  CUSTOMER.PLANT             AS PLANT,
  CUSTOMER.MAT_DESC          AS MAT_DESC,
  CUSTOMER.SAFETY_STOCK      AS SAFETY_STOCK,
  CUSTOMER.UNIT              AS UNIT,
  CUSTOMER.PROC_TYPE         AS PROC_TYPE,
  CUSTOMER.UNIT_COST         AS UNIT_COST,
  CUSTOMER.BU                AS BU,
  CUSTOMER.STRATEGY_GRP      AS STRATEGY_GRP,
  CUSTOMER.MRP_TYPE          AS MRP_TYPE,
  CUSTOMER.MRP_CONTROLLER    AS MRP_CONTROLLER,
  CUSTOMER.PURCH_GROUP       AS PURCH_GROUP,
  CUSTOMER.VENDOR_ITEM       AS VENDOR_ITEM,
  CUSTOMER.MATL_TYPE         AS MATL_TYPE,
  CUSTOMER.MIN_INV           AS MIN_INV,
  CUSTOMER.TARGET_INV        AS TARGET_INV,
  CUSTOMER.MAX_INV           AS MAX_INV,
  CUSTOMER.LEAD_TIME         AS LEAD_TIME,
  CUSTOMER.AVG26_USAGE_QTY   AS AVG26_USAGE_QTY,
  CUSTOMER.AVG13_USAGE_QTY   AS AVG13_USAGE_QTY,
  CUSTOMER.FC_AVG13_WEEK_QTY AS FC_AVG13_WEEK_QTY,
  CUSTOMER.FC_AVG26_WEEK_QTY AS FC_AVG26_WEEK_QTY,
  VENDOR.PLANT               AS VENDOR_PLANT,
  VENDOR.MATERIAL            AS VENDOR_MATERIAL,
  VENDOR.CATALOG_DASH        AS VENDOR_CATALOG_DASH,
  VENDOR.MAT_DESC            AS VENDOR_MAT_DESC,
  VENDOR.SAFETY_STOCK        AS VENDOR_SAFETY_STOCK,
  VENDOR.UNIT                AS VENDOR_UNIT,
  VENDOR.PROC_TYPE           AS VENDOR_PROC_TYPE,
  VENDOR.UNIT_COST           AS VENDOR_UNIT_COST,
  VENDOR.BU                  AS VENDOR_BU,
  VENDOR.STRATEGY_GRP        AS VENDOR_STRATEGY_GRP,
  VENDOR.MRP_TYPE            AS VENDOR_MRP_TYPE,
  VENDOR.MRP_CONTROLLER      AS VENDOR_MRP_CONTROLLER,
  VENDOR.PURCH_GROUP         AS VENDOR_PURCH_GROUP,
  VENDOR.VENDOR_ITEM         AS VENDOR_VENDOR_ITEM,
  VENDOR.MATL_TYPE           AS VENDOR_MATL_TYPE,
  VENDOR.MIN_INV             AS VENDOR_MIN_INV,
  VENDOR.TARGET_INV          AS VENDOR_TARGET_INV,
  VENDOR.MAX_INV             AS VENDOR_MAX_INV,
  VENDOR.LEAD_TIME           AS VENDOR_LEAD_TIME,
  VENDOR.AVG26_USAGE_QTY     AS VENDOR_AVG26_USAGE_QTY,
  VENDOR.AVG13_USAGE_QTY     AS VENDOR_AVG13_USAGE_QTY,
  VENDOR.FC_AVG13_WEEK_QTY   AS VENDOR_FC_AVG13_WEEK_QTY,
  VENDOR.FC_AVG26_WEEK_QTY   AS VENDOR_FC_AVG26_WEEK_QTY
FROM
  (SELECT ID,
    MATERIAL,
    CATALOG_DASH,
    PLANT,
    MAT_DESC,
    SAFETY_STOCK,
    UNIT,
    PROC_TYPE,
    UNIT_COST,
    BU,
    STRATEGY_GRP,
    MRP_TYPE,
    MRP_CONTROLLER,
    PURCH_GROUP,
    VENDOR_ITEM,
    MATL_TYPE,
    MIN_INV,
    TARGET_INV,
    MAX_INV,
    LEAD_TIME,
    AVG26_USAGE_QTY,
    AVG13_USAGE_QTY,
    FC_AVG13_WEEK_QTY,
    FC_AVG26_WEEK_QTY
  FROM INV_SAP_FC_STATS
  )CUSTOMER
LEFT JOIN
  (SELECT ID,
    MATERIAL,
    CATALOG_DASH,
    PLANT,
    MAT_DESC,
    SAFETY_STOCK,
    UNIT,
    PROC_TYPE,
    UNIT_COST,
    BU,
    STRATEGY_GRP,
    MRP_TYPE,
    MRP_CONTROLLER,
    PURCH_GROUP,
    VENDOR_ITEM,
    MATL_TYPE,
    MIN_INV,
    TARGET_INV,
    MAX_INV,
    LEAD_TIME,
    AVG26_USAGE_QTY,
    AVG13_USAGE_QTY,
    FC_AVG13_WEEK_QTY,
    FC_AVG26_WEEK_QTY
  FROM INV_SAP_FC_STATS
  )VENDOR
ON VENDOR.ID = CUSTOMER.VENDOR_ITEM;

 WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140');

DROP VIEW VIEW_INV_SAP_FC_STATS;
DROP TABLE INV_SAP_FC_STATS;
CREATE TABLE INV_SAP_FC_STATS AS 
SELECT * FROM VIEW_INV_SAP_FC_STATS;
CREATE VIEW VIEW_INV_SAP_FC_STATS AS
SELECT ITEM_BASIC_PP_FC13.ID,
  ITEM_BASIC_PP_FC13.LAST_REVIEW,
  ITEM_BASIC_PP_FC13.MATERIAL,
  ITEM_BASIC_PP_FC13.CATALOG_DASH,
  ITEM_BASIC_PP_FC13.CATALOG_NO_DASH,
  ITEM_BASIC_PP_FC13.PLANT,
  ITEM_BASIC_PP_FC13.MAT_DESC,
  ITEM_BASIC_PP_FC13.SAFETY_STOCK,
  ITEM_BASIC_PP_FC13.UNIT,
  ITEM_BASIC_PP_FC13.PROC_TYPE,
  ITEM_BASIC_PP_FC13.UNIT_COST,
  ITEM_BASIC_PP_FC13.BU AS BU,
  ITEM_BASIC_PP_FC13.STRATEGY_GRP,
  ITEM_BASIC_PP_FC13.MRP_TYPE,
  ITEM_BASIC_PP_FC13.MRP_CONTROLLER,
  ITEM_BASIC_PP_FC13.PURCH_GROUP,
  ITEM_BASIC_PP_FC13.VENDOR_ITEM,
  ITEM_BASIC_PP_FC13.MATL_TYPE， MIN_INV,
  ITEM_BASIC_PP_FC13.TARGET_INV,
  ITEM_BASIC_PP_FC13.MAX_INV,
  ITEM_BASIC_PP_FC13.LEAD_TIME,
  ITEM_BASIC_PP_FC13.AVG26_USAGE_QTY,
  ITEM_BASIC_PP_FC13.AVG13_USAGE_QTY,
  ITEM_BASIC_PP_FC13.FC_AVG13_WEEK_QTY,
  FC_AVG26_WEEK.FC_AVG26_WEEK_QTY
FROM
  (SELECT ITEM_BASIC_PP.ID,
    ITEM_BASIC_PP.LAST_REVIEW,
    ITEM_BASIC_PP.MATERIAL,
    ITEM_BASIC_PP.CATALOG_DASH,
    ITEM_BASIC_PP.CATALOG_NO_DASH,
    ITEM_BASIC_PP.PLANT,
    ITEM_BASIC_PP.MAT_DESC,
    ITEM_BASIC_PP.SAFETY_STOCK,
    ITEM_BASIC_PP.UNIT,
    ITEM_BASIC_PP.PROC_TYPE,
    ITEM_BASIC_PP.UNIT_COST,
    ITEM_BASIC_PP.BU AS BU,
    ITEM_BASIC_PP.STRATEGY_GRP,
    ITEM_BASIC_PP.MRP_TYPE,
    ITEM_BASIC_PP.MRP_CONTROLLER,
    ITEM_BASIC_PP.PURCH_GROUP,
    ITEM_BASIC_PP.VENDOR_ITEM,
    ITEM_BASIC_PP.MATL_TYPE， MIN_INV,
    ITEM_BASIC_PP.TARGET_INV,
    ITEM_BASIC_PP.MAX_INV,
    ITEM_BASIC_PP.LEAD_TIME,
    ITEM_BASIC_PP.AVG26_USAGE_QTY,
    ITEM_BASIC_PP.AVG13_USAGE_QTY,
    FC_AVG13_WEEK.FC_AVG13_WEEK_QTY
  FROM
    (SELECT ID,
      LAST_REVIEW,
      MATERIAL,
      CATALOG_DASH,
      CATALOG_NO_DASH,
      PLANT,
      MAT_DESC,
      SAFETY_STOCK,
      UNIT,
      PROC_TYPE,
      UNIT_COST,
      SUBSTR(PROD_BU,0,3) AS BU,
      STRATEGY_GRP,
      MRP_TYPE,
      MRP_CONTROLLER,
      PURCH_GROUP,
      VENDOR_ITEM,
      MATL_TYPE,
      MIN_INV,
      TARGET_INV,
      MAX_INV,
      LEAD_TIME,
      AVG26_USAGE_QTY,
      AVG13_USAGE_QTY
    FROM VIEW_INV_SAP_PP_OPT_X
    WHERE MATL_TYPE IN ('ZTG','ZFG')
    AND PLANT       IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    )ITEM_BASIC_PP
  LEFT JOIN
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                           AS ID,
      MATERIALID                          AS MATERIALID,
      PLANTID                             AS PLANTID,
      CEIL(SUM(PLNMG_PLANNEDQUANTITY)/13) AS FC_AVG13_WEEK_QTY
    FROM INV_SAP_PP_FRCST_PBIM_PBED
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
    AND VERSBP_VERSION = '55'
    GROUP BY MATERIALID,
      PLANTID
    )FC_AVG13_WEEK
  ON FC_AVG13_WEEK.ID = ITEM_BASIC_PP.ID
  )ITEM_BASIC_PP_FC13
LEFT JOIN
  (SELECT MATERIALID
    ||'_'
    ||PLANTID                           AS ID,
    MATERIALID                          AS MATERIALID,
    PLANTID                             AS PLANTID,
    CEIL(SUM(PLNMG_PLANNEDQUANTITY)/26) AS FC_AVG26_WEEK_QTY
  FROM INV_SAP_PP_FRCST_PBIM_PBED
  WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
  AND VERSBP_VERSION = '55'
  GROUP BY MATERIALID,
    PLANTID
  )FC_AVG26_WEEK
ON ITEM_BASIC_PP_FC13.ID = FC_AVG26_WEEK.ID;