--ITEM_PROSPECTIVE_REQUIREMENT
--AUTHOR: HUANG MOYUE
--6/17/2014


SELECT PP_BASIC.ID,
    PP_BASIC.LAST_REVIEW,
    PP_BASIC.MATERIAL,
    ITEM_X.CATALOG_DASH,
    ITEM_X.CATALOG_NO_DASH,
    PP_BASIC.PLANT,
    PP_BASIC.MAT_DESC,
    PP_BASIC.SAFETY_STOCK,
    PP_BASIC.UNIT,
    PP_BASIC.UNIT_COST,
    PP_BASIC.PROD_BU,
    PP_BASIC.STRATEGY_GRP,
    PP_BASIC.MRP_TYPE,
    PP_BASIC.VENDOR_ITEM,
    PP_BASIC.MIN_INV,
    PP_BASIC.TARGET_INV,
    PP_BASIC.MAX_INV,
    PP_BASIC.AVG26_USAGE_QTY,
    PP_BASIC.STDEV26_USAGE,
    PP_BASIC.AVG13_USAGE_QTY,
    PP_BASIC.STDEV13_USAGE FROM VIEW_INV_SAP_PP_OPT_X
    
    
    LEFT JOIN
    
    (
    SELECT ID, 
      MATERIAL,
      PLANT,
      SAFETY_STOCK,
      STRATEGY_GRP,
      LEAD_TIME
      FROM VIEW_INV_SAP_PP_OPT_X WHERE ID IN (SELECT DISTINCT VENDOR_ITEM FROM VIEW_INV_SAP_PP_OPT_X)
    )VENDOR_PP
  LEFT JOIN
  (
    
  )