--ITEM_PROSPECTIVE_REQUIREMENT
--AUTHOR: HUANG MOYUE
--6/17/2014
SELECT *
FROM
  (SELECT ID,
    LAST_REVIEW,
    MATERIAL,
    CATALOG_DASH,
    CATALOG_NO_DASH,
    PLANT,
    MAT_DESC,
    SAFETY_STOCK,
    UNIT,
    UNIT_COST,
    PROD_BU,
    STRATEGY_GRP,
    MRP_TYPE,
    VENDOR_ITEM,
    MIN_INV,
    TARGET_INV,
    MAX_INV,
    AVG26_USAGE_QTY,
    STDEV26_USAGE,
    AVG13_USAGE_QTY,
    STDEV13_USAGE
  FROM VIEW_INV_SAP_PP_OPT_X
  )CUSTOMER_PP
LEFT JOIN
  (SELECT ID,
    MATERIAL,
    PLANT,
    SAFETY_STOCK,
    STRATEGY_GRP,
    LEAD_TIME
  FROM VIEW_INV_SAP_PP_OPT_X
  WHERE ID IN
    (SELECT DISTINCT VENDOR_ITEM FROM VIEW_INV_SAP_PP_OPT_X
    )
  )VENDOR_PP
ON VENDOR_PP.ID = CUSTOMER_PP.ID;
  