---PP TABLE FOR WEEKLY 
DROP TABLE INV_SAP_PP_REPORT_WEEKLY;
CREATE TABLE INV_SAP_PP_REPORT_WEEKLY AS
SELECT 
LAST_REVIEW,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
OH_$$,
MAX_INV_$$,
OH_WOS,
PLAN_INV_WOS,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
AVG52_USAGE_QTY,
STDEV52_USAGE,
AVG26_USAGE_QTY,
STDEV26_USAGE,
AVG13_USAGE_QTY,
STDEV13_USAGE,
Q1_LINES,
Q2_LINES,
Q3_LINES,
Q4_LINES,
Q1_FREQ_COUNT,
Q2_FREQ_COUNT,
Q3_FREQ_COUNT,
Q4_FREQ_COUNT,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
WHERE PLANTID IN ('5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201');

SELECT * FROM INV_SAP_PP_REPORT_WEEKLY;


