--- SVD Report 6/6/2014
--  A Material
--	B AP plant
--	C Strategy Group
--	D SBU
--	E Safety stock
--	F Average 13 weeks usage
--	G On hand
--	H Stock in transit  --
--	I Qty Open sales order committed until 13 weeks to the future ( > 13 weeks)
--	J Qty Open SO due this week 
--	K Qty Open SO Past due 
--	Limit data by only taking materials with SG 40 and Z4
--	Mtype is ZTG and ZFG only
	
--'5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141'
--'5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140'

SELECT * FROM SVD_REPORT_DEMO;
CREATE TABLE SVD_REPORT_DEMO AS
SELECT SVD_BASISC_INFO.ID                AS ID,
  SVD_BASISC_INFO.MATERIAL             AS MATERIAL,
  (SVD_BASISC_INFO.PLANT - 1)                AS PLANT,
  SVD_BASISC_INFO.STRATEGY_GRP           AS STRATEGY_GRP,
  SVD_BASISC_INFO.SBU                    AS SBU,
  SVD_BASISC_INFO.SAFETY_STK             AS SAFETY_STK,
  SVD_BASISC_INFO.AVG13_USAGE_QTY        AS AVG13_USAGE_QTY,
  SVD_BASISC_INFO.OH_QTY                 AS OH_QTY,
  SVD_BASISC_INFO.BACKLOG_OPEN           AS BACKLOG_OPEN,
  SVD_BASISC_INFO.PAST_DUE_OPEN          AS PAST_DUE_OPEN,
  SVD_BASISC_INFO.DUE_OPEN_QTY_TWO_WEEKS AS DUE_OPEN_QTY_TWO_WEEKS,
  STOCK_IN_TRAINST.STOCK_IN_TRANSIT_QTY  AS STOCK_IN_TRANSIT_QTY
FROM
  (SELECT PP_INFO.ID                               AS ID,
    PP_INFO.MATERIALID                             AS MATERIAL,
    PP_INFO.PLANTID                                AS PLANT,
    PP_INFO.STRATEGY_GRP                           AS STRATEGY_GRP,
    PP_INFO.PROD_BU                                AS SBU,
    PP_INFO.SAFETY_STK                             AS SAFETY_STK,
    PP_INFO.AVG13_USAGE_QTY                        AS AVG13_USAGE_QTY,
    PP_INFO.OH_QTY                                 AS OH_QTY,
    BACKLOG_PASTDUE_DUE_TWO.BACKLOG_OPEN           AS BACKLOG_OPEN,
    BACKLOG_PASTDUE_DUE_TWO.PAST_DUE_OPEN          AS PAST_DUE_OPEN,
    BACKLOG_PASTDUE_DUE_TWO.DUE_OPEN_QTY_TWO_WEEKS AS DUE_OPEN_QTY_TWO_WEEKS
  FROM
    (SELECT MATERIALID
      ||'_'
      ||(PLANTID - 1) AS ID,
      MATERIALID,
      PLANTID,
      STRATEGY_GRP,
      PROD_BU,
      SAFETY_STK,
      AVG13_USAGE_QTY,
      OH_QTY
    FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
    WHERE STRATEGY_GRP  IN ('SG', '40', 'Z4')
    AND MATL_TYPE_MTART IN ('ZFG','ZTG')
    AND PLANTID         IN ('5041', '5051', '5101', '5111', '5121', '5161', '5191', '5201','5071','5141')
    )PP_INFO
  LEFT JOIN
    (SELECT BACKLOG_PASTDUE.ID                AS ID,
      BACKLOG_PASTDUE.BACKLOG_OPEN            AS BACKLOG_OPEN,
      BACKLOG_PASTDUE.PAST_DUE_OPEN           AS PAST_DUE_OPEN,
      DUE_IN_TWO_WEEKS.DUE_OPEN_QTY_TWO_WEEKS AS DUE_OPEN_QTY_TWO_WEEKS
    FROM
      (SELECT BACKLOG_OPEN.ID           AS ID,
        BACKLOG_OPEN.OPEN_QTY           AS BACKLOG_OPEN,
        PAST_DUE_OPEN.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN
      FROM
        (SELECT MATERIAL
          ||'_'
          ||PLANT       AS ID,
          MATERIAL      AS MATERIALID,
          PLANT         AS PLANTID,
          SUM(OPEN_QTY) AS OPEN_QTY
        FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
        WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
        AND MAX_COMMIT_DATE < SYSDATE + 91
        GROUP BY MATERIAL
          ||'_'
          ||PLANT,
          MATERIAL,
          PLANT
        )BACKLOG_OPEN
      LEFT JOIN
        (SELECT MATERIAL
          ||'_'
          ||PLANT       AS ID,
          MATERIAL      AS MATERIALID,
          PLANT         AS PLANTID,
          SUM(OPEN_QTY) AS PAST_DUE_OPEN_QTY
        FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
        WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
        AND MAX_COMMIT_DATE < SYSDATE - 1
        GROUP BY MATERIAL
          ||'_'
          ||PLANT,
          MATERIAL,
          PLANT
        )PAST_DUE_OPEN
      ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID
      )BACKLOG_PASTDUE
    LEFT JOIN
      (SELECT MATERIAL
        ||'_'
        ||PLANT       AS ID,
        MATERIAL      AS MATERIALID,
        PLANT         AS PLANTID,
        SUM(OPEN_QTY) AS DUE_OPEN_QTY_TWO_WEEKS
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT                                                      IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
      AND (MAX_COMMIT_DATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 14))
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )DUE_IN_TWO_WEEKS
    ON DUE_IN_TWO_WEEKS.ID                                 = BACKLOG_PASTDUE.ID
    )BACKLOG_PASTDUE_DUE_TWO ON BACKLOG_PASTDUE_DUE_TWO.ID = PP_INFO.ID
  )SVD_BASISC_INFO
LEFT JOIN
  (SELECT MATERIALID
    ||'_'
    ||PLANTID AS ID,
    MATERIALID,
    PLANTID,
    SUM(DELIVERY_QTY_SUOM) AS STOCK_IN_TRANSIT_QTY
  FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DBLINK
  WHERE REFERENCE_DOC_TRIM IN
    (SELECT EBELNPURCHDOCNO
    FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
    WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
    AND DELIVERYCOMPLETE IS NULL
    )
  GROUP BY MATERIALID,
    MATERIALID,
    PLANTID
  )STOCK_IN_TRAINST
ON STOCK_IN_TRAINST.ID = SVD_BASISC_INFO.ID;

SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK WHERE MATERIAL  = '100MXC00';