--Create DBLink
select * from user_sys_privs where privilege like upper('%DATABASE LINK%');  
grant create public database link to system;
select * from global_name; 
create public database link ORCL_HMY_DLINK connect to system identified by abc using 'hmy';
SELECT * FROM  help@ORCL_HMY_DLINK;

////////////////////////////////////////////////////////////////////////////////////////////////////////
--Copy table from ra to local

CREATE TABLE INV_SAP_MATERIAL_CATALOG AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_MATERIAL_CATALOG@ROCKWELL_DBLINK; 

CREATE TABLE INV_SAP_SHIP_SOLD_TO_PARTYID AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID@ROCKWELL_DBLINK; 


CREATE TABLE INV_SAP_CROSS_PART AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_CROSS_PART@ROCKWELL_DBLINK;

SELECT * FROM INV_SAP_CROSS_PART;

select * from dba_jobs
select * from dba_jobs_running

Drop table INV_SAP_PP_OPTIMIZATION;
CREATE TABLE INV_SAP_PP_OPTIMIZATION AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK WHERE PLANTID IN ('5040', '5070', '5100', '5110', '5140', '5200'); 

select * from INV_SAP_PP_OPTIMIZATION;

Drop table INV_SAP_SALES_VBAK_VBAP_VBUP;
CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK WHERE PLANT IN ('5040', '5070', '5100', '5110', '5140', '5200');

Drop table INV_SAP_PP_MVKE;
CREATE TABLE INV_SAP_PP_MVKE AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MVKE@ROCKWELL_DBLINK; 

CREATE TABLE INV_SAP_VENDOR_PLANT_INFO AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_VENDOR_PLANT_INFO@ROCKWELL_DBLINK;

DROP TABLE INV_SAP_PP_FRCST_PBIM_PBED;
CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK WHERE PLANTID IN ('5040', '5070', '5100', '5110', '5140', '5200');

CREATE TABLE INV_SAP_PO_EBAN AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PO_EBAN@ROCKWELL_DBLINK;

CREATE TABLE INV_SAP_PO_EINE AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PO_EINE@ROCKWELL_DBLINK;

CREATE TABLE INV_SAP_PO_PVT AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PO_PVT@ROCKWELL_DBLINK;


CREATE TABLE INV_SAP_PP_MATERIAL_GROWTH AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_MATERIAL_GROWTH@ROCKWELL_DBLINK;

CREATE TABLE INV_SAP_COOIS_RAW_AP AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_COOIS_RAW_AP@ROCKWELL_DBLINK;

CREATE TABLE INV_SAP_BU_LOOKUP AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_BU_LOOKUP@ROCKWELL_DBLINK;
------------------------procedure&sql-------------------------

CREATE TABLE AAA_PROCEDURE_SQL AS
SELECT * FROM DWQ$LIBRARIAN.AAA_PROCEDURE_SQL@ROCKWELL_DBLINK;


CREATE TABLE AAA_PROCEDURE_CHANGE_LOG AS
SELECT * FROM DWQ$LIBRARIAN.AAA_PROCEDURE_CHANGE_LOG@ROCKWELL_DBLINK;


select * from AAA_PROCEDURE_CHANGE_LOG;

select count(*) from DWQ$LIBRARIAN.AAA_PROCEDURE_CHANGE_LOG;


