Select MATERIALID, SALES_ORG, CURRENT_SERIES, DIRECT_SHIP_PLANT from INV_SAP_PP_MVKE where MATERIALID = '1756-N2 B';



SELECT * FROM INV_SAP_VENDOR_PLANT_INFO WHERE MATERIALID = '100-C60DJ00 B';

SELECT * FROM INV_SAP_PP_FRCST_PBIM_PBED WHERE MATERIALID = '1756-N2 B';
