Select MATERIALID, SALES_ORG, CURRENT_SERIES, DIRECT_SHIP_PLANT from INV_SAP_PP_MVKE where MATERIALID = '1756-N2 B';



SELECT * FROM INV_SAP_VENDOR_PLANT_INFO WHERE MATERIALID = '100-C60DJ00 B';

SELECT * FROM INV_SAP_PP_FRCST_PBIM_PBED WHERE MATERIALID = '1756-N2 B';

SELECT MATERIALID,SALES_ORG,D_CHAIN_BLK,CURRENT_SERIES,DIRECT_SHIP_PLANT FROM INV_SAP_PP_MVKE WHERE DIRECT_SHIP_PLANT = '1180' and SALES_ORG = '5007';


SELECT * FROM INV_SAP_VENDOR_PLANT_INFO WHERE MATERIALID = '440T-MRPSE11DA/B';

------------------------------VIEW TEST-------------------------------
select * from view_ctmp_mvk where MATERIALID = '1756-N2 B';
select * from CATALOG_TMP where MATERIALID = '1756-N2 B';

select * from INV_SAP_PP_OPTIMIZATION where MATERIALID = '1756-N2 B';

Select MATERIALID, SALES_ORG, CURRENT_SERIES, DIRECT_SHIP_PLANT from INV_SAP_PP_MVKE where MATERIALID = '1756-N2 B';



  
-- How to use pl sql run all item fc number. And update by week? 
-- Try and use create table...
  SELECT FPP.MATERIALID
    ||'-'
    ||FPP.PLANTID                     AS ID,
    FPP.MATERIALID                    AS MATERIALID,
    FPP.PLANTID                       AS PLANTID,
	ROUND(SUM(FPP.PLNMG_PLANNEDQUANTITY)/13, 2) AS FORECAST_QTY,
    FPP.MEINS_BASEUNITOFMEASURE       AS UNIT,
    FPP.VERSBP_VERSION                AS VERSBP_VERSION
  FROM INV_SAP_PP_FRCST_PBIM_PBED FPP
  WHERE (FPP.PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 91))
  AND VERSBP_VERSION = '55'
  AND MATERIALID in (select CATALOG_TMP.MATERIALID from CATALOG_TMP) group by FPP.MATERIALID, FPP.MATERIALID, FPP.PLANTID, FPP.MEINS_BASEUNITOFMEASURE, FPP.VERSBP_VERSION;


SELECT POP.MATERIALID
    ||'-'
    ||POP.PLANTID                  AS ID,
    POP.MATERIALID                 AS ITEM,
    POP.PLANTID                    AS PLANT,
 POP.PDT                        AS LEAD_TIME,
    POP.SAFETY_STK                 AS SAFETY_STOCK,
    POP.STRATEGY_GRP               AS STRATEGY_GRP,
    POP.OH_QTY                     AS ON_HAND_STOCK,
    POP.ANNUAL52_PLANT_VOLUMNE_QTY AS ANNUAL52,
    POP.AVG52_USAGE_QTY            AS AVG52_USAGE_QTY,
    POP.AVG26_USAGE_QTY            AS AVG26_USAGE_QTY,
    POP.AVG13_USAGE_QTY            AS AVG13_USAGE_QTY
  FROM INV_SAP_PP_OPTIMIZATION POP;
  
SELECT MATERIALID AS MATERIALID,
PLANTID AS PLANT,
STRATEGY_GRP AS STRATEGY_GRP,
EXPECTED_SHIP_PLANT_1 AS VENDOR
FROM INV_SAP_VENDOR_PLANT_INFO WHERE MATERIALID  = '1756-N2 B';

SELECT *
FROM INV_SAP_VENDOR_PLANT_INFO WHERE MATERIALID  = '1756-N2 B';

---------------------------------------JOIN VENDOR AND CURRENT SERIAL------------------------------
SELECT * FROM VIEW_INV_CTMP_MVK WHERE MATERIAL = '1756-N2 B';

SELECT DISTINCT VI.ID, VI.CUSTOMER_PLANT,VM.MATERIAL,VM.CATALOGNODASH,VM.CATALOGBYDASH,VM.CURRENT_SERIES,VI.STRATEGY_GRP,VI.VENDOR
FROM VIEW_INV_CTMP_MVK VM,
  VIEW_INV_VENDOR_INFO VI
WHERE VM.ID = VI.ID AND VM.MATERIAL = '1756-N2 B';


SELECT * FROM VIEW_REPORT_ITEM_PLAN WHERE MATERIAL = '440T-MRPSE11DA/B';

SELECT * FROM VIEW_INV_FRCST_PBIM_CACL WHERE MATERIAL = '440T-MRPSE11DA/B';



SELECT VIO.ID AS ID,
VIO.ITEM AS MATERIAL,
VIO.PLANT AS PLANT,
VIO.LEAD_TIME AS LEAD_TIME,
ROUND(VIO.LEAD_TIME/7, 2) AS LEAD_TIME_BYWEEK,
VIO.ON_HAND_STOCK AS ON_HAND_STOCK,
VIO.SAFETY_STOCK AS SAFETY_STOCK,
VIO.STRATEGY_GRP AS STRATEGY_GRP,
VIO.ANNUAL52 AS ANNUAL52,
VIO.AVG52_USAGE_QTY            AS AVG52_USAGE_QTY,
VIO.AVG26_USAGE_QTY            AS AVG26_USAGE_QTY,
VIO.AVG13_USAGE_QTY            AS AVG13_USAGE_QTY,
VIFPC.FORECAST_QTY AS FORECAST_QTY,
VIFPC.UNIT AS UNIT,
VIFPC.VERSBP_VERSION AS VERSBP_VERSION
FROM VIEW_INV_OPTIMIZATION VIO,VIEW_INV_FRCST_PBIM_CACL VIFPC WHERE VIO.ID = VIFPC.ID;

--------------------------------------------Report------------------------------
SELECT VIOF.ID AS ID,
VIOF.MATERIAL AS MATERIAL,
VIVC.CATALOGNODASH AS CATALOG_NODASH,
    VIVC.CATALOGBYDASH AS CATALOG_BYDASH,
    VIVC.CURRENT_SERIES AS CURRENT_SERIES,
    VIVC.STRATEGY_GRP AS STRATEGY_GRP,
    VIOF.PLANT AS CUSTOMER_PLANT,
    VIVC.VENDOR AS VENDOR,
VIOF.LEAD_TIME AS LEAD_TIME,
ROUND(VIOF.LEAD_TIME/7, 2) AS LEAD_TIME_BYWEEK,
VIOF.ON_HAND_STOCK AS ON_HAND_STOCK,
VIOF.SAFETY_STOCK AS SAFETY_STOCK,
VIOF.STRATEGY_GRP AS STRATEGY_GRP,
VIOF.ANNUAL52 AS ANNUAL52,
VIOF.AVG52_USAGE_QTY            AS AVG52_USAGE_QTY,
VIOF.AVG26_USAGE_QTY            AS AVG26_USAGE_QTY,
VIOF.AVG13_USAGE_QTY            AS AVG13_USAGE_QTY,
VIOF.FORECAST_QTY AS FORECAST_QTY,
VIOF.UNIT AS UNIT,
VIOF.VERSBP_VERSION AS VERSBP_VERSION
FROM VIEW_INV_OP_FCST VIOF, VIEW_INV_VEN_CM VIVC WHERE VIOF.ID = VIVC.ID and VIOF.MATERIAL = '1756-N2 B';


CREATE TABLE TABLE_REPORT_ITEM_PLAN
AS SELECT VIOF.ID AS ID,
VIOF.MATERIAL AS MATERIAL,
VIVC.CATALOGNODASH AS CATALOG_NODASH,
    VIVC.CATALOGBYDASH AS CATALOG_BYDASH,
    VIVC.CURRENT_SERIES AS CURRENT_SERIES,
    VIVC.STRATEGY_GRP AS STRATEGY_GRP,
    VIOF.PLANT AS CUSTOMER_PLANT,
    VIVC.VENDOR AS VENDOR,
VIOF.LEAD_TIME AS LEAD_TIME,
ROUND(VIOF.LEAD_TIME/7, 2) AS LEAD_TIME_BYWEEK,
VIOF.ON_HAND_STOCK AS ON_HAND_STOCK,
VIOF.SAFETY_STOCK AS SAFETY_STOCK,
VIOF.ANNUAL52 AS ANNUAL52,
VIOF.AVG52_USAGE_QTY            AS AVG52_USAGE_QTY,
VIOF.AVG26_USAGE_QTY            AS AVG26_USAGE_QTY,
VIOF.AVG13_USAGE_QTY            AS AVG13_USAGE_QTY,
VIOF.FORECAST_QTY AS FORECAST_QTY,
VIOF.UNIT AS UNIT,
VIOF.VERSBP_VERSION AS VERSBP_VERSION
FROM VIEW_INV_OP_FCST VIOF, VIEW_INV_VEN_CM VIVC WHERE VIOF.ID = VIVC.ID;


SELECt * FROM TABLE_REPORT_ITEM_PLAN where MATERIAL = 'PN-171276';

select * from DWQ$LIBRARIAN.INV_SAP_BOM_EXPLODE_PREF_B where COMPONENT_BOM_PLANTID = '1080';

select * from DWQ$LIBRARIAN.DWQ_SHIP_GBBB_BILLING_ALL where PROD_ID_NO = '1756-N2' and BUSI_DTE > '1-jan-2013';

SELECT POP.MATERIALID
  ||'-'
  ||POP.PLANTID          AS ID,
  POP.MATERIALID         AS ITEM,
  POP.PLANTID            AS PLANT,
  POP.PDT                AS LEAD_TIME,
  pop.SP_MATL_STAT_MMSTA AS STATUS,
  POP.MATL_TYPE_MTART AS MATERIAL_TYPE
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION pop
WHERE POP.PLANTID  = '5050'
AND POP.PDT        < 10
AND POP.MATL_TYPE_MTART in('ZFG','ZTG');



------------------------------------pp--------------------------
select * from DWQ$LIBRARIAN.INV_SAP_PP_DEPEND_DMD_FRCST where  PLWRK_PLANNINGPLANT = '5050';

select * from DWQ$LIBRARIAN.INV_SAP_PP_MARM where MATERIALID ='1756-N2 B';





SELECT *
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION
WHERE PLANTID    ='5110';


select * from DWQ$LIBRARIAN.INV_SAP_PP_PARAM where MATERIALID ='1756-N2 B';



drop table inv_sap_pp_optimization;
drop table TABLE_REPORT_ITEM_PLAN;



--------------------------------------PO---------------------------------

SELECT BANFN_PURCHREQNUMBER,
MATERIALID,
PLANTID,
RESWK_SUPPLYISSNGPLNTINSTO,
MENGE_PURCHREQQUANTITY,
BADAT_REQREQUESTDATE,
LPEIN_CATOFDELIVERYDATE,
LFDAT_ITEMDELIVERYDATE,
FRGDT_PURCHREQRELEASEDATE,
WEBAZ_GRT,
PEINH_PRICEUNIT,
WEPOS_GOODSRECEIPTINDICATOR,
REPOS_INVOICERECEIPTINDICATOR,
LIFNR_DESIREDVENDOR,
FLIEF_FIXEDVENDOR,
EBELN_PONUMBER,
EBELP_POITEMNUMBER,
BEDAT_PODATE,
EBAKZ_PURCHREQCLOSED,
PLIFZ_PDT,
BERID_MRPAREA,
DW_DATE FROM DWQ$LIBRARIAN.INV_SAP_PO_EBAN WHERE PLANTID = '5050' AND MATERIALID = '1756-N2 B' and EBELN_PONUMBER = '6301052528';

SELECT MATERIALID,
PLANTID,
EBELNPURCHDOCNO,
EBELPPURCHITEMNO,
BELNRMATERIALDOC,
BUZEIMATERIALDOCITEM,
BWARTMOVEMENTTYPE,
BUDATPOSTINGDATE,
MENGEQTY,
XBLNRREFERENCEDOCUMENTNUM,
BLDAT,
MATNRMATERIAL,
WERKSPLANT,
CUMDELIVERYQTY,
LASTDELIVERYDATE,
TOTALRECIEVEDYQTY,
POITEMRECIEVEDCUM,
DW_DATE,
POITEMRECIEVEDCUM_CHGE,
ENTRY_DATE,
ENTRY_TIME
FROM DWQ$LIBRARIAN.INV_SAP_PO_EKBE WHERE PLANTID = '5050' AND MATERIALID = '1756-N2 B';

select * from DWQ$LIBRARIAN.inv_sap_po_ekpo where plantid = '5050';
select * from DWQ$LIBRARIAN.inv_sap_po_ekko where plantid = '5050';
select * from DWQ$LIBRARIAN.INV_SAP_PO_plaf  WHERE PLWRK_PLANPLANTID = '5050' AND MATERIALID = '1756-N2 B';
select * from DWQ$LIBRARIAN.INV_SAP_PO_eban;
select * from DWQ$LIBRARIAN.INV_SAP_PO_EKES WHERE EBELN_PURCHDOCNO = '6301288636';
select * from DWQ$LIBRARIAN.INV_SAP_PO_EKKO WHERE EBELN_PURCHDOCNO = '6301288636';
select * from DWQ$LIBRARIAN.INV_SAP_PO_EKPO WHERE PLANTID = '5040' and ELIKZDELIVERYCOMPLETE is null AND MATERIALID = '100S-C85KL14BC A';
select * from DWQ$LIBRARIAN.INV_SAP_PO_EKPV WHERE EBELNPURCHDOCNO = '6301288636';
select * from DWQ$LIBRARIAN.INV_SAP_PO_PVT WHERE PLANTID = '5050' AND MATERIAL = '1756-N2 B';
select * from DWQ$LIBRARIAN.INV_SAP_PO_STAT WHERE PLANTID = '5050' AND MATERIALID = '1756-N2 B';



-------------------------------------SO detail------------------------------------------


-- Below use to test sales orders table in dataware house...
-- Date: 4/12/2014
-- People: Marlon Huang


-------------------------------------------------------------------------------

Select * from DWQ$LIBRARIAN.INV_SAP_SALES_52_PVT where PLANTID = '5040' and materialid = '700-HC24Z1-3 D';

-------------------------------------
--DWQ$LIBRARIAN.INV_SAP_SALES_CROSS
--Table Describtion
    MATERIAL           ,
    DEM_QTY            NUMBER ,
    ORDERAMT           NUMBER ,
    LINE_COUNT         NUMBER ,
    ORDERLINE_COUNTED  NUMBER ,
    ONTIMETO_CONFIRMED NUMBER ,
    DEM_AMT            NUMBER ,
    WEEK               NUMBER ,
    WEEK_DATE          DATE ,
    RANK_WEEK          NUMBER ,
    MAX_WEEK_DAY       DATE ,
    MATL_FIRST_USED    DATE ,
    PLANT              NUMBER ,
    OUTLIER_CURRECTED  NUMBER
-------------------------------------
Select * from DWQ$LIBRARIAN.INV_SAP_SALES_CROSS where MATERIAL = '800FP-F1PX10 A' and plant = '5050';

Select * from DWQ$LIBRARIAN.INV_SAP_SALES_CROSS where MATERIAL = '1756-A10 B' and plant = '5050' and WEEK_DATE > '01-jan-14';


-------------------------------------
--DWQ$LIBRARIAN.INV_SAP_SALES_CROSS
--Table Describtion
    MATERIAL           VARCHAR2(4000 BYTE) ,
    DEM_QTY            Monthly Demand from real orders
    MAX_MONTH_DAY      DATE ,
    RANK_MONTH         NUMBER ,
    YYYYMM             VARCHAR2(6 BYTE) ,
    MAX_MONTH_DATE     DATE ,
    MATL_FIRST_USED    DATE ,
    PLANTID            NUMBER 
-------------------------------------
Select * from DWQ$LIBRARIAN.INV_SAP_SALES_CROSS_MONTH where MATERIAL = '1756-A10 B' and PLANTID = '5050';


Select * from DWQ$LIBRARIAN.INV_SAP_SALES_STAT2 where PLANT = '5050' and MATERIAL = '1756-A10 B';

-- 4.1 Creation Date OK!
-- look up 1 week before.
Select * from DWQ$LIBRARIAN.INV_SAP_SALES_HST  where plantid = '5050' and SALESDOC = '6501812863';  

Select * from DWQ$LIBRARIAN.INV_SAP_SALES_SAP where SALESDOC = '6501812863'; 


Select * from DWQ$LIBRARIAN.INV_SAP_SALES_STO_DTL where SALESDOC = '6501812863'; 
-- THE MOST VALUE TABLE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Select * from DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP where plant = '5040' and MATERIAL = '700-HC24Z1-3 D'; 

-----------------------------PRODUCTION PARAMETERS-------------------------------------------------------------------
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PRODUCTION_PARAMETERS WHERE MATERIALID = '1756-N2 B' AND PLANTID = '5050';








-------------------------------------------------------------------------------------------------

select * from INV_SAP_CROSS_part where materialid = '1756-A10 B';












-----------------------------------Inventory----------------------------------------------------

SELECT * FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT WHERE PLANTID = '5050';


SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SPA_CDC_MEM_COST WHERE MATERIALID = '1756-N2 B';





----------------------------------Usage---------------------------------------------------------
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_IO_INPUTS WHERE PLANTID = '5050' and MATERIALID ='1756-N2 B';








--------------------------------------------------------------------------------------------------
---Special procurement type
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_CODE_LOOKUP WHERE PLANT = '5040';





--------------------------------------------------------------------------------------------------
---Delivery information history
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY where plantid = '5050' and DELIVERY = '8013545908';

SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LOH3 WHERE MATERIALID ='1756-N2 B';





----------------------------LIKP_LIPS------------------------------------------------------------
select * from DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY WHERE MATERIALID ='1756-N2 B' and plantid = '5050';




----------------------------Planning Param--------------------------------------------------------------------------
select * from DWQ$LIBRARIAN.INV_SAP_PLAN_PARAM_REVIEW where PLANTID = '5200' and MATERIALID ='1756-CN2R B';









--------------------------------PP------------------------------------------------------------------------------------
--inv_sap_pp_optimization
---CV Data Report
SELECT MATERIALID,
  PLANTID,
  AVGXX_USAGE_QTY,
  STDEVXX_USAGE,
  CVXX_USAGE
FROM DWQ$LIBRARIAN.inv_sap_pp_optimization
WHERE Plantid = '5040';

CREATE TABLE inv_sap_pp_optimization_5041
Select * from DWQ$LIBRARIAN.inv_sap_pp_optimization;









---INV_SAP_PP_SERVICE_LEVELS
--- Service Level Report in RISO
SELECT SERVISE_LEVEL_TYPE,
  PLANTID,
  LEVEL_TYPE ,
  LEVEL_VALUE ,
  ANALYSIS_COST_X ,
  ANALYSIS_WKSPEED_X ,
  ANALYSIS_LINESPEED_X ,
  ANALYSIS_ABCWI_X ,
  ANALYSIS_TICPOF_X ,
  SERVICE_LEVEL,
  SERVICE_LEVEL_ALTERNATE
FROM DWQ$LIBRARIAN.INV_SAP_PP_SERVICE_LEVELS
WHERE SERVISE_LEVEL_TYPE = 'CSM';

---INV_SAP_PP_CS_LEVELS
--- C&S Growth Report in RISO
SELECT SERVISE_LEVEL_TYPE,
  PLANTID,
  LEVEL_TYPE,
  LEVEL_VALUE,
  GROWTH,
  FIX_COST,
  HOLDING_COST,
  ADDPCTTOMAX,
  EXCHANGE_RATE,
  AUTO_SL_TOLERANCE_MIN,
  AUTO_SL_TOLERANCE_MAX,
  AUTO_$$_THREASHOLD_MIN,
  AUTO_$$_THREASHOLD_MAX,
  COST_MIN,
  COST_MAX,
  VOLUMNE_MIN,
  VOLUMNE_MAX,
  HIGHSPEEDWK_MIN,
  LOWSPEEDWK_MAX,
  DOUBLEWAMMYWK_MAX,
  INACTIVEWK_MAX,
  HIGHSPEEDLN_MIN,
  LOWSPEEDLN_MAX,
  DOUBLEWAMMYLN_MAX,
  INACTIVELN_MAX,
  USESTATISTICS,
  CAPONLOTSIZEFACTOR,
  PLAN_BY_WOS,
  ASSUMPTIONS_NOTES,
  CHANGE_AUTORIZATION
FROM DWQ$LIBRARIAN.INV_SAP_PP_CS_LEVELS
WHERE SERVISE_LEVEL_TYPE = 'CSM';



SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED WHERE MATERIALID = '1489-A1C150 A
' and PLANTID = '5200';










-------------------------------------------CROSS-------------------------------------------------------
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_CROSS_PART WHERE MATERIALID = '1756-N2 B';

SELECT * FROM DWQ$LIBRARIAN.INV_SAP_CROSS_PART_WITH WHERE MATERIALID = '1756-N2 B';



















------------------------------Delivery History Record--------------------------
select * from DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY where PLANTID = '5040' and CREATED_ON_DATE = '13-JAN-14';

SELECT MATERIALID,
  CATALOGID,
  SALESDOC,
  SALESDOCITEM,
  SOLDTOPARTY,
  PLANTID,
  ORDERQTY,
  LINECREATIONDATE,
  REQUIREDDELIVERYDATE
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST
WHERE SOLDTOPARTY = '91312369'
AND MATERIALID    = '74106-869-51';

--Data Report For gloria
SELECT MATERIALID,
  CATALOGID,
  SALESDOC,
  SALESDOCITEM,
  SOLDTOPARTY,
  PLANTID,
  ORDERQTY,
  LINECREATIONDATE,
  REQUIREDDELIVERYDATE
FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST
WHERE PLANTID = '5040'
AND LINECREATIONDATE BETWEEN TO_CHAR(sysdate - 183) AND TO_CHAR(sysdate);


SELECT SSTP.SHIP_SOLD_TOPARTY AS SOLD_PARTY,
  SSTP.SHIP_TO_PARTY_NAME AS CUSTOMER_NAME
FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID SSTP
WHERE SHIP_TO_COUNTRY = 'CN' and SHIP_SOLD_TOPARTY = '91312759';

--LEFT JOIN
SELECT SSHJ.PLANT_ID  AS PLANT_ID,
  SSHJ.SALE_ORDER     AS SALE_ORDER,
  SSHJ.ITEM           AS ITEM,
  SSHJ.MATERIAL_ID    AS MATERIAL_ID,
  SSHJ.CATALOG_ID     AS CATALOG_ID,
  SSHJ.SOLD_TO_PARTY  AS SOLD_TO_PARTY,
  SSTPJ.CUSTOMER_NAME AS CUSTOMER_NAME,
  SSHJ.QTY            AS QTY,
  SSHJ.CREATION_DATE  AS CREATION_DATE,
  SSHJ.REQUIRE_DATE   AS REQUIRE_DATE
FROM
  (SELECT SSH.MATERIALID     AS MATERIAL_ID,
    SSH.CATALOGID            AS CATALOG_ID,
    SSH.SALESDOC             AS SALE_ORDER,
    SSH.SALESDOCITEM         AS ITEM,
    SSH.SOLDTOPARTY          AS SOLD_TO_PARTY,
    SSH.PLANTID              AS PLANT_ID,
    SSH.ORDERQTY             AS QTY,
    SSH.LINECREATIONDATE     AS CREATION_DATE,
    SSH.REQUIREDDELIVERYDATE AS REQUIRE_DATE
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_HST SSH
  WHERE PLANTID = '5040'
  AND LINECREATIONDATE BETWEEN '21-04-14' AND '25-04-14'
  )SSHJ
LEFT JOIN
  (SELECT SSTP.SHIP_SOLD_TOPARTY AS SOLD_TO_PARTY,
    SSTP.SHIP_TO_PARTY_NAME      AS CUSTOMER_NAME
  FROM DWQ$LIBRARIAN.INV_SAP_SHIP_SOLD_TO_PARTYID SSTP
  WHERE SHIP_TO_COUNTRY = 'CN'
  ) SSTPJ
ON SSTPJ.SOLD_TO_PARTY = SSHJ.SOLD_TO_PARTY;





-------------simon report------------------------
Drop table SIMON_REPORT;
CREATE TABLE SIMON_REPORT AS
SELECT MATERIALID,
  MAT_DESC,
  PLANTID,
  PROD_BU,
  SAFETY_STK,
  CVXX_USAGE,
  UNIT_COST,
  CURRENT_PLAN_INV$$,
  MAX_INV_$$,
  STRATEGY_GRP,
  LOT_MIN_BUY,
  AVG26_USAGE_QTY,
  STDEV26_USAGE,
  Q1_LINES,
  Q2_LINES,
  Q3_LINES,
  Q4_LINES,
  Q1_FREQ_COUNT,
  Q2_FREQ_COUNT,
  Q3_FREQ_COUNT,
  Q4_FREQ_COUNT,
  PDT
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
WHERE PROD_BU = 'KNX-KINETIX'
AND PLANTID  IN ('5041', '5051', '5071', '5101', '5111', '5121', '5141', '5161', '5191', '5201');



-----------------------------RISO--------------------------------------------
--Planning Param
SELECT DISTINCT *
FROM dwq$librarian.INV_SAP_PP_OPTIMIZATION
WHERE PLANTID            IN (0, upper(trim('5201')) )
AND MRP_CONTROLLER_DISPO IN ('', upper(trim('003')) )
AND ( MAX_OH_IN_09WEEKS   > 0
OR AVG52_USAGE_QTY        > 0)
ORDER BY OH_DOLLARS DESC;









--------------------------------Stock Item review report------------------------

--Total Sales Order Backlog
SELECT *
FROM
  (SELECT Material,
    plant,
    SUM(OPEN_QTY) AS TOTAL_OPEN
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
  WHERE MATERIAL IN
    (SELECT material
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
    WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
    )
  GROUP BY material,
    plant
  )
WHERE material = 'PN-184723';

--PAST DUE 
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP WHERE Material = 'PN-184723' AND MAX_COMMIT_DATE < SYSDATE and plant = '5040';

SELECT *
FROM
  (SELECT Material,
    plant,
    SUM(OPEN_QTY) AS TOTAL_PASS_DUE
  FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
  WHERE MATERIAL IN
    (SELECT material
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
    WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
    ) AND MAX_COMMIT_DATE < SYSDATE
  GROUP BY material,
    plant
  )
WHERE material = 'PN-184723';


--Avg Weekly Forecast
SELECT
    FPP.MATERIALID                    AS MATERIALID,
    FPP.PLANTID                       AS PLANTID,
    SUM(FPP.PLNMG_PLANNEDQUANTITY)/26 AS PLANNED_QUANTITY
  FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED FPP
  WHERE (FPP.PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
  AND PLANTID IN ('5040', '5070', '5100', '5110', '5140', '5200') and MATERIALID IN
    (SELECT material
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
    WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
    ) group by FPP.MATERIALID, FPP.PLANTID;


--Main Body
SELECT MATERIALID as Material,
PLANTID as Plant,
MATERIALID||''||PLANTID as Key,
MAT_DESC as Material_Description,
PROD_BU as BU,
PROC_TYPE as Procurement_Type,
MRP_CONTROLLER_DISPO as MRP_CONTROLLER_ID,
MRP_CONTROLLER as MRP_CONTROLLER,
MATL_TYPE_MTART as MATL_TYPE,
MRP_TYPE as MRP_TYPE,
STRATEGY_GRP as Stock_Strategy,
UNIT_COST as Unit_Price,
REORDER_PT as Reorder_Point,
SAFETY_STK as Safety_stock_Qty,
LOT_SIZE_DISLS as LOT_SIZE,
LOT_MIN_BUY as Min_LOT_SIZE,
LOT_ROUNDING_VALUE as Rounding_val,
GRT	as GRT,
PDT	 as PDT,
IPT	as IPT,
OH_QTY as	OH_QTY,
OH_$$	as OH_$$,
INV_MAX	as INV_MAX,
CURR_PLAN_INV_QTY as Target_Inv
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION
WHERE STRATEGY_GRP = '40' AND MATL_TYPE_MTART IN ('ZFG','ZTG')
AND PLANTID  IN ('5040', '5070', '5100', '5110',  '5140', '5200');



---JOIN TOGETHER

SELECT *
FROM
  (SELECT MATERIALID
    ||'_'
    ||PLANTID  AS ID,
    MATERIALID AS Material,
    PLANTID    AS Plant,
    MATERIALID
    ||''
    ||PLANTID            AS KEY,
    MAT_DESC             AS Material_Description,
    PROD_BU              AS BU,
    PROC_TYPE            AS Procurement_Type,
    MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_ID,
    MRP_CONTROLLER       AS MRP_CONTROLLER,
    MATL_TYPE_MTART      AS MATL_TYPE,
    MRP_TYPE             AS MRP_TYPE,
    STRATEGY_GRP         AS Stock_Strategy,
    UNIT_COST            AS Unit_Price,
    REORDER_PT           AS Reorder_Point,
    SAFETY_STK           AS Safety_stock_Qty,
    LOT_SIZE_DISLS       AS LOT_SIZE,
    LOT_MIN_BUY          AS Min_LOT_SIZE,
    LOT_ROUNDING_VALUE   AS Rounding_val,
    GRT                  AS GRT,
    PDT                  AS PDT,
    IPT                  AS IPT,
    OH_QTY               AS OH_QTY,
    OH_$$                AS OH_$$,
    INV_MAX              AS INV_MAX,
    CURR_PLAN_INV_QTY    AS Target_Inv
  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION
  WHERE STRATEGY_GRP   = '40'
  AND MATL_TYPE_MTART IN ('ZFG','ZTG')
  AND PLANTID         IN ('5040', '5070', '5100', '5110', '5140', '5200')
  )pp
LEFT JOIN
  (SELECT fc_avg.id         AS ID,
    fc_avg.PLANNED_QUANTITY AS PLANNED_QUANTITY,
    backlog.TOTAL_OPEN
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                     AS ID,
      MATERIALID                    AS MATERIALID,
      PLANTID                       AS PLANTID,
      ROUND(SUM(PLNMG_PLANNEDQUANTITY)/26 + 1,0) AS PLANNED_QUANTITY
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND PLANTID                                                                     IN ('5040', '5070', '5100', '5110', '5140', '5200')
    AND VERSBP_VERSION = '55'
    AND MATERIALID                                                                  IN
      (SELECT material
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
      WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
      )
    GROUP BY MATERIALID,
      MATERIALID
      ||'_'
      ||PLANTID,
      PLANTID
    )fc_avg
  LEFT JOIN
    (SELECT Material
      ||'_'
      ||PLANT AS ID,
      Material,
      plant,
      SUM(OPEN_QTY) AS TOTAL_OPEN
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
    WHERE plant  IN ('5040', '5070', '5100', '5110', '5140', '5200')
    AND MATERIAL IN
      (SELECT material
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP
      WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
      )
    GROUP BY Material
      ||'_'
      ||PLANT,
      Material,
      plant
    )backlog
  ON fc_avg.ID                 = backlog.ID
  )fc_avg_sum ON fc_avg_sum.ID = PP.ID ;

-------------------------------------------------------------------------------







CREATE TABLE INV_SAP_PP_FRCST_PBIM_PBED AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK;

CREATE TABLE INV_SAP_SALES_VBAK_VBAP_VBUP AS
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200');

CREATE TABLE INV_SAP_PP_test_data AS
SELECT MATERIALID
    ||'_'
    ||PLANTID  AS ID,
    MATERIALID AS Material,
    PLANTID    AS Plant,
    MATERIALID
    ||''
    ||PLANTID               AS KEY,
    MAT_DESC                AS Material_Description,
    PROD_BU                 AS BU,
    PROC_TYPE               AS Procurement_Type,
    MRP_CONTROLLER_DISPO    AS MRP_CONTROLLER_ID,
    MRP_CONTROLLER          AS MRP_CONTROLLER,
    MATL_TYPE_MTART         AS MATL_TYPE,
    MRP_TYPE                AS MRP_TYPE,
    STRATEGY_GRP            AS Stock_Strategy,
    UNIT_COST               AS Unit_Price,
    REORDER_PT              AS Reorder_Point,
    SAFETY_STK              AS Safety_stock_Qty,
    LOT_SIZE_DISLS          AS LOT_SIZE,
    LOT_MIN_BUY             AS Min_LOT_SIZE,
    LOT_ROUNDING_VALUE      AS Rounding_val,
    GRT                     AS GRT,
    PDT                     AS PDT,
    IPT                     AS IPT,
    OH_QTY                  AS OH_QTY,
    OH_$$                   AS OH_$$
  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
  WHERE STRATEGY_GRP   = '40'
  AND MATL_TYPE_MTART IN ('ZFG','ZTG')
  AND PLANTID         IN ('5040', '5070', '5100', '5110', '5140', '5200');
-------------------------------------------------------------------------------
  
SELECT * FROM STOCK_ITEM_PERFORMANCE;

--Fecth back to local
DROP TABLE STOCK_ITEM_PERFORMANCE;
CREATE TABLE STOCK_ITEM_PERFORMANCE AS
SELECT PP.ID              AS ID,
  PP.Material             AS Material,
  PP.Plant                AS Plant,
  PP.KEY                  AS KEY,
  PP.Material_Description AS Material_Description,
  PP.BU                   AS BU,
  PP.Procurement_Type     AS Procurement_Type,
  PP.MRP_CONTROLLER_ID    AS MRP_CONTROLLER_ID,
  PP.MRP_CONTROLLER       AS MRP_CONTROLLER,
  PP.MATL_TYPE            AS MATL_TYPE,
  PP.MRP_TYPE             AS MRP_TYPE,
  PP.Stock_Strategy       AS Stock_Strategy,
  PP.Unit_Price           AS Unit_Price,
  PP.Reorder_Point        AS Reorder_Point,
  PP.Safety_stock_Qty     AS Safety_stock_Qty,
  PP.LOT_SIZE             AS LOT_SIZE,
  PP.Min_LOT_SIZE         AS Min_LOT_SIZE,
  PP.Rounding_val         AS Rounding_val,
  PP.GRT                  AS GRT,
  PP.PDT                  AS PDT,
  PP.IPT                  AS IPT,
  PP.OH_QTY               AS OH_QTY,
  PP.OH_$$                AS OH_$$,
  FC_AVG_SUM.PLANNED_QUANTITY AS FC_AVG_WEEKLY,
  FC_AVG_SUM.TOTAL_OPEN      AS BACKLOG_SUM,
  FC_AVG_SUM.TOTAL_PASSDUE AS PASSDUE_SUM
FROM
  (SELECT MATERIALID
    ||'_'
    ||PLANTID  AS ID,
    MATERIALID AS Material,
    PLANTID    AS Plant,
    MATERIALID
    ||''
    ||PLANTID               AS KEY,
    MAT_DESC                AS Material_Description,
    PROD_BU                 AS BU,
    PROC_TYPE               AS Procurement_Type,
    MRP_CONTROLLER_DISPO    AS MRP_CONTROLLER_ID,
    MRP_CONTROLLER          AS MRP_CONTROLLER,
    MATL_TYPE_MTART         AS MATL_TYPE,
    MRP_TYPE                AS MRP_TYPE,
    STRATEGY_GRP            AS Stock_Strategy,
    UNIT_COST               AS Unit_Price,
    REORDER_PT              AS Reorder_Point,
    SAFETY_STK              AS Safety_stock_Qty,
    LOT_SIZE_DISLS          AS LOT_SIZE,
    LOT_MIN_BUY             AS Min_LOT_SIZE,
    LOT_ROUNDING_VALUE      AS Rounding_val,
    GRT                     AS GRT,
    PDT                     AS PDT,
    IPT                     AS IPT,
    OH_QTY                  AS OH_QTY,
    OH_$$                   AS OH_$$
  FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
  WHERE STRATEGY_GRP   = '40'
  AND MATL_TYPE_MTART IN ('ZFG','ZTG')
  AND PLANTID         IN ('5040', '5070', '5100', '5110', '5140', '5200')
  )PP
LEFT JOIN
  (SELECT FC_AVG.ID         AS ID,
    FC_AVG.PLANNED_QUANTITY AS PLANNED_QUANTITY,
    BACKLOG.TOTAL_OPEN AS TOTAL_OPEN,
    BACKLOG.TOTAL_PASSDUE AS TOTAL_PASSDUE
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID                     AS ID,
      MATERIALID                    AS MATERIALID,
      PLANTID                       AS PLANTID,
      ROUND(SUM(PLNMG_PLANNEDQUANTITY)/26 + 1, 0) AS PLANNED_QUANTITY
    FROM DWQ$LIBRARIAN.INV_SAP_PP_FRCST_PBIM_PBED@ROCKWELL_DBLINK
    WHERE (PDATU_DELIV_ORDFINISHDATE BETWEEN TO_CHAR(sysdate) AND TO_CHAR(sysdate + 182))
    AND PLANTID                                                                     IN ('5040', '5070', '5100', '5110', '5140', '5200')
    AND VERSBP_VERSION = '55'
    AND MATERIALID                                                                  IN
      (SELECT material
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
      )
    GROUP BY MATERIALID,
      MATERIALID
      ||'_'
      ||PLANTID,
      PLANTID
    )FC_AVG
  LEFT JOIN
    (
    SELECT TOTAL_OPEN.ID AS ID,
    TOTAL_OPEN.TOTAL_OPEN AS TOTAL_OPEN,
    total_passdue.passdue as TOTAL_PASSDUE
    FROM
    (SELECT Material
      ||'_'
      ||PLANT AS ID,
      Material,
      PLANT,
      SUM(OPEN_QTY) AS TOTAL_OPEN
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
    WHERE PLANT  IN ('5040', '5070', '5100', '5110', '5140', '5200')
    AND MATERIAL IN
      (SELECT material
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
      )
    GROUP BY Material
      ||'_'
      ||PLANT,
      Material,
      plant)TOTAL_OPEN 
      left join
      (SELECT Material
      ||'_'
      ||PLANT AS ID,
      Material,
      PLANT,
      SUM(OPEN_QTY) AS passdue
    FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
    WHERE PLANT  IN ('5040', '5070', '5100', '5110', '5140', '5200')
    AND MATERIAL IN
      (SELECT material
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE plant IN ('5040', '5070', '5100', '5110', '5140', '5200')
      )
    AND MAX_COMMIT_DATE < SYSDATE - 1
    GROUP BY Material
      ||'_'
      ||PLANT,
      Material,
      plant)total_passdue 
      ON total_passdue.ID = TOTAL_OPEN.ID
    )BACKLOG
  ON FC_AVG.ID                 = BACKLOG.ID
  )FC_AVG_SUM ON FC_AVG_SUM.ID = PP.ID ;
  
-----------------------------Transit Date Table---------------------------
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_PLANT_TRANSIT_DAYS_V WHERE RECEIVING_PLANT = '5040' and Supply_Plantid = '1090';



CREATE TABLE INV_SAP_SALES_5070 AS 
SELECT * FROM  DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK WHERE PLANT = '5070';

SELECT * FROM INV_SAP_SALES_5070;
DROP TABLE INV_SAP_SALES_5070;





SELECT * FROM INV_SAP_REPORT_5070;
CREATE TABLE INV_SAP_REPORT_5070 AS 
SELECT MATERIALID ||'_'||(PLANTID - 1) AS ID, LAST_REVIEW,
PROC_TYPE,
MATERIALID,
PLANTID,
MAT_DESC,
SAFETY_STK,
LOT_SIZE,
OH_QTY,
UNIT_COST,
PROD_BU,
PROD_FAM,
PROD_HIERARCHY,
MRP_CONTROLLER,
PURCH_GROUP,
STRATEGY_GRP,
MRP_TYPE,
SP_MATL_STAT_MMSTA,
SPC_PROC_KEY_SOBSL,
VENDOR_NAME,
LOT_ROUNDING_VALUE,
GRT,
PDT,
MEINS_ISSUE_UOM,
PURCH_GROUP_EKGRP,
MATL_TYPE_MTART
FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
WHERE PLANTID IN ('5070');


SELECT MATERIALID
  ||'_'
  ||(PLANTID - 1) AS ID,
  LAST_REVIEW,
  MATERIALID AS MATERIAL,
  (PLANTID - 1) AS PLANT,
  MAT_DESC,
  SAFETY_STK AS SAFETY_STOCK,
  OH_QTY,
  UNIT_COST,
  OH_QTY_INTRANSIT,
  SUBSTR(PROD_BU,0,3) AS PROD_BU,
  PROD_FAM,
  PROC_TYPE,
  STRATEGY_GRP,
  MRP_TYPE,
  PROD_SCHEDULER,
  SP_MATL_STAT_MMSTA AS PLANT_SP_MATL_STA,
  SPC_PROC_KEY_SOBSL AS VENDOR_KEY,
  MATERIALID||'_'||SUBSTR(VENDOR_NAME,0,4) AS VENDOR_ITEM,
  (SAFETY_STK) AS MIN_INV,
  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS TARGET_INV,
  CEIL(SAFETY_STK + 0.5*LOT_SIZE_QTY) AS MAX_INV,
  LOT_SIZE_QTY,
  LOT_ROUNDING_VALUE,
  LOT_SIZE_DISLS,
  AVG26_USAGE_QTY,
  STDEV26_USAGE,
  AVG13_USAGE_QTY,
  STDEV13_USAGE,
  Q1_LINES,
  Q2_LINES,
  Q3_LINES,
  Q4_LINES,
  Q1_FREQ_COUNT,
  Q2_FREQ_COUNT,
  Q3_FREQ_COUNT,
  Q4_FREQ_COUNT,
  EXCHANGE_RATE,
  LEVEL_TYPE,
  MATERIAL_LEVEL_VALUE,
  MRP_CONTROLLER,
  MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_KEY,
  PURCH_GROUP,
  PURCH_GROUP_EKGRP AS   PURCH_GROUP_KEY,
  PROD_SCHED_FEVOR AS PROD_SCHED_KEY,
  REORDER_PT AS RECORDER_POINT,
  (GRT + PDT + 1) AS LEAD_TIME,
  MEINS_ISSUE_UOM,
  ISSUE_UOM_NUMERATOR,
  PO_UOM_NUMERATOR,
  MATL_TYPE_MTART AS MATL_TYPE,
  ULTIMATE_SOURCE
FROM INV_SAP_PP_OPTIMIZATION WHERE PLANTID = '5041';














----

SELECT * FROM INV_DEMO_REPORT WHERE BACKLOG_OPEN_QTY IS NULL AND TOTAL_QTY IS NOT NULL;
SELECT * FROM INV_DEMO_REPORT_china WHERE BACKLOG_OPEN_QTY IS NOT NULL AND Stock_Strategy = '40';

SELECT MATERIALID
      ||'_'
      ||PLANTID     AS ID,
      MATERIALID    AS MATERIAL,
      PLANTID       AS PLANT,
      NVL(OH_QTY,0) AS TOTAL_QTY
    FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5050') 

DROP TABLE INV_DEMO_REPORT_china;
SELECT * FROM INV_DEMO_REPORT_china;
CREATE TABLE INV_DEMO_REPORT_china AS 
SELECT 
  INV_ITEM_BASIC.LAST_REVIEW_DATE      AS LAST_REVIEW_DATE,
  INV_ITEM_BASIC.ID               AS ID,
  INV_ITEM_BASIC.PLANT                 AS PLANT,
  INV_ITEM_BASIC.MATERIAL              AS MATERIAL,
  INV_ITEM_BASIC.TOTAL_QTY             AS TOTAL_QTY,
  INV_ITEM_BASIC.Stock_Strategy      AS Stock_Strategy,
  STO_SALES_OPEN_QTY.BACKLOG_OPEN_QTY  AS BACKLOG_OPEN_QTY
FROM
  (SELECT INV_BASIC.ID              AS ID,
    INV_BASIC.PLANT                 AS PLANT,
    INV_BASIC.MATERIAL              AS MATERIAL,
    INV_BASIC.TOTAL_QTY             AS TOTAL_QTY,
    INV_BASIC.LAST_REVIEW_DATE      AS LAST_REVIEW_DATE,
    INV_BASIC.LOCATION              AS LOCATION,
    ITEM_BASIC.Material_Description AS Material_Description,
    ITEM_BASIC.BU                   AS BU,
    ITEM_BASIC.Procurement_Type     AS Procurement_Type,
    ITEM_BASIC.MATL_TYPE            AS MATL_TYPE,
    ITEM_BASIC.MRP_TYPE             AS MRP_TYPE,
    ITEM_BASIC.Stock_Strategy       AS Stock_Strategy,
    ITEM_BASIC.Safety_Stock_Qty     AS Safety_Stock_Qty,
    ITEM_BASIC.PDT                  AS PDT
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID     AS ID,
      MATERIALID    AS MATERIAL,
      PLANTID       AS PLANT,
      LOCATIONID    AS LOCATION,
      NVL(OH_QTY,0) AS TOTAL_QTY,
      ASOFDATE      AS LAST_REVIEW_DATE
    FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5040') --- ALL PLANTS HERE!!
    )INV_BASIC
  LEFT JOIN
    (SELECT MATERIALID
      ||'_'
      ||PLANTID            AS ID,
      MATERIALID           AS MATERIALID,
      PLANTID              AS PLANTID,
      MAT_DESC             AS Material_Description,
      PROD_BU              AS BU,
      PROC_TYPE            AS Procurement_Type,
      MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_ID,
      MRP_CONTROLLER       AS MRP_CONTROLLER,
      MATL_TYPE_MTART      AS MATL_TYPE,
      MRP_TYPE             AS MRP_TYPE,
      STRATEGY_GRP         AS Stock_Strategy,
      UNIT_COST            AS Unit_Price,
      NVL(REORDER_PT,0)    AS Reorder_Point,
      NVL(SAFETY_STK,0)    AS Safety_Stock_Qty,
      PDT                  AS PDT
    FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5040') --- ALL PLANTS HERE!!
    )ITEM_BASIC
  ON ITEM_BASIC.ID = INV_BASIC.ID
  )INV_ITEM_BASIC
LEFT JOIN
  (
  --OPEN STATUS
  SELECT SALES_OPEN_PASS_QTY.ID           AS ID,
    SALES_OPEN_PASS_QTY.BACKLOG_OPEN_QTY  AS BACKLOG_OPEN_QTY,
    SALES_OPEN_PASS_QTY.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN_QTY,
    STO_OPEN_QTY_S.PO_SO_SA_FLAG          AS PO_SO_SA_FLAG,
    STO_OPEN_QTY_S.STO_OPEN_QTY           AS STO_OPEN_QTY
  FROM
    (
    --Sales Orders Status
    SELECT BACKLOG_OPEN.ID                   AS ID,
      NVL(BACKLOG_OPEN.OPEN_QTY,0)           AS BACKLOG_OPEN_QTY,
      NVL(PAST_DUE_OPEN.PAST_DUE_OPEN_QTY,0) AS PAST_DUE_OPEN_QTY
    FROM
      (SELECT MATERIAL
        ||'_'
        ||PLANT              AS ID,
        MATERIAL             AS MATERIALID,
        PLANT                AS PLANTID,
        NVL(SUM(OPEN_QTY),0) AS OPEN_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT IN ('5040')  ---All Plants
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )BACKLOG_OPEN
    LEFT JOIN
      (SELECT MATERIAL
        ||'_'
        ||PLANT               AS ID,
        MATERIAL              AS MATERIALID,
        PLANT                 AS PLANTID,
        NVL(SUM(OPEN_QTY), 0) AS PAST_DUE_OPEN_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT                  IN ('5040') ---All Plants
      AND MAX_COMMIT_DATE < SYSDATE - 1
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )PAST_DUE_OPEN
    ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID
    )SALES_OPEN_PASS_QTY
  LEFT JOIN
    ---STO_OPEN_QTY
    (
    SELECT MATERIALID
      ||'_'
      ||PLANTID AS ID,
      MATERIALID,
      PLANTID,
      PO_SO_SA_FLAG,
      NVL(SUM(COMMITTEDQTY),0) AS STO_OPEN_QTY
    FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
    WHERE PLANTID        IN ('5040') ---All Plants
    AND PO_SO_SA_FLAG     = 'STO'
    AND DELIVERYCOMPLETE IS NULL
    GROUP BY MATERIALID,
      PLANTID,
      PO_SO_SA_FLAG
    )STO_OPEN_QTY_S
  ON SALES_OPEN_PASS_QTY.ID                    = STO_OPEN_QTY_S.ID
  )STO_SALES_OPEN_QTY ON STO_SALES_OPEN_QTY.ID = INV_ITEM_BASIC.ID;

--3 MONTHS
SELECT MATERIALID,
  SUM(ORDERQTY) AS SALES_THREE_MONTHS,
  PLANTID
FROM INV_SAP_SALES_HST
WHERE PLANTID = '5040'
AND COMMITTEDDATE BETWEEN TO_CHAR(sysdate - 91) AND TO_CHAR(sysdate) group by MATERIALID, PLANTID;


      
SELECT MATERIALID,OH_QTY_INTRANSIT FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK WHERE MATERIALID = '44154' AND PLANTID = '5041';
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_LIKP_LIPS_DAILY@ROCKWELL_DBLINK WHERE MATERIALID = '192639' AND PLANTID = '5040';
SELECT *
      FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
      WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')
      AND DELIVERYCOMPLETE IS NULL AND MATERIALID = '44154'








----LT time Open Sales Orders Qty
SELECT COUNT(*)
FROM
  (SELECT SALESDOC,MATERIAL
  FROM INV_SAP_SALES_VBAK_VBAP_VBUP
  WHERE MAX_CONFIRM_DATE < 
  );


SELECT ID,MATERIAL,LEAD_TIME FROM VIEW_INV_SAP_PP_OPT_X;

SELECT * FROM 
(
SELECT REFERENCE_DOC
  ||'_'
  ||MATERIALID AS SALE_ID,
  MATERIALID||'_'||PLANTID AS ID,
  MATERIALID,
  SUM(DELIVERY_QTY_SUOM) AS DELIVERY_QTY,
  MVMT_TYPE,
  PLANTID
FROM INV_SAP_LIKP_LIPS_DAILY
WHERE PLANTID = '5040' AND MVMT_TYPE = '601' AND CREATED_ON_DATE BETWEEN TO_CHAR(sysdate - 211) AND TO_CHAR(sysdate) group by REFERENCE_DOC, MATERIALID, MVMT_TYPE, PLANTID, MATERIALID||'_'||PLANTID
)DELIVERY
LEFT JOIN
(
SELECT SALESDOC||'_'||MATERIALID as ID,
      MATERIALID,
      ORDERQTY
      FROM INV_SAP_SALES_HST)HST
 ON   HST.ID =   DELIVERY.SALE_ID;












DROP TABLE INV_DEMO_REPORT;
SELECT * FROM INV_DEMO_REPORT;
CREATE TABLE INV_DEMO_REPORT AS 
SELECT 
  INV_ITEM_BASIC.LAST_REVIEW_DATE      AS LAST_REVIEW_DATE,
  INV_ITEM_BASIC.ID               AS ID,
  INV_ITEM_BASIC.PLANT                 AS PLANT,
  INV_ITEM_BASIC.MATERIAL              AS MATERIAL,
  INV_ITEM_BASIC.TOTAL_QTY             AS TOTAL_QTY,
  INV_ITEM_BASIC.LOCATION              AS LOCATION,
  INV_ITEM_BASIC.Material_Description  AS Material_Description,
  INV_ITEM_BASIC.Safety_Stock_Qty      AS Safety_Stock_Qty,
  INV_ITEM_BASIC.LEAD_TIME                   AS LEAD_TIME,
  STO_SALES_OPEN_QTY.BACKLOG_OPEN_QTY  AS BACKLOG_OPEN_QTY,
  STO_SALES_OPEN_QTY.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN_QTY,
  STO_SALES_OPEN_QTY.PO_SO_SA_FLAG     AS PO_SO_SA_FLAG,
  STO_SALES_OPEN_QTY.STO_OPEN_QTY      AS STO_OPEN_QTY,
  INV_ITEM_BASIC.BU                    AS BU,
  INV_ITEM_BASIC.Procurement_Type      AS Procurement_Type,
  INV_ITEM_BASIC.MATL_TYPE             AS MATL_TYPE,
  INV_ITEM_BASIC.MRP_TYPE              AS MRP_TYPE,
  INV_ITEM_BASIC.Stock_Strategy        AS Stock_Strategy
FROM
  (SELECT INV_BASIC.ID              AS ID,
    INV_BASIC.PLANT                 AS PLANT,
    INV_BASIC.MATERIAL              AS MATERIAL,
    INV_BASIC.TOTAL_QTY             AS TOTAL_QTY,
    INV_BASIC.LAST_REVIEW_DATE      AS LAST_REVIEW_DATE,
    INV_BASIC.LOCATION              AS LOCATION,
    ITEM_BASIC.Material_Description AS Material_Description,
    ITEM_BASIC.BU                   AS BU,
    ITEM_BASIC.Procurement_Type     AS Procurement_Type,
    ITEM_BASIC.MATL_TYPE            AS MATL_TYPE,
    ITEM_BASIC.MRP_TYPE             AS MRP_TYPE,
    ITEM_BASIC.Stock_Strategy       AS Stock_Strategy,
    ITEM_BASIC.Safety_Stock_Qty     AS Safety_Stock_Qty,
    ITEM_BASIC.LEAD_TIME                  AS LEAD_TIME
  FROM
    (SELECT MATERIALID
      ||'_'
      ||PLANTID     AS ID,
      MATERIALID    AS MATERIAL,
      PLANTID       AS PLANT,
      LOCATIONID    AS LOCATION,
      NVL(OH_QTY,0) AS TOTAL_QTY,
      ASOFDATE      AS LAST_REVIEW_DATE
    FROM DWQ$LIBRARIAN.INV_SAP_INVENTORY_BY_PLANT@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') --- ALL PLANTS HERE!!
    )INV_BASIC
  LEFT JOIN
    (SELECT MATERIALID
      ||'_'
      ||PLANTID            AS ID,
      MATERIALID           AS MATERIALID,
      PLANTID              AS PLANTID,
      MAT_DESC             AS Material_Description,
      PROD_BU              AS BU,
      PROC_TYPE            AS Procurement_Type,
      MRP_CONTROLLER_DISPO AS MRP_CONTROLLER_ID,
      MRP_CONTROLLER       AS MRP_CONTROLLER,
      MATL_TYPE_MTART      AS MATL_TYPE,
      MRP_TYPE             AS MRP_TYPE,
      STRATEGY_GRP         AS Stock_Strategy,
      UNIT_COST            AS Unit_Price,
      NVL(REORDER_PT,0)    AS Reorder_Point,
      NVL(SAFETY_STK,0)    AS Safety_Stock_Qty,
      (GRT+PDT)                 AS LEAD_TIME
    FROM DWQ$LIBRARIAN.INV_SAP_PP_OPTIMIZATION@ROCKWELL_DBLINK
    WHERE PLANTID IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') --- ALL PLANTS HERE!!
    )ITEM_BASIC
  ON ITEM_BASIC.ID = INV_BASIC.ID
  )INV_ITEM_BASIC
LEFT JOIN
  (
  --OPEN STATUS
  SELECT SALES_OPEN_PASS_QTY.ID           AS ID,
    SALES_OPEN_PASS_QTY.BACKLOG_OPEN_QTY  AS BACKLOG_OPEN_QTY,
    SALES_OPEN_PASS_QTY.PAST_DUE_OPEN_QTY AS PAST_DUE_OPEN_QTY,
    STO_OPEN_QTY_S.PO_SO_SA_FLAG          AS PO_SO_SA_FLAG,
    STO_OPEN_QTY_S.STO_OPEN_QTY           AS STO_OPEN_QTY
  FROM
    (
    --Sales Orders Status
    SELECT BACKLOG_OPEN.ID                   AS ID,
      NVL(BACKLOG_OPEN.OPEN_QTY,0)           AS BACKLOG_OPEN_QTY,
      NVL(PAST_DUE_OPEN.PAST_DUE_OPEN_QTY,0) AS PAST_DUE_OPEN_QTY
    FROM
      (SELECT MATERIAL
        ||'_'
        ||PLANT              AS ID,
        MATERIAL             AS MATERIALID,
        PLANT                AS PLANTID,
        NVL(SUM(OPEN_QTY),0) AS OPEN_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140')  ---All Plants
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )BACKLOG_OPEN
    LEFT JOIN
      (SELECT MATERIAL
        ||'_'
        ||PLANT               AS ID,
        MATERIAL              AS MATERIALID,
        PLANT                 AS PLANTID,
        NVL(SUM(OPEN_QTY), 0) AS PAST_DUE_OPEN_QTY
      FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK
      WHERE PLANT                  IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') ---All Plants
      AND MAX_COMMIT_DATE < SYSDATE - 1
      GROUP BY MATERIAL
        ||'_'
        ||PLANT,
        MATERIAL,
        PLANT
      )PAST_DUE_OPEN
    ON PAST_DUE_OPEN.ID = BACKLOG_OPEN.ID
    )SALES_OPEN_PASS_QTY
  LEFT JOIN
    ---STO_OPEN_QTY
    (
    SELECT MATERIALID
      ||'_'
      ||PLANTID AS ID,
      MATERIALID,
      PLANTID,
      PO_SO_SA_FLAG,
      NVL(SUM(COMMITTEDQTY),0) AS STO_OPEN_QTY
    FROM DWQ$LIBRARIAN.INV_SAP_PP_PO_HISTORY@ROCKWELL_DBLINK
    WHERE PLANTID        IN ('5040', '5050', '5100', '5110', '5120', '5160', '5190', '5200','5070','5140') ---All Plants
    AND PO_SO_SA_FLAG     = 'STO'
    AND DELIVERYCOMPLETE IS NULL
    GROUP BY MATERIALID,
      PLANTID,
      PO_SO_SA_FLAG
    )STO_OPEN_QTY_S
  ON SALES_OPEN_PASS_QTY.ID                    = STO_OPEN_QTY_S.ID
  )STO_SALES_OPEN_QTY ON STO_SALES_OPEN_QTY.ID = INV_ITEM_BASIC.ID;
  
  
  
select LINECREATIONDATE from inv_sap_sales_hst where PLANTID = '5070';
SELECT * FROM VIEW_INV_SAP_ITEM_ALL WHERE SALES_ORG = '1000' AND CURRENT_SERIES = 'X';
SELECT * FROM DWQ$LIBRARIAN.INV_SAP_SALES_VBAK_VBAP_VBUP@ROCKWELL_DBLINK WHERE SALESDOC = '6501883635';

SELECT * FROM
(SELECT DISTINCT DEM_SOURCE AS SO FROM DWQ$LIBRARIAN.INV_SAP_SALES_STO_DTL@ROCKWELL_DBLINK) WHERE SO = '6501883635';

select * from DWQ$LIBRARIAN.INV_SAP_SALES_STAT2@ROCKWELL_DBLINK WHERE MATERIAL = '100-D420EA11 B' and PLANT = '5040';






SELECT *
FROM
  (SELECT REFERENCE_DOC
    ||'_'
    ||MATERIALID AS SALE_ID,
    MATERIALID
    ||'_'
    ||PLANTID AS ID,
    MATERIALID,
    SUM(DELIVERY_QTY_SUOM) AS DELIVERY_QTY,
    MVMT_TYPE,
    PLANTID
  FROM INV_SAP_LIKP_LIPS_DAILY
  WHERE PLANTID = '5040'
  AND MVMT_TYPE = '601'
  AND CREATED_ON_DATE BETWEEN TO_CHAR(sysdate - 211) AND TO_CHAR(sysdate)
  GROUP BY REFERENCE_DOC,
    MATERIALID,
    MVMT_TYPE,
    PLANTID,
    MATERIALID
    ||'_'
    ||PLANTID
  )DELIVERY
LEFT JOIN
  (SELECT SALESDOC
    ||'_'
    ||MATERIALID AS ID,
    MATERIALID,
    ORDERQTY,
    LINECREATIONDATE,
    REQUIREDDELIVERYDATE
  FROM INV_SAP_SALES_HST
  )HST
ON HST.ID = DELIVERY.SALE_ID;


--VIEW_INV_SAP_SO_STATISTICS
--1.pass-due open qty and line
--2.LT open so qty and line
--3.(13weeks - LT) open so qty and line
--4. 13weeks after (Long Committed Date) open so qty and line
--5.All open so qty and line.
--LT 5040 14, 5050 8,5100 10,5110 11,5110 13,5160 16, 5190 16, 5200 10,5070 14, 5140 14

-- 5040 14,5110 13,5070 14, 5140 14

---NEED TO CREATE AND THINK.....

--Due Outside 13weeks
SELECT MATERIAL
  ||'_'
  ||PLANT       AS ID,
  MATERIAL      AS MATERIALID,
  PLANT         AS PLANTID,
  SUM(OPEN_QTY) AS OPEN_QTY_OUT_13WEEKS
FROM INV_SAP_SALES_VBAK_VBAP_VBUP
WHERE MAX_COMMIT_DATE > SYSDATE + 91
GROUP BY MATERIAL
  ||'_'
  ||PLANT,
  MATERIAL,
  PLANT;
  
--PAST DUE QTY
SELECT MATERIAL
  ||'_'
  ||PLANT       AS ID,
  MATERIAL      AS MATERIALID,
  PLANT         AS PLANTID,
  SUM(OPEN_QTY) AS OPEN_QTY_PAST_DUE
FROM INV_SAP_SALES_VBAK_VBAP_VBUP
WHERE MAX_COMMIT_DATE < SYSDATE - 1
GROUP BY MATERIAL
  ||'_'
  ||PLANT,
  MATERIAL,
  PLANT;
  
--BACK LOG OPEN OTY
SELECT MATERIAL
  ||'_'
  ||PLANT       AS ID,
  MATERIAL      AS MATERIALID,
  PLANT         AS PLANTID,
  SUM(OPEN_QTY) AS OPEN_QTY_BACKLOG
FROM INV_SAP_SALES_VBAK_VBAP_VBUP
GROUP BY MATERIAL
  ||'_'
  ||PLANT,
  MATERIAL,
  PLANT;
  
  
  
  
  
  
  
  
  SELECT * FROM INV_SAP_PP_FRCST_PBIM_PBED WHERE MATERIALID = '1756-IB16 A' AND PLANTID = '5040' AND VERSBP_VERSION = '00'
  
  
  SELECT M_C.MATERIALID,
        M_C.CATALOG_STRING1
  FROM
  (
  SELECT CATALOG_STRING1,
MATERIALID FROM INV_SAP_MATERIAL_CATALOG
  )M_C
  LEFT JOIN
  (
  SELECT MATERIAL FROM TEMP
  )TP
  ON TP.MATERIAL = M_C.MATERIALID;
-----------------------------------------------------------
SELECT ID,
      MATERIALID,
      SUM(WEEK_1)  AS WK_1,
      SUM(WEEK_2)  AS WK_2,
      SUM(WEEK_3)  AS WK_3,
      SUM(WEEK_4)  AS WK_4,
      SUM(WEEK_5)  AS WK_5,
      SUM(WEEK_6)  AS WK_6,
      SUM(WEEK_7)  AS WK_7,
      SUM(WEEK_8)  AS WK_8,
      SUM(WEEK_9)  AS WK_9,
      SUM(WEEK_10) AS WK_10,
      SUM(WEEK_11) AS WK_11,
      SUM(WEEK_12) AS WK_12,
      SUM(WEEK_13) AS WK_13
    FROM
      (SELECT MATERIALID
        ||'_'
        ||PLANTID AS ID,
        MATERIALID,
        CASE
          WHEN WEEK_NUMBER <= TO_CHAR(SYSDATE,'iw')
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_1,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 1
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_2,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 2
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_3,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 3
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_4,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 4
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_5,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 5
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_6,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 6
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_7,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 7
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_8,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 8
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_9,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 9
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_10,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 10
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_11,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 11
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_12,
        CASE
          WHEN WEEK_NUMBER = TO_CHAR(SYSDATE,'iw') + 12
          THEN OPEN_PO_QTY
          ELSE 0
        END WEEK_13,
        PLANTID
      FROM
        (SELECT MATERIALID
          ||'_'
          ||PLANTID AS ID,
          MATERIALID,
          PLANTID,
          TO_CHAR(DATEDELIVERY,'iw') AS WEEK_NUMBER,
          PONUMBER,
          PO_OPENQTY                 AS OPEN_PO_QTY
        FROM INV_SAP_IO_INPUTS_DAILY
        WHERE INPUT_TYPE = 'PLAN_PD_PO'
        AND DATEDELIVERY             < TO_CHAR(sysdate + 91) and materialid = '1756-IB16 A' and plantid = '5040'
        )
      )
    GROUP BY ID,
      MATERIALID;